/**
 * Bible Section Headings (Pericope Headings)
 *
 * Editorial section headings that appear before groups of verses in printed Bibles.
 * These are NOT part of the biblical text — they are navigational aids.
 * Keyed by "bookId:chapter" for O(1) lookup.
 */

export interface SectionHeading {
  bookId: number;
  chapter: number;
  /** The verse number this heading appears BEFORE */
  beforeVerse: number;
  title: string;
}

// prettier-ignore
const HEADINGS: SectionHeading[] = [
  // ── Genesis (1) ──
  {bookId:1,chapter:1,beforeVerse:1,title:'The Creation'},
  {bookId:1,chapter:1,beforeVerse:26,title:'The Creation of Man'},
  {bookId:1,chapter:2,beforeVerse:1,title:'The Seventh Day'},
  {bookId:1,chapter:2,beforeVerse:4,title:'Man and Woman in the Garden'},
  {bookId:1,chapter:2,beforeVerse:18,title:'The Creation of Woman'},
  {bookId:1,chapter:3,beforeVerse:1,title:'The Fall of Man'},
  {bookId:1,chapter:3,beforeVerse:14,title:'The Curse'},
  {bookId:1,chapter:3,beforeVerse:22,title:'Banishment from the Garden'},
  {bookId:1,chapter:4,beforeVerse:1,title:'Cain and Abel'},
  {bookId:1,chapter:4,beforeVerse:17,title:'The Line of Cain'},
  {bookId:1,chapter:4,beforeVerse:25,title:'Seth and Enosh'},
  {bookId:1,chapter:5,beforeVerse:1,title:'From Adam to Noah'},
  {bookId:1,chapter:6,beforeVerse:1,title:'Wickedness in the World'},
  {bookId:1,chapter:6,beforeVerse:9,title:'Noah Builds the Ark'},
  {bookId:1,chapter:7,beforeVerse:1,title:'The Flood'},
  {bookId:1,chapter:8,beforeVerse:1,title:'The Flood Recedes'},
  {bookId:1,chapter:8,beforeVerse:20,title:"Noah's Sacrifice"},
  {bookId:1,chapter:9,beforeVerse:1,title:'God Blesses Noah'},
  {bookId:1,chapter:9,beforeVerse:8,title:'The Covenant of the Rainbow'},
  {bookId:1,chapter:9,beforeVerse:18,title:'Noah and His Sons'},
  {bookId:1,chapter:10,beforeVerse:1,title:'The Table of Nations'},
  {bookId:1,chapter:11,beforeVerse:1,title:'The Tower of Babel'},
  {bookId:1,chapter:11,beforeVerse:10,title:'From Shem to Abram'},
  {bookId:1,chapter:11,beforeVerse:27,title:"Terah's Family"},
  {bookId:1,chapter:12,beforeVerse:1,title:'The Call of Abram'},
  {bookId:1,chapter:12,beforeVerse:10,title:'Abram in Egypt'},
  {bookId:1,chapter:13,beforeVerse:1,title:'Abram and Lot Separate'},
  {bookId:1,chapter:14,beforeVerse:1,title:'Abram Rescues Lot'},
  {bookId:1,chapter:14,beforeVerse:17,title:'Abram and Melchizedek'},
  {bookId:1,chapter:15,beforeVerse:1,title:"God's Covenant with Abram"},
  {bookId:1,chapter:16,beforeVerse:1,title:'Hagar and Ishmael'},
  {bookId:1,chapter:17,beforeVerse:1,title:'The Covenant of Circumcision'},
  {bookId:1,chapter:17,beforeVerse:15,title:'Isaac Promised'},
  {bookId:1,chapter:18,beforeVerse:1,title:'The Three Visitors'},
  {bookId:1,chapter:18,beforeVerse:16,title:'Abraham Pleads for Sodom'},
  {bookId:1,chapter:19,beforeVerse:1,title:'The Destruction of Sodom'},
  {bookId:1,chapter:19,beforeVerse:30,title:'Lot and His Daughters'},
  {bookId:1,chapter:20,beforeVerse:1,title:'Abraham and Abimelech'},
  {bookId:1,chapter:21,beforeVerse:1,title:'The Birth of Isaac'},
  {bookId:1,chapter:21,beforeVerse:8,title:'Hagar and Ishmael Sent Away'},
  {bookId:1,chapter:22,beforeVerse:1,title:'The Binding of Isaac'},
  {bookId:1,chapter:23,beforeVerse:1,title:'The Death of Sarah'},
  {bookId:1,chapter:24,beforeVerse:1,title:'A Wife for Isaac'},
  {bookId:1,chapter:25,beforeVerse:1,title:"Abraham's Death"},
  {bookId:1,chapter:25,beforeVerse:19,title:'Jacob and Esau'},
  {bookId:1,chapter:25,beforeVerse:29,title:'Esau Sells His Birthright'},
  {bookId:1,chapter:26,beforeVerse:1,title:'Isaac and Abimelech'},
  {bookId:1,chapter:27,beforeVerse:1,title:'Jacob Steals the Blessing'},
  {bookId:1,chapter:27,beforeVerse:41,title:'Jacob Flees to Laban'},
  {bookId:1,chapter:28,beforeVerse:10,title:"Jacob's Dream at Bethel"},
  {bookId:1,chapter:29,beforeVerse:1,title:'Jacob Meets Rachel'},
  {bookId:1,chapter:29,beforeVerse:31,title:"Jacob's Children"},
  {bookId:1,chapter:30,beforeVerse:25,title:"Jacob's Flocks Increase"},
  {bookId:1,chapter:31,beforeVerse:1,title:'Jacob Flees from Laban'},
  {bookId:1,chapter:32,beforeVerse:1,title:'Jacob Prepares to Meet Esau'},
  {bookId:1,chapter:32,beforeVerse:22,title:'Jacob Wrestles with God'},
  {bookId:1,chapter:33,beforeVerse:1,title:'Jacob Meets Esau'},
  {bookId:1,chapter:34,beforeVerse:1,title:'The Defilement of Dinah'},
  {bookId:1,chapter:35,beforeVerse:1,title:'Jacob Returns to Bethel'},
  {bookId:1,chapter:35,beforeVerse:16,title:'The Deaths of Rachel and Isaac'},
  {bookId:1,chapter:36,beforeVerse:1,title:'The Descendants of Esau'},
  {bookId:1,chapter:37,beforeVerse:1,title:"Joseph's Dreams"},
  {bookId:1,chapter:37,beforeVerse:12,title:'Joseph Sold by His Brothers'},
  {bookId:1,chapter:38,beforeVerse:1,title:'Judah and Tamar'},
  {bookId:1,chapter:39,beforeVerse:1,title:"Joseph and Potiphar's Wife"},
  {bookId:1,chapter:39,beforeVerse:19,title:'Joseph in Prison'},
  {bookId:1,chapter:40,beforeVerse:1,title:'The Cupbearer and the Baker'},
  {bookId:1,chapter:41,beforeVerse:1,title:"Pharaoh's Dreams"},
  {bookId:1,chapter:41,beforeVerse:37,title:'Joseph Made Ruler of Egypt'},
  {bookId:1,chapter:42,beforeVerse:1,title:"Joseph's Brothers Go to Egypt"},
  {bookId:1,chapter:43,beforeVerse:1,title:'The Second Journey to Egypt'},
  {bookId:1,chapter:44,beforeVerse:1,title:"Joseph's Silver Cup"},
  {bookId:1,chapter:45,beforeVerse:1,title:'Joseph Reveals His Identity'},
  {bookId:1,chapter:46,beforeVerse:1,title:'Jacob Goes to Egypt'},
  {bookId:1,chapter:47,beforeVerse:1,title:'Jacob Before Pharaoh'},
  {bookId:1,chapter:48,beforeVerse:1,title:'Jacob Blesses Ephraim and Manasseh'},
  {bookId:1,chapter:49,beforeVerse:1,title:'Jacob Blesses His Sons'},
  {bookId:1,chapter:49,beforeVerse:29,title:'The Death of Jacob'},
  {bookId:1,chapter:50,beforeVerse:1,title:'The Burial of Jacob'},
  {bookId:1,chapter:50,beforeVerse:15,title:'Joseph Reassures His Brothers'},
  {bookId:1,chapter:50,beforeVerse:22,title:'The Death of Joseph'},
  // ── Exodus (2) ──
  {bookId:2,chapter:1,beforeVerse:1,title:'Israel Multiplies in Egypt'},
  {bookId:2,chapter:1,beforeVerse:8,title:'The Israelites Oppressed'},
  {bookId:2,chapter:2,beforeVerse:1,title:'The Birth of Moses'},
  {bookId:2,chapter:2,beforeVerse:11,title:'Moses Flees to Midian'},
  {bookId:2,chapter:3,beforeVerse:1,title:'The Burning Bush'},
  {bookId:2,chapter:4,beforeVerse:1,title:'Signs for Moses'},
  {bookId:2,chapter:4,beforeVerse:18,title:'Moses Returns to Egypt'},
  {bookId:2,chapter:5,beforeVerse:1,title:'Bricks Without Straw'},
  {bookId:2,chapter:6,beforeVerse:1,title:'God Promises Deliverance'},
  {bookId:2,chapter:7,beforeVerse:14,title:'The Plague of Blood'},
  {bookId:2,chapter:8,beforeVerse:1,title:'The Plague of Frogs'},
  {bookId:2,chapter:8,beforeVerse:16,title:'The Plague of Gnats'},
  {bookId:2,chapter:8,beforeVerse:20,title:'The Plague of Flies'},
  {bookId:2,chapter:9,beforeVerse:1,title:'The Plague on Livestock'},
  {bookId:2,chapter:9,beforeVerse:8,title:'The Plague of Boils'},
  {bookId:2,chapter:9,beforeVerse:13,title:'The Plague of Hail'},
  {bookId:2,chapter:10,beforeVerse:1,title:'The Plague of Locusts'},
  {bookId:2,chapter:10,beforeVerse:21,title:'The Plague of Darkness'},
  {bookId:2,chapter:11,beforeVerse:1,title:'The Plague on the Firstborn'},
  {bookId:2,chapter:12,beforeVerse:1,title:'The Passover'},
  {bookId:2,chapter:12,beforeVerse:29,title:'The Exodus'},
  {bookId:2,chapter:13,beforeVerse:17,title:'Pillars of Cloud and Fire'},
  {bookId:2,chapter:14,beforeVerse:1,title:'Crossing the Red Sea'},
  {bookId:2,chapter:15,beforeVerse:1,title:'The Song of Moses'},
  {bookId:2,chapter:15,beforeVerse:22,title:'Bitter Water Made Sweet'},
  {bookId:2,chapter:16,beforeVerse:1,title:'Manna and Quail'},
  {bookId:2,chapter:17,beforeVerse:1,title:'Water from the Rock'},
  {bookId:2,chapter:17,beforeVerse:8,title:'Victory over the Amalekites'},
  {bookId:2,chapter:18,beforeVerse:1,title:'Jethro Visits Moses'},
  {bookId:2,chapter:19,beforeVerse:1,title:'Israel at Mount Sinai'},
  {bookId:2,chapter:20,beforeVerse:1,title:'The Ten Commandments'},
  {bookId:2,chapter:24,beforeVerse:1,title:'The Covenant Confirmed'},
  {bookId:2,chapter:25,beforeVerse:1,title:'Offerings for the Tabernacle'},
  {bookId:2,chapter:25,beforeVerse:10,title:'The Ark of the Covenant'},
  {bookId:2,chapter:26,beforeVerse:1,title:'The Tabernacle'},
  {bookId:2,chapter:28,beforeVerse:1,title:'The Priestly Garments'},
  {bookId:2,chapter:32,beforeVerse:1,title:'The Golden Calf'},
  {bookId:2,chapter:33,beforeVerse:12,title:"Moses Sees God's Glory"},
  {bookId:2,chapter:34,beforeVerse:1,title:'New Tablets of Stone'},
  {bookId:2,chapter:34,beforeVerse:29,title:"The Radiance of Moses' Face"},
  {bookId:2,chapter:40,beforeVerse:34,title:'The Glory of the LORD'},
  // ── Leviticus (3) ──
  {bookId:3,chapter:1,beforeVerse:1,title:'The Burnt Offering'},
  {bookId:3,chapter:2,beforeVerse:1,title:'The Grain Offering'},
  {bookId:3,chapter:3,beforeVerse:1,title:'The Peace Offering'},
  {bookId:3,chapter:4,beforeVerse:1,title:'The Sin Offering'},
  {bookId:3,chapter:5,beforeVerse:14,title:'The Guilt Offering'},
  {bookId:3,chapter:10,beforeVerse:1,title:'Nadab and Abihu'},
  {bookId:3,chapter:11,beforeVerse:1,title:'Clean and Unclean Animals'},
  {bookId:3,chapter:16,beforeVerse:1,title:'The Day of Atonement'},
  {bookId:3,chapter:19,beforeVerse:1,title:'Laws of Holiness'},
  {bookId:3,chapter:23,beforeVerse:1,title:'The Appointed Feasts'},
  {bookId:3,chapter:25,beforeVerse:1,title:'The Sabbath Year'},
  {bookId:3,chapter:25,beforeVerse:8,title:'The Year of Jubilee'},
  {bookId:3,chapter:26,beforeVerse:1,title:'Blessings and Curses'},
  // ── Numbers (4) ──
  {bookId:4,chapter:1,beforeVerse:1,title:'The Census of Israel'},
  {bookId:4,chapter:6,beforeVerse:1,title:'The Nazirite Vow'},
  {bookId:4,chapter:6,beforeVerse:22,title:'The Priestly Blessing'},
  {bookId:4,chapter:11,beforeVerse:4,title:'The Quail and the Plague'},
  {bookId:4,chapter:12,beforeVerse:1,title:'Miriam and Aaron Oppose Moses'},
  {bookId:4,chapter:13,beforeVerse:1,title:'The Twelve Spies'},
  {bookId:4,chapter:14,beforeVerse:1,title:'The People Rebel'},
  {bookId:4,chapter:16,beforeVerse:1,title:'The Rebellion of Korah'},
  {bookId:4,chapter:20,beforeVerse:1,title:'Water from the Rock'},
  {bookId:4,chapter:20,beforeVerse:22,title:'The Death of Aaron'},
  {bookId:4,chapter:21,beforeVerse:4,title:'The Bronze Serpent'},
  {bookId:4,chapter:22,beforeVerse:1,title:'Balak Summons Balaam'},
  {bookId:4,chapter:22,beforeVerse:21,title:"Balaam's Donkey"},
  {bookId:4,chapter:27,beforeVerse:12,title:'Joshua to Succeed Moses'},
  // ── Deuteronomy (5) ──
  {bookId:5,chapter:4,beforeVerse:1,title:'Call to Obedience'},
  {bookId:5,chapter:5,beforeVerse:1,title:'The Ten Commandments Repeated'},
  {bookId:5,chapter:6,beforeVerse:1,title:'Love the LORD Your God'},
  {bookId:5,chapter:6,beforeVerse:4,title:'The Shema'},
  {bookId:5,chapter:7,beforeVerse:1,title:'A Chosen People'},
  {bookId:5,chapter:8,beforeVerse:1,title:'Remember the LORD'},
  {bookId:5,chapter:18,beforeVerse:15,title:'A Prophet Like Moses'},
  {bookId:5,chapter:28,beforeVerse:1,title:'Blessings for Obedience'},
  {bookId:5,chapter:28,beforeVerse:15,title:'Curses for Disobedience'},
  {bookId:5,chapter:30,beforeVerse:1,title:'Life and Death'},
  {bookId:5,chapter:31,beforeVerse:1,title:'Joshua Commissioned'},
  {bookId:5,chapter:32,beforeVerse:1,title:'The Song of Moses'},
  {bookId:5,chapter:34,beforeVerse:1,title:'The Death of Moses'},
  // ── Joshua (6) ──
  {bookId:6,chapter:1,beforeVerse:1,title:'God Commissions Joshua'},
  {bookId:6,chapter:2,beforeVerse:1,title:'Rahab and the Spies'},
  {bookId:6,chapter:3,beforeVerse:1,title:'Crossing the Jordan'},
  {bookId:6,chapter:6,beforeVerse:1,title:'The Fall of Jericho'},
  {bookId:6,chapter:7,beforeVerse:1,title:'The Sin of Achan'},
  {bookId:6,chapter:10,beforeVerse:1,title:'The Sun Stands Still'},
  {bookId:6,chapter:24,beforeVerse:1,title:'The Covenant at Shechem'},
  {bookId:6,chapter:24,beforeVerse:29,title:'The Death of Joshua'},
  // ── Judges (7) ──
  {bookId:7,chapter:4,beforeVerse:1,title:'Deborah and Barak'},
  {bookId:7,chapter:5,beforeVerse:1,title:'The Song of Deborah'},
  {bookId:7,chapter:6,beforeVerse:1,title:'The Call of Gideon'},
  {bookId:7,chapter:7,beforeVerse:1,title:'Gideon Defeats Midian'},
  {bookId:7,chapter:11,beforeVerse:1,title:"Jephthah's Vow"},
  {bookId:7,chapter:13,beforeVerse:1,title:'The Birth of Samson'},
  {bookId:7,chapter:16,beforeVerse:1,title:'Samson and Delilah'},
  {bookId:7,chapter:16,beforeVerse:23,title:'The Death of Samson'},
  // ── Ruth (8) ──
  {bookId:8,chapter:1,beforeVerse:1,title:'Naomi and Ruth'},
  {bookId:8,chapter:1,beforeVerse:6,title:"Ruth's Loyalty"},
  {bookId:8,chapter:2,beforeVerse:1,title:'Ruth Meets Boaz'},
  {bookId:8,chapter:3,beforeVerse:1,title:'Ruth at the Threshing Floor'},
  {bookId:8,chapter:4,beforeVerse:1,title:'Boaz Redeems Ruth'},
  // ── 1 Samuel (9) ──
  {bookId:9,chapter:1,beforeVerse:1,title:'The Birth of Samuel'},
  {bookId:9,chapter:2,beforeVerse:1,title:"Hannah's Prayer"},
  {bookId:9,chapter:3,beforeVerse:1,title:'The LORD Calls Samuel'},
  {bookId:9,chapter:4,beforeVerse:1,title:'The Ark Captured'},
  {bookId:9,chapter:8,beforeVerse:1,title:'Israel Demands a King'},
  {bookId:9,chapter:9,beforeVerse:1,title:'Saul Chosen as King'},
  {bookId:9,chapter:15,beforeVerse:1,title:'The LORD Rejects Saul'},
  {bookId:9,chapter:16,beforeVerse:1,title:'David Anointed King'},
  {bookId:9,chapter:16,beforeVerse:14,title:"David in Saul's Service"},
  {bookId:9,chapter:17,beforeVerse:1,title:'David and Goliath'},
  {bookId:9,chapter:18,beforeVerse:1,title:'David and Jonathan'},
  {bookId:9,chapter:18,beforeVerse:6,title:"Saul's Jealousy"},
  {bookId:9,chapter:24,beforeVerse:1,title:'David Spares Saul'},
  {bookId:9,chapter:25,beforeVerse:1,title:'David, Nabal, and Abigail'},
  {bookId:9,chapter:28,beforeVerse:1,title:'Saul and the Medium at Endor'},
  {bookId:9,chapter:31,beforeVerse:1,title:'The Death of Saul'},
  // ── 2 Samuel (10) ──
  {bookId:10,chapter:1,beforeVerse:17,title:"David's Lament"},
  {bookId:10,chapter:5,beforeVerse:1,title:'David King over All Israel'},
  {bookId:10,chapter:5,beforeVerse:6,title:'David Conquers Jerusalem'},
  {bookId:10,chapter:6,beforeVerse:1,title:'The Ark Brought to Jerusalem'},
  {bookId:10,chapter:7,beforeVerse:1,title:"God's Covenant with David"},
  {bookId:10,chapter:11,beforeVerse:1,title:'David and Bathsheba'},
  {bookId:10,chapter:12,beforeVerse:1,title:'Nathan Rebukes David'},
  {bookId:10,chapter:15,beforeVerse:1,title:"Absalom's Rebellion"},
  {bookId:10,chapter:18,beforeVerse:1,title:'The Death of Absalom'},
  {bookId:10,chapter:22,beforeVerse:1,title:"David's Song of Praise"},
  {bookId:10,chapter:24,beforeVerse:1,title:"David's Census"},
  // ── 1 Kings (11) ──
  {bookId:11,chapter:1,beforeVerse:28,title:'Solomon Made King'},
  {bookId:11,chapter:3,beforeVerse:1,title:'Solomon Asks for Wisdom'},
  {bookId:11,chapter:3,beforeVerse:16,title:"Solomon's Wise Judgment"},
  {bookId:11,chapter:6,beforeVerse:1,title:'Solomon Builds the Temple'},
  {bookId:11,chapter:8,beforeVerse:1,title:'Dedication of the Temple'},
  {bookId:11,chapter:10,beforeVerse:1,title:'The Queen of Sheba Visits'},
  {bookId:11,chapter:11,beforeVerse:1,title:"Solomon's Wives"},
  {bookId:11,chapter:12,beforeVerse:1,title:'The Kingdom Divided'},
  {bookId:11,chapter:17,beforeVerse:1,title:'Elijah Fed by Ravens'},
  {bookId:11,chapter:17,beforeVerse:7,title:'The Widow of Zarephath'},
  {bookId:11,chapter:18,beforeVerse:1,title:'Elijah on Mount Carmel'},
  {bookId:11,chapter:19,beforeVerse:1,title:'Elijah Flees to Horeb'},
  {bookId:11,chapter:19,beforeVerse:11,title:'The Still Small Voice'},
  {bookId:11,chapter:19,beforeVerse:19,title:'The Call of Elisha'},
  {bookId:11,chapter:21,beforeVerse:1,title:"Naboth's Vineyard"},
  // ── 2 Kings (12) ──
  {bookId:12,chapter:2,beforeVerse:1,title:'Elijah Taken Up to Heaven'},
  {bookId:12,chapter:4,beforeVerse:8,title:"The Shunammite's Son"},
  {bookId:12,chapter:5,beforeVerse:1,title:'Naaman Healed of Leprosy'},
  {bookId:12,chapter:17,beforeVerse:1,title:'The Fall of Samaria'},
  {bookId:12,chapter:22,beforeVerse:8,title:'The Book of the Law Found'},
  {bookId:12,chapter:25,beforeVerse:1,title:'The Fall of Jerusalem'},
  // ── 1 Chronicles (13) ──
  {bookId:13,chapter:1,beforeVerse:1,title:'From Adam to Abraham'},
  {bookId:13,chapter:17,beforeVerse:1,title:"God's Promise to David"},
  {bookId:13,chapter:29,beforeVerse:10,title:"David's Prayer"},
  // ── 2 Chronicles (14) ──
  {bookId:14,chapter:6,beforeVerse:1,title:"Solomon's Prayer"},
  {bookId:14,chapter:7,beforeVerse:1,title:"God's Response to Solomon"},
  {bookId:14,chapter:20,beforeVerse:1,title:"Jehoshaphat's Victory"},
  {bookId:14,chapter:36,beforeVerse:15,title:'The Fall of Jerusalem'},
  // ── Ezra (15) ──
  {bookId:15,chapter:1,beforeVerse:1,title:'The Proclamation of Cyrus'},
  {bookId:15,chapter:3,beforeVerse:8,title:'Rebuilding the Temple'},
  {bookId:15,chapter:7,beforeVerse:1,title:'Ezra Comes to Jerusalem'},
  {bookId:15,chapter:9,beforeVerse:1,title:"Ezra's Prayer"},
  // ── Nehemiah (16) ──
  {bookId:16,chapter:1,beforeVerse:1,title:"Nehemiah's Prayer"},
  {bookId:16,chapter:2,beforeVerse:1,title:'Nehemiah Goes to Jerusalem'},
  {bookId:16,chapter:4,beforeVerse:1,title:'Opposition to the Rebuilding'},
  {bookId:16,chapter:6,beforeVerse:15,title:'The Wall Completed'},
  {bookId:16,chapter:8,beforeVerse:1,title:'Ezra Reads the Law'},
  // ── Esther (17) ──
  {bookId:17,chapter:2,beforeVerse:1,title:'Esther Made Queen'},
  {bookId:17,chapter:3,beforeVerse:1,title:"Haman's Plot"},
  {bookId:17,chapter:4,beforeVerse:1,title:'Mordecai Persuades Esther'},
  {bookId:17,chapter:7,beforeVerse:1,title:'Haman Hanged'},
  {bookId:17,chapter:9,beforeVerse:18,title:'The Feast of Purim'},
  // ── Job (18) ──
  {bookId:18,chapter:1,beforeVerse:1,title:"Job's Prosperity and Piety"},
  {bookId:18,chapter:1,beforeVerse:6,title:"Satan's First Test"},
  {bookId:18,chapter:2,beforeVerse:1,title:"Satan's Second Test"},
  {bookId:18,chapter:2,beforeVerse:11,title:"Job's Three Friends"},
  {bookId:18,chapter:3,beforeVerse:1,title:"Job's Lament"},
  {bookId:18,chapter:19,beforeVerse:25,title:'I Know That My Redeemer Lives'},
  {bookId:18,chapter:28,beforeVerse:1,title:'The Hymn to Wisdom'},
  {bookId:18,chapter:38,beforeVerse:1,title:'The LORD Speaks'},
  {bookId:18,chapter:42,beforeVerse:1,title:"Job's Repentance"},
  {bookId:18,chapter:42,beforeVerse:7,title:"Job's Restoration"},
  // ── Psalms (19) ──
  {bookId:19,chapter:1,beforeVerse:1,title:'The Way of the Righteous'},
  {bookId:19,chapter:2,beforeVerse:1,title:"The Reign of the LORD's Anointed"},
  {bookId:19,chapter:4,beforeVerse:1,title:'An Evening Prayer'},
  {bookId:19,chapter:5,beforeVerse:1,title:'A Morning Prayer'},
  {bookId:19,chapter:6,beforeVerse:1,title:'A Prayer for Mercy'},
  {bookId:19,chapter:8,beforeVerse:1,title:"The Majesty of God's Creation"},
  {bookId:19,chapter:13,beforeVerse:1,title:'How Long, O LORD?'},
  {bookId:19,chapter:14,beforeVerse:1,title:'The Fool Says There Is No God'},
  {bookId:19,chapter:16,beforeVerse:1,title:'A Psalm of Confidence'},
  {bookId:19,chapter:18,beforeVerse:1,title:"David's Song of Deliverance"},
  {bookId:19,chapter:19,beforeVerse:1,title:"The Heavens Declare God's Glory"},
  {bookId:19,chapter:22,beforeVerse:1,title:'My God, Why Have You Forsaken Me?'},
  {bookId:19,chapter:23,beforeVerse:1,title:'The LORD Is My Shepherd'},
  {bookId:19,chapter:24,beforeVerse:1,title:'The King of Glory'},
  {bookId:19,chapter:25,beforeVerse:1,title:'A Prayer for Guidance'},
  {bookId:19,chapter:27,beforeVerse:1,title:'The LORD Is My Light'},
  {bookId:19,chapter:29,beforeVerse:1,title:'The Voice of the LORD'},
  {bookId:19,chapter:30,beforeVerse:1,title:'Joy Comes in the Morning'},
  {bookId:19,chapter:31,beforeVerse:1,title:'Into Your Hands I Commit My Spirit'},
  {bookId:19,chapter:32,beforeVerse:1,title:'The Joy of Forgiveness'},
  {bookId:19,chapter:33,beforeVerse:1,title:'Praise to the Creator'},
  {bookId:19,chapter:34,beforeVerse:1,title:'Taste and See That the LORD Is Good'},
  {bookId:19,chapter:37,beforeVerse:1,title:'Do Not Fret'},
  {bookId:19,chapter:40,beforeVerse:1,title:'A Song of Deliverance'},
  {bookId:19,chapter:42,beforeVerse:1,title:'As the Deer Pants for Water'},
  {bookId:19,chapter:46,beforeVerse:1,title:'God Is Our Refuge and Strength'},
  {bookId:19,chapter:51,beforeVerse:1,title:'A Prayer of Repentance'},
  {bookId:19,chapter:62,beforeVerse:1,title:'My Soul Finds Rest in God'},
  {bookId:19,chapter:63,beforeVerse:1,title:'Thirsting for God'},
  {bookId:19,chapter:67,beforeVerse:1,title:'God Bless Us'},
  {bookId:19,chapter:72,beforeVerse:1,title:'A Prayer for the King'},
  {bookId:19,chapter:73,beforeVerse:1,title:'The Prosperity of the Wicked'},
  {bookId:19,chapter:84,beforeVerse:1,title:'How Lovely Is Your Dwelling Place'},
  {bookId:19,chapter:86,beforeVerse:1,title:'A Prayer of David'},
  {bookId:19,chapter:89,beforeVerse:1,title:"God's Covenant with David"},
  {bookId:19,chapter:90,beforeVerse:1,title:'A Prayer of Moses'},
  {bookId:19,chapter:91,beforeVerse:1,title:'The Shelter of the Most High'},
  {bookId:19,chapter:95,beforeVerse:1,title:'A Call to Worship'},
  {bookId:19,chapter:96,beforeVerse:1,title:'Sing a New Song to the LORD'},
  {bookId:19,chapter:100,beforeVerse:1,title:'A Psalm of Thanksgiving'},
  {bookId:19,chapter:103,beforeVerse:1,title:'Bless the LORD, O My Soul'},
  {bookId:19,chapter:104,beforeVerse:1,title:'God the Creator'},
  {bookId:19,chapter:110,beforeVerse:1,title:'The LORD Says to My Lord'},
  {bookId:19,chapter:115,beforeVerse:1,title:'Not to Us, O LORD'},
  {bookId:19,chapter:118,beforeVerse:1,title:'The Stone the Builders Rejected'},
  {bookId:19,chapter:119,beforeVerse:1,title:"The Glory of God's Word"},
  {bookId:19,chapter:121,beforeVerse:1,title:'My Help Comes from the LORD'},
  {bookId:19,chapter:122,beforeVerse:1,title:'A Prayer for Jerusalem'},
  {bookId:19,chapter:126,beforeVerse:1,title:'Restoring the Fortunes of Zion'},
  {bookId:19,chapter:127,beforeVerse:1,title:'Unless the LORD Builds the House'},
  {bookId:19,chapter:130,beforeVerse:1,title:'Out of the Depths'},
  {bookId:19,chapter:133,beforeVerse:1,title:'How Good and Pleasant Is Unity'},
  {bookId:19,chapter:136,beforeVerse:1,title:'His Love Endures Forever'},
  {bookId:19,chapter:137,beforeVerse:1,title:'By the Rivers of Babylon'},
  {bookId:19,chapter:139,beforeVerse:1,title:"God's Perfect Knowledge"},
  {bookId:19,chapter:145,beforeVerse:1,title:'Great Is the LORD'},
  {bookId:19,chapter:148,beforeVerse:1,title:'All Creation Praises God'},
  {bookId:19,chapter:150,beforeVerse:1,title:'Let Everything Praise the LORD'},
  // ── Proverbs (20) ──
  {bookId:20,chapter:1,beforeVerse:1,title:'The Purpose of Proverbs'},
  {bookId:20,chapter:1,beforeVerse:7,title:'The Fear of the LORD'},
  {bookId:20,chapter:1,beforeVerse:20,title:"Wisdom's Rebuke"},
  {bookId:20,chapter:2,beforeVerse:1,title:'The Value of Wisdom'},
  {bookId:20,chapter:3,beforeVerse:1,title:'Trust in the LORD'},
  {bookId:20,chapter:4,beforeVerse:1,title:'Get Wisdom'},
  {bookId:20,chapter:5,beforeVerse:1,title:'Warning Against Adultery'},
  {bookId:20,chapter:6,beforeVerse:6,title:'Lessons from the Ant'},
  {bookId:20,chapter:6,beforeVerse:16,title:'Seven Things God Hates'},
  {bookId:20,chapter:8,beforeVerse:1,title:'The Call of Wisdom'},
  {bookId:20,chapter:9,beforeVerse:1,title:'The Way of Wisdom'},
  {bookId:20,chapter:10,beforeVerse:1,title:'Proverbs of Solomon'},
  {bookId:20,chapter:22,beforeVerse:17,title:'Sayings of the Wise'},
  {bookId:20,chapter:25,beforeVerse:1,title:'More Proverbs of Solomon'},
  {bookId:20,chapter:30,beforeVerse:1,title:'Sayings of Agur'},
  {bookId:20,chapter:31,beforeVerse:1,title:'Sayings of King Lemuel'},
  {bookId:20,chapter:31,beforeVerse:10,title:'The Excellent Wife'},
  // ── Ecclesiastes (21) ──
  {bookId:21,chapter:1,beforeVerse:1,title:'Everything Is Meaningless'},
  {bookId:21,chapter:3,beforeVerse:1,title:'A Time for Everything'},
  {bookId:21,chapter:5,beforeVerse:1,title:'Stand in Awe of God'},
  {bookId:21,chapter:12,beforeVerse:1,title:'Remember Your Creator'},
  {bookId:21,chapter:12,beforeVerse:13,title:'Fear God and Keep His Commands'},
  // ── Song of Solomon (22) ──
  {bookId:22,chapter:1,beforeVerse:1,title:'The Song of Songs'},
  {bookId:22,chapter:4,beforeVerse:1,title:'The Bridegroom Praises the Bride'},
  {bookId:22,chapter:8,beforeVerse:5,title:'The Power of Love'},
  // ── Isaiah (23) ──
  {bookId:23,chapter:1,beforeVerse:1,title:'A Rebellious Nation'},
  {bookId:23,chapter:2,beforeVerse:1,title:'The Mountain of the LORD'},
  {bookId:23,chapter:5,beforeVerse:1,title:'The Song of the Vineyard'},
  {bookId:23,chapter:6,beforeVerse:1,title:"Isaiah's Commission"},
  {bookId:23,chapter:7,beforeVerse:1,title:'The Sign of Immanuel'},
  {bookId:23,chapter:9,beforeVerse:1,title:'A Child Is Born'},
  {bookId:23,chapter:11,beforeVerse:1,title:'The Branch from Jesse'},
  {bookId:23,chapter:14,beforeVerse:3,title:'The Fall of Lucifer'},
  {bookId:23,chapter:35,beforeVerse:1,title:'The Ransomed Shall Return'},
  {bookId:23,chapter:40,beforeVerse:1,title:"Comfort for God's People"},
  {bookId:23,chapter:40,beforeVerse:28,title:'Those Who Wait on the LORD'},
  {bookId:23,chapter:42,beforeVerse:1,title:'The Servant of the LORD'},
  {bookId:23,chapter:43,beforeVerse:1,title:"Israel's Only Savior"},
  {bookId:23,chapter:49,beforeVerse:1,title:"The Servant's Mission"},
  {bookId:23,chapter:52,beforeVerse:13,title:'The Suffering Servant'},
  {bookId:23,chapter:53,beforeVerse:1,title:'He Was Pierced for Our Transgressions'},
  {bookId:23,chapter:55,beforeVerse:1,title:'Come, All Who Are Thirsty'},
  {bookId:23,chapter:58,beforeVerse:1,title:'True Fasting'},
  {bookId:23,chapter:60,beforeVerse:1,title:'The Glory of Zion'},
  {bookId:23,chapter:61,beforeVerse:1,title:"The Year of the LORD's Favor"},
  {bookId:23,chapter:65,beforeVerse:17,title:'New Heavens and a New Earth'},
  // ── Jeremiah (24) ──
  {bookId:24,chapter:1,beforeVerse:1,title:'The Call of Jeremiah'},
  {bookId:24,chapter:7,beforeVerse:1,title:'The Temple Sermon'},
  {bookId:24,chapter:18,beforeVerse:1,title:'The Potter and the Clay'},
  {bookId:24,chapter:23,beforeVerse:1,title:'The Righteous Branch'},
  {bookId:24,chapter:29,beforeVerse:1,title:'A Letter to the Exiles'},
  {bookId:24,chapter:29,beforeVerse:11,title:'Plans to Prosper You'},
  {bookId:24,chapter:31,beforeVerse:1,title:'The New Covenant'},
  {bookId:24,chapter:39,beforeVerse:1,title:'The Fall of Jerusalem'},
  // ── Lamentations (25) ──
  {bookId:25,chapter:1,beforeVerse:1,title:"Jerusalem's Desolation"},
  {bookId:25,chapter:3,beforeVerse:1,title:"Hope in the LORD's Faithfulness"},
  {bookId:25,chapter:3,beforeVerse:22,title:'Great Is Your Faithfulness'},
  {bookId:25,chapter:5,beforeVerse:1,title:'A Prayer for Restoration'},
  // ── Ezekiel (26) ──
  {bookId:26,chapter:1,beforeVerse:1,title:"Ezekiel's Vision of God"},
  {bookId:26,chapter:2,beforeVerse:1,title:"Ezekiel's Call"},
  {bookId:26,chapter:34,beforeVerse:1,title:'The Shepherds and the Sheep'},
  {bookId:26,chapter:36,beforeVerse:22,title:'A New Heart and a New Spirit'},
  {bookId:26,chapter:37,beforeVerse:1,title:'The Valley of Dry Bones'},
  {bookId:26,chapter:47,beforeVerse:1,title:'The River from the Temple'},
  // ── Daniel (27) ──
  {bookId:27,chapter:1,beforeVerse:1,title:"Daniel's Training in Babylon"},
  {bookId:27,chapter:2,beforeVerse:1,title:"Nebuchadnezzar's Dream"},
  {bookId:27,chapter:3,beforeVerse:1,title:'The Fiery Furnace'},
  {bookId:27,chapter:4,beforeVerse:1,title:"Nebuchadnezzar's Humbling"},
  {bookId:27,chapter:5,beforeVerse:1,title:'The Writing on the Wall'},
  {bookId:27,chapter:6,beforeVerse:1,title:"Daniel in the Lions' Den"},
  {bookId:27,chapter:7,beforeVerse:1,title:"Daniel's Vision of Four Beasts"},
  {bookId:27,chapter:7,beforeVerse:9,title:'The Son of Man'},
  {bookId:27,chapter:9,beforeVerse:1,title:"Daniel's Prayer"},
  {bookId:27,chapter:9,beforeVerse:20,title:'The Seventy Weeks'},
  {bookId:27,chapter:12,beforeVerse:1,title:'The Time of the End'},
  // ── Hosea (28) ──
  {bookId:28,chapter:1,beforeVerse:1,title:"Hosea's Unfaithful Wife"},
  {bookId:28,chapter:3,beforeVerse:1,title:"Hosea's Wife Redeemed"},
  {bookId:28,chapter:6,beforeVerse:1,title:'A Call to Repentance'},
  {bookId:28,chapter:11,beforeVerse:1,title:"God's Love for Israel"},
  // ── Joel (29) ──
  {bookId:29,chapter:1,beforeVerse:1,title:'A Plague of Locusts'},
  {bookId:29,chapter:2,beforeVerse:1,title:'The Day of the LORD'},
  {bookId:29,chapter:2,beforeVerse:28,title:'The Outpouring of the Spirit'},
  // ── Amos (30) ──
  {bookId:30,chapter:1,beforeVerse:1,title:'Judgments Against the Nations'},
  {bookId:30,chapter:5,beforeVerse:1,title:'Seek the LORD and Live'},
  {bookId:30,chapter:9,beforeVerse:11,title:"Israel's Restoration"},
  // ── Obadiah (31) ──
  {bookId:31,chapter:1,beforeVerse:1,title:'The Vision of Obadiah'},
  // ── Jonah (32) ──
  {bookId:32,chapter:1,beforeVerse:1,title:'Jonah Flees from the LORD'},
  {bookId:32,chapter:1,beforeVerse:17,title:'Jonah and the Great Fish'},
  {bookId:32,chapter:2,beforeVerse:1,title:"Jonah's Prayer"},
  {bookId:32,chapter:3,beforeVerse:1,title:'Jonah Goes to Nineveh'},
  {bookId:32,chapter:3,beforeVerse:5,title:'Nineveh Repents'},
  {bookId:32,chapter:4,beforeVerse:1,title:"Jonah's Anger"},
  // ── Micah (33) ──
  {bookId:33,chapter:4,beforeVerse:1,title:'The Mountain of the LORD'},
  {bookId:33,chapter:5,beforeVerse:2,title:'The Ruler from Bethlehem'},
  {bookId:33,chapter:6,beforeVerse:6,title:'Act Justly, Love Mercy'},
  // ── Nahum (34) ──
  {bookId:34,chapter:1,beforeVerse:1,title:"The LORD's Anger Against Nineveh"},
  // ── Habakkuk (35) ──
  {bookId:35,chapter:1,beforeVerse:1,title:"Habakkuk's Complaint"},
  {bookId:35,chapter:2,beforeVerse:1,title:'The Just Shall Live by Faith'},
  {bookId:35,chapter:3,beforeVerse:1,title:"Habakkuk's Prayer"},
  // ── Zephaniah (36) ──
  {bookId:36,chapter:1,beforeVerse:1,title:"The Day of the LORD's Judgment"},
  {bookId:36,chapter:3,beforeVerse:14,title:'The LORD Rejoices Over You'},
  // ── Haggai (37) ──
  {bookId:37,chapter:1,beforeVerse:1,title:'A Call to Rebuild the Temple'},
  {bookId:37,chapter:2,beforeVerse:1,title:'The Coming Glory of the Temple'},
  // ── Zechariah (38) ──
  {bookId:38,chapter:1,beforeVerse:1,title:'A Call to Return to the LORD'},
  {bookId:38,chapter:9,beforeVerse:9,title:"The Coming of Zion's King"},
  {bookId:38,chapter:12,beforeVerse:10,title:'They Will Look on the One They Pierced'},
  {bookId:38,chapter:14,beforeVerse:1,title:'The LORD Comes to Reign'},
  // ── Malachi (39) ──
  {bookId:39,chapter:1,beforeVerse:1,title:"The LORD's Love for Israel"},
  {bookId:39,chapter:3,beforeVerse:1,title:'The Messenger of the Covenant'},
  {bookId:39,chapter:3,beforeVerse:6,title:'Robbing God'},
  {bookId:39,chapter:4,beforeVerse:1,title:'The Day of the LORD'},
  {bookId:39,chapter:4,beforeVerse:5,title:'The Coming of Elijah'},
  // ── Matthew (40) ──
  {bookId:40,chapter:1,beforeVerse:1,title:'The Genealogy of Jesus'},
  {bookId:40,chapter:1,beforeVerse:18,title:'The Birth of Jesus Christ'},
  {bookId:40,chapter:2,beforeVerse:1,title:'The Visit of the Magi'},
  {bookId:40,chapter:2,beforeVerse:13,title:'The Flight to Egypt'},
  {bookId:40,chapter:2,beforeVerse:16,title:'The Massacre of Infants'},
  {bookId:40,chapter:2,beforeVerse:19,title:'The Return to Nazareth'},
  {bookId:40,chapter:3,beforeVerse:1,title:'John the Baptist Prepares the Way'},
  {bookId:40,chapter:3,beforeVerse:13,title:'The Baptism of Jesus'},
  {bookId:40,chapter:4,beforeVerse:1,title:'The Temptation of Jesus'},
  {bookId:40,chapter:4,beforeVerse:12,title:'Jesus Begins His Ministry'},
  {bookId:40,chapter:4,beforeVerse:18,title:'The Calling of the First Disciples'},
  {bookId:40,chapter:4,beforeVerse:23,title:'Jesus Heals the Sick'},
  {bookId:40,chapter:5,beforeVerse:1,title:'The Sermon on the Mount'},
  {bookId:40,chapter:5,beforeVerse:3,title:'The Beatitudes'},
  {bookId:40,chapter:5,beforeVerse:13,title:'Salt and Light'},
  {bookId:40,chapter:5,beforeVerse:17,title:'Fulfillment of the Law'},
  {bookId:40,chapter:5,beforeVerse:21,title:'Murder and Anger'},
  {bookId:40,chapter:5,beforeVerse:27,title:'Adultery and Lust'},
  {bookId:40,chapter:5,beforeVerse:38,title:'An Eye for an Eye'},
  {bookId:40,chapter:5,beforeVerse:43,title:'Love Your Enemies'},
  {bookId:40,chapter:6,beforeVerse:1,title:'Giving to the Needy'},
  {bookId:40,chapter:6,beforeVerse:5,title:'How to Pray'},
  {bookId:40,chapter:6,beforeVerse:9,title:"The Lord's Prayer"},
  {bookId:40,chapter:6,beforeVerse:16,title:'Fasting'},
  {bookId:40,chapter:6,beforeVerse:19,title:'Treasures in Heaven'},
  {bookId:40,chapter:6,beforeVerse:25,title:'Do Not Worry'},
  {bookId:40,chapter:7,beforeVerse:1,title:'Judging Others'},
  {bookId:40,chapter:7,beforeVerse:7,title:'Ask, Seek, Knock'},
  {bookId:40,chapter:7,beforeVerse:12,title:'The Golden Rule'},
  {bookId:40,chapter:7,beforeVerse:13,title:'The Narrow Gate'},
  {bookId:40,chapter:7,beforeVerse:15,title:'A Tree and Its Fruit'},
  {bookId:40,chapter:7,beforeVerse:21,title:'I Never Knew You'},
  {bookId:40,chapter:7,beforeVerse:24,title:'The Wise and Foolish Builders'},
  {bookId:40,chapter:8,beforeVerse:1,title:'Jesus Cleanses a Leper'},
  {bookId:40,chapter:8,beforeVerse:5,title:"The Centurion's Faith"},
  {bookId:40,chapter:8,beforeVerse:14,title:'Jesus Heals Many'},
  {bookId:40,chapter:8,beforeVerse:18,title:'The Cost of Following Jesus'},
  {bookId:40,chapter:8,beforeVerse:23,title:'Jesus Calms the Storm'},
  {bookId:40,chapter:9,beforeVerse:1,title:'Jesus Heals a Paralytic'},
  {bookId:40,chapter:9,beforeVerse:9,title:'The Calling of Matthew'},
  {bookId:40,chapter:9,beforeVerse:14,title:'A Question About Fasting'},
  {bookId:40,chapter:9,beforeVerse:35,title:'The Harvest Is Plentiful'},
  {bookId:40,chapter:10,beforeVerse:1,title:'Jesus Sends Out the Twelve'},
  {bookId:40,chapter:10,beforeVerse:26,title:'Fear God, Not Man'},
  {bookId:40,chapter:11,beforeVerse:1,title:'Jesus and John the Baptist'},
  {bookId:40,chapter:11,beforeVerse:25,title:'Come to Me, All Who Are Weary'},
  {bookId:40,chapter:12,beforeVerse:1,title:'Lord of the Sabbath'},
  {bookId:40,chapter:12,beforeVerse:22,title:'A House Divided'},
  {bookId:40,chapter:12,beforeVerse:38,title:'The Sign of Jonah'},
  {bookId:40,chapter:13,beforeVerse:1,title:'The Parable of the Sower'},
  {bookId:40,chapter:13,beforeVerse:24,title:'The Parable of the Weeds'},
  {bookId:40,chapter:13,beforeVerse:31,title:'The Mustard Seed and Leaven'},
  {bookId:40,chapter:13,beforeVerse:44,title:'Hidden Treasure and the Pearl'},
  {bookId:40,chapter:13,beforeVerse:53,title:'Jesus Rejected at Nazareth'},
  {bookId:40,chapter:14,beforeVerse:1,title:'The Death of John the Baptist'},
  {bookId:40,chapter:14,beforeVerse:13,title:'Jesus Feeds the Five Thousand'},
  {bookId:40,chapter:14,beforeVerse:22,title:'Jesus Walks on Water'},
  {bookId:40,chapter:15,beforeVerse:1,title:'Clean and Unclean'},
  {bookId:40,chapter:15,beforeVerse:21,title:'The Faith of the Canaanite Woman'},
  {bookId:40,chapter:15,beforeVerse:32,title:'Jesus Feeds the Four Thousand'},
  {bookId:40,chapter:16,beforeVerse:13,title:"Peter's Confession of Christ"},
  {bookId:40,chapter:16,beforeVerse:21,title:'Jesus Predicts His Death'},
  {bookId:40,chapter:16,beforeVerse:24,title:'Take Up Your Cross'},
  {bookId:40,chapter:17,beforeVerse:1,title:'The Transfiguration'},
  {bookId:40,chapter:17,beforeVerse:14,title:'Jesus Heals a Boy with a Demon'},
  {bookId:40,chapter:18,beforeVerse:1,title:'Who Is the Greatest?'},
  {bookId:40,chapter:18,beforeVerse:10,title:'The Parable of the Lost Sheep'},
  {bookId:40,chapter:18,beforeVerse:15,title:'If Your Brother Sins Against You'},
  {bookId:40,chapter:18,beforeVerse:21,title:'The Parable of the Unforgiving Servant'},
  {bookId:40,chapter:19,beforeVerse:1,title:'Jesus Teaches on Divorce'},
  {bookId:40,chapter:19,beforeVerse:13,title:'Let the Little Children Come'},
  {bookId:40,chapter:19,beforeVerse:16,title:'The Rich Young Man'},
  {bookId:40,chapter:20,beforeVerse:1,title:'The Parable of the Workers'},
  {bookId:40,chapter:20,beforeVerse:29,title:'Two Blind Men Healed'},
  {bookId:40,chapter:21,beforeVerse:1,title:'The Triumphal Entry'},
  {bookId:40,chapter:21,beforeVerse:12,title:'Jesus Cleanses the Temple'},
  {bookId:40,chapter:21,beforeVerse:18,title:'The Fig Tree Withers'},
  {bookId:40,chapter:21,beforeVerse:23,title:'The Authority of Jesus Questioned'},
  {bookId:40,chapter:21,beforeVerse:33,title:'The Parable of the Tenants'},
  {bookId:40,chapter:22,beforeVerse:1,title:'The Parable of the Wedding Feast'},
  {bookId:40,chapter:22,beforeVerse:15,title:'Paying Taxes to Caesar'},
  {bookId:40,chapter:22,beforeVerse:34,title:'The Greatest Commandment'},
  {bookId:40,chapter:23,beforeVerse:1,title:'Woe to the Scribes and Pharisees'},
  {bookId:40,chapter:23,beforeVerse:37,title:'Jesus Laments over Jerusalem'},
  {bookId:40,chapter:24,beforeVerse:1,title:'Signs of the End of the Age'},
  {bookId:40,chapter:24,beforeVerse:36,title:'No One Knows the Day or Hour'},
  {bookId:40,chapter:25,beforeVerse:1,title:'The Parable of the Ten Virgins'},
  {bookId:40,chapter:25,beforeVerse:14,title:'The Parable of the Talents'},
  {bookId:40,chapter:25,beforeVerse:31,title:'The Sheep and the Goats'},
  {bookId:40,chapter:26,beforeVerse:1,title:'The Plot to Kill Jesus'},
  {bookId:40,chapter:26,beforeVerse:6,title:'Jesus Anointed at Bethany'},
  {bookId:40,chapter:26,beforeVerse:14,title:'Judas Agrees to Betray Jesus'},
  {bookId:40,chapter:26,beforeVerse:17,title:'The Last Supper'},
  {bookId:40,chapter:26,beforeVerse:36,title:'Jesus in Gethsemane'},
  {bookId:40,chapter:26,beforeVerse:47,title:'The Betrayal and Arrest'},
  {bookId:40,chapter:26,beforeVerse:57,title:'Jesus Before Caiaphas'},
  {bookId:40,chapter:26,beforeVerse:69,title:'Peter Denies Jesus'},
  {bookId:40,chapter:27,beforeVerse:1,title:'Jesus Before Pilate'},
  {bookId:40,chapter:27,beforeVerse:3,title:'The Death of Judas'},
  {bookId:40,chapter:27,beforeVerse:27,title:'The Soldiers Mock Jesus'},
  {bookId:40,chapter:27,beforeVerse:32,title:'The Crucifixion'},
  {bookId:40,chapter:27,beforeVerse:45,title:'The Death of Jesus'},
  {bookId:40,chapter:27,beforeVerse:57,title:'The Burial of Jesus'},
  {bookId:40,chapter:28,beforeVerse:1,title:'The Resurrection'},
  {bookId:40,chapter:28,beforeVerse:16,title:'The Great Commission'},
  // ── Mark (41) ──
  {bookId:41,chapter:1,beforeVerse:1,title:'John the Baptist Prepares the Way'},
  {bookId:41,chapter:1,beforeVerse:9,title:'The Baptism of Jesus'},
  {bookId:41,chapter:1,beforeVerse:12,title:'The Temptation of Jesus'},
  {bookId:41,chapter:1,beforeVerse:16,title:'The Calling of the First Disciples'},
  {bookId:41,chapter:1,beforeVerse:21,title:'Jesus Drives Out an Evil Spirit'},
  {bookId:41,chapter:1,beforeVerse:29,title:'Jesus Heals Many'},
  {bookId:41,chapter:1,beforeVerse:40,title:'Jesus Cleanses a Leper'},
  {bookId:41,chapter:2,beforeVerse:1,title:'Jesus Heals a Paralytic'},
  {bookId:41,chapter:2,beforeVerse:13,title:'The Calling of Levi'},
  {bookId:41,chapter:2,beforeVerse:23,title:'Lord of the Sabbath'},
  {bookId:41,chapter:3,beforeVerse:13,title:'Jesus Appoints the Twelve'},
  {bookId:41,chapter:3,beforeVerse:20,title:'Jesus and Beelzebul'},
  {bookId:41,chapter:4,beforeVerse:1,title:'The Parable of the Sower'},
  {bookId:41,chapter:4,beforeVerse:30,title:'The Parable of the Mustard Seed'},
  {bookId:41,chapter:4,beforeVerse:35,title:'Jesus Calms the Storm'},
  {bookId:41,chapter:5,beforeVerse:1,title:'Jesus Heals a Demon-Possessed Man'},
  {bookId:41,chapter:5,beforeVerse:21,title:'A Dead Girl and a Sick Woman'},
  {bookId:41,chapter:6,beforeVerse:1,title:'Jesus Rejected at Nazareth'},
  {bookId:41,chapter:6,beforeVerse:7,title:'Jesus Sends Out the Twelve'},
  {bookId:41,chapter:6,beforeVerse:14,title:'The Death of John the Baptist'},
  {bookId:41,chapter:6,beforeVerse:30,title:'Jesus Feeds the Five Thousand'},
  {bookId:41,chapter:6,beforeVerse:45,title:'Jesus Walks on Water'},
  {bookId:41,chapter:7,beforeVerse:1,title:'Clean and Unclean'},
  {bookId:41,chapter:7,beforeVerse:24,title:'The Faith of a Gentile Woman'},
  {bookId:41,chapter:8,beforeVerse:1,title:'Jesus Feeds the Four Thousand'},
  {bookId:41,chapter:8,beforeVerse:22,title:'Jesus Heals a Blind Man'},
  {bookId:41,chapter:8,beforeVerse:27,title:"Peter's Confession of Christ"},
  {bookId:41,chapter:8,beforeVerse:31,title:'Jesus Predicts His Death'},
  {bookId:41,chapter:8,beforeVerse:34,title:'Take Up Your Cross'},
  {bookId:41,chapter:9,beforeVerse:1,title:'The Transfiguration'},
  {bookId:41,chapter:9,beforeVerse:14,title:'Jesus Heals a Boy with a Demon'},
  {bookId:41,chapter:9,beforeVerse:33,title:'Who Is the Greatest?'},
  {bookId:41,chapter:10,beforeVerse:1,title:'Jesus Teaches on Divorce'},
  {bookId:41,chapter:10,beforeVerse:13,title:'Let the Little Children Come'},
  {bookId:41,chapter:10,beforeVerse:17,title:'The Rich Young Man'},
  {bookId:41,chapter:10,beforeVerse:35,title:'The Request of James and John'},
  {bookId:41,chapter:10,beforeVerse:46,title:'Blind Bartimaeus'},
  {bookId:41,chapter:11,beforeVerse:1,title:'The Triumphal Entry'},
  {bookId:41,chapter:11,beforeVerse:15,title:'Jesus Cleanses the Temple'},
  {bookId:41,chapter:11,beforeVerse:27,title:'The Authority of Jesus Questioned'},
  {bookId:41,chapter:12,beforeVerse:1,title:'The Parable of the Tenants'},
  {bookId:41,chapter:12,beforeVerse:13,title:'Paying Taxes to Caesar'},
  {bookId:41,chapter:12,beforeVerse:28,title:'The Greatest Commandment'},
  {bookId:41,chapter:12,beforeVerse:41,title:"The Widow's Offering"},
  {bookId:41,chapter:13,beforeVerse:1,title:'Signs of the End of the Age'},
  {bookId:41,chapter:14,beforeVerse:1,title:'The Plot to Kill Jesus'},
  {bookId:41,chapter:14,beforeVerse:3,title:'Jesus Anointed at Bethany'},
  {bookId:41,chapter:14,beforeVerse:12,title:'The Last Supper'},
  {bookId:41,chapter:14,beforeVerse:32,title:'Jesus in Gethsemane'},
  {bookId:41,chapter:14,beforeVerse:43,title:'The Betrayal and Arrest'},
  {bookId:41,chapter:14,beforeVerse:53,title:'Jesus Before the Sanhedrin'},
  {bookId:41,chapter:14,beforeVerse:66,title:'Peter Denies Jesus'},
  {bookId:41,chapter:15,beforeVerse:1,title:'Jesus Before Pilate'},
  {bookId:41,chapter:15,beforeVerse:16,title:'The Soldiers Mock Jesus'},
  {bookId:41,chapter:15,beforeVerse:21,title:'The Crucifixion'},
  {bookId:41,chapter:15,beforeVerse:33,title:'The Death of Jesus'},
  {bookId:41,chapter:15,beforeVerse:42,title:'The Burial of Jesus'},
  {bookId:41,chapter:16,beforeVerse:1,title:'The Resurrection'},
  {bookId:41,chapter:16,beforeVerse:19,title:'The Ascension'},
  // ── Luke (42) ──
  {bookId:42,chapter:1,beforeVerse:5,title:'The Birth of John Foretold'},
  {bookId:42,chapter:1,beforeVerse:26,title:'The Birth of Jesus Foretold'},
  {bookId:42,chapter:1,beforeVerse:39,title:'Mary Visits Elizabeth'},
  {bookId:42,chapter:1,beforeVerse:46,title:"Mary's Song"},
  {bookId:42,chapter:1,beforeVerse:57,title:'The Birth of John the Baptist'},
  {bookId:42,chapter:1,beforeVerse:67,title:"Zechariah's Song"},
  {bookId:42,chapter:2,beforeVerse:1,title:'The Birth of Jesus'},
  {bookId:42,chapter:2,beforeVerse:8,title:'The Shepherds and the Angels'},
  {bookId:42,chapter:2,beforeVerse:21,title:'Jesus Presented at the Temple'},
  {bookId:42,chapter:2,beforeVerse:41,title:'The Boy Jesus at the Temple'},
  {bookId:42,chapter:3,beforeVerse:1,title:'John the Baptist Prepares the Way'},
  {bookId:42,chapter:3,beforeVerse:21,title:'The Baptism of Jesus'},
  {bookId:42,chapter:4,beforeVerse:1,title:'The Temptation of Jesus'},
  {bookId:42,chapter:4,beforeVerse:14,title:'Jesus Rejected at Nazareth'},
  {bookId:42,chapter:4,beforeVerse:38,title:'Jesus Heals Many'},
  {bookId:42,chapter:5,beforeVerse:1,title:'The Calling of the First Disciples'},
  {bookId:42,chapter:5,beforeVerse:12,title:'Jesus Cleanses a Leper'},
  {bookId:42,chapter:5,beforeVerse:17,title:'Jesus Heals a Paralytic'},
  {bookId:42,chapter:5,beforeVerse:27,title:'The Calling of Levi'},
  {bookId:42,chapter:6,beforeVerse:1,title:'Lord of the Sabbath'},
  {bookId:42,chapter:6,beforeVerse:12,title:'Jesus Appoints the Twelve'},
  {bookId:42,chapter:6,beforeVerse:17,title:'Blessings and Woes'},
  {bookId:42,chapter:6,beforeVerse:27,title:'Love Your Enemies'},
  {bookId:42,chapter:6,beforeVerse:46,title:'The Wise and Foolish Builders'},
  {bookId:42,chapter:7,beforeVerse:1,title:"The Centurion's Faith"},
  {bookId:42,chapter:7,beforeVerse:11,title:"Jesus Raises a Widow's Son"},
  {bookId:42,chapter:7,beforeVerse:18,title:'Jesus and John the Baptist'},
  {bookId:42,chapter:7,beforeVerse:36,title:'Jesus Anointed by a Sinful Woman'},
  {bookId:42,chapter:8,beforeVerse:1,title:'The Parable of the Sower'},
  {bookId:42,chapter:8,beforeVerse:22,title:'Jesus Calms the Storm'},
  {bookId:42,chapter:8,beforeVerse:26,title:'Jesus Heals a Demon-Possessed Man'},
  {bookId:42,chapter:8,beforeVerse:40,title:'A Dead Girl and a Sick Woman'},
  {bookId:42,chapter:9,beforeVerse:1,title:'Jesus Sends Out the Twelve'},
  {bookId:42,chapter:9,beforeVerse:10,title:'Jesus Feeds the Five Thousand'},
  {bookId:42,chapter:9,beforeVerse:18,title:"Peter's Confession of Christ"},
  {bookId:42,chapter:9,beforeVerse:23,title:'Take Up Your Cross'},
  {bookId:42,chapter:9,beforeVerse:28,title:'The Transfiguration'},
  {bookId:42,chapter:9,beforeVerse:37,title:'Jesus Heals a Boy with a Demon'},
  {bookId:42,chapter:9,beforeVerse:51,title:'The Cost of Following Jesus'},
  {bookId:42,chapter:10,beforeVerse:1,title:'Jesus Sends Out the Seventy-Two'},
  {bookId:42,chapter:10,beforeVerse:25,title:'The Parable of the Good Samaritan'},
  {bookId:42,chapter:10,beforeVerse:38,title:'Mary and Martha'},
  {bookId:42,chapter:11,beforeVerse:1,title:'Jesus Teaches on Prayer'},
  {bookId:42,chapter:12,beforeVerse:13,title:'The Parable of the Rich Fool'},
  {bookId:42,chapter:12,beforeVerse:22,title:'Do Not Worry'},
  {bookId:42,chapter:13,beforeVerse:1,title:'Repent or Perish'},
  {bookId:42,chapter:13,beforeVerse:22,title:'The Narrow Door'},
  {bookId:42,chapter:14,beforeVerse:15,title:'The Parable of the Great Banquet'},
  {bookId:42,chapter:14,beforeVerse:25,title:'The Cost of Discipleship'},
  {bookId:42,chapter:15,beforeVerse:1,title:'The Parable of the Lost Sheep'},
  {bookId:42,chapter:15,beforeVerse:8,title:'The Parable of the Lost Coin'},
  {bookId:42,chapter:15,beforeVerse:11,title:'The Parable of the Prodigal Son'},
  {bookId:42,chapter:16,beforeVerse:1,title:'The Shrewd Manager'},
  {bookId:42,chapter:16,beforeVerse:19,title:'The Rich Man and Lazarus'},
  {bookId:42,chapter:17,beforeVerse:11,title:'Ten Lepers Cleansed'},
  {bookId:42,chapter:18,beforeVerse:1,title:'The Persistent Widow'},
  {bookId:42,chapter:18,beforeVerse:9,title:'The Pharisee and the Tax Collector'},
  {bookId:42,chapter:18,beforeVerse:15,title:'Let the Little Children Come'},
  {bookId:42,chapter:18,beforeVerse:18,title:'The Rich Ruler'},
  {bookId:42,chapter:18,beforeVerse:35,title:'A Blind Beggar Healed'},
  {bookId:42,chapter:19,beforeVerse:1,title:'Jesus and Zacchaeus'},
  {bookId:42,chapter:19,beforeVerse:11,title:'The Parable of the Ten Minas'},
  {bookId:42,chapter:19,beforeVerse:28,title:'The Triumphal Entry'},
  {bookId:42,chapter:19,beforeVerse:41,title:'Jesus Weeps over Jerusalem'},
  {bookId:42,chapter:19,beforeVerse:45,title:'Jesus Cleanses the Temple'},
  {bookId:42,chapter:20,beforeVerse:9,title:'The Parable of the Tenants'},
  {bookId:42,chapter:20,beforeVerse:20,title:'Paying Taxes to Caesar'},
  {bookId:42,chapter:21,beforeVerse:1,title:"The Widow's Offering"},
  {bookId:42,chapter:21,beforeVerse:5,title:'Signs of the End of the Age'},
  {bookId:42,chapter:22,beforeVerse:1,title:'Judas Agrees to Betray Jesus'},
  {bookId:42,chapter:22,beforeVerse:7,title:'The Last Supper'},
  {bookId:42,chapter:22,beforeVerse:39,title:'Jesus on the Mount of Olives'},
  {bookId:42,chapter:22,beforeVerse:47,title:'The Betrayal and Arrest'},
  {bookId:42,chapter:22,beforeVerse:54,title:'Peter Denies Jesus'},
  {bookId:42,chapter:23,beforeVerse:1,title:'Jesus Before Pilate'},
  {bookId:42,chapter:23,beforeVerse:26,title:'The Crucifixion'},
  {bookId:42,chapter:23,beforeVerse:44,title:'The Death of Jesus'},
  {bookId:42,chapter:23,beforeVerse:50,title:'The Burial of Jesus'},
  {bookId:42,chapter:24,beforeVerse:1,title:'The Resurrection'},
  {bookId:42,chapter:24,beforeVerse:13,title:'On the Road to Emmaus'},
  {bookId:42,chapter:24,beforeVerse:36,title:'Jesus Appears to the Disciples'},
  {bookId:42,chapter:24,beforeVerse:50,title:'The Ascension'},
  // ── John (43) ──
  {bookId:43,chapter:1,beforeVerse:1,title:'The Word Became Flesh'},
  {bookId:43,chapter:1,beforeVerse:19,title:"John's Witness"},
  {bookId:43,chapter:1,beforeVerse:29,title:'The Lamb of God'},
  {bookId:43,chapter:1,beforeVerse:35,title:'The First Disciples'},
  {bookId:43,chapter:1,beforeVerse:43,title:'Jesus Calls Philip and Nathanael'},
  {bookId:43,chapter:2,beforeVerse:1,title:'The Wedding at Cana'},
  {bookId:43,chapter:2,beforeVerse:13,title:'Jesus Cleanses the Temple'},
  {bookId:43,chapter:3,beforeVerse:1,title:'Jesus and Nicodemus'},
  {bookId:43,chapter:3,beforeVerse:16,title:'For God So Loved the World'},
  {bookId:43,chapter:4,beforeVerse:1,title:'Jesus and the Samaritan Woman'},
  {bookId:43,chapter:4,beforeVerse:43,title:"Jesus Heals an Official's Son"},
  {bookId:43,chapter:5,beforeVerse:1,title:'Jesus Heals at the Pool of Bethesda'},
  {bookId:43,chapter:5,beforeVerse:16,title:'The Authority of the Son'},
  {bookId:43,chapter:6,beforeVerse:1,title:'Jesus Feeds the Five Thousand'},
  {bookId:43,chapter:6,beforeVerse:16,title:'Jesus Walks on Water'},
  {bookId:43,chapter:6,beforeVerse:22,title:'I Am the Bread of Life'},
  {bookId:43,chapter:6,beforeVerse:60,title:'Many Disciples Turn Away'},
  {bookId:43,chapter:7,beforeVerse:1,title:'Jesus at the Feast of Tabernacles'},
  {bookId:43,chapter:7,beforeVerse:37,title:'Rivers of Living Water'},
  {bookId:43,chapter:8,beforeVerse:1,title:'The Woman Caught in Adultery'},
  {bookId:43,chapter:8,beforeVerse:12,title:'I Am the Light of the World'},
  {bookId:43,chapter:8,beforeVerse:31,title:'The Truth Will Set You Free'},
  {bookId:43,chapter:8,beforeVerse:48,title:'Before Abraham Was, I Am'},
  {bookId:43,chapter:9,beforeVerse:1,title:'Jesus Heals a Man Born Blind'},
  {bookId:43,chapter:9,beforeVerse:13,title:'The Pharisees Investigate'},
  {bookId:43,chapter:9,beforeVerse:35,title:'Spiritual Blindness'},
  {bookId:43,chapter:10,beforeVerse:1,title:'The Good Shepherd'},
  {bookId:43,chapter:10,beforeVerse:22,title:'I and the Father Are One'},
  {bookId:43,chapter:11,beforeVerse:1,title:'The Death of Lazarus'},
  {bookId:43,chapter:11,beforeVerse:17,title:'I Am the Resurrection and the Life'},
  {bookId:43,chapter:11,beforeVerse:38,title:'Jesus Raises Lazarus'},
  {bookId:43,chapter:11,beforeVerse:45,title:'The Plot to Kill Jesus'},
  {bookId:43,chapter:12,beforeVerse:1,title:'Jesus Anointed at Bethany'},
  {bookId:43,chapter:12,beforeVerse:12,title:'The Triumphal Entry'},
  {bookId:43,chapter:12,beforeVerse:20,title:'Jesus Predicts His Death'},
  {bookId:43,chapter:13,beforeVerse:1,title:"Jesus Washes the Disciples' Feet"},
  {bookId:43,chapter:13,beforeVerse:18,title:'Jesus Predicts His Betrayal'},
  {bookId:43,chapter:13,beforeVerse:31,title:'A New Commandment'},
  {bookId:43,chapter:14,beforeVerse:1,title:'I Am the Way, the Truth, and the Life'},
  {bookId:43,chapter:14,beforeVerse:15,title:'The Promise of the Holy Spirit'},
  {bookId:43,chapter:14,beforeVerse:27,title:'Peace I Leave with You'},
  {bookId:43,chapter:15,beforeVerse:1,title:'I Am the True Vine'},
  {bookId:43,chapter:15,beforeVerse:18,title:"The World's Hatred"},
  {bookId:43,chapter:16,beforeVerse:5,title:'The Holy Spirit Will Come'},
  {bookId:43,chapter:16,beforeVerse:33,title:'I Have Overcome the World'},
  {bookId:43,chapter:17,beforeVerse:1,title:'Jesus Prays for Himself'},
  {bookId:43,chapter:17,beforeVerse:6,title:'Jesus Prays for His Disciples'},
  {bookId:43,chapter:17,beforeVerse:20,title:'Jesus Prays for All Believers'},
  {bookId:43,chapter:18,beforeVerse:1,title:'The Betrayal and Arrest'},
  {bookId:43,chapter:18,beforeVerse:15,title:'Peter Denies Jesus'},
  {bookId:43,chapter:18,beforeVerse:28,title:'Jesus Before Pilate'},
  {bookId:43,chapter:19,beforeVerse:1,title:'Jesus Sentenced to Be Crucified'},
  {bookId:43,chapter:19,beforeVerse:16,title:'The Crucifixion'},
  {bookId:43,chapter:19,beforeVerse:28,title:'The Death of Jesus'},
  {bookId:43,chapter:19,beforeVerse:38,title:'The Burial of Jesus'},
  {bookId:43,chapter:20,beforeVerse:1,title:'The Empty Tomb'},
  {bookId:43,chapter:20,beforeVerse:10,title:'Jesus Appears to Mary Magdalene'},
  {bookId:43,chapter:20,beforeVerse:19,title:'Jesus Appears to the Disciples'},
  {bookId:43,chapter:20,beforeVerse:24,title:'Jesus and Thomas'},
  {bookId:43,chapter:21,beforeVerse:1,title:'Jesus Appears at the Sea of Galilee'},
  {bookId:43,chapter:21,beforeVerse:15,title:'Jesus Restores Peter'},
  // ── Acts (44) ──
  {bookId:44,chapter:1,beforeVerse:1,title:'Jesus Taken Up to Heaven'},
  {bookId:44,chapter:1,beforeVerse:12,title:'Matthias Chosen to Replace Judas'},
  {bookId:44,chapter:2,beforeVerse:1,title:'The Day of Pentecost'},
  {bookId:44,chapter:2,beforeVerse:14,title:"Peter's Sermon"},
  {bookId:44,chapter:2,beforeVerse:37,title:'Three Thousand Believe'},
  {bookId:44,chapter:2,beforeVerse:42,title:'The Fellowship of Believers'},
  {bookId:44,chapter:3,beforeVerse:1,title:'Peter Heals a Lame Beggar'},
  {bookId:44,chapter:4,beforeVerse:1,title:'Peter and John Before the Council'},
  {bookId:44,chapter:4,beforeVerse:32,title:'All Things in Common'},
  {bookId:44,chapter:5,beforeVerse:1,title:'Ananias and Sapphira'},
  {bookId:44,chapter:5,beforeVerse:17,title:'The Apostles Persecuted'},
  {bookId:44,chapter:5,beforeVerse:33,title:"Gamaliel's Counsel"},
  {bookId:44,chapter:6,beforeVerse:1,title:'Seven Chosen to Serve'},
  {bookId:44,chapter:6,beforeVerse:8,title:'Stephen Arrested'},
  {bookId:44,chapter:7,beforeVerse:1,title:"Stephen's Speech"},
  {bookId:44,chapter:7,beforeVerse:54,title:'The Stoning of Stephen'},
  {bookId:44,chapter:8,beforeVerse:1,title:'The Church Scattered'},
  {bookId:44,chapter:8,beforeVerse:4,title:'Philip in Samaria'},
  {bookId:44,chapter:8,beforeVerse:26,title:'Philip and the Ethiopian'},
  {bookId:44,chapter:9,beforeVerse:1,title:'The Conversion of Saul'},
  {bookId:44,chapter:9,beforeVerse:19,title:'Saul Preaches in Damascus'},
  {bookId:44,chapter:9,beforeVerse:32,title:'Peter Heals Aeneas and Dorcas'},
  {bookId:44,chapter:10,beforeVerse:1,title:'Cornelius Calls for Peter'},
  {bookId:44,chapter:10,beforeVerse:9,title:"Peter's Vision"},
  {bookId:44,chapter:10,beforeVerse:34,title:"Peter's Sermon to the Gentiles"},
  {bookId:44,chapter:10,beforeVerse:44,title:'The Holy Spirit Falls on the Gentiles'},
  {bookId:44,chapter:11,beforeVerse:19,title:'The Church in Antioch'},
  {bookId:44,chapter:12,beforeVerse:1,title:"Peter's Miraculous Escape"},
  {bookId:44,chapter:13,beforeVerse:1,title:'Barnabas and Saul Sent Off'},
  {bookId:44,chapter:13,beforeVerse:13,title:"Paul's Sermon in Antioch"},
  {bookId:44,chapter:14,beforeVerse:8,title:'Paul and Barnabas in Lystra'},
  {bookId:44,chapter:15,beforeVerse:1,title:'The Council at Jerusalem'},
  {bookId:44,chapter:15,beforeVerse:36,title:'Paul and Barnabas Separate'},
  {bookId:44,chapter:16,beforeVerse:1,title:'Timothy Joins Paul and Silas'},
  {bookId:44,chapter:16,beforeVerse:6,title:'The Macedonian Call'},
  {bookId:44,chapter:16,beforeVerse:11,title:'The Conversion of Lydia'},
  {bookId:44,chapter:16,beforeVerse:16,title:'Paul and Silas in Prison'},
  {bookId:44,chapter:16,beforeVerse:25,title:'The Philippian Jailer Converted'},
  {bookId:44,chapter:17,beforeVerse:1,title:'Paul in Thessalonica'},
  {bookId:44,chapter:17,beforeVerse:10,title:'Paul in Berea'},
  {bookId:44,chapter:17,beforeVerse:16,title:'Paul in Athens'},
  {bookId:44,chapter:17,beforeVerse:22,title:"Paul's Sermon on Mars Hill"},
  {bookId:44,chapter:18,beforeVerse:1,title:'Paul in Corinth'},
  {bookId:44,chapter:18,beforeVerse:24,title:'Apollos in Ephesus'},
  {bookId:44,chapter:19,beforeVerse:1,title:'Paul in Ephesus'},
  {bookId:44,chapter:19,beforeVerse:23,title:'The Riot in Ephesus'},
  {bookId:44,chapter:20,beforeVerse:7,title:'Eutychus Raised from the Dead'},
  {bookId:44,chapter:20,beforeVerse:17,title:'Farewell to the Ephesian Elders'},
  {bookId:44,chapter:21,beforeVerse:27,title:'Paul Arrested in the Temple'},
  {bookId:44,chapter:22,beforeVerse:1,title:"Paul's Defense"},
  {bookId:44,chapter:23,beforeVerse:12,title:'The Plot to Kill Paul'},
  {bookId:44,chapter:25,beforeVerse:13,title:'Paul Before Agrippa'},
  {bookId:44,chapter:27,beforeVerse:1,title:'Paul Sails for Rome'},
  {bookId:44,chapter:27,beforeVerse:13,title:'The Storm at Sea'},
  {bookId:44,chapter:27,beforeVerse:39,title:'The Shipwreck'},
  {bookId:44,chapter:28,beforeVerse:1,title:'Paul on Malta'},
  {bookId:44,chapter:28,beforeVerse:11,title:'Paul Arrives in Rome'},
  // ── Romans (45) ──
  {bookId:45,chapter:1,beforeVerse:1,title:"Paul's Greeting to Rome"},
  {bookId:45,chapter:1,beforeVerse:16,title:'The Righteous Shall Live by Faith'},
  {bookId:45,chapter:1,beforeVerse:18,title:"God's Wrath Against Sin"},
  {bookId:45,chapter:2,beforeVerse:1,title:"God's Righteous Judgment"},
  {bookId:45,chapter:3,beforeVerse:9,title:'No One Is Righteous'},
  {bookId:45,chapter:3,beforeVerse:21,title:'Righteousness Through Faith'},
  {bookId:45,chapter:4,beforeVerse:1,title:'Abraham Justified by Faith'},
  {bookId:45,chapter:5,beforeVerse:1,title:'Peace and Hope Through Christ'},
  {bookId:45,chapter:5,beforeVerse:12,title:'Death Through Adam, Life Through Christ'},
  {bookId:45,chapter:6,beforeVerse:1,title:'Dead to Sin, Alive in Christ'},
  {bookId:45,chapter:7,beforeVerse:1,title:'Released from the Law'},
  {bookId:45,chapter:7,beforeVerse:14,title:'The Struggle with Sin'},
  {bookId:45,chapter:8,beforeVerse:1,title:'Life in the Spirit'},
  {bookId:45,chapter:8,beforeVerse:18,title:'Future Glory'},
  {bookId:45,chapter:8,beforeVerse:28,title:'All Things Work for Good'},
  {bookId:45,chapter:8,beforeVerse:31,title:'More Than Conquerors'},
  {bookId:45,chapter:9,beforeVerse:1,title:"Paul's Sorrow for Israel"},
  {bookId:45,chapter:9,beforeVerse:6,title:"God's Sovereign Choice"},
  {bookId:45,chapter:10,beforeVerse:1,title:'Salvation for All Who Believe'},
  {bookId:45,chapter:11,beforeVerse:1,title:'The Remnant of Israel'},
  {bookId:45,chapter:11,beforeVerse:17,title:'The Olive Tree'},
  {bookId:45,chapter:11,beforeVerse:33,title:'A Hymn of Praise'},
  {bookId:45,chapter:12,beforeVerse:1,title:'Living Sacrifices'},
  {bookId:45,chapter:12,beforeVerse:9,title:'Marks of a True Christian'},
  {bookId:45,chapter:13,beforeVerse:1,title:'Submission to Authorities'},
  {bookId:45,chapter:13,beforeVerse:8,title:'Love Fulfills the Law'},
  {bookId:45,chapter:14,beforeVerse:1,title:'The Weak and the Strong'},
  {bookId:45,chapter:15,beforeVerse:14,title:"Paul's Ministry to the Gentiles"},
  {bookId:45,chapter:16,beforeVerse:1,title:'Personal Greetings'},
  {bookId:45,chapter:16,beforeVerse:25,title:'Final Doxology'},
  // ── 1 Corinthians (46) ──
  {bookId:46,chapter:1,beforeVerse:10,title:'Divisions in the Church'},
  {bookId:46,chapter:1,beforeVerse:18,title:'Christ the Wisdom of God'},
  {bookId:46,chapter:2,beforeVerse:6,title:'Wisdom from the Spirit'},
  {bookId:46,chapter:3,beforeVerse:10,title:'The Foundation Is Christ'},
  {bookId:46,chapter:5,beforeVerse:1,title:'Immorality in the Church'},
  {bookId:46,chapter:6,beforeVerse:1,title:'Lawsuits Among Believers'},
  {bookId:46,chapter:6,beforeVerse:12,title:'The Body Is a Temple'},
  {bookId:46,chapter:7,beforeVerse:1,title:'Principles for Marriage'},
  {bookId:46,chapter:8,beforeVerse:1,title:'Food Sacrificed to Idols'},
  {bookId:46,chapter:9,beforeVerse:1,title:'The Rights of an Apostle'},
  {bookId:46,chapter:9,beforeVerse:24,title:'Run to Win the Prize'},
  {bookId:46,chapter:10,beforeVerse:1,title:"Warnings from Israel's History"},
  {bookId:46,chapter:11,beforeVerse:17,title:"The Lord's Supper"},
  {bookId:46,chapter:12,beforeVerse:1,title:'Spiritual Gifts'},
  {bookId:46,chapter:12,beforeVerse:12,title:'One Body, Many Members'},
  {bookId:46,chapter:13,beforeVerse:1,title:'The Way of Love'},
  {bookId:46,chapter:14,beforeVerse:1,title:'Prophecy and Tongues'},
  {bookId:46,chapter:14,beforeVerse:26,title:'Orderly Worship'},
  {bookId:46,chapter:15,beforeVerse:1,title:'The Resurrection of Christ'},
  {bookId:46,chapter:15,beforeVerse:12,title:'The Resurrection of the Dead'},
  {bookId:46,chapter:15,beforeVerse:35,title:'The Resurrection Body'},
  {bookId:46,chapter:15,beforeVerse:58,title:'Stand Firm'},
  {bookId:46,chapter:16,beforeVerse:1,title:"The Collection for God's People"},
  // ── 2 Corinthians (47) ──
  {bookId:47,chapter:1,beforeVerse:3,title:'The God of All Comfort'},
  {bookId:47,chapter:3,beforeVerse:1,title:'Ministers of a New Covenant'},
  {bookId:47,chapter:4,beforeVerse:1,title:'Treasures in Jars of Clay'},
  {bookId:47,chapter:4,beforeVerse:16,title:'An Eternal Weight of Glory'},
  {bookId:47,chapter:5,beforeVerse:1,title:'Our Heavenly Dwelling'},
  {bookId:47,chapter:5,beforeVerse:11,title:'The Ministry of Reconciliation'},
  {bookId:47,chapter:5,beforeVerse:17,title:'A New Creation'},
  {bookId:47,chapter:6,beforeVerse:14,title:'Do Not Be Unequally Yoked'},
  {bookId:47,chapter:8,beforeVerse:9,title:'The Grace of Giving'},
  {bookId:47,chapter:9,beforeVerse:6,title:'God Loves a Cheerful Giver'},
  {bookId:47,chapter:10,beforeVerse:1,title:'Paul Defends His Ministry'},
  {bookId:47,chapter:11,beforeVerse:16,title:"Paul's Sufferings"},
  {bookId:47,chapter:12,beforeVerse:1,title:"Paul's Visions and Revelations"},
  {bookId:47,chapter:12,beforeVerse:7,title:"Paul's Thorn in the Flesh"},
  // ── Galatians (48) ──
  {bookId:48,chapter:1,beforeVerse:1,title:'No Other Gospel'},
  {bookId:48,chapter:2,beforeVerse:11,title:'Paul Opposes Peter'},
  {bookId:48,chapter:2,beforeVerse:15,title:'Justified by Faith'},
  {bookId:48,chapter:3,beforeVerse:1,title:'Faith or Works of the Law?'},
  {bookId:48,chapter:3,beforeVerse:23,title:'Sons of God Through Faith'},
  {bookId:48,chapter:4,beforeVerse:21,title:'Hagar and Sarah'},
  {bookId:48,chapter:5,beforeVerse:1,title:'Freedom in Christ'},
  {bookId:48,chapter:5,beforeVerse:16,title:'The Spirit and the Flesh'},
  {bookId:48,chapter:5,beforeVerse:22,title:'The Fruit of the Spirit'},
  {bookId:48,chapter:6,beforeVerse:1,title:"Bear One Another's Burdens"},
  {bookId:48,chapter:6,beforeVerse:7,title:'Reap What You Sow'},
  // ── Ephesians (49) ──
  {bookId:49,chapter:1,beforeVerse:3,title:'Spiritual Blessings in Christ'},
  {bookId:49,chapter:1,beforeVerse:15,title:"Paul's Prayer for the Ephesians"},
  {bookId:49,chapter:2,beforeVerse:1,title:'Made Alive in Christ'},
  {bookId:49,chapter:2,beforeVerse:8,title:'Saved by Grace Through Faith'},
  {bookId:49,chapter:2,beforeVerse:11,title:'One in Christ'},
  {bookId:49,chapter:3,beforeVerse:1,title:'The Mystery of the Gospel'},
  {bookId:49,chapter:3,beforeVerse:14,title:"Paul's Prayer for the Church"},
  {bookId:49,chapter:4,beforeVerse:1,title:'Unity in the Body of Christ'},
  {bookId:49,chapter:4,beforeVerse:17,title:'The New Self'},
  {bookId:49,chapter:5,beforeVerse:1,title:'Walk in Love'},
  {bookId:49,chapter:5,beforeVerse:22,title:'Wives and Husbands'},
  {bookId:49,chapter:6,beforeVerse:1,title:'Children and Parents'},
  {bookId:49,chapter:6,beforeVerse:10,title:'The Armor of God'},
  // ── Philippians (50) ──
  {bookId:50,chapter:1,beforeVerse:12,title:"Paul's Chains Advance the Gospel"},
  {bookId:50,chapter:1,beforeVerse:21,title:'To Live Is Christ'},
  {bookId:50,chapter:2,beforeVerse:1,title:"Imitating Christ's Humility"},
  {bookId:50,chapter:2,beforeVerse:5,title:"Christ's Humility and Exaltation"},
  {bookId:50,chapter:2,beforeVerse:12,title:'Shine as Lights in the World'},
  {bookId:50,chapter:3,beforeVerse:1,title:'No Confidence in the Flesh'},
  {bookId:50,chapter:3,beforeVerse:12,title:'Pressing Toward the Goal'},
  {bookId:50,chapter:4,beforeVerse:4,title:'Rejoice in the Lord Always'},
  {bookId:50,chapter:4,beforeVerse:6,title:'The Peace of God'},
  {bookId:50,chapter:4,beforeVerse:8,title:'Think on These Things'},
  {bookId:50,chapter:4,beforeVerse:10,title:"Paul's Contentment"},
  // ── Colossians (51) ──
  {bookId:51,chapter:1,beforeVerse:15,title:'The Supremacy of Christ'},
  {bookId:51,chapter:2,beforeVerse:6,title:'Rooted in Christ'},
  {bookId:51,chapter:3,beforeVerse:1,title:'Set Your Minds on Things Above'},
  {bookId:51,chapter:3,beforeVerse:5,title:'Put Off the Old Self'},
  {bookId:51,chapter:3,beforeVerse:12,title:'Put On the New Self'},
  {bookId:51,chapter:3,beforeVerse:18,title:'Household Rules'},
  // ── 1 Thessalonians (52) ──
  {bookId:52,chapter:2,beforeVerse:1,title:"Paul's Ministry in Thessalonica"},
  {bookId:52,chapter:4,beforeVerse:1,title:'A Life Pleasing to God'},
  {bookId:52,chapter:4,beforeVerse:13,title:'The Coming of the Lord'},
  {bookId:52,chapter:5,beforeVerse:1,title:'The Day of the Lord'},
  {bookId:52,chapter:5,beforeVerse:16,title:'Rejoice, Pray, Give Thanks'},
  // ── 2 Thessalonians (53) ──
  {bookId:53,chapter:2,beforeVerse:1,title:'The Man of Lawlessness'},
  {bookId:53,chapter:3,beforeVerse:6,title:'Warning Against Idleness'},
  // ── 1 Timothy (54) ──
  {bookId:54,chapter:1,beforeVerse:1,title:'Warning Against False Teachers'},
  {bookId:54,chapter:2,beforeVerse:1,title:'Instructions on Worship'},
  {bookId:54,chapter:3,beforeVerse:1,title:'Qualifications for Overseers'},
  {bookId:54,chapter:3,beforeVerse:8,title:'Qualifications for Deacons'},
  {bookId:54,chapter:4,beforeVerse:1,title:'Departure from the Faith'},
  {bookId:54,chapter:6,beforeVerse:6,title:'Godliness with Contentment'},
  {bookId:54,chapter:6,beforeVerse:11,title:'Fight the Good Fight'},
  // ── 2 Timothy (55) ──
  {bookId:55,chapter:1,beforeVerse:3,title:'Guard the Good Deposit'},
  {bookId:55,chapter:2,beforeVerse:1,title:'A Good Soldier of Christ'},
  {bookId:55,chapter:2,beforeVerse:14,title:'An Approved Worker'},
  {bookId:55,chapter:3,beforeVerse:1,title:'Godlessness in the Last Days'},
  {bookId:55,chapter:3,beforeVerse:10,title:'All Scripture Is God-Breathed'},
  {bookId:55,chapter:4,beforeVerse:1,title:'Preach the Word'},
  {bookId:55,chapter:4,beforeVerse:6,title:'I Have Fought the Good Fight'},
  // ── Titus (56) ──
  {bookId:56,chapter:1,beforeVerse:5,title:'Appointing Elders in Crete'},
  {bookId:56,chapter:2,beforeVerse:1,title:'Sound Doctrine'},
  {bookId:56,chapter:2,beforeVerse:11,title:'The Grace of God'},
  {bookId:56,chapter:3,beforeVerse:1,title:'Doing What Is Good'},
  // ── Philemon (57) ──
  {bookId:57,chapter:1,beforeVerse:1,title:'Greeting'},
  {bookId:57,chapter:1,beforeVerse:8,title:"Paul's Plea for Onesimus"},
  // ── Hebrews (58) ──
  {bookId:58,chapter:1,beforeVerse:1,title:'God Has Spoken by His Son'},
  {bookId:58,chapter:1,beforeVerse:4,title:'The Son Superior to Angels'},
  {bookId:58,chapter:2,beforeVerse:1,title:'A Warning Against Neglect'},
  {bookId:58,chapter:3,beforeVerse:1,title:'Jesus Greater Than Moses'},
  {bookId:58,chapter:4,beforeVerse:1,title:"A Sabbath Rest for God's People"},
  {bookId:58,chapter:4,beforeVerse:14,title:'Jesus the Great High Priest'},
  {bookId:58,chapter:7,beforeVerse:1,title:'Melchizedek the Priest'},
  {bookId:58,chapter:8,beforeVerse:1,title:'The New Covenant'},
  {bookId:58,chapter:9,beforeVerse:11,title:'The Blood of Christ'},
  {bookId:58,chapter:10,beforeVerse:1,title:"Christ's Sacrifice Superior"},
  {bookId:58,chapter:10,beforeVerse:19,title:'A Call to Persevere'},
  {bookId:58,chapter:11,beforeVerse:1,title:'By Faith'},
  {bookId:58,chapter:11,beforeVerse:8,title:'The Faith of Abraham'},
  {bookId:58,chapter:11,beforeVerse:23,title:'The Faith of Moses'},
  {bookId:58,chapter:12,beforeVerse:1,title:'Run the Race with Endurance'},
  {bookId:58,chapter:12,beforeVerse:4,title:'God Disciplines His Children'},
  {bookId:58,chapter:12,beforeVerse:18,title:'Mount Sinai and Mount Zion'},
  {bookId:58,chapter:13,beforeVerse:1,title:'Concluding Exhortations'},
  {bookId:58,chapter:13,beforeVerse:7,title:'Jesus Christ Is the Same'},
  // ── James (59) ──
  {bookId:59,chapter:1,beforeVerse:2,title:'Trials and Temptations'},
  {bookId:59,chapter:1,beforeVerse:5,title:'Ask God for Wisdom'},
  {bookId:59,chapter:1,beforeVerse:19,title:'Hearing and Doing the Word'},
  {bookId:59,chapter:2,beforeVerse:1,title:'Do Not Show Favoritism'},
  {bookId:59,chapter:2,beforeVerse:14,title:'Faith and Works'},
  {bookId:59,chapter:3,beforeVerse:1,title:'Taming the Tongue'},
  {bookId:59,chapter:3,beforeVerse:13,title:'Two Kinds of Wisdom'},
  {bookId:59,chapter:4,beforeVerse:1,title:'Submit Yourselves to God'},
  {bookId:59,chapter:5,beforeVerse:1,title:'A Warning to the Rich'},
  {bookId:59,chapter:5,beforeVerse:7,title:'Patience in Suffering'},
  {bookId:59,chapter:5,beforeVerse:13,title:'The Prayer of Faith'},
  // ── 1 Peter (60) ──
  {bookId:60,chapter:1,beforeVerse:3,title:'A Living Hope'},
  {bookId:60,chapter:1,beforeVerse:13,title:'Be Holy'},
  {bookId:60,chapter:2,beforeVerse:1,title:'The Living Stone'},
  {bookId:60,chapter:2,beforeVerse:9,title:'A Chosen People'},
  {bookId:60,chapter:2,beforeVerse:13,title:'Submission to Authority'},
  {bookId:60,chapter:3,beforeVerse:1,title:'Wives and Husbands'},
  {bookId:60,chapter:3,beforeVerse:8,title:'Suffering for Doing Good'},
  {bookId:60,chapter:4,beforeVerse:7,title:"Stewards of God's Grace"},
  {bookId:60,chapter:4,beforeVerse:12,title:'Suffering as a Christian'},
  {bookId:60,chapter:5,beforeVerse:1,title:'Shepherd the Flock'},
  {bookId:60,chapter:5,beforeVerse:8,title:'Be Sober-Minded and Watchful'},
  // ── 2 Peter (61) ──
  {bookId:61,chapter:1,beforeVerse:3,title:'Grow in Virtue'},
  {bookId:61,chapter:2,beforeVerse:1,title:'False Teachers'},
  {bookId:61,chapter:3,beforeVerse:1,title:'The Day of the Lord'},
  {bookId:61,chapter:3,beforeVerse:8,title:'The Lord Is Patient'},
  // ── 1 John (62) ──
  {bookId:62,chapter:1,beforeVerse:1,title:'The Word of Life'},
  {bookId:62,chapter:1,beforeVerse:5,title:'Walking in the Light'},
  {bookId:62,chapter:2,beforeVerse:1,title:'Jesus Our Advocate'},
  {bookId:62,chapter:2,beforeVerse:15,title:'Do Not Love the World'},
  {bookId:62,chapter:2,beforeVerse:18,title:'Warning Against Antichrists'},
  {bookId:62,chapter:3,beforeVerse:11,title:'Love One Another'},
  {bookId:62,chapter:4,beforeVerse:1,title:'Test the Spirits'},
  {bookId:62,chapter:4,beforeVerse:7,title:'God Is Love'},
  {bookId:62,chapter:5,beforeVerse:1,title:'Overcoming the World'},
  {bookId:62,chapter:5,beforeVerse:13,title:'Confidence in Prayer'},
  // ── 2 John (63) ──
  {bookId:63,chapter:1,beforeVerse:4,title:'Walking in Truth and Love'},
  {bookId:63,chapter:1,beforeVerse:7,title:'Beware of Deceivers'},
  // ── 3 John (64) ──
  {bookId:64,chapter:1,beforeVerse:5,title:'Support for Fellow Workers'},
  {bookId:64,chapter:1,beforeVerse:9,title:'Diotrephes and Demetrius'},
  // ── Jude (65) ──
  {bookId:65,chapter:1,beforeVerse:3,title:'Contend for the Faith'},
  {bookId:65,chapter:1,beforeVerse:5,title:'Warning Against False Teachers'},
  {bookId:65,chapter:1,beforeVerse:24,title:'A Doxology'},
  // ── Revelation (66) ──
  {bookId:66,chapter:1,beforeVerse:1,title:'Prologue'},
  {bookId:66,chapter:1,beforeVerse:9,title:'A Vision of the Son of Man'},
  {bookId:66,chapter:2,beforeVerse:1,title:'To the Church in Ephesus'},
  {bookId:66,chapter:2,beforeVerse:8,title:'To the Church in Smyrna'},
  {bookId:66,chapter:2,beforeVerse:12,title:'To the Church in Pergamum'},
  {bookId:66,chapter:2,beforeVerse:18,title:'To the Church in Thyatira'},
  {bookId:66,chapter:3,beforeVerse:1,title:'To the Church in Sardis'},
  {bookId:66,chapter:3,beforeVerse:7,title:'To the Church in Philadelphia'},
  {bookId:66,chapter:3,beforeVerse:14,title:'To the Church in Laodicea'},
  {bookId:66,chapter:4,beforeVerse:1,title:'The Throne in Heaven'},
  {bookId:66,chapter:5,beforeVerse:1,title:'The Scroll and the Lamb'},
  {bookId:66,chapter:6,beforeVerse:1,title:'The First Seal'},
  {bookId:66,chapter:6,beforeVerse:3,title:'The Second Seal'},
  {bookId:66,chapter:6,beforeVerse:5,title:'The Third Seal'},
  {bookId:66,chapter:6,beforeVerse:7,title:'The Fourth Seal'},
  {bookId:66,chapter:6,beforeVerse:9,title:'The Fifth Seal'},
  {bookId:66,chapter:6,beforeVerse:12,title:'The Sixth Seal'},
  {bookId:66,chapter:7,beforeVerse:1,title:'The 144,000 Sealed'},
  {bookId:66,chapter:7,beforeVerse:9,title:'The Great Multitude'},
  {bookId:66,chapter:8,beforeVerse:1,title:'The Seventh Seal'},
  {bookId:66,chapter:8,beforeVerse:6,title:'The First Four Trumpets'},
  {bookId:66,chapter:9,beforeVerse:1,title:'The Fifth Trumpet'},
  {bookId:66,chapter:9,beforeVerse:13,title:'The Sixth Trumpet'},
  {bookId:66,chapter:10,beforeVerse:1,title:'The Angel and the Little Scroll'},
  {bookId:66,chapter:11,beforeVerse:1,title:'The Two Witnesses'},
  {bookId:66,chapter:11,beforeVerse:15,title:'The Seventh Trumpet'},
  {bookId:66,chapter:12,beforeVerse:1,title:'The Woman and the Dragon'},
  {bookId:66,chapter:12,beforeVerse:7,title:'War in Heaven'},
  {bookId:66,chapter:13,beforeVerse:1,title:'The Beast from the Sea'},
  {bookId:66,chapter:13,beforeVerse:11,title:'The Beast from the Earth'},
  {bookId:66,chapter:14,beforeVerse:1,title:'The Lamb and the 144,000'},
  {bookId:66,chapter:14,beforeVerse:6,title:'The Three Angels'},
  {bookId:66,chapter:14,beforeVerse:14,title:'The Harvest of the Earth'},
  {bookId:66,chapter:15,beforeVerse:1,title:'Seven Angels with Seven Plagues'},
  {bookId:66,chapter:16,beforeVerse:1,title:'The Seven Bowls of Wrath'},
  {bookId:66,chapter:17,beforeVerse:1,title:'The Woman on the Beast'},
  {bookId:66,chapter:18,beforeVerse:1,title:'The Fall of Babylon'},
  {bookId:66,chapter:19,beforeVerse:1,title:'Hallelujah!'},
  {bookId:66,chapter:19,beforeVerse:6,title:'The Marriage Supper of the Lamb'},
  {bookId:66,chapter:19,beforeVerse:11,title:'The Rider on the White Horse'},
  {bookId:66,chapter:20,beforeVerse:1,title:'The Thousand Years'},
  {bookId:66,chapter:20,beforeVerse:7,title:"Satan's Final Defeat"},
  {bookId:66,chapter:20,beforeVerse:11,title:'The Great White Throne Judgment'},
  {bookId:66,chapter:21,beforeVerse:1,title:'The New Heaven and New Earth'},
  {bookId:66,chapter:21,beforeVerse:9,title:'The New Jerusalem'},
  {bookId:66,chapter:22,beforeVerse:1,title:'The River of Life'},
  {bookId:66,chapter:22,beforeVerse:6,title:'Jesus Is Coming Soon'},
  {bookId:66,chapter:22,beforeVerse:18,title:'Final Warnings'},
];

// ─── Index by "bookId:chapter" for O(1) Lookup ─────────────────────────────

const HEADING_INDEX = new Map<string, SectionHeading[]>();

for (const heading of HEADINGS) {
  const key = `${heading.bookId}:${heading.chapter}`;
  const existing = HEADING_INDEX.get(key);
  if (existing) {
    existing.push(heading);
  } else {
    HEADING_INDEX.set(key, [heading]);
  }
}

// Sort each chapter's headings by beforeVerse (ascending)
Array.from(HEADING_INDEX.entries()).forEach(([, headings]) => {
  headings.sort((a, b) => a.beforeVerse - b.beforeVerse);
});

// ─── Public API ──────────────────────────────────────────────────────────────

/**
 * Get section headings for a specific chapter.
 *
 * @param bookId - The book ID (1-66, matching bible-constants.ts)
 * @param chapter - The chapter number
 * @returns Array of section headings sorted by beforeVerse, or empty array if none
 */
export function getSectionHeadings(
  bookId: number,
  chapter: number,
): SectionHeading[] {
  return HEADING_INDEX.get(`${bookId}:${chapter}`) ?? [];
}

/**
 * Get the section heading that applies to a specific verse.
 * Returns the heading whose beforeVerse is closest to (but not greater than) the given verse.
 *
 * @param bookId - The book ID (1-66)
 * @param chapter - The chapter number
 * @param verse - The verse number
 * @returns The applicable section heading, or null if none
 */
export function getSectionHeadingForVerse(
  bookId: number,
  chapter: number,
  verse: number,
): SectionHeading | null {
  const headings = getSectionHeadings(bookId, chapter);
  if (headings.length === 0) return null;

  let result: SectionHeading | null = null;
  for (const heading of headings) {
    if (heading.beforeVerse <= verse) {
      result = heading;
    } else {
      break;
    }
  }
  return result;
}

/** Total number of section headings in the dataset */
export const TOTAL_SECTION_HEADINGS = HEADINGS.length;
