// ==========================================
// STORY REPOSITORY: CULTURAL MOMENTS — EXPANDED
// Deeper, wider moments across space, music, art, sports, disasters,
// communication, philosophy, social movements, and cultural concepts
// Supplement to the main cultural moments batch
// Used by AI devotional generation as illustration source material
// ==========================================

export interface CulturalMomentEntry {
  id: string;
  title: string;
  era: string;
  category: 'cultural-moment';
  themes: string[];
  oneLineSummary: string;
  spiritualAngle: string;
  source: 'historical';
  spinnable: boolean;
}

export const CULTURAL_MOMENTS_EXPANDED: CulturalMomentEntry[] = [
  // ==========================================
  // SPACE EXPLORATION — AWE & PERSPECTIVE
  // ==========================================
  {
    id: 'apollo-8-genesis-reading',
    title: 'Astronauts Read Genesis While Orbiting the Moon',
    era: '1968',
    category: 'cultural-moment',
    themes: ['awe', 'creation', 'perspective', 'wonder', 'Scripture'],
    oneLineSummary: 'On Christmas Eve 1968, the Apollo 8 crew became the first humans to orbit the moon and chose to read from Genesis 1 — "In the beginning, God created the heavens and the earth."',
    spiritualAngle: 'When humans finally saw Earth from space, the most natural response was to read the creation story — as if seeing it from that distance made Genesis feel true for the first time.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'voyager-1-leaves-solar-system',
    title: 'The Spacecraft That Left the Sun Behind',
    era: '2012',
    category: 'cultural-moment',
    themes: ['journey', 'exploration', 'persistence', 'unknown', 'beyond'],
    oneLineSummary: 'Voyager 1 crossed into interstellar space — the first human-made object to leave the solar system, carrying a golden record of sounds from Earth including greetings in 55 languages.',
    spiritualAngle: 'We launched a message in a bottle into the cosmos — an act of faith that someone might be listening, the same instinct behind every prayer sent into silence.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'hubble-ultra-deep-field',
    title: 'The Telescope That Found 10000 Galaxies in a Dark Spot',
    era: '2004',
    category: 'cultural-moment',
    themes: ['awe', 'hidden', 'vastness', 'humility', 'wonder'],
    oneLineSummary: 'NASA pointed Hubble at a dark, seemingly empty patch of sky for 11 days and discovered 10,000 galaxies — each containing hundreds of billions of stars.',
    spiritualAngle: 'Every "empty" space is full of more than we can imagine — a cosmic lesson in the danger of assuming that what we cannot see does not exist.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'pale-blue-dot-photo',
    title: 'Earths Portrait from 3.7 Billion Miles Away',
    era: '1990',
    category: 'cultural-moment',
    themes: ['perspective', 'humility', 'fragility', 'home', 'stewardship'],
    oneLineSummary: 'At Carl Sagans request, Voyager 1 turned its camera back toward Earth from 3.7 billion miles away, capturing our planet as a pale blue dot suspended in a sunbeam.',
    spiritualAngle: 'Every war, every love story, every prayer ever uttered happened on that dot — a humbling reminder that we are both insignificant and precious.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'earthrise-photo-apollo-8',
    title: 'The Photo That Changed How We See Our Home',
    era: '1968',
    category: 'cultural-moment',
    themes: ['perspective', 'beauty', 'stewardship', 'home', 'fragility'],
    oneLineSummary: 'Astronaut Bill Anders snapped Earthrise — the first color photo of Earth rising over the moons horizon — and the environmental movement was born from that single image.',
    spiritualAngle: 'We went to explore the moon and discovered the Earth — sometimes you have to leave home to truly see it, just as the prodigal son had to leave to appreciate what he had.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'james-webb-first-deep-field',
    title: 'The New Telescope That Peered 13 Billion Years Back',
    era: '2022',
    category: 'cultural-moment',
    themes: ['awe', 'discovery', 'time', 'wonder', 'creation'],
    oneLineSummary: 'The James Webb Space Telescopes first deep field image revealed galaxies from 13 billion years ago — light that left those stars when the universe was less than 5% its current age.',
    spiritualAngle: 'We are looking at the beginning of things — and the deeper we look into creation, the more it echoes the psalmists declaration that the heavens declare the glory of God.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'apollo-13-successful-failure',
    title: 'The Mission That Failed Its Way to Triumph',
    era: '1970',
    category: 'cultural-moment',
    themes: ['teamwork', 'crisis', 'ingenuity', 'perseverance', 'hope'],
    oneLineSummary: 'After an oxygen tank exploded, Apollo 13 engineers on Earth built a makeshift CO2 filter from duct tape and cardboard to save three astronauts — calling the disaster a successful failure.',
    spiritualAngle: 'The greatest creativity often emerges from the greatest constraints — when you have nothing but duct tape and prayer, solutions appear that comfort never would have produced.',
    source: 'historical',
    spinnable: true,
  },

  // ==========================================
  // MUSIC MOMENTS
  // ==========================================
  {
    id: 'amazing-grace-protests-funerals',
    title: 'The Slave Traders Hymn That Became Everyones Anthem',
    era: '1772-present',
    category: 'cultural-moment',
    themes: ['redemption', 'grace', 'repentance', 'universality', 'healing'],
    oneLineSummary: 'Written by former slave trader John Newton, Amazing Grace has been sung at funerals, civil rights marches, and 9/11 memorials — becoming the default sound of human need for mercy.',
    spiritualAngle: 'A songs origin story is itself a sermon — that the man who trafficked humans wrote the worlds most beloved hymn about being saved is grace in its rawest form.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'handel-messiah-24-days',
    title: 'The Composer Who Wrote the Hallelujah Chorus in a Fever',
    era: '1741',
    category: 'cultural-moment',
    themes: ['inspiration', 'creativity', 'worship', 'transcendence', 'calling'],
    oneLineSummary: 'George Frideric Handel composed the entire Messiah — including the Hallelujah Chorus — in 24 days, barely eating or sleeping, telling his servant "I did think I did see all Heaven before me."',
    spiritualAngle: 'Handel experienced something artists call flow and mystics call inspiration — a creative state so intense it feels like dictation from beyond yourself.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'sam-cooke-change-gonna-come',
    title: 'The Gospel Singer Who Wrote the Civil Rights Anthem',
    era: '1964',
    category: 'cultural-moment',
    themes: ['hope', 'justice', 'perseverance', 'lament', 'prophecy'],
    oneLineSummary: 'After being turned away from a whites-only motel, Sam Cooke wrote "A Change Is Gonna Come" — a song that fused gospel longing with civil rights prophecy and became the movements anthem.',
    spiritualAngle: 'The song is a secular psalm of lament — born from pain, sustained by hope, and prophetically certain that justice will come even when the timeline is unknown.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'beethoven-ninth-symphony-deaf',
    title: 'The Deaf Composer Conducting Joy',
    era: '1824',
    category: 'cultural-moment',
    themes: ['perseverance', 'joy', 'suffering', 'creativity', 'transcendence'],
    oneLineSummary: 'Completely deaf, Beethoven conducted the premiere of his Ninth Symphony and had to be turned around by a musician to see the audience in rapturous applause he could not hear.',
    spiritualAngle: 'He composed the greatest expression of human joy while trapped in silence — proof that the deepest music comes from somewhere beyond the ears.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'strange-fruit-billie-holiday',
    title: 'The Song That Made America Look at Its Lynching Trees',
    era: '1939',
    category: 'cultural-moment',
    themes: ['injustice', 'witness', 'lament', 'courage', 'truth'],
    oneLineSummary: 'Billie Holiday sang Strange Fruit — about Black bodies hanging from Southern trees — and the room would go completely silent, the song so devastating that clubs required she sing it last.',
    spiritualAngle: 'Some truths are so terrible that only art can carry them — Holiday bore witness the way Jeremiah bore witness, through a grief that refused to look away.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'we-shall-overcome-civil-rights',
    title: 'The Hymn That Became a Freedom Song',
    era: '1960s',
    category: 'cultural-moment',
    themes: ['hope', 'community', 'perseverance', 'faith', 'solidarity'],
    oneLineSummary: 'We Shall Overcome evolved from a gospel hymn into the anthem of the civil rights movement — sung by crowds linking arms, its power coming not from melody but from collective belief.',
    spiritualAngle: 'When people sing together about a future they cannot yet see, they are practicing faith — the substance of things hoped for, performed in four-part harmony.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'rostropovich-plays-berlin-wall',
    title: 'The Cellist Who Played Bach at the Fallen Wall',
    era: '1989',
    category: 'cultural-moment',
    themes: ['freedom', 'beauty', 'art', 'celebration', 'spontaneity'],
    oneLineSummary: 'When the Berlin Wall fell, cellist Mstislav Rostropovich flew to Berlin on impulse and played Bach suites at Checkpoint Charlie — beauty as the first response to freedom.',
    spiritualAngle: 'His instinct was not to make a speech but to play music — because some moments are too sacred for words and only beauty can carry the weight.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'blind-boys-of-alabama-gospel',
    title: 'The Group That Sang Gospel for 80 Years',
    era: '1939-2019',
    category: 'cultural-moment',
    themes: ['perseverance', 'worship', 'joy', 'longevity', 'faithfulness'],
    oneLineSummary: 'The Blind Boys of Alabama began singing gospel in 1939 at a school for the blind and continued for 80 years — the longest-running performing group in American music history.',
    spiritualAngle: 'Eighty years of singing the same songs about the same God — faithfulness is not about novelty but about the willingness to show up again tomorrow.',
    source: 'historical',
    spinnable: true,
  },

  // ==========================================
  // ARCHITECTURE, ART & SACRED SPACES
  // ==========================================
  {
    id: 'cathedral-builders-unseen',
    title: 'The Workers Who Built Beauty They Would Never See',
    era: '1100-1500',
    category: 'cultural-moment',
    themes: ['faithfulness', 'legacy', 'patience', 'craftsmanship', 'generational-thinking'],
    oneLineSummary: 'Medieval cathedral builders spent entire lifetimes on structures that took 200+ years to complete — knowing they would never see the finished work, carving details only God would notice.',
    spiritualAngle: 'They carved gargoyles on the backs of pillars no one would ever see because the audience was God — a radical definition of working as unto the Lord.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'michelangelo-pieta',
    title: 'The Sculpture That Makes Mary Look 16',
    era: '1499',
    category: 'cultural-moment',
    themes: ['beauty', 'grief', 'youth', 'sacrifice', 'motherhood'],
    oneLineSummary: 'Michelangelo sculpted the Pieta at 24, depicting Mary holding her dead son — and made her impossibly young, saying that her purity preserved her youth.',
    spiritualAngle: 'The most heartbreaking moment in Scripture — a mother holding her dead child — became the most beautiful sculpture ever made, proving that grief and beauty are not opposites.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'rothko-chapel-silence',
    title: 'The Abstract Painter Who Built a Chapel of Darkness',
    era: '1971',
    category: 'cultural-moment',
    themes: ['silence', 'contemplation', 'mystery', 'presence', 'sacred-space'],
    oneLineSummary: 'Mark Rothko designed a chapel in Houston with 14 massive dark canvases — no symbols, no images, just color and silence — as a space for any faith or none.',
    spiritualAngle: 'Rothko understood that the deepest spiritual experiences happen not in decoration but in emptiness — the chapel creates the conditions for encounter precisely by removing everything.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'kintsugi-golden-repair',
    title: 'The Japanese Art of Making Broken Things More Beautiful',
    era: '15th century',
    category: 'cultural-moment',
    themes: ['brokenness', 'beauty', 'healing', 'redemption', 'imperfection'],
    oneLineSummary: 'Kintsugi is the Japanese art of repairing broken pottery with gold — making the fracture lines visible and beautiful rather than hiding them.',
    spiritualAngle: 'God does not restore us by erasing our scars but by filling them with gold — our broken places become the most luminous parts of our story.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'hagia-sophia-converted-reconverted',
    title: 'The Building That Has Been Everything',
    era: '537-present',
    category: 'cultural-moment',
    themes: ['endurance', 'faith', 'change', 'sacred-space', 'identity'],
    oneLineSummary: 'The Hagia Sophia has served as a cathedral, a mosque, a museum, and a mosque again over 1,500 years — its walls holding the prayers of millions across traditions.',
    spiritualAngle: 'A building that has absorbed the prayers of Christians and Muslims alike suggests that sacred space transcends the categories we impose on it.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'sistine-chapel-ceiling',
    title: 'The Painter Who Didnt Want the Job',
    era: '1508-1512',
    category: 'cultural-moment',
    themes: ['reluctance', 'calling', 'perseverance', 'beauty', 'obedience'],
    oneLineSummary: 'Michelangelo insisted he was a sculptor, not a painter, and resisted painting the Sistine Chapel ceiling for two years — then spent four years on his back creating the most famous painting in history.',
    spiritualAngle: 'The calling you resist the hardest might be the one that produces your greatest work — Moses said I cant speak, Jeremiah said Im too young, and Michelangelo said Im not a painter.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'taj-mahal-love-monument',
    title: 'The Emperor Who Built a Monument to Grief',
    era: '1632-1653',
    category: 'cultural-moment',
    themes: ['love', 'grief', 'beauty', 'devotion', 'memory'],
    oneLineSummary: 'Shah Jahan built the Taj Mahal as a tomb for his wife Mumtaz, who died giving birth to their 14th child — 20,000 workers labored for 22 years to make grief visible.',
    spiritualAngle: 'The Taj Mahal proves that love does not end at death — the impulse to build something permanent from something lost echoes the human conviction that love is eternal.',
    source: 'historical',
    spinnable: true,
  },

  // ==========================================
  // SPORTS — DEEPER CUTS
  // ==========================================
  {
    id: 'all-blacks-haka',
    title: 'The War Dance That Begins with Vulnerability',
    era: '1905-present',
    category: 'cultural-moment',
    themes: ['identity', 'community', 'strength', 'vulnerability', 'tradition'],
    oneLineSummary: 'Before every match, New Zealands All Blacks perform the haka — a Maori war dance that begins with an expression of grief and ends in a display of power, declaring who they are before the contest begins.',
    spiritualAngle: 'The haka teaches that true strength begins with acknowledging where you come from and who you belong to — identity before performance.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'miracle-on-ice-1980',
    title: 'The College Kids Who Beat an Empire on Ice',
    era: '1980',
    category: 'cultural-moment',
    themes: ['underdog', 'teamwork', 'belief', 'courage', 'impossible'],
    oneLineSummary: 'A team of American college hockey players defeated the dominant Soviet team at the 1980 Olympics — a victory so improbable that the announcer could only shout "Do you believe in miracles?"',
    spiritualAngle: 'The word miracle in the announcer\'s mouth was instinctive — when the impossible happens, the first language we reach for is the language of faith.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'kathrine-switzer-boston-marathon',
    title: 'The Woman Who Ran When Women Werent Allowed',
    era: '1967',
    category: 'cultural-moment',
    themes: ['courage', 'barrier-breaking', 'perseverance', 'gender', 'defiance'],
    oneLineSummary: 'Kathrine Switzer registered for the Boston Marathon using initials, and when an official tried to physically remove her mid-race, she kept running — opening the door for women in distance running.',
    spiritualAngle: 'Sometimes the most revolutionary act is simply refusing to stop doing what you know you were made to do, even when someone is trying to pull you off the course.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'tommy-smith-john-carlos-1968',
    title: 'The Fists That Spoke Louder Than Gold Medals',
    era: '1968',
    category: 'cultural-moment',
    themes: ['protest', 'courage', 'justice', 'sacrifice', 'symbol'],
    oneLineSummary: 'Tommie Smith and John Carlos raised black-gloved fists on the 1968 Olympic podium, sacrificing their careers to make injustice visible on the worlds largest stage.',
    spiritualAngle: 'They turned a moment of personal triumph into a prophetic act — choosing to use their platform for others rather than themselves, at enormous personal cost.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'jesse-owens-luz-long-friendship',
    title: 'The Enemy Competitor Who Became a Friend',
    era: '1936',
    category: 'cultural-moment',
    themes: ['friendship', 'kindness', 'enemy-love', 'sportsmanship', 'humanity'],
    oneLineSummary: 'German athlete Luz Long helped Jesse Owens qualify for the long jump final at Hitlers Olympics, then embraced him publicly — Long was killed in World War II, and Owens stayed in touch with his family for decades.',
    spiritualAngle: 'Love your enemies was practiced by Luz Long in the most hostile setting imaginable — and that one act of kindness outlasted the empire that tried to forbid it.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'derek-redmond-father-1992',
    title: 'The Father Who Carried His Son Across the Finish Line',
    era: '1992',
    category: 'cultural-moment',
    themes: ['fatherhood', 'support', 'pain', 'perseverance', 'love'],
    oneLineSummary: 'When runner Derek Redmond tore his hamstring mid-race at the Barcelona Olympics, his father ran from the stands, pushed through security, and helped his son hobble across the finish line.',
    spiritualAngle: 'The image of a father leaving the stands to carry his broken son to the finish is the most visual sermon on grace ever preached in a stadium.',
    source: 'historical',
    spinnable: true,
  },

  // ==========================================
  // DISASTERS THAT REVEALED CHARACTER
  // ==========================================
  {
    id: 'fukushima-fifty-stayed',
    title: 'The Workers Who Stayed in a Melting Reactor',
    era: '2011',
    category: 'cultural-moment',
    themes: ['sacrifice', 'duty', 'courage', 'selflessness', 'crisis'],
    oneLineSummary: 'After the Fukushima meltdown, 50 plant workers refused to evacuate and stayed inside the damaged reactors to prevent a larger catastrophe — knowingly exposing themselves to lethal radiation.',
    spiritualAngle: 'Greater love has no one than this — to lay down your life for others, even strangers, even people who will never know your name.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: '911-first-responders-ascending',
    title: 'The People Who Ran Up While Everyone Ran Down',
    era: '2001',
    category: 'cultural-moment',
    themes: ['sacrifice', 'courage', 'duty', 'heroism', 'calling'],
    oneLineSummary: 'On September 11, 343 firefighters climbed the stairs of the World Trade Center while thousands fled down — ascending into fire because that was their calling.',
    spiritualAngle: 'Running toward danger when everyone else is running away is the purest expression of vocation — the willingness to ascend because others need you at the top.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'christa-mcauliffe-challenger',
    title: 'The Teacher Who Brought Her Classroom to Space',
    era: '1986',
    category: 'cultural-moment',
    themes: ['courage', 'teaching', 'loss', 'inspiration', 'dreams'],
    oneLineSummary: 'Christa McAuliffe was a social studies teacher selected from 11,000 applicants to be the first teacher in space — the Challenger disaster killed her 73 seconds after launch, with millions of students watching.',
    spiritualAngle: 'She said I touch the future — I teach, and her willingness to risk everything for that future is a teacher\'s version of the grain of wheat that falls to the ground.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'titanic-band-played-on',
    title: 'The Musicians Who Played While the Ship Sank',
    era: '1912',
    category: 'cultural-moment',
    themes: ['courage', 'beauty', 'sacrifice', 'calm', 'dignity'],
    oneLineSummary: 'As the Titanic sank, the eight-member band continued playing music to calm passengers — reportedly ending with "Nearer, My God, to Thee" as the water rose around their feet.',
    spiritualAngle: 'They chose beauty in the face of death — the conviction that music matters even at the end, that worship is appropriate precisely when hope is disappearing.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'chernobyl-liquidators',
    title: 'The Volunteers Who Cleaned Up with Their Bodies',
    era: '1986',
    category: 'cultural-moment',
    themes: ['sacrifice', 'duty', 'courage', 'hidden-heroes', 'cost'],
    oneLineSummary: 'Over 600,000 liquidators worked to contain the Chernobyl disaster — some shoveling radioactive graphite from rooftops for 90 seconds at a time before hitting their lifetime radiation dose.',
    spiritualAngle: 'They measured their service in seconds because each second cost them years of life — the most extreme example of spending yourself for others.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'armenian-earthquake-father-dug',
    title: 'The Father Who Dug for 38 Hours',
    era: '1988',
    category: 'cultural-moment',
    themes: ['persistence', 'fatherhood', 'promise', 'faith', 'determination'],
    oneLineSummary: 'After the 1988 Armenian earthquake, a father dug through rubble for 38 hours to reach his son trapped in a school, because he had promised "No matter what, I will always be there for you."',
    spiritualAngle: 'He kept digging when everyone told him to stop — a father\'s promise is a picture of divine persistence, the God who will not stop reaching for us.',
    source: 'historical',
    spinnable: true,
  },

  // ==========================================
  // COMMUNICATION MILESTONES
  // ==========================================
  {
    id: 'first-telegraph-message',
    title: 'The First Electronic Message Was a Bible Verse',
    era: '1844',
    category: 'cultural-moment',
    themes: ['communication', 'wonder', 'technology', 'Scripture', 'awe'],
    oneLineSummary: 'Samuel Morses first telegraph message was "What hath God wrought" — a line from Numbers 23:23, chosen because the invention felt too miraculous for secular words.',
    spiritualAngle: 'When technology felt genuinely miraculous, the instinct was to reach for Scripture — a reminder that wonder and worship are the same impulse.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'carl-sagan-cosmos-know-itself',
    title: 'The Astronomer Who Said We Are How the Universe Knows Itself',
    era: '1980',
    category: 'cultural-moment',
    themes: ['wonder', 'consciousness', 'purpose', 'connection', 'identity'],
    oneLineSummary: 'Carl Sagan said "We are a way for the cosmos to know itself" — suggesting that human consciousness is not an accident but the universe becoming aware.',
    spiritualAngle: 'If we are how the cosmos knows itself, then self-awareness is sacred — and the examined life is not just philosophical but cosmically purposeful.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'gutenberg-bible-first-printed-book',
    title: 'The First Mass-Produced Book Was the Bible',
    era: '1455',
    category: 'cultural-moment',
    themes: ['access', 'Scripture', 'revolution', 'democratization', 'knowledge'],
    oneLineSummary: 'The first major book printed with movable type was a Bible — meaning the technology that would transform human civilization was inaugurated by making Gods word more accessible.',
    spiritualAngle: 'Every communication revolution — print, radio, internet — has been used to spread Scripture, as if the Word keeps finding new ways to be heard.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'rosetta-stone-decipherment',
    title: 'The Rock That Unlocked a Lost Language',
    era: '1799',
    category: 'cultural-moment',
    themes: ['discovery', 'language', 'revelation', 'hidden-meaning', 'patience'],
    oneLineSummary: 'The Rosetta Stone, found by accident in Egypt, provided the key to deciphering hieroglyphics — a language lost for 1,400 years suddenly became readable again.',
    spiritualAngle: 'Sometimes God hides meaning in plain sight for centuries until someone is ready to understand — the right key at the right time unlocks everything.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'dead-sea-scrolls-discovery',
    title: 'The Shepherd Boy Who Found Ancient Scripture in a Cave',
    era: '1947',
    category: 'cultural-moment',
    themes: ['discovery', 'Scripture', 'preservation', 'providence', 'hidden'],
    oneLineSummary: 'A Bedouin shepherd boy threw a rock into a cave near the Dead Sea and heard pottery shatter — discovering the oldest known biblical manuscripts, preserved for 2,000 years.',
    spiritualAngle: 'Gods word was preserved in clay jars in desert caves for two millennia, as if waiting for the exact moment it needed to be found to confirm what we already believed.',
    source: 'historical',
    spinnable: true,
  },

  // ==========================================
  // PHILOSOPHY IN ACTION
  // ==========================================
  {
    id: 'kierkegaard-leap-of-faith-concept',
    title: 'The Idea That Faith Begins Where Proof Ends',
    era: '1843',
    category: 'cultural-moment',
    themes: ['faith', 'doubt', 'risk', 'decision', 'trust'],
    oneLineSummary: 'Kierkegaard argued that the leap of faith is not irrational but trans-rational — the moment when you have weighed all evidence and still must choose to trust what you cannot prove.',
    spiritualAngle: 'Every relationship requires a leap — you can never fully prove someone is trustworthy, you must at some point choose to trust — and faith in God follows the same pattern.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'simone-weil-attention-generosity',
    title: 'The Idea That Paying Attention Is the Highest Form of Love',
    era: '1942',
    category: 'cultural-moment',
    themes: ['attention', 'love', 'presence', 'generosity', 'prayer'],
    oneLineSummary: 'Simone Weil wrote that attention is the rarest and purest form of generosity — and that prayer is nothing other than the highest quality of attention.',
    spiritualAngle: 'In a world designed to distract us, choosing to fully attend to another person or to God is the most countercultural — and most loving — thing we can do.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'hannah-arendt-banality-evil',
    title: 'The Discovery That Evil Is Often Just Thoughtlessness',
    era: '1963',
    category: 'cultural-moment',
    themes: ['evil', 'thinking', 'conformity', 'conscience', 'responsibility'],
    oneLineSummary: 'Hannah Arendt watched Eichmann\'s trial and saw not a monster but a bureaucrat who simply never stopped to think about what he was doing — coining the term the banality of evil.',
    spiritualAngle: 'The greatest moral danger is not dramatic temptation but the quiet failure to think — going along with systems that destroy people because everyone else is going along too.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'victor-frankl-meaning-logotherapy',
    title: 'The Idea That Purpose Can Outlast Any Suffering',
    era: '1946',
    category: 'cultural-moment',
    themes: ['meaning', 'suffering', 'purpose', 'choice', 'endurance'],
    oneLineSummary: 'Viktor Frankl observed in Auschwitz that prisoners who had a reason to survive — a child waiting, a book to finish — outlived those who did not, proving that meaning sustains life itself.',
    spiritualAngle: 'He who has a why can endure any how — Frankl discovered empirically what faith has always taught: purpose is not a luxury but a survival necessity.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'martin-buber-i-thou',
    title: 'The Philosopher Who Said Every Encounter Can Be Sacred',
    era: '1923',
    category: 'cultural-moment',
    themes: ['relationship', 'presence', 'encounter', 'sacred', 'connection'],
    oneLineSummary: 'Martin Buber distinguished between I-It relationships — where we use others as objects — and I-Thou encounters — where we meet another as a whole person, and in doing so, meet God.',
    spiritualAngle: 'Every person you encounter is a potential I-Thou moment — and according to Buber, every genuine encounter with another person is simultaneously an encounter with the Eternal Thou.',
    source: 'historical',
    spinnable: true,
  },

  // ==========================================
  // SOCIAL MOVEMENTS
  // ==========================================
  {
    id: 'montgomery-bus-boycott-planning',
    title: 'The 40000 People Who Walked to Work for 381 Days',
    era: '1955-1956',
    category: 'cultural-moment',
    themes: ['perseverance', 'community', 'sacrifice', 'justice', 'discipline'],
    oneLineSummary: 'The Montgomery Bus Boycott was not spontaneous — 40,000 Black residents organized carpools, walked miles in rain and heat for 381 days, losing jobs and facing violence, until the buses desegregated.',
    spiritualAngle: 'The boycott was sustained not by a single dramatic act but by 381 days of quiet, costly faithfulness — the same endurance faith requires.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'greensboro-sit-ins',
    title: 'The Four Students Who Sat Down and Wouldnt Get Up',
    era: '1960',
    category: 'cultural-moment',
    themes: ['courage', 'youth', 'nonviolence', 'dignity', 'resistance'],
    oneLineSummary: 'Four Black college freshmen sat at a whites-only Woolworths lunch counter in Greensboro, were refused service, and simply stayed — within two months, sit-ins spread to 55 cities.',
    spiritualAngle: 'They did not shout or fight — they just sat, embodying the power of nonviolent presence, the same quiet defiance that characterizes prayer.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'singing-revolution-estonia',
    title: 'The Nation That Sang Its Way to Freedom',
    era: '1988',
    category: 'cultural-moment',
    themes: ['freedom', 'community', 'nonviolence', 'culture', 'identity'],
    oneLineSummary: 'Estonia freed itself from Soviet occupation through mass singing — 300,000 people gathering to sing forbidden national songs, a revolution accomplished without a single weapon.',
    spiritualAngle: 'The Singing Revolution proved that shared song can be more powerful than shared weapons — that when a people remember who they are together, empires lose their grip.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'tiananmen-square-tank-man',
    title: 'The Man Who Stopped a Column of Tanks with His Body',
    era: '1989',
    category: 'cultural-moment',
    themes: ['courage', 'defiance', 'anonymity', 'powerlessness', 'witness'],
    oneLineSummary: 'An unidentified man stood in front of a column of tanks in Tiananmen Square with shopping bags in his hands — and the tanks stopped, creating the most iconic image of individual defiance against state power.',
    spiritualAngle: 'We do not know his name, his faith, or what happened to him — yet his single act of standing still echoes David facing Goliath with nothing but conviction.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'salt-march-gandhi',
    title: 'The 240-Mile Walk That Broke an Empires Monopoly',
    era: '1930',
    category: 'cultural-moment',
    themes: ['nonviolence', 'justice', 'simplicity', 'defiance', 'solidarity'],
    oneLineSummary: 'Gandhi walked 240 miles to the sea to make salt — an act so simple and so illegal under British law that it exposed the absurdity of empire and ignited Indian independence.',
    spiritualAngle: 'The most powerful protests are often the most mundane — making salt, sitting at a counter, kneeling — small acts that reveal the injustice of enormous systems.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'mothers-plaza-de-mayo',
    title: 'The Mothers Who Walked in Circles Until the World Noticed',
    era: '1977-present',
    category: 'cultural-moment',
    themes: ['perseverance', 'grief', 'justice', 'motherhood', 'witness'],
    oneLineSummary: 'The Mothers of the Plaza de Mayo walked in circles around Buenos Aires plaza every Thursday for decades, wearing white headscarves, demanding to know what happened to their disappeared children.',
    spiritualAngle: 'Their circular walk was both protest and prayer — the refusal to stop asking, the same stubborn persistence Jesus praised in the widow who kept knocking on the judges door.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'arab-spring-facebook',
    title: 'The Revolution That Started with a Status Update',
    era: '2010-2011',
    category: 'cultural-moment',
    themes: ['technology', 'justice', 'youth', 'communication', 'courage'],
    oneLineSummary: 'The Arab Spring uprisings were organized through social media — young people in Tunisia, Egypt, and beyond using Facebook and Twitter to coordinate protests that toppled governments.',
    spiritualAngle: 'Technology amplifies whatever is already in the human heart — the same tools that spread misinformation also spread the cry for justice when people are desperate enough to speak.',
    source: 'historical',
    spinnable: true,
  },

  // ==========================================
  // CULTURAL CONCEPTS FROM AROUND THE WORLD
  // ==========================================
  {
    id: 'japanese-ichigo-ichie',
    title: 'The Japanese Belief That This Moment Will Never Come Again',
    era: 'traditional',
    category: 'cultural-moment',
    themes: ['presence', 'gratitude', 'mindfulness', 'impermanence', 'encounter'],
    oneLineSummary: 'Ichigo ichie — one moment, one encounter — is the Japanese concept that each meeting between people is utterly unique and will never be repeated, so it deserves full attention.',
    spiritualAngle: 'This is why Jesus said do not worry about tomorrow — because this moment, this conversation, this person in front of you is unrepeatable and worthy of your full presence.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'danish-hygge-community',
    title: 'The Danish Art of Making Warmth Together',
    era: 'traditional',
    category: 'cultural-moment',
    themes: ['community', 'simplicity', 'warmth', 'belonging', 'contentment'],
    oneLineSummary: 'Hygge is the Danish concept of cozy togetherness — candlelight, shared food, unhurried conversation — that helps Denmark consistently rank among the happiest countries despite dark winters.',
    spiritualAngle: 'The early church devoted themselves to breaking bread together — hygge is a secular echo of the deep human need for unhurried fellowship that faith was always meant to provide.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'south-african-ubuntu',
    title: 'The African Philosophy That Says I Am Because We Are',
    era: 'traditional',
    category: 'cultural-moment',
    themes: ['community', 'identity', 'interconnection', 'belonging', 'humanity'],
    oneLineSummary: 'Ubuntu — I am because we are — is the South African philosophy that a person is a person through other people, that individual humanity is incomplete without community.',
    spiritualAngle: 'Ubuntu echoes Pauls teaching that we are one body with many members — no part can say to another I dont need you, because our identity is inherently communal.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'finnish-sisu-resilience',
    title: 'The Finnish Word for Stubborn Courage That Wont Quit',
    era: 'traditional',
    category: 'cultural-moment',
    themes: ['resilience', 'perseverance', 'courage', 'endurance', 'grit'],
    oneLineSummary: 'Sisu is the Finnish concept of extraordinary determination in the face of adversity — not mere persistence but a deep reserve of courage that activates when rational hope is gone.',
    spiritualAngle: 'Sisu is what faith looks like when feelings have left the building — the stubborn decision to keep going not because you feel hopeful but because quitting is not an option.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'hawaiian-hooponopono',
    title: 'The Hawaiian Practice of Setting Relationships Right',
    era: 'traditional',
    category: 'cultural-moment',
    themes: ['forgiveness', 'reconciliation', 'healing', 'community', 'restoration'],
    oneLineSummary: 'Ho\'oponopono is the Hawaiian practice of reconciliation and forgiveness where families gather to confess wrongs, seek forgiveness, and restore broken relationships before anyone sleeps.',
    spiritualAngle: 'Do not let the sun go down on your anger — this ancient Hawaiian practice mirrors the biblical command to reconcile before the day ends.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'japanese-wabi-sabi',
    title: 'The Japanese Art of Finding Beauty in Imperfection',
    era: 'traditional',
    category: 'cultural-moment',
    themes: ['imperfection', 'beauty', 'acceptance', 'transience', 'simplicity'],
    oneLineSummary: 'Wabi-sabi is the Japanese aesthetic of finding beauty in impermanence, imperfection, and incompleteness — a cracked bowl, a weathered fence, an asymmetrical flower arrangement.',
    spiritualAngle: 'Gods strength is made perfect in weakness — wabi-sabi sees what grace sees: that the flawed, the worn, and the unfinished can be more beautiful than the polished and complete.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'nordic-friluftsliv',
    title: 'The Scandinavian Way of Living in Open Air',
    era: 'traditional',
    category: 'cultural-moment',
    themes: ['nature', 'simplicity', 'well-being', 'creation', 'presence'],
    oneLineSummary: 'Friluftsliv — open-air living — is the Scandinavian philosophy that regular, unhurried time in nature is essential for human well-being, not a luxury but a necessity.',
    spiritualAngle: 'Jesus withdrew to lonely places to pray — the instinct that we need nature is not just wellness culture but a recognition that we were made for gardens, not cubicles.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'german-waldeinsamkeit',
    title: 'The German Word for the Feeling of Being Alone in the Forest',
    era: 'traditional',
    category: 'cultural-moment',
    themes: ['solitude', 'nature', 'peace', 'contemplation', 'belonging'],
    oneLineSummary: 'Waldeinsamkeit is the German word for the feeling of solitude and connectedness when alone in the woods — not loneliness but a peaceful sense of being held by something larger.',
    spiritualAngle: 'There is a solitude that is not emptiness but fullness — the same quality of aloneness Jesus sought in the wilderness, where absence of people becomes presence of God.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'greek-philotimo',
    title: 'The Greek Virtue That Has No Translation',
    era: 'traditional',
    category: 'cultural-moment',
    themes: ['honor', 'generosity', 'duty', 'virtue', 'selflessness'],
    oneLineSummary: 'Philotimo — roughly "love of honor" — is the Greek concept of doing the right thing simply because it is right, helping others without expecting anything back, living with dignity and generosity.',
    spiritualAngle: 'Philotimo is what virtue looks like before it becomes a religious rule — the natural law written on every human heart that Paul described in Romans.',
    source: 'historical',
    spinnable: true,
  },

  // ==========================================
  // FORGIVENESS STORIES
  // ==========================================
  {
    id: 'south-africa-truth-reconciliation',
    title: 'The Nation That Chose Truth Over Punishment',
    era: '1996',
    category: 'cultural-moment',
    themes: ['forgiveness', 'justice', 'truth', 'reconciliation', 'healing'],
    oneLineSummary: 'South Africas Truth and Reconciliation Commission chose restorative over retributive justice — perpetrators who fully confessed could receive amnesty, trading punishment for truth.',
    spiritualAngle: 'The commission bet that truth-telling heals more than punishment — the same gamble the gospel makes when it offers confession and grace instead of condemnation.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'rwandan-gacaca-courts',
    title: 'The Village Courts That Processed a Genocide',
    era: '2001-2012',
    category: 'cultural-moment',
    themes: ['justice', 'forgiveness', 'community', 'healing', 'reconciliation'],
    oneLineSummary: 'After the genocide, Rwanda processed nearly 2 million cases through gacaca — community courts held on village grass where neighbors judged neighbors, choosing restoration over retribution.',
    spiritualAngle: 'Justice on the grass, face to face with your neighbors — because reconciliation cannot happen at a distance, only in the painful proximity of community.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'charleston-church-shooting-forgiveness',
    title: 'The Families Who Forgave the Shooter in 48 Hours',
    era: '2015',
    category: 'cultural-moment',
    themes: ['forgiveness', 'faith', 'grace', 'mourning', 'radical-love'],
    oneLineSummary: 'Two days after Dylann Roof shot nine people during Bible study at Emanuel AME Church, family members stood in court and told him they forgave him — stunning the world.',
    spiritualAngle: 'They forgave not because it was easy but because their faith demanded it — and their forgiveness was more powerful than any verdict could ever be.',
    source: 'historical',
    spinnable: true,
  },

  // ==========================================
  // NATURE & ECOLOGICAL MOMENTS
  // ==========================================
  {
    id: 'great-pacific-garbage-patch',
    title: 'The Trash Island Twice the Size of Texas',
    era: '1997',
    category: 'cultural-moment',
    themes: ['stewardship', 'consequence', 'creation-care', 'responsibility', 'interconnection'],
    oneLineSummary: 'The Great Pacific Garbage Patch — a floating mass of plastic debris twice the size of Texas — was discovered in the middle of the ocean, a monument to collective neglect.',
    spiritualAngle: 'We were given dominion over the earth, not permission to destroy it — the garbage patch is a physical manifestation of what happens when stewardship becomes exploitation.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'ozone-layer-recovery',
    title: 'The Time Humanity Actually Fixed an Environmental Crisis',
    era: '1987-present',
    category: 'cultural-moment',
    themes: ['hope', 'cooperation', 'stewardship', 'redemption', 'collective-action'],
    oneLineSummary: 'The Montreal Protocol banned CFCs in 1987, and the ozone layer is now healing — the one time humanity identified an environmental threat, acted collectively, and reversed the damage.',
    spiritualAngle: 'Proof that repentance works — when humanity stops doing the harmful thing and chooses differently, creation responds with healing.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'yellowstone-wolves-rivers',
    title: 'The Wolves That Changed the Rivers',
    era: '1995',
    category: 'cultural-moment',
    themes: ['interconnection', 'restoration', 'stewardship', 'ripple-effect', 'creation'],
    oneLineSummary: 'When wolves were reintroduced to Yellowstone, they reduced elk overgrazing, which regrew riverbank vegetation, which stabilized the soil, which literally changed the course of rivers.',
    spiritualAngle: 'One right restoration can cascade through an entire ecosystem — a picture of how one act of obedience can reshape everything downstream.',
    source: 'historical',
    spinnable: true,
  },

  // ==========================================
  // SCIENTIFIC DISCOVERIES WITH SPIRITUAL RESONANCE
  // ==========================================
  {
    id: 'dna-discovery-code-of-life',
    title: 'The Discovery That Life Runs on a Four-Letter Alphabet',
    era: '1953',
    category: 'cultural-moment',
    themes: ['wonder', 'design', 'complexity', 'code', 'creation'],
    oneLineSummary: 'Watson and Crick discovered that all life on Earth is written in a four-letter genetic code — A, T, C, G — an information system more sophisticated than any human language.',
    spiritualAngle: 'In the beginning was the Word — the discovery that life itself is literally written in code suggests an Author behind the alphabet.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'human-genome-project-completed',
    title: 'The Day We Read Our Own Blueprint',
    era: '2003',
    category: 'cultural-moment',
    themes: ['wonder', 'identity', 'complexity', 'knowledge', 'humility'],
    oneLineSummary: 'The Human Genome Project mapped all 3 billion base pairs of human DNA — and the lead scientist, Francis Collins, said the experience deepened his faith in God.',
    spiritualAngle: 'Collins called the genome the language of God — the deeper we read our own blueprint, the more it reads like a text that was written on purpose.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'first-photo-of-black-hole',
    title: 'The First Image of Something That Swallows Light',
    era: '2019',
    category: 'cultural-moment',
    themes: ['mystery', 'hiddenness', 'awe', 'darkness', 'discovery'],
    oneLineSummary: 'The Event Horizon Telescope captured the first image of a black hole — a void so massive that light cannot escape it — requiring a telescope effectively the size of Earth.',
    spiritualAngle: 'A black hole is invisible by definition, known only by its effect on everything around it — which is how many people experience God: unseen, but shaping everything.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'crispr-gene-editing',
    title: 'The Tool That Lets Humans Edit the Code of Life',
    era: '2012',
    category: 'cultural-moment',
    themes: ['power', 'responsibility', 'creation', 'ethics', 'stewardship'],
    oneLineSummary: 'CRISPR gave humanity the ability to precisely edit DNA — potentially curing genetic diseases, but also raising the question of whether we should rewrite what was written.',
    spiritualAngle: 'With great power comes great responsibility — CRISPR is the tree of knowledge of good and evil in a lab, and what we do with it will define us.',
    source: 'historical',
    spinnable: true,
  },

  // ==========================================
  // MOMENTS OF COLLECTIVE HUMAN EXPERIENCE
  // ==========================================
  {
    id: 'christmas-truce-1914',
    title: 'The Night Enemies Stopped Fighting to Sing Carols',
    era: '1914',
    category: 'cultural-moment',
    themes: ['peace', 'enemy-love', 'humanity', 'Christmas', 'truce'],
    oneLineSummary: 'On Christmas Eve 1914, German and British soldiers spontaneously stopped fighting, sang carols, and played football in no-mans-land — before returning to kill each other the next morning.',
    spiritualAngle: 'For one night, the birth of the Prince of Peace actually stopped a war — and the tragedy is that the peace did not last, a picture of our inability to sustain what we glimpse.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'moon-landing-united-world',
    title: 'The Moment Eight Hundred Million People Watched Together',
    era: '1969',
    category: 'cultural-moment',
    themes: ['unity', 'achievement', 'wonder', 'human-potential', 'awe'],
    oneLineSummary: 'An estimated 600 million people worldwide watched Neil Armstrong step onto the moon — the largest shared experience in human history, briefly uniting a divided world in wonder.',
    spiritualAngle: 'For one night, humanity looked up together — and the sense that we are capable of more than we imagined is itself a form of encountering transcendence.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'fall-of-berlin-wall',
    title: 'The Night a Wall Fell Because Someone Misspoke',
    era: '1989',
    category: 'cultural-moment',
    themes: ['freedom', 'surprise', 'community', 'joy', 'liberation'],
    oneLineSummary: 'The Berlin Wall fell partly because a government spokesperson misstated the new travel policy as "effective immediately" — thousands rushed to the gates, guards stood aside, and an era ended.',
    spiritualAngle: 'Sometimes liberation arrives not through grand strategy but through a stumble in the system — Gods sense of humor working through human mistakes.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'live-aid-1985',
    title: 'The Concert That Made the World Care About Famine',
    era: '1985',
    category: 'cultural-moment',
    themes: ['compassion', 'community', 'generosity', 'awareness', 'music'],
    oneLineSummary: 'Live Aid connected 1.9 billion viewers across 150 countries to watch musicians play for Ethiopian famine relief — raising $127 million and proving that compassion can be contagious at scale.',
    spiritualAngle: 'When we see suffering clearly, the instinct to help is overwhelming — Live Aid proved that apathy is often just a failure of exposure, not a failure of compassion.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'end-of-apartheid-election',
    title: 'The Day South Africa Waited in Line for Hours to Vote',
    era: '1994',
    category: 'cultural-moment',
    themes: ['freedom', 'patience', 'dignity', 'justice', 'hope'],
    oneLineSummary: 'On April 27, 1994, millions of South Africans — many voting for the first time — waited in lines stretching for miles, some for 12 hours, to participate in the first free election.',
    spiritualAngle: 'They waited all day because the vote was worth the wait — patience born of decades of suffering, a picture of what hope looks like when it finally becomes tangible.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'ebola-doctors-without-borders',
    title: 'The Doctors Who Walked Into the Hemorrhagic Ward',
    era: '2014',
    category: 'cultural-moment',
    themes: ['sacrifice', 'courage', 'service', 'calling', 'risk'],
    oneLineSummary: 'During the 2014 Ebola outbreak, Medecins Sans Frontieres workers suited up in PPE to enter hemorrhagic fever wards, knowing that a single tear in their suit could be fatal.',
    spiritualAngle: 'Walking into a ward where the disease kills half its victims is a modern parallel to Jesus touching lepers — approaching the untouchable because mercy overrides self-preservation.',
    source: 'historical',
    spinnable: true,
  },

  // ==========================================
  // LITERARY & CREATIVE MOMENTS
  // ==========================================
  {
    id: 'anne-frank-diary',
    title: 'The Girl Who Believed People Were Good While Hiding from Evil',
    era: '1942-1944',
    category: 'cultural-moment',
    themes: ['hope', 'innocence', 'witness', 'humanity', 'faith'],
    oneLineSummary: 'Anne Frank wrote "I still believe, in spite of everything, that people are really good at heart" while hiding in an attic from people who wanted to kill her — and the diary survived when she did not.',
    spiritualAngle: 'Her faith in human goodness from inside a hiding place is either naive or prophetic — and the fact that her words outlived her murderers suggests it was prophetic.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'les-miserables-candlesticks-scene',
    title: 'The Fictional Moment That Taught the World About Grace',
    era: '1862',
    category: 'cultural-moment',
    themes: ['grace', 'mercy', 'transformation', 'redemption', 'generosity'],
    oneLineSummary: 'When the bishop gives Valjean the silver candlesticks — after Valjean stole from him — and says "I have bought your soul for God," a million readers understood grace for the first time.',
    spiritualAngle: 'Fiction sometimes preaches the gospel more clearly than sermons — because a story sneaks past the defenses that theology bounces off.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'burned-library-of-alexandria',
    title: 'The Day Humanitys Largest Library Was Lost',
    era: 'circa 48 BC - 642 AD',
    category: 'cultural-moment',
    themes: ['loss', 'knowledge', 'destruction', 'impermanence', 'stewardship'],
    oneLineSummary: 'The Library of Alexandria held an estimated 400,000 scrolls — humanitys collective knowledge — and its destruction over centuries remains a symbol of everything we lose when we fail to preserve what matters.',
    spiritualAngle: 'Every generation is a steward of what the previous generation built — and the loss of Alexandria reminds us that knowledge, culture, and faith must be actively protected or they disappear.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'first-printed-english-bible-tyndale',
    title: 'The Man Who Died So English Speakers Could Read the Bible',
    era: '1536',
    category: 'cultural-moment',
    themes: ['sacrifice', 'Scripture', 'access', 'courage', 'martyrdom'],
    oneLineSummary: 'William Tyndale translated the Bible into English against church law, was strangled and burned at the stake, and his last words were "Lord, open the King of Englands eyes" — two years later, King Henry authorized an English Bible.',
    spiritualAngle: 'Tyndale died for the conviction that ordinary people should read Scripture in their own language — a prayer answered posthumously, the pattern of all prophetic sacrifice.',
    source: 'historical',
    spinnable: true,
  },

  // ==========================================
  // TECHNOLOGY & HUMAN RECKONING
  // ==========================================
  {
    id: 'hiroshima-bombing',
    title: 'The Morning Humanity Split the Atom Over a City',
    era: '1945',
    category: 'cultural-moment',
    themes: ['power', 'destruction', 'responsibility', 'conscience', 'reckoning'],
    oneLineSummary: 'The atomic bomb killed 80,000 people in Hiroshima instantly, and Robert Oppenheimer quoted the Bhagavad Gita: "Now I am become Death, the destroyer of worlds."',
    spiritualAngle: 'Oppenheimer instinctively reached for sacred text to describe what science had done — because some human acts are so consequential that only theological language can hold them.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'internet-creation-cern',
    title: 'The Physicist Who Gave Away the World Wide Web',
    era: '1989',
    category: 'cultural-moment',
    themes: ['generosity', 'access', 'communication', 'gift', 'connection'],
    oneLineSummary: 'Tim Berners-Lee invented the World Wide Web at CERN and gave it away for free, refusing to patent it — believing information access was a fundamental right, not a product.',
    spiritualAngle: 'He could have been the richest person alive but chose to give his creation away — freely you have received, freely give, applied to the most transformative technology of the century.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'ai-chess-defeats-kasparov',
    title: 'The Machine That Outthought the Human Mind',
    era: '1997',
    category: 'cultural-moment',
    themes: ['identity', 'technology', 'humility', 'humanity', 'meaning'],
    oneLineSummary: 'Deep Blue defeated world chess champion Garry Kasparov, forcing humanity to reckon with the question of what makes us unique if machines can outthink us at our own games.',
    spiritualAngle: 'If intelligence alone defined human worth, the machines would win — but the image of God in us is not our processing power but our capacity to love, grieve, and worship.',
    source: 'historical',
    spinnable: true,
  },

  // ==========================================
  // RITUALS & SACRED PRACTICES
  // ==========================================
  {
    id: 'day-of-the-dead-mexico',
    title: 'The Festival That Celebrates the Dead with Joy',
    era: 'traditional',
    category: 'cultural-moment',
    themes: ['death', 'celebration', 'memory', 'love', 'community'],
    oneLineSummary: 'Dia de los Muertos is the Mexican tradition of honoring the dead with altars, flowers, food, and music — treating death not as an ending but as a continuation of the relationship.',
    spiritualAngle: 'The Mexican conviction that love does not end at the grave echoes the Christian hope that death is not a wall but a door — and that the communion of saints includes those who have gone before.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'shabbat-weekly-rest',
    title: 'The Ancient Practice of Doing Nothing on Purpose',
    era: 'ancient to present',
    category: 'cultural-moment',
    themes: ['rest', 'sabbath', 'resistance', 'identity', 'trust'],
    oneLineSummary: 'For 3,000 years, Jewish communities have observed Shabbat — stopping all work for 25 hours every week — a practice so countercultural that the Romans called it laziness.',
    spiritualAngle: 'Sabbath is not a break from productivity but a declaration that your worth is not your output — the most radical act of trust is to stop and believe the world can survive without you.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'labyrinth-walking-meditation',
    title: 'The Ancient Path That Goes Nowhere and Everywhere',
    era: 'medieval to present',
    category: 'cultural-moment',
    themes: ['journey', 'meditation', 'trust', 'patience', 'path'],
    oneLineSummary: 'Medieval cathedrals built labyrinths on their floors — a winding path with no dead ends that always reaches the center — as a walking meditation for pilgrims who could not travel to Jerusalem.',
    spiritualAngle: 'The labyrinth teaches that the spiritual path is not a straight line but a winding one — and that every apparent detour is actually part of the design.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'ramadan-fasting-community',
    title: 'The Month Where a Billion People Fast Together',
    era: 'traditional',
    category: 'cultural-moment',
    themes: ['discipline', 'community', 'empathy', 'fasting', 'solidarity'],
    oneLineSummary: 'During Ramadan, 1.8 billion Muslims fast from dawn to sunset — not just for spiritual discipline but to feel what the hungry feel, building empathy through shared deprivation.',
    spiritualAngle: 'Fasting is practiced across every major religion because the body teaches what the mind cannot — that letting go of comfort makes room for something deeper.',
    source: 'historical',
    spinnable: true,
  },

  // ==========================================
  // SMALL MOMENTS WITH OUTSIZED MEANING
  // ==========================================
  {
    id: 'earthworm-sally-darwin-worms',
    title: 'The Scientist Who Studied Worms for 40 Years',
    era: '1881',
    category: 'cultural-moment',
    themes: ['patience', 'attention', 'small-things', 'faithfulness', 'hidden-impact'],
    oneLineSummary: 'Darwins last book was about earthworms — 40 years of patient observation proving that the smallest creatures reshape entire landscapes, one tiny tunnel at a time.',
    spiritualAngle: 'The kingdom of heaven is like a worm — invisible, underappreciated, working in the dark, slowly transforming the world without anyone noticing until it is done.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'voyager-golden-record-contents',
    title: 'What Humanity Chose to Say to the Universe',
    era: '1977',
    category: 'cultural-moment',
    themes: ['identity', 'hope', 'communication', 'beauty', 'faith'],
    oneLineSummary: 'NASAs Golden Record sent into space contains Bachs music, a baby crying, whale songs, greetings in 55 languages, and Chuck Berrys "Johnny B. Goode" — humanitys mixtape for the cosmos.',
    spiritualAngle: 'When we chose what to say to the universe, we chose music, laughter, and greetings — not our weapons or wealth — revealing what we believe is most essentially human.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'random-act-kindness-chain',
    title: 'The Drive-Through Line That Paid It Forward for Hours',
    era: '2020',
    category: 'cultural-moment',
    themes: ['kindness', 'generosity', 'chain-reaction', 'community', 'joy'],
    oneLineSummary: 'A customer at a Dairy Queen paid for the car behind them, sparking a chain of 900 consecutive cars paying for the next persons order over several hours.',
    spiritualAngle: 'Generosity is contagious — one small act of kindness created a 900-person chain, proving that grace has a ripple effect far beyond what the first giver imagined.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'daily-clapping-for-nhs-covid',
    title: 'The Night an Entire Nation Stood on Doorsteps and Clapped',
    era: '2020',
    category: 'cultural-moment',
    themes: ['gratitude', 'community', 'recognition', 'sacrifice', 'solidarity'],
    oneLineSummary: 'During COVID-19, millions across the UK stood on their doorsteps every Thursday evening to clap for healthcare workers — a spontaneous ritual of gratitude that briefly turned strangers into neighbors.',
    spiritualAngle: 'The clapping was not just appreciation but worship — a collective acknowledgment that some people sacrifice more than the rest of us, and the least we can do is notice.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'international-space-station-cooperation',
    title: 'The Place Where Former Enemies Live Together in Space',
    era: '1998-present',
    category: 'cultural-moment',
    themes: ['cooperation', 'unity', 'peace', 'shared-mission', 'perspective'],
    oneLineSummary: 'The International Space Station is the most expensive object ever built, crewed continuously since 2000 by astronauts from nations that are often adversaries on Earth — united by the shared project of exploration.',
    spiritualAngle: 'When you zoom out far enough, borders disappear — the ISS proves that a shared mission big enough can unite people who cannot agree on anything else.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'japanese-train-station-dog-hachiko',
    title: 'The Dog Who Waited for His Owner for Nine Years',
    era: '1925-1935',
    category: 'cultural-moment',
    themes: ['loyalty', 'faithfulness', 'love', 'devotion', 'waiting'],
    oneLineSummary: 'After his owner died, the dog Hachiko returned to Shibuya Station every day for nine years to wait for a train his master would never exit again — becoming Japans most famous symbol of loyalty.',
    spiritualAngle: 'Hachikos faithfulness is both heartbreaking and instructive — the willingness to wait, day after day, for someone you love is the purest picture of what devotion means.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'cave-paintings-lascaux',
    title: 'The First Art Was Made in the Dark',
    era: '17000 BC',
    category: 'cultural-moment',
    themes: ['creativity', 'beauty', 'mystery', 'humanity', 'worship'],
    oneLineSummary: 'The Lascaux cave paintings — 17,000 years old — were created by torchlight deep underground, suggesting that the human impulse to create beauty predates civilization and does not require an audience.',
    spiritualAngle: 'The first artists painted in caves that no one else would see — creating for the sake of creating, the most primal evidence that we are made in the image of a Creator.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'last-speaker-of-a-language',
    title: 'The Moment a Language Dies with Its Last Speaker',
    era: 'ongoing',
    category: 'cultural-moment',
    themes: ['loss', 'identity', 'preservation', 'grief', 'stewardship'],
    oneLineSummary: 'A language dies every two weeks — and when the last speaker of a language dies, an entire way of seeing the world vanishes, including words and concepts that exist in no other tongue.',
    spiritualAngle: 'At Babel, God scattered languages to multiply perspectives — every language that dies takes with it a unique way of understanding creation that can never be recovered.',
    source: 'historical',
    spinnable: true,
  },
];
