// ==========================================
// STORY REPOSITORY
// 200 real, documented stories for AI devotional illustration
// Two categories: Biblical Narratives (lesser-known) + Church History (2,000 years)
// Used by the generation engine to inject concrete illustrations into devotionals
// ==========================================

export interface Story {
  id: string;
  title: string;
  era: string;
  category: 'biblical' | 'church-history';
  themes: string[];
  oneLineSummary: string;
  scriptureConnection: string;
  source: 'biblical' | 'historical';
  spinnable: boolean;
}

// ==========================================
// CATEGORY 1: BIBLICAL NARRATIVES (LESSER-KNOWN)
// 100 hidden gems — skip the Sunday School staples
// ==========================================

export const BIBLICAL_STORIES: Story[] = [
  // ---------- JUDGES ----------
  {
    id: 'ehud-left-handed-assassin',
    title: 'The Left-Handed Assassin Judge',
    era: 'Judges period (~1300 BC)',
    category: 'biblical',
    themes: ['courage', 'calling', 'identity', 'obedience'],
    oneLineSummary: 'A left-handed man from the tribe named "Son of the Right Hand" smuggles a blade past guards and single-handedly liberates Israel.',
    scriptureConnection: 'Judges 3:12-30',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'jael-tent-peg',
    title: 'Jael and the Tent Peg',
    era: 'Judges period (~1200 BC)',
    category: 'biblical',
    themes: ['courage', 'justice', 'surrender', 'calling'],
    oneLineSummary: 'A nomad woman offers milk and a blanket to a fleeing general, then drives a tent peg through his skull while he sleeps.',
    scriptureConnection: 'Judges 4:17-22',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'jephthahs-daughter',
    title: "Jephthah's Unnamed Daughter",
    era: 'Judges period (~1100 BC)',
    category: 'biblical',
    themes: ['sacrifice', 'grief', 'obedience', 'lament'],
    oneLineSummary: 'A father makes a rash vow to God before battle, and his only daughter is the first to greet him when he returns victorious.',
    scriptureConnection: 'Judges 11:29-40',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'levites-concubine',
    title: 'The Levite and His Concubine',
    era: 'Judges period (~1100 BC)',
    category: 'biblical',
    themes: ['justice', 'lament', 'community', 'suffering'],
    oneLineSummary: 'The most horrifying story in the Bible — a woman is brutalized by an entire town, and her body is dismembered to wake up a nation.',
    scriptureConnection: 'Judges 19',
    source: 'biblical',
    spinnable: false,
  },
  {
    id: 'othniel-first-judge',
    title: 'Othniel: The Forgotten First Judge',
    era: 'Judges period (~1350 BC)',
    category: 'biblical',
    themes: ['calling', 'courage', 'trust', 'obedience'],
    oneLineSummary: "The Spirit of the Lord came upon Caleb's nephew — the very first judge — and nobody remembers his name.",
    scriptureConnection: 'Judges 3:7-11',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'shamgar-ox-goad',
    title: 'Shamgar and the Ox Goad',
    era: 'Judges period (~1250 BC)',
    category: 'biblical',
    themes: ['courage', 'provision', 'calling', 'humility'],
    oneLineSummary: 'A farmer kills 600 Philistines with a pointed stick used for herding cattle — and gets exactly one verse in the Bible.',
    scriptureConnection: 'Judges 3:31',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'abimelech-millstone',
    title: 'The Woman with the Millstone',
    era: 'Judges period (~1150 BC)',
    category: 'biblical',
    themes: ['justice', 'humility', 'pride'],
    oneLineSummary: 'A tyrant who murdered 70 brothers on one stone is killed when an unnamed woman drops a millstone on his head from a tower.',
    scriptureConnection: 'Judges 9:50-57',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'micahs-idol',
    title: "Micah's Household Idol",
    era: 'Judges period (~1100 BC)',
    category: 'biblical',
    themes: ['identity', 'trust', 'surrender'],
    oneLineSummary: 'A man steals silver from his mother, she curses the thief unknowingly, and they use the returned money to build an idol — then hire a Levite as a personal priest.',
    scriptureConnection: 'Judges 17-18',
    source: 'biblical',
    spinnable: true,
  },

  // ---------- 1-2 SAMUEL ----------
  {
    id: 'rizpah-vigil',
    title: "Rizpah's Six-Month Vigil",
    era: 'United Monarchy (~1000 BC)',
    category: 'biblical',
    themes: ['grief', 'perseverance', 'justice', 'sacrifice', 'hope'],
    oneLineSummary: 'A mother guards the exposed bodies of her executed sons from vultures and wild animals for six months — and her grief moves a king to act.',
    scriptureConnection: '2 Samuel 21:1-14',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'hannah-mistaken-for-drunk',
    title: 'Hannah Mistaken for Drunk',
    era: 'Judges/Monarchy transition (~1100 BC)',
    category: 'biblical',
    themes: ['prayer', 'grief', 'perseverance', 'hope', 'surrender'],
    oneLineSummary: 'A childless woman prays so desperately in the temple that the priest accuses her of being drunk — then she gives away the son she finally receives.',
    scriptureConnection: '1 Samuel 1:1-28',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'abigail-intercepts-david',
    title: 'Abigail Rides to Stop a Massacre',
    era: 'United Monarchy (~1010 BC)',
    category: 'biblical',
    themes: ['courage', 'wisdom', 'mercy', 'integrity'],
    oneLineSummary: "A brilliant woman loads donkeys with food and rides out alone to stop a future king from committing murder over her foolish husband's insult.",
    scriptureConnection: '1 Samuel 25:1-42',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'david-eats-holy-bread',
    title: 'David Eats the Forbidden Bread',
    era: 'United Monarchy (~1015 BC)',
    category: 'biblical',
    themes: ['mercy', 'provision', 'trust'],
    oneLineSummary: 'A starving fugitive eats bread reserved only for priests — and Jesus later uses this moment to redefine what holiness means.',
    scriptureConnection: '1 Samuel 21:1-6; Matthew 12:3-4',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'mephibosheth-at-davids-table',
    title: "The Crippled Prince at the King's Table",
    era: 'United Monarchy (~1000 BC)',
    category: 'biblical',
    themes: ['grace', 'identity', 'generosity', 'mercy'],
    oneLineSummary: "Saul's crippled grandson, hiding in fear, is found by David and given a permanent seat at the king's table — not for anything he did, but because of a promise.",
    scriptureConnection: '2 Samuel 9:1-13',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'witch-of-endor',
    title: 'Saul and the Medium of Endor',
    era: 'United Monarchy (~1010 BC)',
    category: 'biblical',
    themes: ['fear', 'loneliness', 'faith-in-doubt', 'suffering'],
    oneLineSummary: "A desperate king who banned mediums secretly visits one at night — and the ghost of Samuel delivers his death sentence.",
    scriptureConnection: '1 Samuel 28:3-25',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'davids-census-plague',
    title: "David's Census and the Threshing Floor",
    era: 'United Monarchy (~970 BC)',
    category: 'biblical',
    themes: ['pride', 'humility', 'sacrifice', 'mercy'],
    oneLineSummary: 'David counts his army out of pride, a plague kills 70,000, and when offered free land for an altar, he insists on paying because worship that costs nothing is worth nothing.',
    scriptureConnection: '2 Samuel 24:1-25',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'tamar-and-amnon',
    title: "Tamar's Torn Robe",
    era: 'United Monarchy (~990 BC)',
    category: 'biblical',
    themes: ['suffering', 'justice', 'lament', 'grief'],
    oneLineSummary: "David's daughter Tamar is assaulted by her half-brother, tears her royal robe, and her father the king does absolutely nothing about it.",
    scriptureConnection: '2 Samuel 13:1-22',
    source: 'biblical',
    spinnable: false,
  },
  {
    id: 'jonathan-strips-armor-for-david',
    title: "Jonathan Strips His Armor for David",
    era: 'United Monarchy (~1020 BC)',
    category: 'biblical',
    themes: ['sacrifice', 'friendship', 'generosity', 'surrender'],
    oneLineSummary: "The crown prince voluntarily gives his robe, armor, sword, and belt to a shepherd boy — surrendering his claim to the throne out of love.",
    scriptureConnection: '1 Samuel 18:1-4',
    source: 'biblical',
    spinnable: true,
  },

  // ---------- 1-2 KINGS ----------
  {
    id: 'elisha-floating-axe-head',
    title: 'The Floating Axe Head',
    era: 'Divided Kingdom (~850 BC)',
    category: 'biblical',
    themes: ['provision', 'trust', 'humility'],
    oneLineSummary: "A seminary student loses a borrowed axe head in the river and panics — not about the tool, but because he can't afford to replace what he borrowed.",
    scriptureConnection: '2 Kings 6:1-7',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'widow-oil-jars',
    title: "The Widow's Endless Oil",
    era: 'Divided Kingdom (~850 BC)',
    category: 'biblical',
    themes: ['provision', 'trust', 'hope', 'community'],
    oneLineSummary: "A prophet's widow about to lose her sons to a creditor is told to borrow every empty jar she can find — and her tiny flask of oil doesn't stop pouring until every jar is full.",
    scriptureConnection: '2 Kings 4:1-7',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'naamans-servant-girl',
    title: "The Servant Girl Who Saved a General",
    era: 'Divided Kingdom (~850 BC)',
    category: 'biblical',
    themes: ['forgiveness', 'courage', 'humility', 'mercy'],
    oneLineSummary: "A kidnapped Israelite slave girl tells her captor's leprous wife about a prophet who can heal him — showing mercy to the man who stole her from her family.",
    scriptureConnection: '2 Kings 5:1-14',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'elisha-invisible-army',
    title: "Elisha's Invisible Army",
    era: 'Divided Kingdom (~850 BC)',
    category: 'biblical',
    themes: ['trust', 'fear', 'faith-in-doubt', 'provision'],
    oneLineSummary: "A servant panics at the enemy army surrounding them until God opens his eyes to see the mountains filled with horses and chariots of fire.",
    scriptureConnection: '2 Kings 6:8-17',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'four-lepers-at-the-gate',
    title: 'Four Lepers Discover Abundance',
    era: 'Divided Kingdom (~850 BC)',
    category: 'biblical',
    themes: ['hope', 'provision', 'courage', 'generosity'],
    oneLineSummary: "Four starving lepers decide they have nothing to lose, walk into the enemy camp, and find it completely abandoned — with enough food to save a city.",
    scriptureConnection: '2 Kings 7:3-11',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'elijah-fed-by-ravens',
    title: 'Fed by Unclean Birds',
    era: 'Divided Kingdom (~870 BC)',
    category: 'biblical',
    themes: ['provision', 'trust', 'surrender', 'humility'],
    oneLineSummary: "God sends ravens — birds Jews considered unclean — to deliver bread and meat to his prophet, as if to say: my provision won't always look the way you expect.",
    scriptureConnection: '1 Kings 17:1-6',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'elijah-depression-broom-tree',
    title: "Elijah's Depression Under the Broom Tree",
    era: 'Divided Kingdom (~865 BC)',
    category: 'biblical',
    themes: ['suffering', 'loneliness', 'hope', 'provision'],
    oneLineSummary: "One day after his greatest victory, the prophet sits under a bush and asks God to kill him — and God responds not with a lecture but with food and sleep.",
    scriptureConnection: '1 Kings 19:1-8',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'obadiah-hides-100-prophets',
    title: 'Obadiah Hides 100 Prophets in Caves',
    era: 'Divided Kingdom (~870 BC)',
    category: 'biblical',
    themes: ['courage', 'integrity', 'sacrifice', 'faith-in-doubt'],
    oneLineSummary: "A high-ranking government official secretly hides 100 prophets in caves and feeds them while serving a queen who wants them dead.",
    scriptureConnection: '1 Kings 18:1-16',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'jehosheba-saves-joash',
    title: 'Jehosheba Hides the Baby King',
    era: 'Divided Kingdom (~841 BC)',
    category: 'biblical',
    themes: ['courage', 'sacrifice', 'hope', 'calling'],
    oneLineSummary: "When the queen murders every royal heir to seize power, one woman steals a baby prince and hides him in the temple for six years — saving the entire messianic line.",
    scriptureConnection: '2 Kings 11:1-3',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'dead-man-touches-elishas-bones',
    title: "The Corpse That Touched Elisha's Bones",
    era: 'Divided Kingdom (~800 BC)',
    category: 'biblical',
    themes: ['hope', 'provision', 'transformation'],
    oneLineSummary: "A dead man is hastily thrown into Elisha's tomb during a raid, touches the prophet's bones, and immediately comes back to life.",
    scriptureConnection: '2 Kings 13:20-21',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'josiah-finds-the-book',
    title: "Josiah Finds the Lost Bible",
    era: 'Late Monarchy (~622 BC)',
    category: 'biblical',
    themes: ['transformation', 'obedience', 'humility', 'hope'],
    oneLineSummary: "During temple renovations, workers discover the Book of the Law that Israel had literally lost — and the young king tears his clothes when he hears what it says.",
    scriptureConnection: '2 Kings 22:1-20',
    source: 'biblical',
    spinnable: true,
  },

  // ---------- RUTH, ESTHER, EZRA, NEHEMIAH ----------
  {
    id: 'ruth-threshing-floor',
    title: "Ruth's Midnight Visit to the Threshing Floor",
    era: 'Judges period (~1100 BC)',
    category: 'biblical',
    themes: ['courage', 'trust', 'identity', 'provision'],
    oneLineSummary: "A Moabite widow follows her mother-in-law's risky plan: wash, perfume, dress up, and go lie at a sleeping man's feet at midnight.",
    scriptureConnection: 'Ruth 3:1-18',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'nehemiah-prays-before-asking',
    title: "Nehemiah's Four-Month Prayer Before Speaking",
    era: 'Post-Exile (~445 BC)',
    category: 'biblical',
    themes: ['patience', 'prayer', 'courage', 'calling'],
    oneLineSummary: "A cupbearer hears devastating news about Jerusalem and prays for four months before saying a single word to the king about it.",
    scriptureConnection: 'Nehemiah 1:1-2:8',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'ezra-weeping-in-rain',
    title: "Ezra's Weeping Assembly in the Rain",
    era: 'Post-Exile (~458 BC)',
    category: 'biblical',
    themes: ['lament', 'community', 'transformation', 'obedience'],
    oneLineSummary: "An entire nation stands trembling in the rain while Ezra weeps over their unfaithfulness — and they don't ask to go inside.",
    scriptureConnection: 'Ezra 10:1-17',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'sanballat-mocks-the-wall',
    title: "Sanballat's Mockery of the Builders",
    era: 'Post-Exile (~445 BC)',
    category: 'biblical',
    themes: ['perseverance', 'courage', 'community', 'calling'],
    oneLineSummary: "Enemies mock the wall builders — 'Even a fox climbing on it would break it down' — and Nehemiah's people build with swords in one hand and tools in the other.",
    scriptureConnection: 'Nehemiah 4:1-23',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'vashti-refuses-the-king',
    title: "Queen Vashti Says No",
    era: 'Persian period (~483 BC)',
    category: 'biblical',
    themes: ['courage', 'integrity', 'identity', 'sacrifice'],
    oneLineSummary: "A queen refuses to parade herself before her drunk husband's guests, loses her crown, and is never mentioned again — but her 'no' changes history.",
    scriptureConnection: 'Esther 1:10-22',
    source: 'biblical',
    spinnable: true,
  },

  // ---------- MINOR PROPHETS ----------
  {
    id: 'hosea-buys-back-gomer',
    title: "Hosea Buys Back His Unfaithful Wife",
    era: 'Divided Kingdom (~750 BC)',
    category: 'biblical',
    themes: ['forgiveness', 'mercy', 'sacrifice', 'love'],
    oneLineSummary: "God tells a prophet to marry a prostitute, she leaves him repeatedly, and then God says: go buy her back from the slave market — because that's what my love looks like.",
    scriptureConnection: 'Hosea 3:1-5',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'amos-the-fig-farmer-prophet',
    title: "Amos: The Fig Farmer Who Confronted a Nation",
    era: 'Divided Kingdom (~760 BC)',
    category: 'biblical',
    themes: ['justice', 'calling', 'courage', 'humility'],
    oneLineSummary: "A fig farmer with no prophetic credentials walks into the wealthiest city in Israel and tells them their worship makes God sick.",
    scriptureConnection: 'Amos 7:14-15; 5:21-24',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'habakkuk-argues-with-god',
    title: "Habakkuk's Argument with God",
    era: 'Late Monarchy (~610 BC)',
    category: 'biblical',
    themes: ['faith-in-doubt', 'trust', 'lament', 'hope'],
    oneLineSummary: "A prophet files a formal complaint with God — 'Why do you make me look at injustice?' — and God's answer makes things worse before it gets better.",
    scriptureConnection: 'Habakkuk 1:1-2:4',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'malachi-robbing-god',
    title: "Malachi: The People Who Robbed God and Didn't Know It",
    era: 'Post-Exile (~430 BC)',
    category: 'biblical',
    themes: ['generosity', 'integrity', 'trust', 'obedience'],
    oneLineSummary: "God accuses an entire nation of robbery, they ask 'How?' and he says: by keeping for yourselves what was meant for others.",
    scriptureConnection: 'Malachi 3:8-12',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'micah-what-god-requires',
    title: "Micah's Three-Word Answer",
    era: 'Divided Kingdom (~735 BC)',
    category: 'biblical',
    themes: ['justice', 'humility', 'mercy', 'obedience'],
    oneLineSummary: "After eight chapters of complicated prophecy, Micah boils down everything God wants into three things: do justice, love mercy, walk humbly.",
    scriptureConnection: 'Micah 6:6-8',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'zechariah-vision-of-joshua',
    title: "Joshua the High Priest's Filthy Clothes",
    era: 'Post-Exile (~520 BC)',
    category: 'biblical',
    themes: ['grace', 'identity', 'transformation', 'mercy'],
    oneLineSummary: "The high priest stands before God in filthy rags while Satan accuses him, and God says: take off those clothes and dress him in clean robes — I'm not done with him.",
    scriptureConnection: 'Zechariah 3:1-7',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'joel-locusts-and-restoration',
    title: "Joel's Promise After the Locusts",
    era: 'Post-Exile (~500 BC)',
    category: 'biblical',
    themes: ['hope', 'provision', 'transformation', 'patience'],
    oneLineSummary: "After a locust plague devours everything in sight, God makes a staggering promise: I will repay you for the years the locusts have eaten.",
    scriptureConnection: 'Joel 2:25-27',
    source: 'biblical',
    spinnable: true,
  },

  // ---------- GENESIS / PATRIARCHS ----------
  {
    id: 'hagar-god-who-sees',
    title: "Hagar Names God 'The God Who Sees Me'",
    era: 'Patriarchs (~2000 BC)',
    category: 'biblical',
    themes: ['identity', 'hope', 'suffering', 'provision'],
    oneLineSummary: "A pregnant slave girl, thrown out by her mistress, becomes the first person in the Bible to give God a name: El Roi — the God who sees me.",
    scriptureConnection: 'Genesis 16:1-14',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'jacob-wrestles-god',
    title: "Jacob Wrestles Until Daybreak",
    era: 'Patriarchs (~1900 BC)',
    category: 'biblical',
    themes: ['perseverance', 'transformation', 'surrender', 'identity'],
    oneLineSummary: "A con man spends the night wrestling a mysterious stranger and refuses to let go until he receives a blessing — and walks away with a limp and a new name.",
    scriptureConnection: 'Genesis 32:22-32',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'tamar-disguises-as-prostitute',
    title: "Tamar's Desperate Disguise",
    era: 'Patriarchs (~1850 BC)',
    category: 'biblical',
    themes: ['justice', 'courage', 'identity', 'hope'],
    oneLineSummary: "A twice-widowed woman disguises herself as a prostitute to trick her father-in-law into fulfilling his obligation — and ends up in the genealogy of Jesus.",
    scriptureConnection: 'Genesis 38:1-30',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'lot-wife-looks-back',
    title: "Lot's Wife Turns to Salt",
    era: 'Patriarchs (~2000 BC)',
    category: 'biblical',
    themes: ['surrender', 'trust', 'obedience'],
    oneLineSummary: "She wasn't running back — she just looked. One glance toward what she was leaving behind turned her into a pillar of salt.",
    scriptureConnection: 'Genesis 19:26; Luke 17:32',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'josephs-brothers-dont-recognize',
    title: "Joseph's Brothers at the Table",
    era: 'Patriarchs (~1880 BC)',
    category: 'biblical',
    themes: ['forgiveness', 'patience', 'mercy', 'transformation'],
    oneLineSummary: "The most powerful man in Egypt seats his clueless brothers at a table in exact birth order, gives the youngest five times more food, and weeps in private.",
    scriptureConnection: 'Genesis 43:29-34',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'enoch-walked-with-god',
    title: "Enoch Walked with God and Was No More",
    era: 'Pre-Flood',
    category: 'biblical',
    themes: ['presence', 'trust', 'hope'],
    oneLineSummary: "In a genealogy of people who lived and died, one man breaks the pattern: Enoch walked with God — and then he was not, because God took him.",
    scriptureConnection: 'Genesis 5:21-24',
    source: 'biblical',
    spinnable: true,
  },

  // ---------- EXODUS / NUMBERS / DEUTERONOMY ----------
  {
    id: 'shiphrah-puah-midwives',
    title: "The Midwives Who Lied to Pharaoh",
    era: 'Exodus (~1500 BC)',
    category: 'biblical',
    themes: ['courage', 'integrity', 'justice', 'calling'],
    oneLineSummary: "Two Hebrew midwives are ordered to kill every newborn boy — they refuse, lie to Pharaoh's face about it, and God rewards them with families of their own.",
    scriptureConnection: 'Exodus 1:15-21',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'moses-face-glows',
    title: "Moses Wears a Veil Over His Glowing Face",
    era: 'Exodus (~1440 BC)',
    category: 'biblical',
    themes: ['presence', 'transformation', 'identity'],
    oneLineSummary: "After speaking with God, Moses' face glows so brightly the people are afraid — so he wears a veil, and Paul later says it was to hide that the glory was fading.",
    scriptureConnection: 'Exodus 34:29-35; 2 Corinthians 3:13',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'balaams-donkey',
    title: "Balaam's Donkey Sees the Angel",
    era: 'Wilderness period (~1400 BC)',
    category: 'biblical',
    themes: ['humility', 'obedience', 'trust'],
    oneLineSummary: "A prophet for hire can't see the angel blocking his path, but his donkey can — and when God gives the donkey a voice, the animal is more theologically astute than the prophet.",
    scriptureConnection: 'Numbers 22:21-39',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'zelophehads-daughters',
    title: "The Five Daughters Who Changed the Law",
    era: 'Wilderness period (~1400 BC)',
    category: 'biblical',
    themes: ['justice', 'courage', 'identity', 'calling'],
    oneLineSummary: "Five sisters with no brothers challenge Moses himself about inheritance law — and God sides with them, rewriting the legal code of Israel.",
    scriptureConnection: 'Numbers 27:1-11',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'bronze-serpent-pole',
    title: "The Bronze Snake on a Pole",
    era: 'Wilderness period (~1400 BC)',
    category: 'biblical',
    themes: ['trust', 'faith-in-doubt', 'hope', 'provision'],
    oneLineSummary: "After poisonous snakes plague the camp, God tells Moses to make a bronze snake and put it on a pole — anyone who looks at it lives, and Jesus says this foreshadows the cross.",
    scriptureConnection: 'Numbers 21:4-9; John 3:14',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'moses-strikes-rock-twice',
    title: "Moses Strikes the Rock Twice",
    era: 'Wilderness period (~1407 BC)',
    category: 'biblical',
    themes: ['obedience', 'patience', 'humility', 'grief'],
    oneLineSummary: "After 40 years of faithful leadership, Moses loses the Promised Land because he hit a rock in anger when God told him to speak to it.",
    scriptureConnection: 'Numbers 20:1-12',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'korahs-rebellion-earth-swallows',
    title: "The Earth Swallows Korah",
    era: 'Wilderness period (~1400 BC)',
    category: 'biblical',
    themes: ['pride', 'humility', 'justice', 'obedience'],
    oneLineSummary: "A man challenges Moses' authority saying 'the whole community is holy' — and the ground beneath him opens up and swallows his entire household alive.",
    scriptureConnection: 'Numbers 16:1-35',
    source: 'biblical',
    spinnable: false,
  },

  // ---------- PSALMS / WISDOM ----------
  {
    id: 'psalm-88-no-resolution',
    title: "The Psalm with No Happy Ending",
    era: 'Monarchy period',
    category: 'biblical',
    themes: ['lament', 'loneliness', 'suffering', 'faith-in-doubt'],
    oneLineSummary: "Psalm 88 is the only psalm that ends in complete darkness — no resolution, no praise, no hope at the end — just 'darkness is my closest friend.'",
    scriptureConnection: 'Psalm 88',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'ecclesiastes-meaningless',
    title: "The Teacher Who Called Everything Meaningless",
    era: 'Monarchy period (~950 BC)',
    category: 'biblical',
    themes: ['faith-in-doubt', 'identity', 'surrender', 'joy-in-pain'],
    oneLineSummary: "The wisest and richest man alive tries everything — pleasure, work, wisdom, wealth — and concludes it's all meaningless vapor, yet still says: eat, drink, enjoy your work.",
    scriptureConnection: 'Ecclesiastes 1:1-2; 9:7-10',
    source: 'biblical',
    spinnable: true,
  },

  // ---------- ISAIAH / JEREMIAH / EZEKIEL / DANIEL ----------
  {
    id: 'isaiah-naked-three-years',
    title: "Isaiah Walks Naked for Three Years",
    era: 'Divided Kingdom (~713 BC)',
    category: 'biblical',
    themes: ['obedience', 'humility', 'calling', 'surrender'],
    oneLineSummary: "God tells Isaiah to strip naked and walk barefoot for three years as a living prophecy — and he does it.",
    scriptureConnection: 'Isaiah 20:1-6',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'jeremiah-buys-field-during-siege',
    title: "Jeremiah Buys Land During a Siege",
    era: 'Late Monarchy (~588 BC)',
    category: 'biblical',
    themes: ['hope', 'trust', 'faith-in-doubt', 'obedience'],
    oneLineSummary: "While Babylon's army surrounds Jerusalem and he's in prison, Jeremiah buys a field — because God says houses and fields will be bought again in this land.",
    scriptureConnection: 'Jeremiah 32:1-15',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'ezekiel-cooks-over-dung',
    title: "Ezekiel's Dung-Fire Bread",
    era: 'Exile (~593 BC)',
    category: 'biblical',
    themes: ['obedience', 'humility', 'calling'],
    oneLineSummary: "God tells Ezekiel to cook bread over human dung as a sign to Israel — the prophet objects, so God 'compromises' and lets him use cow dung instead.",
    scriptureConnection: 'Ezekiel 4:9-17',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'ezekiel-valley-dry-bones',
    title: "The Valley of Dry Bones",
    era: 'Exile (~586 BC)',
    category: 'biblical',
    themes: ['hope', 'transformation', 'trust', 'community'],
    oneLineSummary: "God walks Ezekiel through a valley of bleached bones and asks: can these bones live? — then commands him to prophesy, and an army reassembles from the dust.",
    scriptureConnection: 'Ezekiel 37:1-14',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'jeremiah-thrown-in-cistern',
    title: "Jeremiah in the Mud Cistern",
    era: 'Late Monarchy (~588 BC)',
    category: 'biblical',
    themes: ['perseverance', 'suffering', 'calling', 'hope'],
    oneLineSummary: "Officials throw the prophet into a cistern to die — he sinks into the mud — and an Ethiopian eunuch named Ebed-Melech risks his life to pull him out with old rags as rope cushions.",
    scriptureConnection: 'Jeremiah 38:1-13',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'daniel-friends-refuse-food',
    title: "The Vegetable Test in Babylon",
    era: 'Exile (~605 BC)',
    category: 'biblical',
    themes: ['integrity', 'courage', 'identity', 'trust'],
    oneLineSummary: "Four teenagers in a foreign empire politely refuse the king's gourmet food and ask for vegetables and water — and after ten days look healthier than everyone else.",
    scriptureConnection: 'Daniel 1:1-21',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'nebuchadnezzar-eats-grass',
    title: "The King Who Ate Grass Like an Animal",
    era: 'Exile (~570 BC)',
    category: 'biblical',
    themes: ['pride', 'humility', 'transformation', 'mercy'],
    oneLineSummary: "The most powerful king on earth says 'look what I built' — and immediately goes insane, eats grass like cattle for seven years, until he looks up at heaven.",
    scriptureConnection: 'Daniel 4:28-37',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'handwriting-on-the-wall',
    title: "The Fingers That Wrote on the Wall",
    era: 'Exile (~539 BC)',
    category: 'biblical',
    themes: ['pride', 'justice', 'humility'],
    oneLineSummary: "During a feast using stolen temple cups, a disembodied hand writes four words on the wall that no one can read — that night, the empire falls.",
    scriptureConnection: 'Daniel 5:1-31',
    source: 'biblical',
    spinnable: true,
  },

  // ---------- NEW TESTAMENT — GOSPELS (OVERLOOKED MOMENTS) ----------
  {
    id: 'woman-bent-18-years',
    title: "The Woman Bent Double for 18 Years",
    era: '~30 AD',
    category: 'biblical',
    themes: ['suffering', 'hope', 'identity', 'joy-in-pain'],
    oneLineSummary: "For 18 years she could only see the ground — then Jesus calls her forward on the Sabbath, touches her, and she stands up straight for the first time in two decades.",
    scriptureConnection: 'Luke 13:10-17',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'jesus-writes-in-dirt',
    title: "Jesus Writes in the Dirt",
    era: '~30 AD',
    category: 'biblical',
    themes: ['mercy', 'justice', 'humility', 'grace'],
    oneLineSummary: "Religious leaders throw a woman at Jesus' feet demanding execution — he bends down, writes something in the dirt, and they walk away one by one starting with the oldest.",
    scriptureConnection: 'John 8:1-11',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'syrophoenician-woman-crumbs',
    title: "The Woman Who Argued with Jesus and Won",
    era: '~30 AD',
    category: 'biblical',
    themes: ['perseverance', 'faith-in-doubt', 'courage', 'identity'],
    oneLineSummary: "A Gentile mother asks Jesus for help, he compares her to a dog, and she fires back — 'even dogs eat crumbs from the table' — and he heals her daughter.",
    scriptureConnection: 'Mark 7:24-30',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'peter-sinks-walking-on-water',
    title: "Peter's Three Steps on Water",
    era: '~29 AD',
    category: 'biblical',
    themes: ['faith-in-doubt', 'trust', 'courage', 'fear'],
    oneLineSummary: "Everyone remembers Peter sinking — but he's the only person besides Jesus who ever walked on water, even if just for a few steps.",
    scriptureConnection: 'Matthew 14:28-31',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'widow-two-coins',
    title: "The Widow's Two Coins",
    era: '~30 AD',
    category: 'biblical',
    themes: ['generosity', 'sacrifice', 'humility', 'trust'],
    oneLineSummary: "Rich people make a show of large donations while a widow drops in two tiny coins — and Jesus says she gave more than all of them combined.",
    scriptureConnection: 'Mark 12:41-44',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'jesus-weeps-at-lazarus-tomb',
    title: "Jesus Wept (Though He Knew the Ending)",
    era: '~30 AD',
    category: 'biblical',
    themes: ['grief', 'presence', 'suffering', 'hope'],
    oneLineSummary: "Jesus knows he's about to raise Lazarus from the dead — he's walking to the tomb to do it — and he still stops and weeps.",
    scriptureConnection: 'John 11:33-36',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'hemorrhaging-woman-touches-cloak',
    title: "Twelve Years of Bleeding, One Touch",
    era: '~29 AD',
    category: 'biblical',
    themes: ['perseverance', 'hope', 'faith-in-doubt', 'identity'],
    oneLineSummary: "A woman who spent everything on doctors and only got worse crawls through a crowd to touch the edge of Jesus' cloak — and he stops a whole procession to find her.",
    scriptureConnection: 'Mark 5:25-34',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'mary-anoints-jesus-feet',
    title: "The Perfume Worth a Year's Wages",
    era: '~30 AD',
    category: 'biblical',
    themes: ['surrender', 'generosity', 'sacrifice', 'love'],
    oneLineSummary: "A woman breaks open a jar of perfume worth a year's salary, pours it on Jesus' feet, and wipes them with her hair — while the disciples calculate the waste.",
    scriptureConnection: 'John 12:1-8',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'garden-of-gethsemane-ear',
    title: "Jesus Heals the Ear of His Arrester",
    era: '~30 AD',
    category: 'biblical',
    themes: ['mercy', 'forgiveness', 'love', 'surrender'],
    oneLineSummary: "Peter slashes off a soldier's ear during Jesus' arrest, and the last miracle Jesus performs before the cross is healing the man who came to take him away.",
    scriptureConnection: 'Luke 22:49-51',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'young-man-runs-naked',
    title: "The Young Man Who Fled Naked",
    era: '~30 AD',
    category: 'biblical',
    themes: ['fear', 'identity', 'surrender'],
    oneLineSummary: "During Jesus' arrest, a young man following in only a linen cloth is grabbed — he slips out of it and runs away naked into the night.",
    scriptureConnection: 'Mark 14:51-52',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'thomas-asks-to-see-wounds',
    title: "Thomas Touches the Wounds",
    era: '~30 AD',
    category: 'biblical',
    themes: ['faith-in-doubt', 'trust', 'hope', 'presence'],
    oneLineSummary: "Jesus doesn't rebuke Thomas for doubting — he shows up, holds out his scarred hands, and says 'put your finger here.'",
    scriptureConnection: 'John 20:24-29',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'jesus-cooks-breakfast-after-resurrection',
    title: "The Risen Christ Makes Breakfast",
    era: '~30 AD',
    category: 'biblical',
    themes: ['presence', 'provision', 'hope', 'love'],
    oneLineSummary: "After conquering death, the first thing Jesus does is stand on a beach at dawn and cook fish over charcoal for his exhausted, failed friends.",
    scriptureConnection: 'John 21:1-14',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'two-on-road-to-emmaus',
    title: "The Stranger on the Road to Emmaus",
    era: '~30 AD',
    category: 'biblical',
    themes: ['presence', 'hope', 'grief', 'transformation'],
    oneLineSummary: "Two grieving disciples walk with a stranger who explains everything — and they only recognize Jesus when he breaks bread, then he vanishes.",
    scriptureConnection: 'Luke 24:13-35',
    source: 'biblical',
    spinnable: true,
  },

  // ---------- NEW TESTAMENT — ACTS ----------
  {
    id: 'ananias-prays-for-paul',
    title: "Ananias Prays for the Man Who Hunted Him",
    era: '~34 AD',
    category: 'biblical',
    themes: ['courage', 'forgiveness', 'obedience', 'trust'],
    oneLineSummary: "God tells Ananias to go heal the man who has warrants to arrest every Christian in Damascus — and Ananias goes, lays hands on him, and calls him 'Brother Saul.'",
    scriptureConnection: 'Acts 9:10-19',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'tabitha-raised-from-dead',
    title: "Tabitha/Dorcas Raised from the Dead",
    era: '~40 AD',
    category: 'biblical',
    themes: ['generosity', 'community', 'hope', 'love'],
    oneLineSummary: "When a beloved seamstress dies, the widows she clothed stand weeping and showing Peter the coats she made — and he raises her from the dead.",
    scriptureConnection: 'Acts 9:36-42',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'ethiopian-eunuch-on-road',
    title: "The Ethiopian Official Reading Isaiah",
    era: '~34 AD',
    category: 'biblical',
    themes: ['calling', 'identity', 'hope', 'transformation'],
    oneLineSummary: "A powerful Ethiopian eunuch — excluded from the temple by Jewish law — is reading Isaiah alone in his chariot when Philip appears, explains the passage, and baptizes him on the spot.",
    scriptureConnection: 'Acts 8:26-39',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'paul-and-silas-sing-in-prison',
    title: "Singing at Midnight in Chains",
    era: '~50 AD',
    category: 'biblical',
    themes: ['joy-in-pain', 'perseverance', 'trust', 'hope'],
    oneLineSummary: "Paul and Silas are beaten and chained in the deepest cell at midnight — and instead of crying, they start singing hymns so loudly the other prisoners listen.",
    scriptureConnection: 'Acts 16:22-34',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'eutychus-falls-from-window',
    title: "The Boy Who Fell Asleep During Paul's Sermon",
    era: '~57 AD',
    category: 'biblical',
    themes: ['community', 'hope', 'provision'],
    oneLineSummary: "A young man sitting in a third-story window falls asleep during Paul's long sermon, falls to his death — Paul goes down, hugs him, and he comes back to life.",
    scriptureConnection: 'Acts 20:7-12',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'lydia-first-european-convert',
    title: "Lydia: The First European Convert",
    era: '~50 AD',
    category: 'biblical',
    themes: ['calling', 'generosity', 'community', 'transformation'],
    oneLineSummary: "A wealthy businesswoman selling luxury purple cloth becomes the first person to accept the gospel in Europe — and immediately opens her home as the first European church.",
    scriptureConnection: 'Acts 16:13-15',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'rhoda-leaves-peter-at-door',
    title: "Rhoda Forgets to Open the Door",
    era: '~44 AD',
    category: 'biblical',
    themes: ['prayer', 'joy-in-pain', 'community', 'hope'],
    oneLineSummary: "The church prays all night for Peter's release from prison — an angel frees him — he knocks on the door, and the servant girl is so excited she leaves him standing outside.",
    scriptureConnection: 'Acts 12:12-17',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'paul-shipwreck-malta',
    title: "Paul Bitten by a Snake on Malta",
    era: '~60 AD',
    category: 'biblical',
    themes: ['perseverance', 'provision', 'trust', 'calling'],
    oneLineSummary: "After surviving a shipwreck, Paul is bitten by a viper — the locals wait for him to die, and when he doesn't, they decide he must be a god.",
    scriptureConnection: 'Acts 28:1-6',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'stephens-face-like-angel',
    title: "Stephen's Face Like an Angel",
    era: '~34 AD',
    category: 'biblical',
    themes: ['courage', 'forgiveness', 'sacrifice', 'hope'],
    oneLineSummary: "As Stephen is being stoned to death, the crowd sees his face shining like an angel, and his last words echo Jesus: 'Lord, do not hold this sin against them.'",
    scriptureConnection: 'Acts 6:15; 7:54-60',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'cornelius-vision-gentile-inclusion',
    title: "The Sheet from Heaven",
    era: '~40 AD',
    category: 'biblical',
    themes: ['transformation', 'identity', 'community', 'mercy'],
    oneLineSummary: "God gives Peter a vision of unclean animals on a sheet and says 'eat' — Peter refuses three times, and then realizes the vision isn't about food at all.",
    scriptureConnection: 'Acts 10:1-48',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'aquila-priscilla-teach-apollos',
    title: "Priscilla and Aquila Correct Apollos",
    era: '~52 AD',
    category: 'biblical',
    themes: ['humility', 'community', 'wisdom', 'generosity'],
    oneLineSummary: "A brilliant preacher has his theology incomplete — and a tentmaking couple pulls him aside privately to explain the way of God more accurately.",
    scriptureConnection: 'Acts 18:24-28',
    source: 'biblical',
    spinnable: true,
  },

  // ---------- NEW TESTAMENT — EPISTLES ----------
  {
    id: 'onesimus-runaway-slave',
    title: "Paul Returns a Runaway Slave as a Brother",
    era: '~60 AD',
    category: 'biblical',
    themes: ['forgiveness', 'identity', 'transformation', 'mercy'],
    oneLineSummary: "Paul sends a runaway slave back to his master with a letter: receive him not as property but as a beloved brother — and charge anything he owes to my account.",
    scriptureConnection: 'Philemon 1:8-21',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'epaphroditus-almost-dies',
    title: "Epaphroditus Nearly Dies Delivering a Gift",
    era: '~61 AD',
    category: 'biblical',
    themes: ['sacrifice', 'friendship', 'community', 'love'],
    oneLineSummary: "A man nearly works himself to death delivering a care package to Paul in prison — and Paul tells the church to honor people like him.",
    scriptureConnection: 'Philippians 2:25-30',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'thorn-in-pauls-flesh',
    title: "The Thorn That God Refused to Remove",
    era: '~55 AD',
    category: 'biblical',
    themes: ['suffering', 'trust', 'surrender', 'faith-in-doubt'],
    oneLineSummary: "Paul begs God three times to remove a mysterious affliction, and God says no — my grace is enough, because my power works best in your weakness.",
    scriptureConnection: '2 Corinthians 12:7-10',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'pauls-list-of-sufferings',
    title: "Paul's Resume of Suffering",
    era: '~55 AD',
    category: 'biblical',
    themes: ['perseverance', 'suffering', 'joy-in-pain', 'calling'],
    oneLineSummary: "When challenged to prove his credentials, Paul lists: five times whipped, three times beaten with rods, once stoned, three shipwrecks, a night in the open sea.",
    scriptureConnection: '2 Corinthians 11:23-28',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'phoebe-the-deacon',
    title: "Phoebe: The Woman Who Carried Romans",
    era: '~57 AD',
    category: 'biblical',
    themes: ['calling', 'community', 'courage', 'generosity'],
    oneLineSummary: "Paul entrusts the most theologically important letter ever written to a woman named Phoebe — a deacon — to hand-carry across the Mediterranean to Rome.",
    scriptureConnection: 'Romans 16:1-2',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'junia-outstanding-among-apostles',
    title: "Junia: Outstanding Among the Apostles",
    era: '~57 AD',
    category: 'biblical',
    themes: ['calling', 'identity', 'community', 'courage'],
    oneLineSummary: "In Romans 16, Paul greets a woman named Junia and calls her 'outstanding among the apostles' — later translators changed her name to a man's for centuries.",
    scriptureConnection: 'Romans 16:7',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'james-tongue-small-fire',
    title: "The Tongue: A Small Fire",
    era: '~48 AD',
    category: 'biblical',
    themes: ['integrity', 'humility', 'wisdom', 'discipline'],
    oneLineSummary: "James compares the tongue to a tiny spark that sets an entire forest ablaze — the same mouth that praises God on Sunday curses people made in God's image on Monday.",
    scriptureConnection: 'James 3:1-12',
    source: 'biblical',
    spinnable: true,
  },

  // ---------- REVELATION ----------
  {
    id: 'letters-to-seven-churches',
    title: "The Church That Was Neither Hot nor Cold",
    era: '~95 AD',
    category: 'biblical',
    themes: ['surrender', 'identity', 'transformation', 'discipline'],
    oneLineSummary: "Jesus tells the Laodicean church: you think you're rich and need nothing, but you're actually wretched, pitiful, poor, blind, and naked — and I'm about to spit you out.",
    scriptureConnection: 'Revelation 3:14-22',
    source: 'biblical',
    spinnable: true,
  },

  // ---------- MORE OLD TESTAMENT HIDDEN GEMS ----------
  {
    id: 'jabez-prayer',
    title: "The Prayer of Jabez",
    era: 'Pre-Monarchy',
    category: 'biblical',
    themes: ['prayer', 'identity', 'hope', 'courage'],
    oneLineSummary: "A man whose name literally means 'pain' — named by his mother because of her painful labor — prays for blessing, and God grants it in two verses.",
    scriptureConnection: '1 Chronicles 4:9-10',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'uzzah-touches-the-ark',
    title: "Uzzah Steadies the Ark and Dies",
    era: 'United Monarchy (~1000 BC)',
    category: 'biblical',
    themes: ['obedience', 'fear', 'trust', 'humility'],
    oneLineSummary: "When the ark nearly tips off an oxcart, a man reaches out to steady it — a seemingly good reflex — and God strikes him dead on the spot.",
    scriptureConnection: '2 Samuel 6:1-11',
    source: 'biblical',
    spinnable: false,
  },
  {
    id: 'naaman-dips-seven-times',
    title: "The General Too Proud to Bathe",
    era: 'Divided Kingdom (~850 BC)',
    category: 'biblical',
    themes: ['pride', 'humility', 'obedience', 'transformation'],
    oneLineSummary: "A powerful military commander with leprosy almost misses his healing because washing in a muddy river felt beneath him.",
    scriptureConnection: '2 Kings 5:1-14',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'elisha-bears-and-boys',
    title: "The Bears and the Mocking Boys",
    era: 'Divided Kingdom (~850 BC)',
    category: 'biblical',
    themes: ['justice', 'fear'],
    oneLineSummary: "Young men mock the prophet Elisha — 'Go on up, baldy!' — and two bears come out of the woods and maul 42 of them.",
    scriptureConnection: '2 Kings 2:23-25',
    source: 'biblical',
    spinnable: false,
  },
  {
    id: 'huldah-authenticates-scripture',
    title: "Huldah: The Woman Who Authenticated the Bible",
    era: 'Late Monarchy (~622 BC)',
    category: 'biblical',
    themes: ['calling', 'wisdom', 'courage', 'identity'],
    oneLineSummary: "When the lost Book of the Law is found, the king bypasses Jeremiah and every male prophet and sends it to a woman named Huldah to verify if it's really God's word.",
    scriptureConnection: '2 Kings 22:14-20',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'gehazi-greed-leprosy',
    title: "Gehazi's Secret Greed",
    era: 'Divided Kingdom (~850 BC)',
    category: 'biblical',
    themes: ['integrity', 'greed', 'justice'],
    oneLineSummary: "After Elisha refuses payment for healing Naaman, his servant Gehazi secretly chases down the general and takes the money — and inherits Naaman's leprosy.",
    scriptureConnection: '2 Kings 5:19-27',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'the-shunammite-woman',
    title: "The Shunammite Who Held Her Son",
    era: 'Divided Kingdom (~850 BC)',
    category: 'biblical',
    themes: ['faith-in-doubt', 'grief', 'perseverance', 'hope'],
    oneLineSummary: "A wealthy woman builds a room for the prophet, receives a promised son, and when the boy dies in her lap, she tells everyone 'It is well' while riding urgently to find Elisha.",
    scriptureConnection: '2 Kings 4:8-37',
    source: 'biblical',
    spinnable: true,
  },
];

// ==========================================
// CATEGORY 2: CHURCH HISTORY (2,000 YEARS)
// 100 documented stories spanning every era
// ==========================================

export const CHURCH_HISTORY_STORIES: Story[] = [
  // ---------- EARLY CHURCH (30-300 AD) ----------
  {
    id: 'perpetua-and-felicity',
    title: "Perpetua and Felicity in the Arena",
    era: '203 AD, Carthage',
    category: 'church-history',
    themes: ['courage', 'sacrifice', 'friendship', 'hope'],
    oneLineSummary: "A young noblewoman and her pregnant slave refuse to recant, Felicity gives birth in prison so she won't miss their martyrdom, and they walk into the arena holding hands.",
    scriptureConnection: 'Philippians 1:21',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'polycarp-86-years',
    title: "Polycarp: 86 Years of Service",
    era: '155 AD, Smyrna',
    category: 'church-history',
    themes: ['perseverance', 'courage', 'faithfulness', 'surrender'],
    oneLineSummary: "When told to curse Christ to save his life, the 86-year-old bishop replied: 'Eighty-six years I have served him, and he has done me no wrong — how can I blaspheme my King?'",
    scriptureConnection: 'Revelation 2:10',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'anthony-of-egypt-desert',
    title: "Anthony Goes to the Desert",
    era: '270 AD, Egypt',
    category: 'church-history',
    themes: ['surrender', 'discipline', 'calling', 'solitude'],
    oneLineSummary: "A wealthy young man hears 'sell everything you have' read aloud in church, does exactly that, and walks into the Egyptian desert for 20 years of solitude.",
    scriptureConnection: 'Matthew 19:21',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'moses-the-black',
    title: "Moses the Black: From Bandit to Saint",
    era: '330-405 AD, Egypt',
    category: 'church-history',
    themes: ['transformation', 'forgiveness', 'humility', 'patience'],
    oneLineSummary: "A violent gang leader and murderer flees to a monastery to hide from the law, encounters Christ there, and becomes one of the most beloved Desert Fathers.",
    scriptureConnection: '1 Timothy 1:15-16',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'syncletica-desert-mother',
    title: "Amma Syncletica's Teaching on Suffering",
    era: '~350 AD, Egypt',
    category: 'church-history',
    themes: ['suffering', 'wisdom', 'discipline', 'surrender'],
    oneLineSummary: "A wealthy woman gave away everything and lived in a tomb, teaching others: 'In the beginning there is struggle and a lot of work, but then there is indescribable joy.'",
    scriptureConnection: 'James 1:2-4',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'origen-mother-hides-clothes',
    title: "Origen's Mother Hides His Clothes",
    era: '~202 AD, Alexandria',
    category: 'church-history',
    themes: ['courage', 'calling', 'sacrifice'],
    oneLineSummary: "When teenage Origen tried to join his father in martyrdom, his mother hid all his clothes — he couldn't go outside naked, so he wrote his father a letter instead: 'Don't change your mind on our account.'",
    scriptureConnection: 'Matthew 10:37',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'valentine-secret-marriages',
    title: "Valentine Performs Marriages in Secret",
    era: '~269 AD, Rome',
    category: 'church-history',
    themes: ['courage', 'love', 'sacrifice', 'justice'],
    oneLineSummary: "When Emperor Claudius bans marriages to keep men available for war, a priest named Valentine secretly marries couples anyway — and is executed for it.",
    scriptureConnection: 'Genesis 2:18',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'augustine-take-up-and-read',
    title: "Augustine Hears 'Take Up and Read'",
    era: '386 AD, Milan',
    category: 'church-history',
    themes: ['transformation', 'surrender', 'calling', 'hope'],
    oneLineSummary: "A brilliant philosopher weeping in a garden hears a child singing 'take up and read' — he opens to Romans 13:13, and the man who couldn't control his desires becomes the church's greatest theologian.",
    scriptureConnection: 'Romans 13:13-14',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'blandina-slave-girl-martyr',
    title: "Blandina: The Slave Who Outlasted Them All",
    era: '177 AD, Lyon',
    category: 'church-history',
    themes: ['perseverance', 'courage', 'hope', 'identity'],
    oneLineSummary: "A frail slave girl endured more torture than any other Christian in the arena — her tormentors exhausted themselves while she kept repeating: 'I am a Christian, and nothing wicked happens among us.'",
    scriptureConnection: '2 Corinthians 12:9',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'justin-martyr-dialogue',
    title: "Justin Martyr's Open Letter",
    era: '~155 AD, Rome',
    category: 'church-history',
    themes: ['courage', 'wisdom', 'integrity', 'calling'],
    oneLineSummary: "A pagan philosopher converts after meeting an old man by the sea, then writes an open letter to the Roman Emperor defending Christians — knowing it could cost his life.",
    scriptureConnection: '1 Peter 3:15',
    source: 'historical',
    spinnable: true,
  },

  // ---------- MEDIEVAL (300-1500) ----------
  {
    id: 'patrick-returns-to-captors',
    title: "Patrick Returns to the Land of His Slavery",
    era: '~432 AD, Ireland',
    category: 'church-history',
    themes: ['forgiveness', 'courage', 'calling', 'obedience'],
    oneLineSummary: "Kidnapped at 16 and enslaved for six years in Ireland, Patrick escapes — then God tells him to go back to the people who enslaved him, and he evangelizes the entire island.",
    scriptureConnection: 'Romans 8:28',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'columba-exiled-to-iona',
    title: "Columba's Exile of Penance",
    era: '563 AD, Iona',
    category: 'church-history',
    themes: ['grief', 'transformation', 'calling', 'humility'],
    oneLineSummary: "An Irish prince's pride causes a battle that kills 3,000 men — he exiles himself vowing to save as many souls as lives he cost, and builds the monastery that Christianizes Scotland.",
    scriptureConnection: 'Psalm 51:10-12',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'aidan-gives-away-kings-horse',
    title: "Aidan Gives Away the King's Horse",
    era: '~640 AD, Lindisfarne',
    category: 'church-history',
    themes: ['humility', 'generosity', 'integrity'],
    oneLineSummary: "The king gives Bishop Aidan a fine horse to make travel easier — Aidan gives it to the first beggar he meets, because he'd rather walk with the poor than ride past them.",
    scriptureConnection: 'Matthew 25:40',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'brigid-of-kildare',
    title: "Brigid Gives Away Her Father's Sword",
    era: '~480 AD, Ireland',
    category: 'church-history',
    themes: ['generosity', 'courage', 'calling', 'justice'],
    oneLineSummary: "When her father tries to sell her into marriage, Brigid gives his jeweled sword to a leper — her father is so stunned by her fearlessness he sets her free.",
    scriptureConnection: 'Matthew 6:19-21',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'francis-kisses-the-leper',
    title: "Francis Kisses the Leper",
    era: '~1206, Assisi',
    category: 'church-history',
    themes: ['transformation', 'surrender', 'humility', 'love'],
    oneLineSummary: "A wealthy playboy who was terrified of lepers meets one on the road, dismounts, and kisses his hand — and later says that moment turned his bitterness into sweetness.",
    scriptureConnection: 'Matthew 25:35-40',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'clare-of-assisi-runs-away',
    title: "Clare Runs Away on Palm Sunday Night",
    era: '1212, Assisi',
    category: 'church-history',
    themes: ['courage', 'surrender', 'calling', 'sacrifice'],
    oneLineSummary: "An 18-year-old noblewoman sneaks out of her family's palace on Palm Sunday night, has Francis cut off her hair, and founds an order of radical poverty — her family sends armed men to bring her back.",
    scriptureConnection: 'Luke 14:33',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'julian-of-norwich-all-shall-be-well',
    title: "Julian of Norwich: 'All Shall Be Well'",
    era: '1373, Norwich',
    category: 'church-history',
    themes: ['hope', 'suffering', 'trust', 'presence'],
    oneLineSummary: "A woman on her deathbed receives 16 visions of Christ's love, recovers, and spends the next 20 years in a cell writing: 'All shall be well, and all shall be well, and all manner of thing shall be well.'",
    scriptureConnection: 'Romans 8:28',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'abba-moses-go-sit-in-cell',
    title: "Abba Moses: 'Go Sit in Your Cell'",
    era: '~380 AD, Egypt',
    category: 'church-history',
    themes: ['patience', 'discipline', 'solitude', 'wisdom'],
    oneLineSummary: "When a young monk asks Abba Moses for advice, the old Desert Father says: 'Go, sit in your cell, and your cell will teach you everything.'",
    scriptureConnection: 'Psalm 46:10',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'benedict-poisoned-cup',
    title: "Benedict and the Poisoned Cup",
    era: '~530 AD, Subiaco',
    category: 'church-history',
    themes: ['integrity', 'perseverance', 'trust'],
    oneLineSummary: "Monks who resented Benedict's strict rule tried to poison his wine — when he blessed the cup, the glass shattered, and he calmly said: 'May God forgive you, brothers.'",
    scriptureConnection: 'Mark 16:18',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'john-chrysostom-exiled',
    title: "Chrysostom Exiled for Preaching Too Well",
    era: '404 AD, Constantinople',
    category: 'church-history',
    themes: ['courage', 'justice', 'integrity', 'perseverance'],
    oneLineSummary: "The greatest preacher of the early church was exiled twice by the empress for sermons against luxury and greed — he died on a forced march, his last words: 'Glory be to God for all things.'",
    scriptureConnection: 'Amos 5:21-24',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'hildegard-of-bingen',
    title: "Hildegard: The Medieval Polymath",
    era: '1098-1179, Germany',
    category: 'church-history',
    themes: ['calling', 'courage', 'wisdom', 'creativity'],
    oneLineSummary: "A cloistered nun who had visions since age three became a composer, theologian, herbalist, and scientist — and at age 60 went on preaching tours when women weren't allowed to preach.",
    scriptureConnection: 'Joel 2:28',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'waldensians-memorize-gospels',
    title: "The Waldensians Memorize Entire Gospels",
    era: '1170s, Lyon/Alps',
    category: 'church-history',
    themes: ['perseverance', 'courage', 'discipline', 'community'],
    oneLineSummary: "When the church banned them from reading Scripture in their own language, the Waldensian 'Poor Men' memorized entire books of the Bible and recited them in marketplaces disguised as merchants.",
    scriptureConnection: 'Psalm 119:11',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'john-of-the-cross-dark-night',
    title: "John of the Cross Writes in Prison",
    era: '1577, Toledo',
    category: 'church-history',
    themes: ['suffering', 'hope', 'faith-in-doubt', 'surrender'],
    oneLineSummary: "Imprisoned by his own religious order in a closet-sized cell, beaten weekly, John of the Cross composes 'Dark Night of the Soul' — one of history's greatest poems about God's hidden love.",
    scriptureConnection: 'Psalm 88:1',
    source: 'historical',
    spinnable: true,
  },

  // ---------- REFORMATION (1500-1700) ----------
  {
    id: 'tyndale-last-words',
    title: "Tyndale's Last Words: 'Open the King's Eyes'",
    era: '1536, Belgium',
    category: 'church-history',
    themes: ['sacrifice', 'perseverance', 'calling', 'hope'],
    oneLineSummary: "Strangled and burned for translating the Bible into English, Tyndale's dying prayer — 'Lord, open the King of England's eyes' — was answered within a year when Henry VIII authorized an English Bible.",
    scriptureConnection: '2 Timothy 4:6-8',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'luther-here-i-stand',
    title: "Luther: 'Here I Stand'",
    era: '1521, Worms',
    category: 'church-history',
    themes: ['courage', 'integrity', 'calling', 'faith-in-doubt'],
    oneLineSummary: "A monk stands before the most powerful rulers in Europe, is told to recant or die, and says: 'My conscience is captive to the Word of God — I cannot and will not recant. Here I stand.'",
    scriptureConnection: 'Acts 5:29',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'dirk-willems-turns-back',
    title: "Dirk Willems Turns Back for His Pursuer",
    era: '1569, Netherlands',
    category: 'church-history',
    themes: ['mercy', 'sacrifice', 'love', 'forgiveness'],
    oneLineSummary: "An Anabaptist escapee crosses a frozen lake, hears his pursuer fall through the ice, turns back to save the man's life — and is recaptured and burned at the stake.",
    scriptureConnection: 'Matthew 5:44',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'cranmer-burns-his-hand',
    title: "Cranmer Burns His Hand First",
    era: '1556, Oxford',
    category: 'church-history',
    themes: ['courage', 'transformation', 'integrity', 'hope'],
    oneLineSummary: "Archbishop Cranmer had signed a recantation under torture — at his burning, he thrust the hand that signed it into the flames first, crying: 'This hand hath offended.'",
    scriptureConnection: 'Matthew 5:30',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'bunyan-writes-in-prison',
    title: "Bunyan Writes a Masterpiece in Prison",
    era: '1660-1672, Bedford',
    category: 'church-history',
    themes: ['perseverance', 'creativity', 'calling', 'hope'],
    oneLineSummary: "A tinker jailed 12 years for preaching without a license could have walked free any day by agreeing to stop — instead he stayed and wrote Pilgrim's Progress, the most-read book after the Bible.",
    scriptureConnection: 'Philippians 1:12-14',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'lady-jane-grey-scaffold',
    title: "Lady Jane Grey's Final Prayer",
    era: '1554, London',
    category: 'church-history',
    themes: ['courage', 'trust', 'surrender', 'faith-in-doubt'],
    oneLineSummary: "The 16-year-old Protestant queen, deposed after nine days, was offered her life if she converted — she refused and went to the scaffold quoting Psalm 51.",
    scriptureConnection: 'Psalm 51:1-2',
    source: 'historical',
    spinnable: false,
  },
  {
    id: 'menno-simons-underground',
    title: "Menno Simons: The Priest Who Went Underground",
    era: '1536-1561, Netherlands',
    category: 'church-history',
    themes: ['courage', 'calling', 'sacrifice', 'community'],
    oneLineSummary: "A Catholic priest with a bounty on his head spent 25 years moving from house to house, never sleeping in the same place twice, rebuilding the peaceful Anabaptist movement after its radical wing destroyed it.",
    scriptureConnection: 'Matthew 10:23',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'huguenot-galley-slaves-sing',
    title: "The Huguenot Galley Slaves Who Sang Psalms",
    era: '1685-1715, France',
    category: 'church-history',
    themes: ['perseverance', 'joy-in-pain', 'community', 'hope'],
    oneLineSummary: "After Louis XIV revoked their rights, thousands of French Protestants were chained to galley oars — and they sang psalms so loudly it unnerved their captors.",
    scriptureConnection: 'Acts 16:25',
    source: 'historical',
    spinnable: true,
  },

  // ---------- GREAT AWAKENING / MODERN MISSIONS (1700-1900) ----------
  {
    id: 'wesley-heart-strangely-warmed',
    title: "Wesley's Heart 'Strangely Warmed'",
    era: '1738, London',
    category: 'church-history',
    themes: ['transformation', 'faith-in-doubt', 'hope', 'surrender'],
    oneLineSummary: "A depressed Anglican priest who felt like a failure attends a Moravian meeting and writes in his journal: 'I felt my heart strangely warmed' — then launches the Methodist movement.",
    scriptureConnection: 'Luke 24:32',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'william-carey-cobbler',
    title: "The Cobbler Who Wouldn't Sit Down",
    era: '1792, England/India',
    category: 'church-history',
    themes: ['perseverance', 'calling', 'courage', 'hope'],
    oneLineSummary: "When William Carey said God was calling him to India, an older pastor snapped: 'Sit down, young man — when God wants to convert the heathen, he'll do it without your help.'",
    scriptureConnection: 'Isaiah 54:2-3',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'hudson-taylor-chinese-dress',
    title: "Hudson Taylor Dresses Chinese",
    era: '1855, China',
    category: 'church-history',
    themes: ['humility', 'calling', 'identity', 'courage'],
    oneLineSummary: "Other missionaries lived in coastal compounds; Hudson Taylor shaved his head, grew a pigtail, wore Chinese clothes, and was ridiculed by Western missionaries — but reached interior China.",
    scriptureConnection: '1 Corinthians 9:22',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'sojourner-truth-speech',
    title: "Sojourner Truth: 'Ain't I a Woman?'",
    era: '1851, Ohio',
    category: 'church-history',
    themes: ['justice', 'courage', 'identity', 'hope'],
    oneLineSummary: "A formerly enslaved woman silences a room of skeptics with a speech grounded in Scripture: 'Where did your Christ come from? From God and a woman. Man had nothing to do with it.'",
    scriptureConnection: 'Galatians 3:28',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'harriet-tubman-moses',
    title: "Harriet Tubman: The Moses Who Prayed Aloud",
    era: '1849-1860, American South',
    category: 'church-history',
    themes: ['courage', 'calling', 'trust', 'justice'],
    oneLineSummary: "Tubman prayed out loud on every rescue mission, trusting God for specific guidance — she made 13 trips and never lost a single passenger on the Underground Railroad.",
    scriptureConnection: 'Exodus 3:7-10',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'george-muller-orphanages',
    title: "George Muller Never Asked for Money",
    era: '1836-1898, Bristol',
    category: 'church-history',
    themes: ['trust', 'prayer', 'provision', 'generosity'],
    oneLineSummary: "Muller housed 10,000 orphans over 60 years and never once asked anyone for money — once, with no food for breakfast, he sat the children down, said grace, and a baker knocked on the door.",
    scriptureConnection: 'Matthew 6:31-33',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'adoniram-judson-burma',
    title: "Judson: Six Years Before One Convert",
    era: '1813-1850, Burma',
    category: 'church-history',
    themes: ['perseverance', 'patience', 'grief', 'hope'],
    oneLineSummary: "Adoniram Judson buried two wives and seven children in Burma, spent 17 months in a death prison, and waited six years for his first convert — today there are 3.7 million Christians in Myanmar.",
    scriptureConnection: 'Galatians 6:9',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'lottie-moon-starvation',
    title: "Lottie Moon Starves Giving Her Food Away",
    era: '1912, China',
    category: 'church-history',
    themes: ['sacrifice', 'generosity', 'love', 'calling'],
    oneLineSummary: "During a famine in China, missionary Lottie Moon gave away all her food and money to starving Chinese neighbors until she herself died of starvation at 72 pounds.",
    scriptureConnection: 'John 15:13',
    source: 'historical',
    spinnable: false,
  },
  {
    id: 'pandita-ramabai-rescues-widows',
    title: "Pandita Ramabai: Scholar Who Saved Thousands",
    era: '1889-1922, India',
    category: 'church-history',
    themes: ['justice', 'courage', 'calling', 'transformation'],
    oneLineSummary: "India's first female Sanskrit scholar converted to Christianity, toured famine villages with ox carts, and rescued thousands of child widows and orphans — translating the Bible into Marathi from the original Hebrew and Greek.",
    scriptureConnection: 'James 1:27',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'mary-slessor-calabar',
    title: "Mary Slessor Stops the Twin Killings",
    era: '1876-1915, Nigeria',
    category: 'church-history',
    themes: ['courage', 'justice', 'love', 'perseverance'],
    oneLineSummary: "A Scottish mill worker moved to Calabar where twin babies were killed as cursed — she personally adopted every set of twins she could find and changed the cultural practice.",
    scriptureConnection: 'Psalm 82:3-4',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'david-livingstone-heart-in-africa',
    title: "Livingstone: 'I Am Prepared to Go Anywhere'",
    era: '1841-1873, Africa',
    category: 'church-history',
    themes: ['calling', 'perseverance', 'sacrifice', 'courage'],
    oneLineSummary: "Lost in Africa for years, found by Stanley who said 'Dr. Livingstone, I presume?' — when his body was shipped home, they found his heart had been buried under a tree in Africa by the people who loved him.",
    scriptureConnection: 'Matthew 28:19-20',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'moravian-100-year-prayer',
    title: "The 100-Year Prayer Meeting",
    era: '1727-1827, Herrnhut',
    category: 'church-history',
    themes: ['prayer', 'community', 'perseverance', 'calling'],
    oneLineSummary: "A small community of Moravian refugees began a 24/7 prayer watch that continued unbroken for 100 years — and sent out more missionaries in 20 years than all Protestants had in 200.",
    scriptureConnection: '1 Thessalonians 5:17',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'whitefield-preaches-outdoors',
    title: "Whitefield Preaches to 30,000 Without a Microphone",
    era: '1739, London/Philadelphia',
    category: 'church-history',
    themes: ['calling', 'courage', 'transformation'],
    oneLineSummary: "Banned from every church in England, George Whitefield started preaching in open fields — Benjamin Franklin calculated his unamplified voice could reach 30,000 people simultaneously.",
    scriptureConnection: 'Romans 1:16',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'charles-simeon-54-years',
    title: "Simeon's 54 Years of Rejection",
    era: '1782-1836, Cambridge',
    category: 'church-history',
    themes: ['perseverance', 'humility', 'patience', 'faithfulness'],
    oneLineSummary: "Charles Simeon's own congregation locked pew doors so visitors couldn't sit, threw things at him, and spread rumors — he stayed 54 years and quietly transformed Anglican evangelicalism.",
    scriptureConnection: 'Hebrews 12:1-2',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'wilberforce-abolition',
    title: "Wilberforce: 46 Years to End the Slave Trade",
    era: '1787-1833, England',
    category: 'church-history',
    themes: ['justice', 'perseverance', 'calling', 'patience'],
    oneLineSummary: "Wilberforce introduced an abolition bill to Parliament every single year for 18 years before it passed — and spent another 28 fighting until slavery itself was abolished three days before he died.",
    scriptureConnection: 'Micah 6:8',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'george-liele-first-missionary',
    title: "George Liele: America's First Foreign Missionary",
    era: '1783, Jamaica',
    category: 'church-history',
    themes: ['courage', 'calling', 'perseverance', 'identity'],
    oneLineSummary: "A formerly enslaved man from Virginia became America's first foreign missionary — years before William Carey — sailing to Jamaica in 1783 to plant churches.",
    scriptureConnection: 'Acts 1:8',
    source: 'historical',
    spinnable: true,
  },

  // ---------- 20TH CENTURY ----------
  {
    id: 'bonhoeffer-returns-to-germany',
    title: "Bonhoeffer Returns to Germany to Die",
    era: '1939-1945, Germany',
    category: 'church-history',
    themes: ['courage', 'sacrifice', 'integrity', 'calling'],
    oneLineSummary: "Safe in New York, Dietrich Bonhoeffer boards a ship back to Nazi Germany saying: 'I will have no right to participate in the reconstruction of Germany after the war if I do not share the trials of this time.'",
    scriptureConnection: 'John 10:11',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'corrie-ten-boom-fleas',
    title: "Corrie ten Boom Thanks God for Fleas",
    era: '1944, Ravensbruck',
    category: 'church-history',
    themes: ['gratitude', 'hope', 'joy-in-pain', 'trust'],
    oneLineSummary: "In a concentration camp infested with fleas, Corrie's sister Betsie insists they thank God for the fleas — they later discover the guards avoided their barracks because of the fleas, letting them hold Bible studies.",
    scriptureConnection: '1 Thessalonians 5:18',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'mlk-letter-birmingham-jail',
    title: "MLK's Letter from Birmingham Jail",
    era: '1963, Birmingham',
    category: 'church-history',
    themes: ['justice', 'courage', 'patience', 'calling'],
    oneLineSummary: "Jailed for marching, King writes in the margins of a newspaper to white pastors who called him an 'outside agitator': 'Injustice anywhere is a threat to justice everywhere.'",
    scriptureConnection: 'Amos 5:24',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'mother-teresa-50-year-darkness',
    title: "Mother Teresa's 50 Years of Spiritual Darkness",
    era: '1948-1997, Calcutta',
    category: 'church-history',
    themes: ['faith-in-doubt', 'perseverance', 'suffering', 'faithfulness'],
    oneLineSummary: "After her death, letters revealed Mother Teresa felt no presence of God for nearly 50 years — she served the poorest of the poor in complete spiritual darkness, calling it 'my secret.'",
    scriptureConnection: 'Psalm 22:1-2',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'richard-wurmbrand-14-years',
    title: "Wurmbrand: 14 Years in a Communist Prison",
    era: '1948-1964, Romania',
    category: 'church-history',
    themes: ['perseverance', 'forgiveness', 'joy-in-pain', 'hope'],
    oneLineSummary: "A Romanian pastor spent 14 years in communist prisons including 3 years in solitary — he composed sermons by tapping on walls in Morse code to prisoners in neighboring cells.",
    scriptureConnection: '2 Corinthians 4:8-9',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'wang-mingdao-refuses',
    title: "Wang Mingdao: The Man Who Would Not Yield",
    era: '1955-1980, China',
    category: 'church-history',
    themes: ['courage', 'integrity', 'perseverance', 'surrender'],
    oneLineSummary: "China's most influential house church pastor spent 23 years in prison rather than join the government-controlled church — he signed a confession once, then retracted it, saying: 'I am Peter, I have denied my Lord.'",
    scriptureConnection: 'Matthew 16:25',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'watchman-nee-last-note',
    title: "Watchman Nee's Last Note",
    era: '1952-1972, China',
    category: 'church-history',
    themes: ['perseverance', 'hope', 'faithfulness', 'joy-in-pain'],
    oneLineSummary: "After 20 years in a Chinese labor camp, Watchman Nee died. Under his pillow they found a note: 'Christ is the Son of God who died for the redemption of sinners and rose after three days. This is the greatest truth in the universe. I die because of my belief in Christ.'",
    scriptureConnection: 'Revelation 2:10',
    source: 'historical',
    spinnable: false,
  },
  {
    id: 'janani-luwum-confronts-amin',
    title: "Archbishop Luwum Confronts Idi Amin",
    era: '1977, Uganda',
    category: 'church-history',
    themes: ['courage', 'justice', 'sacrifice', 'integrity'],
    oneLineSummary: "The Archbishop of Uganda publicly confronted dictator Idi Amin about the murder of Christians — he was found dead the next day, but his courage sparked a movement that outlasted the regime.",
    scriptureConnection: 'Esther 4:14',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'oscar-romero-shot-at-altar',
    title: "Romero Shot While Lifting the Chalice",
    era: '1980, El Salvador',
    category: 'church-history',
    themes: ['justice', 'sacrifice', 'courage', 'calling'],
    oneLineSummary: "Archbishop Romero pleaded on radio for soldiers to stop killing — 'I beg you, I implore you, I order you: stop the repression' — the next day he was assassinated while celebrating Mass.",
    scriptureConnection: 'John 12:24',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'bonhoeffer-last-morning',
    title: "Bonhoeffer's Last Morning",
    era: '1945, Flossenburg',
    category: 'church-history',
    themes: ['courage', 'hope', 'surrender', 'trust'],
    oneLineSummary: "The camp doctor wrote: 'I saw Pastor Bonhoeffer kneeling on the floor praying fervently to God. At the place of execution, he again said a short prayer and then climbed the steps to the gallows, brave and composed.'",
    scriptureConnection: 'Philippians 1:21',
    source: 'historical',
    spinnable: false,
  },
  {
    id: 'desmond-tutu-stares-down-police',
    title: "Tutu Stares Down Armed Police",
    era: '1985, South Africa',
    category: 'church-history',
    themes: ['courage', 'justice', 'hope', 'mercy'],
    oneLineSummary: "During apartheid, Bishop Tutu walked between armed police and protesters, telling the government: 'You have already lost. Come and join the winning side.'",
    scriptureConnection: 'Romans 12:21',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'brother-andrew-smuggles-bibles',
    title: "Brother Andrew: God's Smuggler",
    era: '1955-2022, Netherlands/Eastern Europe',
    category: 'church-history',
    themes: ['courage', 'trust', 'calling', 'provision'],
    oneLineSummary: "A Dutch missionary smuggled Bibles behind the Iron Curtain for decades, praying at each border: 'Lord, when you were on earth, you made blind eyes see — now make seeing eyes blind.'",
    scriptureConnection: '2 Kings 6:17-18',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'back-to-jerusalem-movement',
    title: "The Back to Jerusalem Movement",
    era: '1940s-present, China',
    category: 'church-history',
    themes: ['calling', 'perseverance', 'courage', 'hope'],
    oneLineSummary: "Chinese house church leaders envision sending 100,000 missionaries westward along the Silk Road — back through the Muslim, Buddhist, and Hindu worlds — to complete the gospel's journey around the world back to Jerusalem.",
    scriptureConnection: 'Matthew 24:14',
    source: 'historical',
    spinnable: true,
  },

  // ---------- GLOBAL & CONTEMPORARY ----------
  {
    id: 'korean-prayer-mountains',
    title: "The Korean Prayer Mountains",
    era: '1950s-present, South Korea',
    category: 'church-history',
    themes: ['prayer', 'perseverance', 'community', 'discipline'],
    oneLineSummary: "After the Korean War devastated the nation, Christians built prayer mountains where believers still climb before dawn to pray — South Korea now sends more missionaries per capita than any country on earth.",
    scriptureConnection: 'Luke 6:12',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'ethiopian-church-1700-years',
    title: "The Ethiopian Eunuch's Legacy: 1,700 Years",
    era: '4th century-present, Ethiopia',
    category: 'church-history',
    themes: ['perseverance', 'identity', 'community', 'faithfulness'],
    oneLineSummary: "Ethiopia has maintained an unbroken Christian tradition since the 4th century — they were Christian before most of Europe, and kept their faith through invasions, communism, and famine.",
    scriptureConnection: 'Acts 8:39',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'underground-church-iran',
    title: "The Fastest-Growing Church in the World",
    era: '1979-present, Iran',
    category: 'church-history',
    themes: ['courage', 'transformation', 'hope', 'perseverance'],
    oneLineSummary: "After the Islamic Revolution, Christianity in Iran was nearly extinguished — now it's the fastest-growing church in the world, with an estimated 1 million believers meeting in secret house churches.",
    scriptureConnection: 'Matthew 16:18',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'samuel-ajayi-crowther',
    title: "Crowther: From Slave Ship to Bishop",
    era: '1843-1891, Nigeria/England',
    category: 'church-history',
    themes: ['transformation', 'forgiveness', 'calling', 'hope'],
    oneLineSummary: "Captured as a boy by slave traders, rescued by the British Navy, Samuel Ajayi Crowther became the first African Anglican bishop — and returned to the very region where he'd been enslaved to plant churches.",
    scriptureConnection: 'Genesis 50:20',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'gladys-aylward-small-woman',
    title: "Gladys Aylward: The Small Woman",
    era: '1930-1970, China',
    category: 'church-history',
    themes: ['courage', 'calling', 'perseverance', 'love'],
    oneLineSummary: "Rejected by every mission agency as 'too uneducated,' a British parlor maid traveled to China alone, became a Chinese citizen, and led 100 orphans on a 12-day mountain trek to escape the Japanese invasion.",
    scriptureConnection: '1 Corinthians 1:27',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'five-missionaries-waodani',
    title: "The Five Missionaries and the Waodani",
    era: '1956, Ecuador',
    category: 'church-history',
    themes: ['sacrifice', 'forgiveness', 'love', 'hope'],
    oneLineSummary: "Five missionaries were killed by the Waodani people — then the wife and sister of two of the slain men moved into the tribe, and the man who threw the first spear later baptized the martyrs' children.",
    scriptureConnection: 'John 12:24',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'helen-roseveare-congo',
    title: "Helen Roseveare: The Doctor Who Stayed",
    era: '1953-1973, Congo',
    category: 'church-history',
    themes: ['perseverance', 'suffering', 'trust', 'calling'],
    oneLineSummary: "A British doctor survived a brutal attack during the Congo's Simba Rebellion and was asked: 'Can you thank me for trusting you with this experience?' — she stayed and served for another decade.",
    scriptureConnection: '2 Corinthians 1:3-5',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'grandmother-li-living-bible',
    title: "Grandmother Li and the House Churches",
    era: '1950s-1990s, China',
    category: 'church-history',
    themes: ['perseverance', 'courage', 'community', 'faithfulness'],
    oneLineSummary: "During the Cultural Revolution, when every Bible was burned, an elderly Chinese grandmother who had memorized large portions of Scripture became a living Bible — entire house church networks grew from her memory.",
    scriptureConnection: 'Psalm 119:11',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'alexander-men-murdered',
    title: "Father Alexander Men: Murdered for Preaching",
    era: '1990, Russia',
    category: 'church-history',
    themes: ['courage', 'calling', 'sacrifice', 'hope'],
    oneLineSummary: "The most popular Christian preacher in post-Soviet Russia was axed to death on his way to church on a Sunday morning — his final sermon the day before was titled 'Christianity Is Just Beginning.'",
    scriptureConnection: 'John 16:33',
    source: 'historical',
    spinnable: false,
  },
  {
    id: 'sabina-wurmbrand-forgives',
    title: "Sabina Wurmbrand Forgives Her Family's Killer",
    era: '1945, Romania',
    category: 'church-history',
    themes: ['forgiveness', 'courage', 'mercy', 'transformation'],
    oneLineSummary: "At a congress of former political prisoners, Sabina Wurmbrand publicly embraced a man who had been responsible for the deaths of her family members — saying only: 'I forgive you with all my heart.'",
    scriptureConnection: 'Matthew 18:21-22',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'john-perkins-returns',
    title: "John Perkins Beaten, Then Returns",
    era: '1970, Mississippi',
    category: 'church-history',
    themes: ['forgiveness', 'justice', 'courage', 'transformation'],
    oneLineSummary: "Civil rights leader John Perkins was nearly beaten to death by Mississippi police — then returned to the same town to build a ministry of racial reconciliation.",
    scriptureConnection: 'Luke 23:34',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'kim-phuc-napalm-girl',
    title: "Kim Phuc: The Girl in the Photo",
    era: '1972-present, Vietnam/Canada',
    category: 'church-history',
    themes: ['forgiveness', 'transformation', 'hope', 'suffering'],
    oneLineSummary: "The girl from the iconic napalm photo became a Christian, publicly forgave the man who ordered the strike, and said: 'Napalm is very powerful, but faith, forgiveness, and love are much more powerful.'",
    scriptureConnection: 'Romans 12:17-21',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'african-church-explosion',
    title: "Africa: 10 Million to 685 Million in a Century",
    era: '1900-2025, Africa',
    category: 'church-history',
    themes: ['hope', 'transformation', 'community', 'calling'],
    oneLineSummary: "In 1900, there were roughly 10 million Christians in Africa — today there are over 685 million, making Africa the new center of global Christianity.",
    scriptureConnection: 'Isaiah 43:19',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'north-korea-underground',
    title: "North Korea: The Most Dangerous Place to Believe",
    era: '1950s-present, North Korea',
    category: 'church-history',
    themes: ['courage', 'perseverance', 'suffering', 'hope'],
    oneLineSummary: "Before 1945, Pyongyang was called 'the Jerusalem of the East' with more churches than any Asian city — today an estimated 50,000-70,000 Christians worship in absolute secrecy, where discovery means a labor camp.",
    scriptureConnection: 'Hebrews 11:36-38',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'chinese-baptism-frozen-lake',
    title: "Baptisms in Frozen Lakes at Midnight",
    era: '1960s-1980s, China',
    category: 'church-history',
    themes: ['courage', 'community', 'sacrifice', 'joy-in-pain'],
    oneLineSummary: "During the Cultural Revolution, Chinese believers held baptisms by breaking ice on frozen lakes in the middle of the night — the only way to perform the sacrament without being caught and imprisoned.",
    scriptureConnection: 'Romans 6:3-4',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'bonhoeffer-cheap-grace',
    title: "Bonhoeffer's 'Cheap Grace' Warning",
    era: '1937, Germany',
    category: 'church-history',
    themes: ['integrity', 'discipline', 'calling', 'transformation'],
    oneLineSummary: "As the German church caved to the Nazis, Bonhoeffer wrote: 'Cheap grace is the preaching of forgiveness without requiring repentance — it is grace without the cross.'",
    scriptureConnection: 'Luke 14:27-33',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'clarence-jordan-cotton-patch',
    title: "Jordan's Interracial Farm in 1940s Georgia",
    era: '1942, Georgia',
    category: 'church-history',
    themes: ['justice', 'courage', 'community', 'love'],
    oneLineSummary: "A Greek New Testament scholar started an interracial farming community in rural Georgia in 1942 — it was shot at, bombed, boycotted, and excommunicated by every church in the county.",
    scriptureConnection: 'Galatians 3:28',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'pacific-islander-missionaries',
    title: "The Pacific Islanders Who Evangelized Each Other",
    era: '1800s, Pacific Islands',
    category: 'church-history',
    themes: ['calling', 'courage', 'sacrifice', 'community'],
    oneLineSummary: "Pacific Islander converts became missionaries to neighboring islands — often landing on shores where the previous missionaries had been killed — with a mortality rate that dwarfed any Western mission agency.",
    scriptureConnection: 'Acts 20:24',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'emma-whittemore-doors-of-hope',
    title: "Emma Whittemore Opens 97 Doors of Hope",
    era: '1890-1931, New York',
    category: 'church-history',
    themes: ['mercy', 'calling', 'generosity', 'love'],
    oneLineSummary: "After burying her only child, a wealthy New York socialite began taking in prostitutes off the street — eventually opening 97 rescue homes across North America.",
    scriptureConnection: 'Isaiah 61:1-3',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'toyohiko-kagawa-slums',
    title: "Kagawa Moves into the Slums",
    era: '1909, Japan',
    category: 'church-history',
    themes: ['sacrifice', 'love', 'justice', 'humility'],
    oneLineSummary: "A Japanese seminary student moved into the worst slum in Kobe — a 6x6 room — and gave away everything he owned, including his shirt and his futon, becoming Japan's leading social reformer and a Nobel Peace Prize nominee.",
    scriptureConnection: 'Philippians 2:5-8',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'perpetua-prison-diary',
    title: "Perpetua's Prison Diary: The Oldest Female Writing",
    era: '203 AD, Carthage',
    category: 'church-history',
    themes: ['courage', 'identity', 'calling', 'sacrifice'],
    oneLineSummary: "Perpetua's prison diary is one of the oldest surviving texts written by a woman — she recorded visions, arguments with her father, and nursing her baby in a dungeon before walking into the arena.",
    scriptureConnection: '2 Timothy 1:7',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'romania-underground-seminary',
    title: "Romania's Underground Seminary",
    era: '1970s, Romania',
    category: 'church-history',
    themes: ['courage', 'community', 'discipline', 'perseverance'],
    oneLineSummary: "Romanian pastors ran an illegal seminary in basements — students memorized entire lectures because writing anything down could send everyone to prison.",
    scriptureConnection: '2 Timothy 2:2',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'festo-kivengere-loves-amin',
    title: "Kivengere: 'I Love Idi Amin'",
    era: '1977, Uganda',
    category: 'church-history',
    themes: ['forgiveness', 'courage', 'love', 'mercy'],
    oneLineSummary: "After fleeing Uganda when his archbishop was murdered by Idi Amin, Bishop Festo Kivengere wrote a book titled 'I Love Idi Amin' — arguing that forgiveness was the only path forward.",
    scriptureConnection: 'Matthew 5:44',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'lilias-trotter-art-sacrifice',
    title: "Lilias Trotter Chooses Algeria Over Art",
    era: '1888, Algeria',
    category: 'church-history',
    themes: ['surrender', 'calling', 'sacrifice', 'creativity'],
    oneLineSummary: "John Ruskin said she could be the greatest living painter — instead, Lilias Trotter moved alone to Algeria as a missionary and spent 38 years painting watercolors of the desert and sharing the gospel.",
    scriptureConnection: 'Mark 8:36',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'athanasius-contra-mundum',
    title: "Athanasius Against the World",
    era: '325-373 AD, Alexandria',
    category: 'church-history',
    themes: ['courage', 'integrity', 'perseverance', 'calling'],
    oneLineSummary: "When nearly every bishop in the empire accepted the Arian heresy that Jesus was not fully God, one man — exiled five times — stood alone until the truth prevailed, earning the title 'Athanasius contra mundum.'",
    scriptureConnection: 'Jude 1:3',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'amy-carmichael-india',
    title: "Amy Carmichael Rescues Temple Children",
    era: '1901-1951, India',
    category: 'church-history',
    themes: ['justice', 'sacrifice', 'love', 'perseverance'],
    oneLineSummary: "An Irish woman who never took a furlough in 55 years of missionary work in India rescued children from temple prostitution — sometimes dyeing her skin with coffee to go undercover in temple districts.",
    scriptureConnection: 'Isaiah 1:17',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'latin-american-base-communities',
    title: "The Base Communities of Latin America",
    era: '1960s-present, Brazil/Latin America',
    category: 'church-history',
    themes: ['community', 'justice', 'hope', 'calling'],
    oneLineSummary: "When there weren't enough priests, poor communities in Brazil started reading the Bible together without clergy — and discovered it spoke directly to their poverty, sparking a continent-wide movement.",
    scriptureConnection: 'Luke 4:18-19',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'coptic-martyrs-libya',
    title: "The 21 Coptic Martyrs on the Beach",
    era: '2015, Libya',
    category: 'church-history',
    themes: ['courage', 'hope', 'sacrifice', 'faithfulness'],
    oneLineSummary: "Twenty-one Coptic Christians from Egypt were executed on a Libyan beach by ISIS — the video shows them mouthing the name of Jesus, and their village in Egypt named a church after them.",
    scriptureConnection: 'Revelation 12:11',
    source: 'historical',
    spinnable: false,
  },
  {
    id: 'sudanese-church-under-bombs',
    title: "The Sudanese Church That Worships Under Bombs",
    era: '2000s-present, Sudan/South Sudan',
    category: 'church-history',
    themes: ['perseverance', 'joy-in-pain', 'community', 'hope'],
    oneLineSummary: "During the Sudanese civil war, churches in the Nuba Mountains gathered to worship under the trees as bombs fell — they sang louder when the planes came closer.",
    scriptureConnection: 'Psalm 27:1-3',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'teresa-of-avila-mud',
    title: "Teresa of Avila Falls in the Mud",
    era: '~1570, Spain',
    category: 'church-history',
    themes: ['humility', 'trust', 'joy-in-pain', 'faith-in-doubt'],
    oneLineSummary: "When Teresa of Avila fell off her donkey into a muddy stream, she prayed in frustration — and heard God say: 'This is how I treat my friends.' She replied: 'No wonder you have so few of them.'",
    scriptureConnection: 'Job 13:15',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'bartolome-de-las-casas',
    title: "De las Casas: The Conquistador Who Repented",
    era: '1514, Hispaniola',
    category: 'church-history',
    themes: ['justice', 'transformation', 'courage', 'mercy'],
    oneLineSummary: "A Spanish priest who owned enslaved Indigenous people read Ecclesiasticus 34:22 — 'To take away a neighbor's living is to commit murder' — freed his slaves, and spent 50 years fighting for Indigenous rights.",
    scriptureConnection: 'Amos 5:21-24',
    source: 'historical',
    spinnable: true,
  },
];

// ==========================================
// COMBINED REPOSITORY + HELPERS
// ==========================================

export const ALL_STORIES: Story[] = [
  ...BIBLICAL_STORIES,
  ...CHURCH_HISTORY_STORIES,
];

/** Get stories by theme tag */
export function getStoriesByTheme(theme: string): Story[] {
  return ALL_STORIES.filter((s) => s.themes.includes(theme));
}

/** Get stories that are spinnable (can support multiple devotional angles) */
export function getSpinnableStories(): Story[] {
  return ALL_STORIES.filter((s) => s.spinnable);
}

/** Get a random story from a category */
export function getRandomStory(
  category?: 'biblical' | 'church-history'
): Story {
  const pool = category
    ? ALL_STORIES.filter((s) => s.category === category)
    : ALL_STORIES;
  return pool[Math.floor(Math.random() * pool.length)];
}

/** Get stories matching multiple themes (any match) */
export function getStoriesByThemes(themes: string[]): Story[] {
  return ALL_STORIES.filter((s) =>
    s.themes.some((t) => themes.includes(t))
  );
}

/** Get stories from a specific biblical era or historical period */
export function getStoriesByEra(eraSubstring: string): Story[] {
  return ALL_STORIES.filter((s) =>
    s.era.toLowerCase().includes(eraSubstring.toLowerCase())
  );
}
