// ==========================================
// STORY REPOSITORY: CHURCH HISTORY — GLOBAL & MODERN
// Non-Western Christianity, 20th-21st century, overlooked traditions
// Used by AI devotional generation as illustration source material
// ==========================================

export interface ChurchHistoryStoryEntry {
  id: string;
  title: string;
  era: string;
  category: 'church-history';
  themes: string[];
  oneLineSummary: string;
  scriptureConnection: string;
  source: 'historical';
  spinnable: boolean;
}

export const CHURCH_HISTORY_GLOBAL_STORIES: ChurchHistoryStoryEntry[] = [
  // ==========================================
  // AFRICAN CHRISTIANITY
  // ==========================================
  {
    id: 'ethiopian-eunuch-legacy',
    title: 'The Eunuch Who Brought Christianity to Africa',
    era: '~34 AD onward',
    category: 'church-history',
    themes: ['missions', 'Africa', 'inclusion', 'Spirit-led', 'legacy', 'outsider'],
    oneLineSummary: 'Ethiopian tradition holds that the eunuch from Acts 8 brought Christianity to Ethiopia, establishing one of the world\'s oldest continuous Christian traditions.',
    scriptureConnection: 'Acts 8:26-40',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'coptic-martyrs-libya-2015',
    title: 'The 21 Martyrs Who Whispered "Lord Jesus" on a Beach',
    era: '2015',
    category: 'church-history',
    themes: ['martyrdom', 'courage', 'faith-under-fire', 'witness', 'modern-persecution'],
    oneLineSummary: 'Twenty-one Coptic Christians were beheaded by ISIS on a Libyan beach, and the video captured them whispering the name of Jesus as they died.',
    scriptureConnection: 'Revelation 12:11',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'desmond-tutu-forgiveness-theology',
    title: 'The Archbishop Who Chose Forgiveness Over Revenge',
    era: '1990s',
    category: 'church-history',
    themes: ['forgiveness', 'justice', 'reconciliation', 'ubuntu', 'South-Africa', 'peace'],
    oneLineSummary: 'Desmond Tutu led South Africa\'s Truth and Reconciliation Commission, choosing restorative justice over retribution — "No future without forgiveness."',
    scriptureConnection: 'Matthew 5:44; 2 Corinthians 5:18-19',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'nigerian-revival-1930s',
    title: 'The Nigerian Revival That Started with a Blind Man',
    era: '1930s',
    category: 'church-history',
    themes: ['revival', 'Africa', 'prayer', 'healing', 'grassroots', 'Spirit'],
    oneLineSummary: 'Joseph Babalola, a former steamroller driver, led a revival across Western Nigeria in the 1930s after intense fasting and prayer, founding the Christ Apostolic Church.',
    scriptureConnection: 'Acts 2:17-18',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'sudan-persecuted-church',
    title: 'The Church That Grew Under Bombs',
    era: '1983-2011',
    category: 'church-history',
    themes: ['persecution', 'growth', 'suffering', 'resilience', 'Africa', 'war'],
    oneLineSummary: 'During Sudan\'s civil war, the southern Sudanese church faced genocide and forced conversion, yet Christianity grew explosively — the blood of martyrs as seed.',
    scriptureConnection: 'Acts 8:1-4',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'athanasius-contra-mundum',
    title: 'The African Bishop Who Stood Against the World',
    era: '~328-373 AD',
    category: 'church-history',
    themes: ['courage', 'truth', 'exile', 'Africa', 'orthodoxy', 'perseverance'],
    oneLineSummary: 'Athanasius of Alexandria was exiled five times for defending that Jesus was fully God — earning the phrase "Athanasius contra mundum" (against the world).',
    scriptureConnection: 'John 1:1-3',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'augustine-of-hippo-conversion',
    title: 'The Party Boy from North Africa Who Shaped Western Theology',
    era: '386 AD',
    category: 'church-history',
    themes: ['conversion', 'Africa', 'sin', 'grace', 'transformation', 'mother-prayer'],
    oneLineSummary: 'Augustine lived a life of pleasure and intellectual wandering until he heard a child sing "Take up and read" — he opened Romans and was converted instantly.',
    scriptureConnection: 'Romans 13:13-14',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'samuel-ajayi-crowther',
    title: 'From Enslaved Boy to First African Anglican Bishop',
    era: '1843-1891',
    category: 'church-history',
    themes: ['slavery', 'redemption', 'Africa', 'education', 'leadership', 'translation'],
    oneLineSummary: 'Samuel Ajayi Crowther was captured as a slave at age 12, freed by the British navy, became a linguist, and was ordained the first African Anglican bishop.',
    scriptureConnection: 'Genesis 50:20',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'perpetua-felicity-martyrdom',
    title: 'The Noblewoman and Slave Who Died Together',
    era: '203 AD',
    category: 'church-history',
    themes: ['martyrdom', 'women', 'Africa', 'equality', 'courage', 'friendship'],
    oneLineSummary: 'Perpetua (a noblewoman) and Felicity (her pregnant slave) were martyred together in Carthage — their prison diary is one of the earliest Christian women\'s writings.',
    scriptureConnection: 'Galatians 3:28',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'simon-kimbangu-prophet-imprisoned',
    title: 'The Congolese Prophet Imprisoned for 30 Years',
    era: '1921-1951',
    category: 'church-history',
    themes: ['persecution', 'colonialism', 'Africa', 'resilience', 'prophetic-ministry', 'imprisonment'],
    oneLineSummary: 'Simon Kimbangu\'s healing ministry in the Congo threatened Belgian colonial power so much they sentenced him to life in prison, where he died after 30 years.',
    scriptureConnection: 'Matthew 25:36',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'janani-luwum-uganda-martyr',
    title: 'The Archbishop Killed by Idi Amin',
    era: '1977',
    category: 'church-history',
    themes: ['martyrdom', 'courage', 'Africa', 'tyranny', 'truth-to-power', 'sacrifice'],
    oneLineSummary: 'Archbishop Janani Luwum publicly denounced Idi Amin\'s atrocities in Uganda and was killed for it — his death helped turn global opinion against the regime.',
    scriptureConnection: 'John 15:13',
    source: 'historical',
    spinnable: true,
  },

  // ==========================================
  // ASIAN CHRISTIANITY
  // ==========================================
  {
    id: 'kakure-kirishitan-japan',
    title: 'The Hidden Christians Who Survived 250 Years Underground',
    era: '1597-1873',
    category: 'church-history',
    themes: ['persecution', 'hiddenness', 'survival', 'Japan', 'faithfulness', 'endurance'],
    oneLineSummary: 'When Christianity was banned in Japan under penalty of death, thousands of Kakure Kirishitan practiced secretly for 250 years with no priests or Bibles.',
    scriptureConnection: 'Matthew 10:26-28',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'korean-prayer-mountain',
    title: 'The Prayer Mountains Where Millions Cry Out at Dawn',
    era: '1950s-present',
    category: 'church-history',
    themes: ['prayer', 'Korea', 'revival', 'discipline', 'fervor', 'spiritual-warfare'],
    oneLineSummary: 'Korean Christians built prayer mountains where believers gather at 4 AM to pray, weep, and fast — fueling one of the fastest-growing churches in history.',
    scriptureConnection: 'Mark 1:35',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'chinese-house-church-movement',
    title: 'The Underground Church That Became 100 Million Strong',
    era: '1950s-present',
    category: 'church-history',
    themes: ['persecution', 'China', 'house-church', 'growth', 'resilience', 'Spirit'],
    oneLineSummary: 'After Mao tried to destroy Chinese Christianity, the underground house church movement grew from perhaps 1 million to an estimated 100 million believers.',
    scriptureConnection: 'Matthew 16:18',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'thomas-christians-india',
    title: 'The Indian Christians Who Predate European Missions',
    era: '52 AD onward',
    category: 'church-history',
    themes: ['ancient-church', 'India', 'apostolic', 'tradition', 'diversity'],
    oneLineSummary: 'The Saint Thomas Christians of Kerala, India claim their church was founded by the apostle Thomas in 52 AD — centuries before Christianity reached most of Europe.',
    scriptureConnection: 'John 20:24-29',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'wang-mingdao-23-years-prison',
    title: 'The Pastor Who Refused to Register His Church',
    era: '1955-1978',
    category: 'church-history',
    themes: ['persecution', 'integrity', 'China', 'imprisonment', 'conscience', 'faithfulness'],
    oneLineSummary: 'Wang Mingdao refused to register his church under Communist control, was imprisoned for 23 years, and became the conscience of Chinese Christianity.',
    scriptureConnection: 'Acts 5:29',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'watchman-nee-imprisoned-to-death',
    title: 'The Theologian Who Died in a Chinese Prison',
    era: '1952-1972',
    category: 'church-history',
    themes: ['persecution', 'China', 'theology', 'imprisonment', 'legacy', 'faithfulness'],
    oneLineSummary: 'Watchman Nee, whose books influenced millions, was imprisoned by the Communist government in 1952 and died in a labor camp 20 years later — a note was found: "Christ is the Son of God."',
    scriptureConnection: 'Philippians 1:21',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'korean-church-growth-from-war',
    title: 'The Church Born in the Ashes of War',
    era: '1950-1988',
    category: 'church-history',
    themes: ['suffering', 'growth', 'Korea', 'revival', 'prayer', 'resilience'],
    oneLineSummary: 'South Korea went from 2% Christian to nearly 30% in a single generation after the Korean War, with the largest church in the world reaching 800,000 members.',
    scriptureConnection: 'Romans 8:28',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'toyohiko-kagawa-slums',
    title: 'The Japanese Mystic Who Moved Into the Slums',
    era: '1909-1960',
    category: 'church-history',
    themes: ['poverty', 'incarnation', 'Japan', 'social-justice', 'sacrifice', 'love'],
    oneLineSummary: 'Toyohiko Kagawa gave up wealth to live in Kobe\'s worst slum, organized labor unions, and became Japan\'s most famous Christian activist — nominated for the Nobel Peace Prize.',
    scriptureConnection: 'Philippians 2:5-8',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'sadhu-sundar-singh',
    title: 'The Indian Mystic Who Walked the Himalayas for Christ',
    era: '1905-1929',
    category: 'church-history',
    themes: ['mysticism', 'India', 'renunciation', 'Christ-encounter', 'cross-cultural'],
    oneLineSummary: 'Sadhu Sundar Singh, a Sikh convert, dressed as an Indian holy man and walked through the Himalayas preaching Christ until he disappeared into Tibet and was never seen again.',
    scriptureConnection: 'Galatians 2:20',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'li-tim-oi-first-woman-priest',
    title: 'The First Woman Ordained as an Anglican Priest',
    era: '1944',
    category: 'church-history',
    themes: ['women', 'ordination', 'China', 'courage', 'pioneer', 'sacrifice'],
    oneLineSummary: 'Florence Li Tim-Oi was ordained in wartime Hong Kong because no male priest could reach her flock — then voluntarily gave up her license to avoid controversy, continuing to serve.',
    scriptureConnection: 'Galatians 3:28',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'underground-seminary-china',
    title: 'The Seminary That Met in Caves',
    era: '1970s-1990s',
    category: 'church-history',
    themes: ['education', 'persecution', 'China', 'faithfulness', 'risk', 'formation'],
    oneLineSummary: 'During China\'s religious repression, underground seminaries operated in caves, basements, and moving locations, training pastors who risked prison to serve.',
    scriptureConnection: 'Hebrews 11:38',
    source: 'historical',
    spinnable: true,
  },

  // ==========================================
  // LATIN AMERICAN CHRISTIANITY
  // ==========================================
  {
    id: 'oscar-romero-assassination-altar',
    title: 'The Archbishop Shot While Lifting the Chalice',
    era: '1980',
    category: 'church-history',
    themes: ['martyrdom', 'justice', 'Latin-America', 'courage', 'Eucharist', 'prophetic-voice'],
    oneLineSummary: 'Oscar Romero of El Salvador was assassinated by a sniper\'s bullet while celebrating Mass, moments after lifting the communion chalice at the altar.',
    scriptureConnection: 'Luke 22:20',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'base-communities-movement',
    title: 'When Poor Villagers Became Their Own Theologians',
    era: '1960s-1980s',
    category: 'church-history',
    themes: ['community', 'empowerment', 'Latin-America', 'Scripture', 'justice', 'grassroots'],
    oneLineSummary: 'Base ecclesial communities across Latin America taught poor villagers to read the Bible in their own context, sparking both spiritual renewal and social revolution.',
    scriptureConnection: 'Luke 4:18-19',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'bartolome-de-las-casas',
    title: 'The Conquistador Who Became the Indians\' Defender',
    era: '1514-1566',
    category: 'church-history',
    themes: ['repentance', 'justice', 'indigenous-rights', 'conversion', 'advocacy', 'colonialism'],
    oneLineSummary: 'Bartolome de las Casas was a Spanish colonist who owned enslaved Indigenous people until a sermon convicted him — he spent the rest of his life fighting to end their exploitation.',
    scriptureConnection: 'Isaiah 1:17',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'six-jesuits-el-salvador',
    title: 'The Six Professors Murdered for Teaching Justice',
    era: '1989',
    category: 'church-history',
    themes: ['martyrdom', 'education', 'justice', 'Latin-America', 'courage', 'witness'],
    oneLineSummary: 'Six Jesuit professors at UCA in El Salvador were dragged from their beds and executed by soldiers for their teaching about social justice — along with their housekeeper and her daughter.',
    scriptureConnection: 'Matthew 5:10',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'pentecostalism-latin-america-explosion',
    title: 'The Fastest Religious Shift in Modern History',
    era: '1960s-present',
    category: 'church-history',
    themes: ['revival', 'Latin-America', 'Pentecostalism', 'transformation', 'Spirit', 'growth'],
    oneLineSummary: 'In 60 years, Latin America went from nearly 100% Catholic to over 20% Protestant — the largest voluntary religious shift in recorded history, driven largely by Pentecostalism.',
    scriptureConnection: 'Joel 2:28-29',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'sor-juana-ines-de-la-cruz',
    title: 'The Nun Who Was the Greatest Mind of Her Age',
    era: '1651-1695',
    category: 'church-history',
    themes: ['women', 'intellect', 'Mexico', 'education', 'resistance', 'calling'],
    oneLineSummary: 'Sor Juana Ines de la Cruz became a nun to access education in 17th-century Mexico, wrote groundbreaking poetry and theology, and defended women\'s right to study.',
    scriptureConnection: 'Proverbs 1:7',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'gustavo-gutierrez-liberation-theology',
    title: 'The Peruvian Priest Who Asked "Where Is God in Poverty?"',
    era: '1971',
    category: 'church-history',
    themes: ['justice', 'poverty', 'theology', 'Latin-America', 'preferential-option-for-poor'],
    oneLineSummary: 'Gustavo Gutierrez, a Peruvian priest, wrote "A Theology of Liberation" arguing that God has a preferential option for the poor — reshaping global Christianity.',
    scriptureConnection: 'Luke 6:20; James 2:5',
    source: 'historical',
    spinnable: true,
  },

  // ==========================================
  // MIDDLE EASTERN CHRISTIANITY
  // ==========================================
  {
    id: 'syriac-christians-manuscript-preservation',
    title: 'The Monks Who Saved the Ancient World\'s Knowledge',
    era: '5th-13th century',
    category: 'church-history',
    themes: ['preservation', 'Middle-East', 'scholarship', 'faithfulness', 'knowledge', 'translation'],
    oneLineSummary: 'Syriac Christian monks translated and preserved Greek philosophical and scientific texts that would have been lost — later transmitted to Europe via Arabic scholars.',
    scriptureConnection: 'Proverbs 25:2',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'iraqi-christians-mosul',
    title: 'The Community That Survived 2,000 Years Then Lost Everything',
    era: '2014',
    category: 'church-history',
    themes: ['persecution', 'displacement', 'Iraq', 'loss', 'endurance', 'home'],
    oneLineSummary: 'When ISIS invaded Mosul in 2014, they painted the Arabic "N" (Nazarene) on Christian homes, giving families hours to convert, pay, or die — emptying a 2,000-year community.',
    scriptureConnection: 'Hebrews 11:37-38',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'maronite-christians-lebanon',
    title: 'The Mountain Christians Who Never Broke from Rome',
    era: '5th century-present',
    category: 'church-history',
    themes: ['endurance', 'Lebanon', 'identity', 'community', 'survival', 'tradition'],
    oneLineSummary: 'The Maronites retreated to the Lebanese mountains in the 5th century and maintained their unique Christian identity through 1,500 years of conquest, crusade, and civil war.',
    scriptureConnection: 'Matthew 5:14',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'coptic-cave-churches',
    title: 'The Churches Carved Into Cliffs',
    era: '4th century-present',
    category: 'church-history',
    themes: ['worship', 'Egypt', 'endurance', 'hiddenness', 'sacred-space', 'creativity'],
    oneLineSummary: 'Egyptian Coptic Christians have worshipped in cave churches carved into the Mokattam cliffs for centuries — including a modern garbage-collector community church seating 20,000.',
    scriptureConnection: 'Hebrews 11:38',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'church-of-the-east-silk-road',
    title: 'The Church That Reached China Before Marco Polo',
    era: '635 AD',
    category: 'church-history',
    themes: ['missions', 'Middle-East', 'China', 'Silk-Road', 'courage', 'forgotten-history'],
    oneLineSummary: 'The Church of the East sent missionaries along the Silk Road who reached Tang Dynasty China in 635 AD — 700 years before Marco Polo — as documented on the Xi\'an Stele.',
    scriptureConnection: 'Matthew 28:19',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'armenian-genocide-church-survival',
    title: 'The First Genocide of the 20th Century',
    era: '1915-1923',
    category: 'church-history',
    themes: ['genocide', 'survival', 'Armenia', 'martyrdom', 'memory', 'resilience'],
    oneLineSummary: 'The Ottoman Empire systematically killed 1.5 million Armenian Christians — yet the Armenian Apostolic Church, the world\'s oldest state church, survived and persists.',
    scriptureConnection: 'Psalm 124:1-3',
    source: 'historical',
    spinnable: true,
  },

  // ==========================================
  // ORTHODOX TRADITION STORIES
  // ==========================================
  {
    id: 'seraphim-of-sarov-bear',
    title: 'The Saint Who Fed Bears from His Hand',
    era: '1759-1833',
    category: 'church-history',
    themes: ['holiness', 'nature', 'peace', 'Russia', 'mysticism', 'gentleness'],
    oneLineSummary: 'Seraphim of Sarov spent years in solitary prayer in the Russian forest and became so gentle that wild bears would eat from his hand — his greeting was "Christ is risen, my joy!"',
    scriptureConnection: 'Isaiah 11:6-9',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'jesus-prayer-hesychasm',
    title: 'Seven Words Repeated Until They Become Your Heartbeat',
    era: '4th century-present',
    category: 'church-history',
    themes: ['prayer', 'contemplation', 'repetition', 'breath', 'presence', 'simplicity'],
    oneLineSummary: 'The Jesus Prayer — "Lord Jesus Christ, Son of God, have mercy on me" — has been prayed by Eastern Christians for 1,600 years, synchronized with breathing until it becomes automatic.',
    scriptureConnection: 'Luke 18:13; 1 Thessalonians 5:17',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'icons-written-in-prayer',
    title: 'The Images Painted as an Act of Worship',
    era: '5th century-present',
    category: 'church-history',
    themes: ['art', 'worship', 'contemplation', 'beauty', 'incarnation', 'prayer'],
    oneLineSummary: 'Orthodox iconographers don\'t "paint" icons — they "write" them, fasting and praying throughout the process, believing the icon becomes a window into heaven.',
    scriptureConnection: 'Exodus 25:18-22',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'desert-fathers-mothers',
    title: 'The First Christians Who Fled to the Desert',
    era: '3rd-5th century',
    category: 'church-history',
    themes: ['solitude', 'simplicity', 'desert', 'formation', 'wisdom', 'renunciation'],
    oneLineSummary: 'When Christianity became comfortable and imperial, the Desert Fathers and Mothers fled to the Egyptian wilderness, pioneering practices of silence, solitude, and spiritual combat.',
    scriptureConnection: 'Matthew 4:1-2; Luke 5:16',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'russian-new-martyrs',
    title: 'The Millions of Faithful Killed by the Soviet State',
    era: '1917-1991',
    category: 'church-history',
    themes: ['martyrdom', 'Russia', 'atheism', 'persecution', 'resilience', 'witness'],
    oneLineSummary: 'The Soviet regime killed an estimated 12-20 million Christians, destroyed 50,000 churches, and tried to eliminate faith — yet Russian Orthodoxy survived and revived.',
    scriptureConnection: 'Matthew 16:18',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'philokalia-spiritual-classic',
    title: 'The Book That Taught Eastern Christianity to Pray',
    era: '1782',
    category: 'church-history',
    themes: ['prayer', 'contemplation', 'spiritual-formation', 'inner-life', 'tradition'],
    oneLineSummary: 'The Philokalia, compiled by two monks in 1782, collected 1,100 years of Eastern Christian wisdom on prayer, attention, and the inner life — it remains the go-to guide for Orthodox spirituality.',
    scriptureConnection: 'Psalm 46:10',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'maria-skobtsova-nazi-martyr',
    title: 'The Russian Nun Who Died in a Nazi Gas Chamber',
    era: '1945',
    category: 'church-history',
    themes: ['martyrdom', 'sacrifice', 'hospitality', 'Holocaust', 'courage', 'women'],
    oneLineSummary: 'Mother Maria Skobtsova sheltered Jews in Paris during the Holocaust, smuggled children to safety in garbage bins, and died in Ravensbruck gas chamber on Good Friday.',
    scriptureConnection: 'John 15:13',
    source: 'historical',
    spinnable: true,
  },

  // ==========================================
  // 20TH CENTURY MARTYRS (DEEPER CUTS)
  // ==========================================
  {
    id: 'bonhoeffer-cost-of-discipleship',
    title: 'The Pastor Who Returned to Germany to Die',
    era: '1939-1945',
    category: 'church-history',
    themes: ['courage', 'discipleship', 'cost', 'resistance', 'Germany', 'sacrifice'],
    oneLineSummary: 'Bonhoeffer escaped to safety in America but returned to Germany, saying "I have no right to participate in the reconstruction of Christian life in Germany after the war if I don\'t share the trials."',
    scriptureConnection: 'Mark 8:34-35',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'bonhoeffer-cheap-grace',
    title: 'The Theologian Who Declared War on Easy Belief',
    era: '1937',
    category: 'church-history',
    themes: ['discipleship', 'grace', 'cost', 'theology', 'challenge', 'authenticity'],
    oneLineSummary: '"Cheap grace is the mortal enemy of our church" — Bonhoeffer challenged Christians who wanted forgiveness without transformation, grace without the cross.',
    scriptureConnection: 'Luke 14:27-33',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'trappist-monks-tibhirine',
    title: 'The Seven Monks Who Stayed When Everyone Said Leave',
    era: '1996',
    category: 'church-history',
    themes: ['martyrdom', 'Algeria', 'presence', 'peace', 'interfaith', 'courage'],
    oneLineSummary: 'Seven Trappist monks in Tibhirine, Algeria refused to leave their Muslim neighbors during civil war, were kidnapped and beheaded — their prior\'s testament forgave his killers in advance.',
    scriptureConnection: 'John 10:11-12',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'jim-elliot-auca-martyrdom',
    title: 'The Missionaries Killed by the People They Came to Love',
    era: '1956',
    category: 'church-history',
    themes: ['martyrdom', 'missions', 'sacrifice', 'Ecuador', 'forgiveness', 'fruit'],
    oneLineSummary: 'Jim Elliot and four missionaries were speared to death by the Waorani people of Ecuador — their widows then returned to live among the tribe, and many converted.',
    scriptureConnection: 'John 12:24',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'elisabeth-elliot-returns',
    title: 'The Widow Who Went Back to Her Husband\'s Killers',
    era: '1958',
    category: 'church-history',
    themes: ['forgiveness', 'courage', 'women', 'missions', 'enemy-love', 'grief'],
    oneLineSummary: 'Two years after the Waorani killed her husband Jim, Elisabeth Elliot took her three-year-old daughter and moved into the tribe that had murdered him.',
    scriptureConnection: 'Matthew 5:44',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'maximilian-kolbe-volunteer-death',
    title: 'The Priest Who Volunteered to Die in Another Man\'s Place',
    era: '1941',
    category: 'church-history',
    themes: ['sacrifice', 'substitution', 'Holocaust', 'love', 'courage', 'priesthood'],
    oneLineSummary: 'In Auschwitz, when a prisoner was selected for the starvation bunker, Father Maximilian Kolbe stepped forward and said "I will take his place" — the man he saved lived to 93.',
    scriptureConnection: 'John 15:13; Romans 5:7-8',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'corrie-ten-boom-hiding-place',
    title: 'The Watchmaker Who Hid Jews Behind a False Wall',
    era: '1940-1944',
    category: 'church-history',
    themes: ['courage', 'hiding', 'Holocaust', 'forgiveness', 'risk', 'faith'],
    oneLineSummary: 'Corrie ten Boom\'s family hid Jews in a secret room behind a false wall; she survived Ravensbruck concentration camp and later forgave a former guard face to face.',
    scriptureConnection: 'Proverbs 31:8-9',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'oscar-romero-transformation',
    title: 'The Conservative Bishop Radicalized by a Murder',
    era: '1977-1980',
    category: 'church-history',
    themes: ['transformation', 'justice', 'El-Salvador', 'prophetic-voice', 'conversion'],
    oneLineSummary: 'Romero was a quiet, bookish conservative until his friend Father Rutilio Grande was assassinated — the murder transformed him into the fearless voice of the Salvadoran poor.',
    scriptureConnection: 'Micah 6:8',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'alexander-men-murdered-priest',
    title: 'The Russian Priest Murdered on His Way to Church',
    era: '1990',
    category: 'church-history',
    themes: ['martyrdom', 'Russia', 'intellectual-faith', 'evangelism', 'courage'],
    oneLineSummary: 'Father Alexander Men was axed to death walking to his church in 1990 — he had been the Soviet Union\'s most effective Christian evangelist to intellectuals and artists.',
    scriptureConnection: 'Matthew 10:28',
    source: 'historical',
    spinnable: true,
  },

  // ==========================================
  // REVIVAL STORIES
  // ==========================================
  {
    id: 'azusa-street-revival',
    title: 'The Revival That Started in a Stable',
    era: '1906-1915',
    category: 'church-history',
    themes: ['revival', 'Spirit', 'racial-reconciliation', 'Pentecost', 'power', 'Los-Angeles'],
    oneLineSummary: 'The Azusa Street Revival, led by one-eyed Black preacher William Seymour in an old stable, broke racial barriers and launched global Pentecostalism — now 650 million strong.',
    scriptureConnection: 'Acts 2:1-4',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'welsh-revival-1904',
    title: 'The Revival That Shut Down the Pubs',
    era: '1904-1905',
    category: 'church-history',
    themes: ['revival', 'Wales', 'transformation', 'prayer', 'society', 'repentance'],
    oneLineSummary: 'The Welsh Revival of 1904 was so intense that pubs closed, police had nothing to do, pit ponies in mines stopped working because miners stopped swearing.',
    scriptureConnection: '2 Chronicles 7:14',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'east-african-revival',
    title: 'The Revival Built on Public Confession',
    era: '1930s-1960s',
    category: 'church-history',
    themes: ['revival', 'Africa', 'confession', 'transparency', 'community', 'holiness'],
    oneLineSummary: 'The East African Revival spread through Rwanda, Uganda, and Kenya through radical public confession of sin — even missionaries confessing racism to African believers.',
    scriptureConnection: 'James 5:16',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'hebrides-revival-1949',
    title: 'The Revival That Started with Two Old Women Praying',
    era: '1949-1953',
    category: 'church-history',
    themes: ['revival', 'Scotland', 'prayer', 'elderly', 'Spirit', 'transformation'],
    oneLineSummary: 'The Hebrides Revival began when two elderly sisters, one blind and one arthritic, prayed Isaiah 44:3 in their cottage — within weeks, whole villages were converted.',
    scriptureConnection: 'Isaiah 44:3',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'asbury-revival-2023',
    title: 'The College Chapel Service That Wouldn\'t End',
    era: '2023',
    category: 'church-history',
    themes: ['revival', 'youth', 'worship', 'spontaneity', 'Spirit', 'modern'],
    oneLineSummary: 'A routine chapel service at Asbury University in February 2023 simply didn\'t end — students kept worshipping for two weeks straight, drawing 50,000+ visitors from around the world.',
    scriptureConnection: 'Acts 2:42-47',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'great-awakening-jonathan-edwards',
    title: 'The Sermon That Made People Grab Church Pews',
    era: '1741',
    category: 'church-history',
    themes: ['revival', 'preaching', 'conviction', 'awakening', 'America', 'holiness'],
    oneLineSummary: 'Jonathan Edwards read "Sinners in the Hands of an Angry God" in a monotone voice, yet people wept so violently they grabbed pews to keep from falling into hell.',
    scriptureConnection: 'Hebrews 10:31',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'moravian-prayer-100-years',
    title: 'The Prayer Meeting That Lasted a Century',
    era: '1727-1827',
    category: 'church-history',
    themes: ['prayer', 'missions', 'perseverance', 'community', 'dedication'],
    oneLineSummary: 'The Moravian community started a 24/7 prayer chain in 1727 that continued unbroken for over 100 years, sending out more missionaries per capita than any church in history.',
    scriptureConnection: '1 Thessalonians 5:17',
    source: 'historical',
    spinnable: true,
  },

  // ==========================================
  // EVERYDAY SAINTS — ORDINARY HOLINESS
  // ==========================================
  {
    id: 'brother-lawrence-kitchen',
    title: 'The Monk Who Found God Washing Dishes',
    era: '1614-1691',
    category: 'church-history',
    themes: ['presence', 'ordinary-life', 'mindfulness', 'work', 'prayer', 'simplicity'],
    oneLineSummary: 'Brother Lawrence, a clumsy former soldier assigned to kitchen duty, practiced God\'s presence so deeply while scrubbing pots that nobles sought his spiritual counsel.',
    scriptureConnection: '1 Corinthians 10:31',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'jean-vanier-larche',
    title: 'The Philosopher Who Moved In with Disabled Strangers',
    era: '1964',
    category: 'church-history',
    themes: ['disability', 'community', 'vulnerability', 'dignity', 'love', 'downward-mobility'],
    oneLineSummary: 'Jean Vanier, a naval officer and philosopher, invited two men with intellectual disabilities to live with him — founding L\'Arche, now 154 communities in 38 countries.',
    scriptureConnection: '1 Corinthians 1:27-28',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'dorothy-day-catholic-worker',
    title: 'The Radical Who Served Soup and Wrote Revolution',
    era: '1933-1980',
    category: 'church-history',
    themes: ['justice', 'poverty', 'radical-hospitality', 'activism', 'faith', 'women'],
    oneLineSummary: 'Dorothy Day opened Catholic Worker houses to feed the hungry and published a penny newspaper — living voluntary poverty while challenging both church and state.',
    scriptureConnection: 'Matthew 25:35-40',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'mother-teresa-dark-night',
    title: 'The Saint Who Felt Nothing for 50 Years',
    era: '1946-1997',
    category: 'church-history',
    themes: ['dark-night', 'faithfulness', 'doubt', 'service', 'presence', 'perseverance'],
    oneLineSummary: 'Mother Teresa\'s private letters revealed she experienced almost no sense of God\'s presence for nearly 50 years — yet served the dying in Calcutta every single day.',
    scriptureConnection: 'Habakkuk 3:17-18',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'george-muller-orphanages',
    title: 'The Man Who Fed 10,000 Orphans on Prayer Alone',
    era: '1836-1898',
    category: 'church-history',
    themes: ['faith', 'provision', 'prayer', 'orphans', 'trust', 'miracles'],
    oneLineSummary: 'George Muller never asked anyone for money — he only prayed — yet fed and housed over 10,000 orphans in Bristol, receiving exactly what was needed, when it was needed.',
    scriptureConnection: 'Matthew 6:31-33',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'pandita-ramabai-india',
    title: 'The Indian Widow Who Built a Refuge for Women',
    era: '1889-1922',
    category: 'church-history',
    themes: ['women', 'India', 'justice', 'education', 'rescue', 'empowerment'],
    oneLineSummary: 'Pandita Ramabai, a Sanskrit scholar and widow in India, opened rescue homes for child widows, famine victims, and abandoned women, educating thousands when society discarded them.',
    scriptureConnection: 'James 1:27',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'amy-carmichael-india-rescue',
    title: 'The Woman Who Rescued Children from Temple Slavery',
    era: '1901-1951',
    category: 'church-history',
    themes: ['rescue', 'India', 'children', 'sacrifice', 'courage', 'long-obedience'],
    oneLineSummary: 'Amy Carmichael spent 55 years in India without furlough, rescuing children from temple prostitution — she never returned to England and is buried in India under a bird bath marked "Amma."',
    scriptureConnection: 'Psalm 68:5-6',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'clarence-jordan-koinonia-farm',
    title: 'The Farmer Who Integrated the Deep South with a Garden',
    era: '1942',
    category: 'church-history',
    themes: ['racial-reconciliation', 'community', 'America', 'risk', 'farming', 'kingdom'],
    oneLineSummary: 'Clarence Jordan founded Koinonia Farm in 1940s Georgia where Black and white families farmed together — they were bombed, shot at, and boycotted, but the farm still stands.',
    scriptureConnection: 'Galatians 3:28',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'dietrich-bonhoeffer-underground-seminary',
    title: 'The Seminary That Had to Hide from the Government',
    era: '1935-1937',
    category: 'church-history',
    themes: ['formation', 'resistance', 'community', 'Germany', 'discipleship', 'risk'],
    oneLineSummary: 'Bonhoeffer ran an underground seminary at Finkenwalde, training pastors in community life and resistance to Nazism — the Gestapo shut it down, but the book "Life Together" survived.',
    scriptureConnection: 'Hebrews 10:25',
    source: 'historical',
    spinnable: true,
  },

  // ==========================================
  // MODERN FAITH STORIES (21st CENTURY)
  // ==========================================
  {
    id: 'iraqi-christian-refugees-forgiveness',
    title: 'The Refugees Who Forgave ISIS on Camera',
    era: '2015',
    category: 'church-history',
    themes: ['forgiveness', 'persecution', 'Iraq', 'witness', 'enemy-love', 'modern'],
    oneLineSummary: 'Iraqi Christian refugees, displaced by ISIS, shocked journalists by publicly forgiving their persecutors on camera — "We forgive them because Jesus taught us to."',
    scriptureConnection: 'Luke 23:34',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'chinese-christianity-2030-projection',
    title: 'The Country on Track to Have More Christians Than America',
    era: '2010s-2030s (projected)',
    category: 'church-history',
    themes: ['growth', 'China', 'future', 'persecution', 'unstoppable', 'Spirit'],
    oneLineSummary: 'Despite intense government persecution, China\'s Christian population is growing so fast that some researchers project it will become the world\'s largest Christian nation by 2030.',
    scriptureConnection: 'Matthew 16:18',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'iran-fastest-growing-church',
    title: 'The Church Growing Fastest in the Islamic Republic',
    era: '2000s-present',
    category: 'church-history',
    themes: ['growth', 'Iran', 'persecution', 'conversion', 'house-church', 'dreams'],
    oneLineSummary: 'Iran has the fastest-growing evangelical church in the world — many converts report encountering Jesus in dreams, and house churches multiply despite prison sentences.',
    scriptureConnection: 'Joel 2:28',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'open-doors-persecution-index',
    title: 'The 360 Million Christians Under Persecution Today',
    era: '2020s',
    category: 'church-history',
    themes: ['persecution', 'global', 'solidarity', 'suffering', 'modern', 'awareness'],
    oneLineSummary: 'Open Doors estimates that 360 million Christians worldwide face high levels of persecution — more than any other faith group and more than at any point in history.',
    scriptureConnection: 'John 15:18-20',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'african-christianity-center-shift',
    title: 'When the Center of Christianity Moved South',
    era: '2000-present',
    category: 'church-history',
    themes: ['Africa', 'global-shift', 'growth', 'decolonization', 'future', 'diversity'],
    oneLineSummary: 'The center of global Christianity has shifted from Europe to the Global South — there are now more Anglicans in Nigeria alone than in England, the US, and Canada combined.',
    scriptureConnection: 'Revelation 7:9',
    source: 'historical',
    spinnable: true,
  },

  // ==========================================
  // REFORMATION & COUNTER-REFORMATION DEEP CUTS
  // ==========================================
  {
    id: 'jan-hus-burned-at-stake',
    title: 'The Reformer Burned 100 Years Before Luther',
    era: '1415',
    category: 'church-history',
    themes: ['courage', 'reform', 'martyrdom', 'truth', 'conscience', 'forerunner'],
    oneLineSummary: 'Jan Hus was burned at the stake for challenging church corruption a century before Luther — he prophesied "In 100 years, God will raise up a man whose calls for reform cannot be suppressed."',
    scriptureConnection: 'Galatians 5:1',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'william-tyndale-english-bible',
    title: 'The Man Strangled and Burned for Translating the Bible',
    era: '1536',
    category: 'church-history',
    themes: ['Bible-translation', 'martyrdom', 'courage', 'language', 'access', 'sacrifice'],
    oneLineSummary: 'William Tyndale was strangled and burned at the stake for translating the Bible into English — his dying words were "Lord, open the King of England\'s eyes."',
    scriptureConnection: 'Psalm 119:105',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'anabaptist-martyrs-mirror',
    title: 'The Christians Who Were Drowned for Baptism',
    era: '1525-1600s',
    category: 'church-history',
    themes: ['martyrdom', 'baptism', 'pacifism', 'conscience', 'persecution', 'radical-faith'],
    oneLineSummary: 'The Anabaptists were persecuted by both Catholics and Protestants — ironically drowned for practicing adult baptism — their Martyrs Mirror records over 800 accounts.',
    scriptureConnection: 'Romans 6:3-4',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'john-bunyan-prison-pilgrims-progress',
    title: 'The Tinker Who Wrote a Masterpiece in Prison',
    era: '1660-1672',
    category: 'church-history',
    themes: ['imprisonment', 'creativity', 'calling', 'perseverance', 'literature', 'faith'],
    oneLineSummary: 'John Bunyan, an uneducated tinker, was imprisoned for 12 years for preaching without a license — and in prison wrote Pilgrim\'s Progress, the most widely read Christian book after the Bible.',
    scriptureConnection: 'Philippians 1:12-14',
    source: 'historical',
    spinnable: true,
  },

  // ==========================================
  // UNIQUE MOVEMENTS AND PRACTICES
  // ==========================================
  {
    id: 'quaker-silent-worship',
    title: 'The Christians Who Sit in Silence Until God Speaks',
    era: '1650s-present',
    category: 'church-history',
    themes: ['silence', 'Spirit', 'simplicity', 'worship', 'listening', 'peace'],
    oneLineSummary: 'Quaker worship has no pastor, no music, no agenda — the congregation sits in silence, sometimes for an entire hour, waiting for the Holy Spirit to prompt someone to speak.',
    scriptureConnection: 'Psalm 46:10; 1 Kings 19:12',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'taize-community-reconciliation',
    title: 'The Ecumenical Community Founded During WWII',
    era: '1940-present',
    category: 'church-history',
    themes: ['reconciliation', 'ecumenism', 'community', 'France', 'youth', 'chant'],
    oneLineSummary: 'Brother Roger founded Taize in France during WWII, hiding Jewish refugees; it became an ecumenical community drawing 100,000+ young people annually for prayer and reconciliation.',
    scriptureConnection: 'John 17:21',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'coptic-garbage-collectors-church',
    title: 'The Garbage Collectors Who Built a Cathedral in a Cave',
    era: '1970s-present',
    category: 'church-history',
    themes: ['dignity', 'Egypt', 'poverty', 'worship', 'transformation', 'beauty'],
    oneLineSummary: 'The Zabaleen, Cairo\'s garbage collectors, carved a massive church into the Mokattam mountain that seats 20,000 — built by the hands of people the city considers untouchable.',
    scriptureConnection: '1 Corinthians 1:27-29',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'celtic-christianity-thin-places',
    title: 'The Faith That Found God in Wild Places',
    era: '5th-9th century',
    category: 'church-history',
    themes: ['nature', 'Celtic', 'mysticism', 'creation', 'pilgrimage', 'beauty'],
    oneLineSummary: 'Celtic Christians believed in "thin places" where the boundary between heaven and earth was nearly transparent — cliffs, islands, forests became sanctuaries of encounter.',
    scriptureConnection: 'Romans 1:20',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'francis-of-assisi-poverty',
    title: 'The Rich Boy Who Stripped Naked in the Town Square',
    era: '1206',
    category: 'church-history',
    themes: ['poverty', 'renunciation', 'freedom', 'radical-obedience', 'joy', 'creation'],
    oneLineSummary: 'Francis of Assisi literally stripped off his expensive clothes in the town square, handed them to his father, and walked away naked — choosing poverty and preaching to birds.',
    scriptureConnection: 'Matthew 19:21',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'john-of-the-cross-dark-night',
    title: 'The Mystic Who Named the Depression That Leads to God',
    era: '1577-1578',
    category: 'church-history',
    themes: ['dark-night', 'suffering', 'mysticism', 'transformation', 'imprisonment', 'poetry'],
    oneLineSummary: 'John of the Cross was imprisoned by his own religious order in a closet-sized cell; there he wrote "Dark Night of the Soul," naming the spiritual depression as God\'s hidden work.',
    scriptureConnection: 'Psalm 23:4',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'hildegard-of-bingen',
    title: 'The Medieval Nun Who Was a Doctor, Composer, and Mystic',
    era: '1098-1179',
    category: 'church-history',
    themes: ['women', 'creativity', 'visions', 'medicine', 'music', 'multifaceted-calling'],
    oneLineSummary: 'Hildegard of Bingen composed 70+ musical works, wrote medical and scientific texts, counseled popes and emperors, and reported visions of God\'s "Living Light" — all in the 12th century.',
    scriptureConnection: 'Joel 2:28',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'harriet-tubman-moses',
    title: 'The Woman They Called Moses',
    era: '1849-1863',
    category: 'church-history',
    themes: ['liberation', 'courage', 'faith', 'America', 'slavery', 'calling'],
    oneLineSummary: 'Harriet Tubman made 13 trips on the Underground Railroad, freeing 70+ enslaved people, guided by prayer and visions — she said "I never ran my train off the track and I never lost a passenger."',
    scriptureConnection: 'Exodus 3:7-8',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'sojourner-truth-aint-i-woman',
    title: 'The Preacher Who Asked "Ain\'t I a Woman?"',
    era: '1851',
    category: 'church-history',
    themes: ['justice', 'women', 'race', 'preaching', 'courage', 'dignity'],
    oneLineSummary: 'Sojourner Truth, born enslaved, became a traveling preacher who silenced critics at a women\'s rights convention by listing her suffering and asking "Ain\'t I a woman?"',
    scriptureConnection: 'Galatians 3:28',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'dietrich-bonhoeffer-who-stands',
    title: '"Who Stands Fast? Only the One Whose Final Standard Is Not Reason but God"',
    era: '1942',
    category: 'church-history',
    themes: ['ethics', 'courage', 'discernment', 'obedience', 'conscience', 'resistance'],
    oneLineSummary: 'In his unfinished Ethics, Bonhoeffer argued that in a world of radical evil, the responsible person must sometimes break rules and accept guilt — trusting only in God\'s grace.',
    scriptureConnection: 'Acts 5:29',
    source: 'historical',
    spinnable: true,
  },

  // ==========================================
  // FAITH AND SCIENCE / INTELLECTUAL COURAGE
  // ==========================================
  {
    id: 'george-washington-carver',
    title: 'The Former Slave Who Talked to Flowers',
    era: '1864-1943',
    category: 'church-history',
    themes: ['science', 'faith', 'humility', 'creativity', 'race', 'calling'],
    oneLineSummary: 'George Washington Carver said he asked God what the universe was for and God said "Ask something more your size" — so he asked about the peanut and discovered 300 uses.',
    scriptureConnection: 'Psalm 19:1-2',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'blaise-pascal-night-of-fire',
    title: 'The Mathematician Who Sewed His Conversion Into His Coat',
    era: '1654',
    category: 'church-history',
    themes: ['encounter', 'intellect', 'conversion', 'fire', 'passion', 'hiddenness'],
    oneLineSummary: 'On November 23, 1654, mathematician Blaise Pascal had a mystical encounter he called "FIRE" — he wrote it on parchment and sewed it into his coat lining, found only after his death.',
    scriptureConnection: 'Exodus 3:2-6',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'gregor-mendel-monk-genetics',
    title: 'The Monk in the Garden Who Discovered Genetics',
    era: '1856-1863',
    category: 'church-history',
    themes: ['science', 'faith', 'patience', 'discovery', 'obscurity', 'vindication'],
    oneLineSummary: 'Gregor Mendel, an Augustinian friar, spent years cross-breeding pea plants in his monastery garden and discovered the laws of genetics — his work was ignored for 35 years.',
    scriptureConnection: '1 Corinthians 3:6',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'georges-lemaitre-big-bang',
    title: 'The Priest Who Proposed the Big Bang',
    era: '1927',
    category: 'church-history',
    themes: ['science', 'faith', 'creation', 'cosmology', 'intellect', 'courage'],
    oneLineSummary: 'Georges Lemaitre, a Belgian Catholic priest, first proposed the Big Bang theory — Einstein initially dismissed it, but Lemaitre proved him wrong about the expanding universe.',
    scriptureConnection: 'Genesis 1:1; Hebrews 11:3',
    source: 'historical',
    spinnable: true,
  },

  // ==========================================
  // MUSIC, ART, AND CREATIVE FAITH
  // ==========================================
  {
    id: 'amazing-grace-slave-trader',
    title: 'The Hymn Written by a Former Slave Trader',
    era: '1772',
    category: 'church-history',
    themes: ['grace', 'conversion', 'slavery', 'redemption', 'music', 'repentance'],
    oneLineSummary: 'John Newton captained slave ships before his conversion; his hymn "Amazing Grace" was written from the gut-level knowledge of how wretched he had truly been.',
    scriptureConnection: 'Ephesians 2:8-9',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'bach-soli-deo-gloria',
    title: 'The Composer Who Signed Every Piece "To God Alone the Glory"',
    era: '1685-1750',
    category: 'church-history',
    themes: ['art', 'worship', 'creativity', 'dedication', 'music', 'vocation'],
    oneLineSummary: 'J.S. Bach inscribed "S.D.G." (Soli Deo Gloria — "To God alone the glory") at the end of every composition, sacred and secular alike.',
    scriptureConnection: '1 Corinthians 10:31',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'thomas-dorsey-precious-lord',
    title: 'The Hymn Born from a Wife\'s Death in Childbirth',
    era: '1932',
    category: 'church-history',
    themes: ['grief', 'music', 'lament', 'healing', 'creation-from-pain'],
    oneLineSummary: 'Thomas Dorsey wrote "Precious Lord, Take My Hand" after his wife and newborn son both died — the song Martin Luther King Jr. requested just before his assassination.',
    scriptureConnection: 'Psalm 34:18',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'fanny-crosby-blind-hymn-writer',
    title: 'The Blind Woman Who Wrote 8,000 Hymns',
    era: '1820-1915',
    category: 'church-history',
    themes: ['disability', 'creativity', 'worship', 'perseverance', 'women', 'joy'],
    oneLineSummary: 'Fanny Crosby was blinded as an infant by medical malpractice yet wrote over 8,000 hymns — she said blindness was a gift because "the first face I ever see will be Jesus."',
    scriptureConnection: '2 Corinthians 4:17-18',
    source: 'historical',
    spinnable: true,
  },

  // ==========================================
  // INDIGENOUS AND DECOLONIZED FAITH
  // ==========================================
  {
    id: 'kateri-tekakwitha',
    title: 'The Mohawk Woman Who Became a Catholic Saint',
    era: '1656-1680',
    category: 'church-history',
    themes: ['indigenous', 'conversion', 'suffering', 'holiness', 'cultural-identity', 'women'],
    oneLineSummary: 'Kateri Tekakwitha, a Mohawk-Algonquin woman scarred by smallpox, converted to Christianity and was shunned by her village — she became the first Native American Catholic saint.',
    scriptureConnection: 'Matthew 5:10-11',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'vincent-donovan-masai',
    title: 'The Missionary Who Let the Masai Reinvent Church',
    era: '1960s-1970s',
    category: 'church-history',
    themes: ['missions', 'decolonization', 'inculturation', 'Africa', 'humility', 'fresh-eyes'],
    oneLineSummary: 'Father Vincent Donovan abandoned the mission compound approach to sit with Masai elders and let them encounter the gospel on their own terms, documented in "Christianity Rediscovered."',
    scriptureConnection: 'Acts 15:28-29',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'lottie-moon-china',
    title: 'The 4-Foot-3 Woman Who Changed How Christians Fund Missions',
    era: '1873-1912',
    category: 'church-history',
    themes: ['missions', 'China', 'sacrifice', 'women', 'generosity', 'fasting'],
    oneLineSummary: 'Lottie Moon served 39 years in China and starved to death giving her food to famine victims — the annual offering in her name has since raised over $5 billion for missions.',
    scriptureConnection: 'John 12:24',
    source: 'historical',
    spinnable: true,
  },

  // ==========================================
  // MODERN MOVEMENTS AND FIGURES
  // ==========================================
  {
    id: 'martin-luther-king-letter-birmingham',
    title: 'The Letter That Redefined Christian Resistance',
    era: '1963',
    category: 'church-history',
    themes: ['justice', 'civil-rights', 'America', 'nonviolence', 'prophetic-voice', 'courage'],
    oneLineSummary: 'Martin Luther King Jr. wrote his Letter from Birmingham Jail on newspaper margins, arguing that injustice anywhere is a threat to justice everywhere — a masterclass in prophetic Christianity.',
    scriptureConnection: 'Amos 5:24',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'john-perkins-reconciliation',
    title: 'The Man Beaten Nearly to Death Who Preached Reconciliation',
    era: '1970-present',
    category: 'church-history',
    themes: ['reconciliation', 'racial-justice', 'forgiveness', 'America', 'community-development'],
    oneLineSummary: 'John Perkins was beaten nearly to death by police in Mississippi, yet dedicated his life to racial reconciliation and Christian community development — founding the CCDA.',
    scriptureConnection: 'Ephesians 2:14-16',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'henrietta-mears-influence',
    title: 'The Sunday School Teacher Who Shaped a Generation of Leaders',
    era: '1928-1963',
    category: 'church-history',
    themes: ['women', 'teaching', 'influence', 'leadership-development', 'education'],
    oneLineSummary: 'Henrietta Mears taught Sunday school at Hollywood Presbyterian and directly mentored Bill Bright (Campus Crusade founder) and influenced Billy Graham — never ordained, never a pastor.',
    scriptureConnection: '2 Timothy 2:2',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'c-s-lewis-reluctant-convert',
    title: 'The Atheist Dragged Kicking and Screaming to God',
    era: '1929-1931',
    category: 'church-history',
    themes: ['conversion', 'intellect', 'reluctance', 'apologetics', 'honesty', 'joy'],
    oneLineSummary: 'C.S. Lewis called himself "the most dejected and reluctant convert in all England," saying he was brought to faith "kicking, struggling, resentful, and darting his eyes in every direction for a chance of escape."',
    scriptureConnection: 'Acts 9:5',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'billy-graham-racial-integration',
    title: 'The Evangelist Who Personally Removed the Segregation Ropes',
    era: '1953',
    category: 'church-history',
    themes: ['racial-reconciliation', 'courage', 'evangelism', 'America', 'integration'],
    oneLineSummary: 'At his 1953 Chattanooga crusade, Billy Graham personally walked down and removed the ropes separating Black and white seating sections, refusing to preach to a segregated audience.',
    scriptureConnection: 'Galatians 3:28',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'richard-wurmbrand-tortured-for-christ',
    title: 'The Pastor Who Spent 14 Years in Communist Prisons',
    era: '1948-1964',
    category: 'church-history',
    themes: ['persecution', 'Romania', 'imprisonment', 'forgiveness', 'endurance', 'witness'],
    oneLineSummary: 'Richard Wurmbrand endured 14 years of torture in Romanian Communist prisons, including 3 years in solitary confinement, then founded Voice of the Martyrs to serve the persecuted church.',
    scriptureConnection: '2 Corinthians 4:8-9',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'brother-roger-taize-murdered',
    title: 'The Peacemaker Stabbed During Evening Prayer',
    era: '2005',
    category: 'church-history',
    themes: ['martyrdom', 'peace', 'vulnerability', 'ecumenism', 'prayer', 'community'],
    oneLineSummary: 'Brother Roger of Taize, who spent 65 years building a global community of reconciliation, was stabbed to death by a disturbed woman during an evening prayer service with 2,500 worshippers.',
    scriptureConnection: 'John 17:20-21',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'night-commuters-uganda',
    title: 'The Children Who Walked Miles Every Night to Sleep Safely',
    era: '2003-2006',
    category: 'church-history',
    themes: ['children', 'protection', 'Uganda', 'war', 'church-response', 'hospitality'],
    oneLineSummary: 'During the LRA conflict in Uganda, up to 40,000 children walked miles each night to church compounds and NGO shelters to avoid being abducted as child soldiers.',
    scriptureConnection: 'Matthew 18:10',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'shanghai-church-reopening-1979',
    title: 'The Church That Reopened After 13 Years to a Standing-Room Crowd',
    era: '1979',
    category: 'church-history',
    themes: ['resilience', 'China', 'faith', 'persecution', 'joy', 'return'],
    oneLineSummary: 'When Shanghai\'s Moore Memorial Church reopened in 1979 after being closed during the Cultural Revolution, thousands showed up — the congregation had secretly multiplied during persecution.',
    scriptureConnection: 'Isaiah 55:11',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'nestorian-stele-china',
    title: 'The 8th-Century Stone That Proves Christianity Reached China',
    era: '781 AD (discovered 1625)',
    category: 'church-history',
    themes: ['history', 'China', 'missions', 'discovery', 'forgotten-faith', 'evidence'],
    oneLineSummary: 'The Nestorian Stele, discovered in 1625, is a 9-foot limestone monument from 781 AD documenting 150 years of Christian presence in Tang Dynasty China — complete with a cross and Chinese text.',
    scriptureConnection: 'Matthew 28:19',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'slave-spirituals-coded-messages',
    title: 'The Songs That Were Secret Maps to Freedom',
    era: '1700s-1860s',
    category: 'church-history',
    themes: ['slavery', 'music', 'liberation', 'coded-language', 'hope', 'resistance'],
    oneLineSummary: 'Enslaved African Americans embedded escape routes and freedom instructions in spirituals like "Wade in the Water" and "Follow the Drinking Gourd" — faith as resistance literature.',
    scriptureConnection: 'Exodus 15:1-2',
    source: 'historical',
    spinnable: true,
  },
];
