// ==========================================
// STORY REPOSITORY: LITERATURE & FILM — EXTENDED
// Deeper cuts, world literature, poetry, TV, and lesser-known film
// Supplements the base stories-literature-film.ts collection
// ==========================================

import type { StoryEntry } from './stories-psychology-science';

export const LITERATURE_FILM_STORIES_EXTENDED: StoryEntry[] = [
  // ==========================================
  // CLASSIC / WORLD LITERATURE — DEEPER CUTS
  // ==========================================
  {
    id: 'brothers-karamazov-ivan-ticket',
    title: 'Ivan Returns His Ticket to God',
    era: '1880',
    category: 'literature-film',
    themes: ['suffering', 'theodicy', 'doubt', 'protest', 'honesty-with-God'],
    oneLineSummary: 'Ivan tells Alyosha he accepts God but cannot accept a world where children suffer — so he "returns his ticket" to the universe out of moral protest.',
    spiritualAngle: 'Ivan\'s rebellion is the most honest form of faith: refusing to pretend the problem of suffering is solved. God can handle your returned ticket better than your polite silence.',
    source: 'literature',
    specificReference: 'Fyodor Dostoevsky, "The Brothers Karamazov" (1880), Book V Ch. 4: "Rebellion"',
    spinnable: true,
  },
  {
    id: 'idiot-myshkin-destroyed',
    title: 'The Perfectly Good Man Gets Destroyed by the World',
    era: '1869',
    category: 'literature-film',
    themes: ['innocence', 'vulnerability', 'goodness', 'suffering', 'Christ-figure'],
    oneLineSummary: 'Prince Myshkin is Dostoevsky\'s attempt to depict a perfectly good man — and the novel traces how the world systematically destroys him precisely because of his goodness.',
    spiritualAngle: 'Perfect goodness does not survive contact with a fallen world — it gets crucified. Myshkin is a parable about why the Incarnation had to end the way it did.',
    source: 'literature',
    specificReference: 'Fyodor Dostoevsky, "The Idiot" (1869)',
    spinnable: true,
  },
  {
    id: 'death-ivan-ilyich-never-lived',
    title: 'A Man Discovers at Death That He Never Lived',
    era: '1886',
    category: 'literature-film',
    themes: ['mortality', 'authenticity', 'repentance', 'meaning', 'wasted-life'],
    oneLineSummary: 'As Ivan Ilyich lies dying, he realizes his entire respectable life was a lie — every promotion, every social success was a step away from anything real. Only in his final hours does he find authentic compassion.',
    spiritualAngle: '"What does it profit a man to gain the whole world and forfeit his soul?" Tolstoy wrote the novella version of that question, and the answer arrives only on the deathbed.',
    source: 'literature',
    specificReference: 'Leo Tolstoy, "The Death of Ivan Ilyich" (1886)',
    spinnable: true,
  },
  {
    id: 'princess-goblin-invisible-thread',
    title: 'Following a Thread You Cannot See Through Darkness',
    era: '1872',
    category: 'literature-film',
    themes: ['faith', 'trust', 'guidance', 'obedience', 'invisible'],
    oneLineSummary: 'Princess Irene must follow a magical thread through pitch-dark mines — a thread only she can feel, invisible to others, given by her great-great-grandmother who lives in a hidden tower.',
    spiritualAngle: 'Faith is following a thread you cannot show to others, given by someone they may not believe exists, through darkness where it is the only guide. MacDonald wrote the purest metaphor for trust.',
    source: 'literature',
    specificReference: 'George MacDonald, "The Princess and the Goblin" (1872), Ch. 15: "Woven and Then Spun"',
    spinnable: true,
  },
  {
    id: 'jayber-crow-hidden-faithfulness',
    title: 'A Barber\'s Lifelong Secret Faithfulness',
    era: '2000',
    category: 'literature-film',
    themes: ['faithfulness', 'obscurity', 'vocation', 'love', 'perseverance'],
    oneLineSummary: 'Jayber Crow silently loves a married woman for decades, serving his small Kentucky town as a barber, never acting on his love but remaining faithful in ways only he and God know.',
    spiritualAngle: 'Not all faithfulness is visible. Jayber\'s hidden devotion is a parable about the millions of quiet, unseen acts of love that hold the world together without applause.',
    source: 'literature',
    specificReference: 'Wendell Berry, "Jayber Crow" (2000)',
    spinnable: true,
  },
  {
    id: 'godric-terrible-saint',
    title: 'A Medieval Saint Who Was Also Terrible',
    era: '1980',
    category: 'literature-film',
    themes: ['hypocrisy', 'honesty', 'sin', 'holiness', 'complexity'],
    oneLineSummary: 'The historical saint Godric narrates his own life and unlike the hagiographies, tells the truth: he was a pirate, a lecher, and a liar who stumbled into holiness through the back door.',
    spiritualAngle: 'The saints were not edited people. Godric\'s insistence on his own wretchedness is the realest form of holiness — because it makes grace the explanation rather than willpower.',
    source: 'literature',
    specificReference: 'Frederick Buechner, "Godric" (1980), National Book Award finalist',
    spinnable: true,
  },
  {
    id: 'power-glory-whisky-priest',
    title: 'The Last Priest Is a Drunk and a Coward',
    era: '1940',
    category: 'literature-film',
    themes: ['weakness', 'calling', 'unworthiness', 'grace', 'vocation', 'persecution'],
    oneLineSummary: 'The last priest in anti-clerical Mexico is an alcoholic with an illegitimate child who keeps running — yet he cannot stop being a priest, and his flawed sacraments remain valid.',
    spiritualAngle: 'God\'s grace does not require a worthy vessel. The whisky priest\'s sacraments work because they depend on God, not on him. Your unworthiness does not disqualify your calling.',
    source: 'literature',
    specificReference: 'Graham Greene, "The Power and the Glory" (1940)',
    spinnable: true,
  },
  {
    id: 'silence-endo-fumie',
    title: 'God Speaks Through the Act of Stepping on His Face',
    era: '1966',
    category: 'literature-film',
    themes: ['silence-of-God', 'suffering', 'apostasy', 'grace', 'sacrifice'],
    oneLineSummary: 'A Jesuit priest is told to apostatize by stepping on an image of Christ to save tortured Christians — and as he steps, he hears Christ say "It was to be trampled on by men that I was born."',
    spiritualAngle: 'Sometimes the most faithful act looks like betrayal from the outside. Christ\'s voice breaking decades of silence to give permission to step on him is the most radical image of grace in modern fiction.',
    source: 'literature',
    specificReference: 'Shusaku Endo, "Silence" (1966), Ch. 10: the fumie scene',
    spinnable: true,
  },
  {
    id: 'till-we-have-faces-orual',
    title: 'You Cannot Meet God Until You Have a Face',
    era: '1956',
    category: 'literature-film',
    themes: ['identity', 'self-knowledge', 'honesty', 'masks', 'encounter-with-God'],
    oneLineSummary: 'Queen Orual demands to know why the gods are silent — until she realizes she has been wearing a veil her whole life and cannot meet the divine until she removes it.',
    spiritualAngle: '"How can the gods meet us face to face till we have faces?" You cannot encounter God authentically while hiding behind the persona you constructed. Self-knowledge precedes divine encounter.',
    source: 'literature',
    specificReference: 'C.S. Lewis, "Till We Have Faces" (1956), Lewis\'s self-described best novel',
    spinnable: true,
  },
  {
    id: 'great-divorce-grey-town',
    title: 'Hell Is Getting Everything You Want and No One Else',
    era: '1945',
    category: 'literature-film',
    themes: ['hell', 'selfishness', 'isolation', 'choice', 'freedom'],
    oneLineSummary: 'In Lewis\'s fantasy, hell is a grey town where everyone has moved farther and farther apart because they cannot stand each other — hell is simply the final state of getting everything you want.',
    spiritualAngle: 'Hell is not God\'s punishment imposed from outside but the natural endpoint of self-chosen isolation. Every step away from community is a step toward the grey town.',
    source: 'literature',
    specificReference: 'C.S. Lewis, "The Great Divorce" (1945)',
    spinnable: true,
  },
  {
    id: 'beloved-ghost-rememory',
    title: 'Trauma Lives in the House Like a Ghost',
    era: '1987',
    category: 'literature-film',
    themes: ['trauma', 'memory', 'healing', 'haunting', 'freedom'],
    oneLineSummary: 'A murdered baby returns as a ghost to the house of the mother who killed her to save her from slavery — the past literally refuses to stay buried until it is named, mourned, and released.',
    spiritualAngle: 'Unprocessed trauma haunts like Beloved: consuming the present, demanding all attention, growing stronger when ignored. Healing requires the community to come together and speak the unspeakable aloud.',
    source: 'literature',
    specificReference: 'Toni Morrison, "Beloved" (1987), Pulitzer Prize for Fiction (1988)',
    spinnable: true,
  },
  {
    id: 'dostoevsky-beauty-saves',
    title: 'Beauty Will Save the World',
    era: '1869',
    category: 'literature-film',
    themes: ['beauty', 'salvation', 'aesthetics', 'hope', 'transcendence'],
    oneLineSummary: 'Prince Myshkin declares that "beauty will save the world" — meaning not prettiness but the arresting, disarming power of genuine goodness made visible.',
    spiritualAngle: 'Beauty — true beauty, not decoration — is a form of revelation. It stops you in your tracks. This is why the church historically invested in art, architecture, and music: beauty is evangelism.',
    source: 'literature',
    specificReference: 'Fyodor Dostoevsky, "The Idiot" (1869), Part 3, Ch. 5; Solzhenitsyn\'s Nobel lecture on the phrase',
    spinnable: true,
  },
  {
    id: 'anna-karenina-levin-faith',
    title: 'A Rationalist Finds Faith by Watching a Peasant Live',
    era: '1878',
    category: 'literature-film',
    themes: ['faith', 'intellect', 'simplicity', 'imitation', 'formation'],
    oneLineSummary: 'Levin, Tolstoy\'s intellectual hero, cannot think his way to God — but watching a peasant say "we live for God" cracks something open. Faith arrives not through argument but through witness.',
    spiritualAngle: 'Formation happens through imitation, not information. Levin needed to see faith lived, not explained. This is why Paul said "imitate me as I imitate Christ" rather than "study my theology."',
    source: 'literature',
    specificReference: 'Leo Tolstoy, "Anna Karenina" (1878), Part 8: Levin\'s conversion',
    spinnable: true,
  },
  {
    id: 'hobbit-unexpected-party',
    title: 'Adventures Start When You Leave Your Comfortable Hole',
    era: '1937',
    category: 'literature-film',
    themes: ['calling', 'comfort', 'adventure', 'courage', 'vocation'],
    oneLineSummary: 'Bilbo Baggins loves his comfortable hobbit hole — until Gandalf arrives and he discovers that the life he never wanted was the life that would make him fully himself.',
    spiritualAngle: 'God\'s call always disrupts comfort. Abraham left Ur, Moses left Midian, the disciples left their nets. The life you are clinging to may be the life keeping you small.',
    source: 'literature',
    specificReference: 'J.R.R. Tolkien, "The Hobbit" (1937), Chapter 1: "An Unexpected Party"',
    spinnable: true,
  },
  {
    id: 'phantom-tollbooth-doldrums',
    title: 'The Biggest Danger Is Not Caring About Anything',
    era: '1961',
    category: 'literature-film',
    themes: ['apathy', 'purpose', 'engagement', 'calling', 'attention'],
    oneLineSummary: 'Milo discovers the Doldrums — where people who don\'t think and don\'t care slowly sink into nothing. Escape requires thinking, which the Lethargarians have forgotten how to do.',
    spiritualAngle: 'Acedia — spiritual apathy — is the most dangerous vice because it disguises itself as normality. The opposite of faith is not doubt; it is indifference.',
    source: 'literature',
    specificReference: 'Norton Juster, "The Phantom Tollbooth" (1961), Chapter 2: "Beyond Expectations"',
    spinnable: true,
  },
  {
    id: 'handmaids-tale-nolite',
    title: 'Don\'t Let the Bastards Grind You Down',
    era: '1985',
    category: 'literature-film',
    themes: ['resistance', 'oppression', 'hope', 'endurance', 'solidarity'],
    oneLineSummary: 'Offred finds a previous handmaid\'s scratched message in the closet: "Nolite te bastardes carborundorum." A message from one prisoner to the next.',
    spiritualAngle: 'The saints who went before scratched their faith into the walls for you to find. Every testimony, every psalm of lament is one captive encouraging the next one: hold on.',
    source: 'literature',
    specificReference: 'Margaret Atwood, "The Handmaid\'s Tale" (1985), Chapter 29',
    spinnable: true,
  },
  {
    id: 'unbroken-zamperini-forgiveness',
    title: 'A Man Survives the Impossible but Cannot Survive the Peace',
    era: '2010',
    category: 'literature-film',
    themes: ['trauma', 'forgiveness', 'endurance', 'healing', 'PTSD', 'faith'],
    oneLineSummary: 'Louis Zamperini survived a plane crash, 47 days adrift, and years in a POW camp — but was destroyed by peacetime PTSD until a Billy Graham crusade gave him the ability to forgive.',
    spiritualAngle: 'Surviving the trial is not the same as healing from it. Endurance without forgiveness becomes its own prison.',
    source: 'literature',
    specificReference: 'Laura Hillenbrand, "Unbroken" (2010); Zamperini\'s conversion at 1949 Billy Graham crusade',
    spinnable: true,
  },
  {
    id: 'grief-observed-lewis',
    title: 'The Great Apologist Loses His Faith in Grief',
    era: '1961',
    category: 'literature-film',
    themes: ['grief', 'doubt', 'honesty', 'loss', 'faith-crisis', 'lament'],
    oneLineSummary: 'Lewis wrote: "Go to Him when your need is desperate, when all other help is vain, and what do you find? A door slammed in your face, and a sound of bolting and double bolting on the inside."',
    spiritualAngle: 'If Lewis can lose his grip on faith in grief, your doubt in suffering is not failure. The Psalms sound like this. Honest grief is not the enemy of faith — it is faith\'s most raw expression.',
    source: 'literature',
    specificReference: 'C.S. Lewis, "A Grief Observed" (1961), written after the death of Joy Davidman',
    spinnable: true,
  },
  {
    id: 'song-solomon-morrison-flight',
    title: 'Learning to Fly by Learning Where You Came From',
    era: '1977',
    category: 'literature-film',
    themes: ['identity', 'ancestry', 'freedom', 'roots', 'home'],
    oneLineSummary: 'Milkman Dead cannot fly until he traces his ancestry back to Solomon, who "could fly, could just fly on off" — the recovery of his story becomes the recovery of his freedom.',
    spiritualAngle: 'You cannot rise until you know where you come from. Genealogies in Scripture are not boring lists — they are roots. Knowing your origin story is the prerequisite for flight.',
    source: 'literature',
    specificReference: 'Toni Morrison, "Song of Solomon" (1977), National Book Critics Circle Award',
    spinnable: true,
  },
  {
    id: 'story-your-life-chiang',
    title: 'Knowing the Future Does Not Change the Choice',
    era: '1998',
    category: 'literature-film',
    themes: ['foreknowledge', 'free-will', 'suffering', 'love', 'acceptance'],
    oneLineSummary: 'A linguist learns to perceive time non-linearly and knows her daughter will die young — yet she embraces the pregnancy, every moment, and the eventual loss.',
    spiritualAngle: 'Omniscience does not produce detachment — it produces deeper engagement. God knew the cross before Eden and created anyway.',
    source: 'literature',
    specificReference: 'Ted Chiang, "Story of Your Life" (1998), in "Stories of Your Life and Others"',
    spinnable: true,
  },
  {
    id: 'name-of-wind-three-silences',
    title: 'The Patient, Cut-Flower Sound of a Man Waiting to Die',
    era: '2007',
    category: 'literature-film',
    themes: ['silence', 'loss', 'waiting', 'identity', 'patience'],
    oneLineSummary: 'Rothfuss opens with three silences in a bar where a legendary hero hides as a nobody — the third silence belonging to the man himself, waiting.',
    spiritualAngle: 'There is a season where the hero becomes the innkeeper — where your gifts are hidden and your story feels over. The silence between chapters is not failure; it is intermission.',
    source: 'literature',
    specificReference: 'Patrick Rothfuss, "The Name of the Wind" (2007), opening and closing frame',
    spinnable: true,
  },
  {
    id: 'alchemist-treasure-home',
    title: 'The Treasure Was Buried Under the Tree Where You Started',
    era: '1988',
    category: 'literature-film',
    themes: ['journey', 'calling', 'home', 'purpose', 'seeking'],
    oneLineSummary: 'Santiago travels from Spain to Egypt seeking treasure only to discover it was buried under the very tree where his journey began. He needed the journey to recognize what was always there.',
    spiritualAngle: 'You sometimes need to travel far to recognize what was always right in front of you. The purpose of the quest was not the treasure — it was the transformation.',
    source: 'literature',
    specificReference: 'Paulo Coelho, "The Alchemist" (1988)',
    spinnable: true,
  },
  {
    id: 'count-of-monte-cristo-revenge',
    title: 'Revenge Consumed the Man More Than the Injustice Did',
    era: '1844',
    category: 'literature-film',
    themes: ['revenge', 'justice', 'forgiveness', 'obsession', 'freedom'],
    oneLineSummary: 'Edmond Dantes escapes unjust imprisonment and dedicates his life to elaborate revenge — but by the end, the vengeance has consumed him and he realizes that "all human wisdom is contained in Wait and Hope."',
    spiritualAngle: '"Vengeance is mine, says the Lord" is not a prohibition but a mercy: carrying revenge destroys the carrier. Dantes discovered that the prison he built for his enemies became his own cell.',
    source: 'literature',
    specificReference: 'Alexandre Dumas, "The Count of Monte Cristo" (1844), final letter: "Wait and Hope"',
    spinnable: true,
  },
  {
    id: 'wuthering-heights-destructive-love',
    title: 'A Love So Consuming It Destroys Everything It Touches',
    era: '1847',
    category: 'literature-film',
    themes: ['obsession', 'love', 'idolatry', 'destruction', 'possession'],
    oneLineSummary: 'Heathcliff and Catherine\'s love is absolute — "I am Heathcliff" — but because it deifies another human, it destroys both of them and everyone around them across two generations.',
    spiritualAngle: 'Love that makes a human your God becomes the most destructive force in your life. Idolatry does not always look like a golden calf — sometimes it looks like romantic devotion that consumes everything.',
    source: 'literature',
    specificReference: 'Emily Bronte, "Wuthering Heights" (1847), Catherine\'s "I am Heathcliff" declaration',
    spinnable: true,
  },
  {
    id: 'moby-dick-ahab-obsession',
    title: 'Obsession with an Enemy Becomes Your Entire Identity',
    era: '1851',
    category: 'literature-film',
    themes: ['obsession', 'vengeance', 'identity', 'pride', 'self-destruction'],
    oneLineSummary: 'Captain Ahab stakes his ship, his crew, and his life on killing the white whale — and the obsession with what wounded him becomes the only thing he can see. He sinks chasing what he swore he would destroy.',
    spiritualAngle: 'The thing you are determined to destroy can become the thing that defines you. Ahab\'s leg was taken by Moby Dick, but his soul was taken by the pursuit. "Let it go" is a survival instruction.',
    source: 'literature',
    specificReference: 'Herman Melville, "Moby-Dick" (1851), Ahab\'s monologues and the final chase',
    spinnable: true,
  },
  {
    id: 'les-mis-sewers-carrying',
    title: 'Carrying a Stranger Through the Sewers',
    era: '1862',
    category: 'literature-film',
    themes: ['sacrifice', 'burden-bearing', 'service', 'anonymous-love', 'rescue'],
    oneLineSummary: 'Jean Valjean carries the unconscious Marius through the Paris sewers for miles — the most disgusting, suffocating journey imaginable — to save the life of a man he has every reason to resent.',
    spiritualAngle: 'Sometimes love means carrying someone through the worst of it when they cannot carry themselves and do not even know you are there. The deepest service happens in the sewers, not on the stage.',
    source: 'literature',
    specificReference: 'Victor Hugo, "Les Miserables" (1862), Volume 5, Book 3: the sewer journey',
    spinnable: true,
  },
  {
    id: 'jane-eyre-integrity-alone',
    title: 'Walking Away from Love to Keep Your Integrity',
    era: '1847',
    category: 'literature-film',
    themes: ['integrity', 'temptation', 'self-respect', 'conscience', 'cost'],
    oneLineSummary: 'Jane Eyre loves Rochester completely but walks away when she discovers his secret — not because she stops loving him but because staying would require betraying her own conscience.',
    spiritualAngle: 'The hardest moral decisions involve walking away from something good because keeping it would require becoming someone you are not. Integrity is not the absence of desire — it is desire under authority.',
    source: 'literature',
    specificReference: 'Charlotte Bronte, "Jane Eyre" (1847), Chapter 27: Jane\'s departure',
    spinnable: true,
  },

  // ==========================================
  // POETRY — DEEP AND DIVERSE
  // ==========================================
  {
    id: 'oliver-summer-day-grasshopper',
    title: 'What Will You Do With Your One Wild Life?',
    era: '1990',
    category: 'literature-film',
    themes: ['purpose', 'wonder', 'attention', 'calling', 'presence'],
    oneLineSummary: 'Mary Oliver ends "The Summer Day" by asking the reader what they plan to do with their "one wild and precious life" — after spending the whole poem simply paying attention to a grasshopper.',
    spiritualAngle: 'The question is not what you will achieve but what you will attend to. Oliver models a spirituality of attention: the sacred is in the grasshopper, the field, the ordinary afternoon.',
    source: 'poetry',
    specificReference: 'Mary Oliver, "The Summer Day" from "House of Light" (1990)',
    spinnable: true,
  },
  {
    id: 'hopkins-gods-grandeur-broods',
    title: 'The World Is Charged with God\'s Grandeur',
    era: '1877',
    category: 'literature-film',
    themes: ['creation', 'wonder', 'resilience', 'renewal', 'sacred-in-ordinary'],
    oneLineSummary: 'Hopkins writes that despite humanity\'s smearing of the world, "nature is never spent" — because the Holy Ghost "over the bent world broods with warm breast and with ah! bright wings."',
    spiritualAngle: 'No matter how thoroughly humans damage the world, the grandeur persists. Creation is not a past event but an ongoing brooding — God is still incubating life over the wreckage.',
    source: 'poetry',
    specificReference: 'Gerard Manley Hopkins, "God\'s Grandeur" (1877, published 1918)',
    spinnable: true,
  },
  {
    id: 'rilke-live-questions-now',
    title: 'Live the Questions Now',
    era: '1903',
    category: 'literature-film',
    themes: ['doubt', 'patience', 'mystery', 'faith', 'waiting'],
    oneLineSummary: 'Rilke advises: "Be patient toward all that is unsolved in your heart... Live the questions now. Perhaps you will gradually, without noticing it, live along some distant day into the answer."',
    spiritualAngle: 'Faith is not having answers — it is living the questions with enough patience that the answers arrive experientially rather than intellectually.',
    source: 'poetry',
    specificReference: 'Rainer Maria Rilke, "Letters to a Young Poet" (1903), Letter Four',
    spinnable: true,
  },
  {
    id: 'eliot-still-point-turning-world',
    title: 'At the Still Point of the Turning World',
    era: '1936',
    category: 'literature-film',
    themes: ['presence', 'eternity', 'stillness', 'time', 'transcendence'],
    oneLineSummary: 'Eliot describes a still point where past and future are gathered, and the dance exists. "Except for the point, the still point, there would be no dance."',
    spiritualAngle: 'Every spinning life needs a still center. Prayer, Sabbath, contemplation — these are the axis around which everything else turns. Without the still point, the dance collapses.',
    source: 'poetry',
    specificReference: 'T.S. Eliot, "Four Quartets: Burnt Norton" (1936), Part II',
    spinnable: true,
  },
  {
    id: 'eliot-end-of-exploring',
    title: 'The End of Exploring Is Knowing Where You Started',
    era: '1942',
    category: 'literature-film',
    themes: ['journey', 'home', 'wisdom', 'return', 'transformation'],
    oneLineSummary: '"We shall not cease from exploration / And the end of all our exploring / Will be to arrive where we started / And know the place for the first time."',
    spiritualAngle: 'Spiritual growth is a spiral that returns you to the same truths, each time knowing them deeper. You may end up back in Genesis, but you will read it with resurrection eyes.',
    source: 'poetry',
    specificReference: 'T.S. Eliot, "Four Quartets: Little Gidding" (1942), Part V',
    spinnable: true,
  },
  {
    id: 'hughes-harlem-dream-deferred',
    title: 'What Happens to a Dream Deferred?',
    era: '1951',
    category: 'literature-film',
    themes: ['justice', 'calling', 'oppression', 'patience', 'anger'],
    oneLineSummary: 'Hughes asks whether a deferred dream dries up, festers, sags, or explodes — compressing centuries of deferred aspiration into six devastating images.',
    spiritualAngle: 'God\'s promises sometimes feel deferred. The spiritual life must hold both "wait on the Lord" and "how long, O Lord?" The explosion at the end is not sin; it is prophetic rage.',
    source: 'poetry',
    specificReference: 'Langston Hughes, "Harlem" from "Montage of a Dream Deferred" (1951)',
    spinnable: true,
  },
  {
    id: 'berry-peace-wild-things',
    title: 'Resting in the Grace of the World',
    era: '1968',
    category: 'literature-film',
    themes: ['anxiety', 'rest', 'nature', 'peace', 'creation', 'sabbath'],
    oneLineSummary: 'When despair for the world grows, Berry goes to lie down where the wood drake rests in beauty on the water, and feels "the grace of the world."',
    spiritualAngle: '"Consider the birds of the air." Berry\'s poem is a practical discipline: when anxiety overwhelms, go to where creation is at peace and let it tutor your nervous system.',
    source: 'poetry',
    specificReference: 'Wendell Berry, "The Peace of Wild Things" from "Openings" (1968)',
    spinnable: true,
  },
  {
    id: 'rumi-guest-house-emotions',
    title: 'Welcome Every Emotion as a Visitor',
    era: '13th century',
    category: 'literature-film',
    themes: ['emotions', 'acceptance', 'hospitality', 'suffering', 'openness'],
    oneLineSummary: 'Rumi compares the self to a guest house where joy, depression, and meanness arrive as unexpected visitors — and advises welcoming them all, because "each has been sent as a guide from beyond."',
    spiritualAngle: 'The Psalms model Rumi\'s guest house: rage, despair, ecstasy, and confusion are all welcomed into the house of prayer. Every feeling is a visitor with a message.',
    source: 'poetry',
    specificReference: 'Rumi, "The Guest House," translated by Coleman Barks, "The Essential Rumi" (1995)',
    spinnable: true,
  },
  {
    id: 'dickinson-tell-truth-slant',
    title: 'The Truth Must Dazzle Gradually or It Blinds',
    era: '1872',
    category: 'literature-film',
    themes: ['truth', 'parable', 'indirect-communication', 'wisdom', 'teaching'],
    oneLineSummary: 'Dickinson argues truth must be told indirectly because "the Truth\'s superb surprise" would blind us — "the Truth must dazzle gradually / Or every man be blind."',
    spiritualAngle: 'This is why Jesus taught in parables, not propositions. Direct truth is often too bright to receive — it needs the slant of story and metaphor to bypass your defenses.',
    source: 'poetry',
    specificReference: 'Emily Dickinson, "Tell all the truth but tell it slant" (c. 1872), Poem 1263',
    spinnable: true,
  },
  {
    id: 'herbert-love-bade-me-welcome',
    title: 'Love Insisted I Stay Despite My Unworthiness',
    era: '1633',
    category: 'literature-film',
    themes: ['grace', 'unworthiness', 'welcome', 'communion', 'hospitality'],
    oneLineSummary: 'Herbert\'s speaker tries to refuse Love\'s dinner invitation because he is "unkind, ungrateful" — but Love takes his hand and asks "Who made the eyes but I?" until the guest sits and eats.',
    spiritualAngle: 'Every objection about your unworthiness, Love has already answered. The poem is a communion liturgy: you resist, God insists, and eventually you sit down and eat.',
    source: 'poetry',
    specificReference: 'George Herbert, "Love (III)" from "The Temple" (1633)',
    spinnable: true,
  },
  {
    id: 'frost-road-not-taken-misread',
    title: 'Both Roads Were Really About the Same',
    era: '1916',
    category: 'literature-film',
    themes: ['choice', 'self-deception', 'narrative', 'meaning-making'],
    oneLineSummary: 'Frost\'s poem is widely misread as celebrating nonconformity — but it says both roads were "really about the same." The "difference" is a story the speaker will tell later to give a random choice meaning.',
    spiritualAngle: 'We retroactively narrate our lives as purposeful. This is the meaning-making instinct God planted in us. Providence looks clearer in the rearview mirror.',
    source: 'poetry',
    specificReference: 'Robert Frost, "The Road Not Taken" from "Mountain Interval" (1916)',
    spinnable: true,
  },
  {
    id: 'hopkins-wreck-deutschland',
    title: 'A Nun\'s Cry in a Shipwreck Broke Open a Poet\'s Silence',
    era: '1875',
    category: 'literature-film',
    themes: ['suffering', 'faith', 'witness', 'calling', 'crisis'],
    oneLineSummary: 'When five nuns drowned in a shipwreck, one was heard crying "O Christ, come quickly!" Hopkins, moved by her faith in extremis, broke seven years of poetic silence.',
    spiritualAngle: 'Your faithfulness in crisis may be the thing that breaks open someone else\'s calling. The nun did not know a poet was listening.',
    source: 'poetry',
    specificReference: 'Gerard Manley Hopkins, "The Wreck of the Deutschland" (1875-76), inspired by the SS Deutschland disaster',
    spinnable: true,
  },
  {
    id: 'oliver-heavy-box-darkness',
    title: 'A Box Full of Darkness Was Also a Gift',
    era: '2006',
    category: 'literature-film',
    themes: ['grief', 'gift', 'darkness', 'loss', 'transformation'],
    oneLineSummary: '"Someone I loved once gave me / a box full of darkness. / It took me years to understand that this too, was a gift."',
    spiritualAngle: 'The worst thing that happened to you may take years to become visible as gift. "You meant it for evil, but God meant it for good." The box is still being unpacked.',
    source: 'poetry',
    specificReference: 'Mary Oliver, "Heavy" from "Thirst" (2006)',
    spinnable: true,
  },
  {
    id: 'rumi-wound-light-enters',
    title: 'The Wound Is Where the Light Gets In',
    era: '13th century',
    category: 'literature-film',
    themes: ['suffering', 'brokenness', 'healing', 'light', 'transformation'],
    oneLineSummary: '"The wound is the place where the Light enters you" — the places you most want to hide are the openings through which grace arrives.',
    spiritualAngle: 'A vessel without cracks cannot be filled. Your scars are not something to hide but evidence of where God has access. The resurrected Christ kept his wounds.',
    source: 'poetry',
    specificReference: 'Rumi (Jalal al-Din Muhammad Rumi), 13th century; frequently cited from various translations',
    spinnable: true,
  },
  {
    id: 'hafiz-light-holding-you',
    title: 'Light Is Holding You in Ten Thousand Different Ways',
    era: '14th century',
    category: 'literature-film',
    themes: ['creation', 'providence', 'help', 'awareness', 'gratitude'],
    oneLineSummary: 'Hafiz writes that every creature is doing its best to help you, and that light is constantly holding you "ten thousand different ways."',
    spiritualAngle: 'Creation is not backdrop but collaborator. Every living thing is part of a conspiracy of grace. "All creation groans" in solidarity, not indifference.',
    source: 'poetry',
    specificReference: 'Hafiz, "Tired of Speaking Sweetly" from "The Gift" translated by Daniel Ladinsky (1999)',
    spinnable: true,
  },
  {
    id: 'wendell-berry-manifesto-mad-farmer',
    title: 'Practice Resurrection',
    era: '1973',
    category: 'literature-film',
    themes: ['resurrection', 'practice', 'counter-culture', 'daily-life', 'hope'],
    oneLineSummary: 'Berry\'s Mad Farmer Liberation Front manifesto ends with two words: "Practice resurrection." Not believe in it, not wait for it — practice it. Daily. Now.',
    spiritualAngle: 'Resurrection is not just an eschatological hope but a daily discipline: choosing life over cynicism, forgiveness over grudge, planting over consuming. Practice resurrection.',
    source: 'poetry',
    specificReference: 'Wendell Berry, "Manifesto: The Mad Farmer Liberation Front" from "The Country of Marriage" (1973)',
    spinnable: true,
  },
  {
    id: 'celan-death-fugue',
    title: 'Black Milk of Daybreak — Poetry After the Holocaust',
    era: '1948',
    category: 'literature-film',
    themes: ['suffering', 'lament', 'horror', 'witness', 'language-failing'],
    oneLineSummary: 'Celan, a Holocaust survivor, wrote "Death Fugue" in a language where words kept collapsing under the weight of what happened — proving that some experiences can only be approached through broken poetry.',
    spiritualAngle: 'Adorno said "To write poetry after Auschwitz is barbaric." Celan proved it is also necessary. When words fail, we do not stop speaking — we speak in fragments, like the Psalms of Lament.',
    source: 'poetry',
    specificReference: 'Paul Celan, "Death Fugue" (Todesfuge) (1948); "black milk of daybreak we drink it at evening"',
    spinnable: true,
  },
  {
    id: 'maya-angelou-still-i-rise',
    title: 'You May Kill Me with Your Hatefulness, But Still I Rise',
    era: '1978',
    category: 'literature-film',
    themes: ['resilience', 'dignity', 'oppression', 'defiance', 'hope'],
    oneLineSummary: 'Angelou\'s poem catalogues every form of diminishment — shame, lies, hatred, violence — and answers each with the same refrain: "Still I rise." Not "I might" or "I hope to." I rise.',
    spiritualAngle: 'Resurrection is the ultimate "Still I Rise." Every force of death, oppression, and despair says "Stay down," and the Easter answer is always the same: I rise.',
    source: 'poetry',
    specificReference: 'Maya Angelou, "Still I Rise" from "And Still I Rise" (1978)',
    spinnable: true,
  },
  {
    id: 'whitman-i-contain-multitudes',
    title: 'Do I Contradict Myself? Very Well, I Am Large',
    era: '1855',
    category: 'literature-film',
    themes: ['complexity', 'identity', 'wholeness', 'acceptance', 'humanity'],
    oneLineSummary: 'Whitman responds to accusations of self-contradiction: "Do I contradict myself? / Very well then I contradict myself, / (I am large, I contain multitudes.)"',
    spiritualAngle: 'You do not have to resolve all your contradictions to be whole. God contains mystery, paradox, and apparent contradiction (justice and mercy, sovereignty and freedom). Being large enough to hold tension is divine capacity.',
    source: 'poetry',
    specificReference: 'Walt Whitman, "Song of Myself" (1855), Section 51, in "Leaves of Grass"',
    spinnable: true,
  },

  // ==========================================
  // FILM — DEEPER CUTS
  // ==========================================
  {
    id: 'silence-scorsese-stepping',
    title: 'God Finally Speaks Through an Act of Betrayal',
    era: '2016',
    category: 'literature-film',
    themes: ['doubt', 'silence-of-God', 'sacrifice', 'suffering', 'paradox'],
    oneLineSummary: 'Scorsese\'s adaptation lingers on Rodrigues stepping on the fumie — and the audience hears Christ say "Step. I understand. I was silent because I suffered beside you."',
    spiritualAngle: 'The silence of God is not absence but solidarity. God was silent because God was hanging on the same cross, in the same darkness.',
    source: 'film',
    specificReference: 'Martin Scorsese, "Silence" (2016), the fumie scene; adapted from Endo\'s novel',
    spinnable: true,
  },
  {
    id: 'of-gods-and-men-monks',
    title: 'Monks Vote Individually to Stay and Die',
    era: '2010',
    category: 'literature-film',
    themes: ['sacrifice', 'vocation', 'courage', 'community', 'faithfulness'],
    oneLineSummary: 'The Tibhirine monks vote individually to remain in Algeria despite death threats — their last supper set to Swan Lake shows faces accepting death with tears and peace simultaneously.',
    spiritualAngle: 'The Last Supper scene is the closest cinema has come to the original: ordinary people choosing not to run.',
    source: 'film',
    specificReference: 'Xavier Beauvois, "Of Gods and Men" (2010), Grand Prix at Cannes; based on the 1996 Tibhirine assassination',
    spinnable: true,
  },
  {
    id: 'man-all-seasons-water',
    title: 'Integrity Is Water in Your Hands — Open Your Fingers and It\'s Gone',
    era: '1966',
    category: 'literature-film',
    themes: ['integrity', 'conscience', 'cost', 'truth', 'courage'],
    oneLineSummary: 'Thomas More tells his daughter that when a man takes an oath, he holds his self in his hands "like water" — and if he opens his fingers, he will never find himself again.',
    spiritualAngle: 'There is a line you cannot cross without losing yourself. More lost his head and kept his soul.',
    source: 'film',
    specificReference: 'Fred Zinnemann, "A Man for All Seasons" (1966), Academy Award for Best Picture',
    spinnable: true,
  },
  {
    id: 'seventh-seal-chess-death',
    title: 'Playing Chess with Death While Asking Unanswered Questions',
    era: '1957',
    category: 'literature-film',
    themes: ['death', 'doubt', 'questioning', 'meaning', 'faith-crisis'],
    oneLineSummary: 'A medieval knight plays chess with Death — not to win but to buy time to keep asking whether God exists, even though Death never answers.',
    spiritualAngle: 'Sometimes faith is buying time to keep asking the question. The knight does not get answers — he gets one more day to look for them.',
    source: 'film',
    specificReference: 'Ingmar Bergman, "The Seventh Seal" (1957)',
    spinnable: true,
  },
  {
    id: 'wings-desire-angel-falls',
    title: 'An Angel Chooses to Fall in Order to Feel',
    era: '1987',
    category: 'literature-film',
    themes: ['incarnation', 'embodiment', 'choice', 'sensation', 'limitation'],
    oneLineSummary: 'An angel who has observed human life for eternity chooses to become mortal — trading infinite perspective for the ability to feel cold, taste coffee, and bleed.',
    spiritualAngle: '"The Word became flesh" was not a demotion — it was a fall chosen for the sake of touch.',
    source: 'film',
    specificReference: 'Wim Wenders, "Wings of Desire" (1987)',
    spinnable: true,
  },
  {
    id: 'children-of-men-baby-stops-war',
    title: 'A Baby\'s Cry Stops a War',
    era: '2006',
    category: 'literature-film',
    themes: ['hope', 'birth', 'new-life', 'war', 'wonder'],
    oneLineSummary: 'In a world where no child has been born in 18 years, soldiers stop shooting when they hear a baby crying — stunned, weeping — before the fighting resumes.',
    spiritualAngle: 'God\'s invasion of the world comes not as an army but as an infant\'s cry. New life stops everything, if only for a moment.',
    source: 'film',
    specificReference: 'Alfonso Cuaron, "Children of Men" (2006), the Bexhill battle scene',
    spinnable: true,
  },
  {
    id: 'magnolia-frogs-rain',
    title: 'Sometimes It Rains Frogs and Nobody Can Explain It',
    era: '1999',
    category: 'literature-film',
    themes: ['mystery', 'chaos', 'providence', 'coincidence', 'beyond-understanding'],
    oneLineSummary: 'At the climax, frogs rain from the sky — connecting every character\'s story in an inexplicable event. Strange things happen, patterns exist, and sometimes the explanation exceeds our categories.',
    spiritualAngle: 'Exodus 8. The frog rain is a biblical plague in the San Fernando Valley — a reminder that reality is stranger than rationalism permits.',
    source: 'film',
    specificReference: 'Paul Thomas Anderson, "Magnolia" (1999), the frog sequence; Exodus 8:2 reference',
    spinnable: true,
  },
  {
    id: 'places-in-heart-communion',
    title: 'The Dead and the Living Take Communion Together',
    era: '1984',
    category: 'literature-film',
    themes: ['communion', 'reconciliation', 'forgiveness', 'community', 'resurrection'],
    oneLineSummary: 'The film ends with every character — including those who died, including the murderer and his victim — passing the bread and cup to each other in the same pew.',
    spiritualAngle: 'The final communion dissolves every boundary: living and dead, victim and murderer. This is what the Eucharist claims: at this table, every division is healed.',
    source: 'film',
    specificReference: 'Robert Benton, "Places in the Heart" (1984), final communion sequence',
    spinnable: true,
  },
  {
    id: 'about-time-ordinary-day-secret',
    title: 'The Secret Is Living Each Ordinary Day As If You Chose It',
    era: '2013',
    category: 'literature-film',
    themes: ['presence', 'attention', 'gratitude', 'time', 'ordinary-life'],
    oneLineSummary: 'Tim can travel back in time — and eventually stops, instead just living each day fully for the first time. The superpower is not time travel but paying attention.',
    spiritualAngle: '"This is the day the Lord has made." Tim\'s conclusion is the psalmist\'s: the superpower is not escaping the ordinary but inhabiting it.',
    source: 'film',
    specificReference: 'Richard Curtis, "About Time" (2013), Tim\'s final monologue',
    spinnable: true,
  },
  {
    id: 'mission-oboe-jungle',
    title: 'A Priest Plays an Oboe and Weapons Drop',
    era: '1986',
    category: 'literature-film',
    themes: ['beauty', 'peace', 'disarmament', 'art', 'trust'],
    oneLineSummary: 'Father Gabriel climbs above the falls into hostile territory and plays his oboe. Warriors approach to kill him, listen, and lower their weapons. Beauty does what force never could.',
    spiritualAngle: 'David played harp for Saul\'s torment. Jehoshaphat sent singers before the army. The first missionary tool is not a sermon — it is a song.',
    source: 'film',
    specificReference: 'Roland Joffe, "The Mission" (1986), Palme d\'Or; oboe scene; Ennio Morricone score',
    spinnable: true,
  },
  {
    id: 'three-billboards-rage-grace',
    title: 'When Righteous Anger Meets the Possibility of Grace',
    era: '2017',
    category: 'literature-film',
    themes: ['anger', 'grief', 'justice', 'forgiveness', 'grace'],
    oneLineSummary: 'Mildred Hayes puts up three billboards demanding justice for her murdered daughter — and the film asks whether righteous anger can coexist with, or transform into, something like grace.',
    spiritualAngle: 'The imprecatory Psalms are three billboards outside Jerusalem: raw rage directed at God. The question is not whether the anger is valid but whether it can grow.',
    source: 'film',
    specificReference: 'Martin McDonagh, "Three Billboards Outside Ebbing, Missouri" (2017)',
    spinnable: true,
  },
  {
    id: 'amelie-anonymous-kindness',
    title: 'A Woman Who Anonymously Repairs Other People\'s Lives',
    era: '2001',
    category: 'literature-film',
    themes: ['kindness', 'anonymity', 'service', 'connection', 'avoidance'],
    oneLineSummary: 'Amelie orchestrates small acts of kindness for strangers while struggling to connect herself — a parable about secret kindness as both gift and avoidance.',
    spiritualAngle: '"Do not let your left hand know what your right hand is doing." But also: helping others can become a way to avoid being helped yourself.',
    source: 'film',
    specificReference: 'Jean-Pierre Jeunet, "Amelie" (Le Fabuleux Destin d\'Amelie Poulain) (2001)',
    spinnable: true,
  },
  {
    id: 'moonlight-armor-recognition',
    title: 'The Armor That Kept You Safe Now Keeps You Alone',
    era: '2016',
    category: 'literature-film',
    themes: ['identity', 'masks', 'vulnerability', 'formation', 'authenticity'],
    oneLineSummary: 'Chiron builds thicker armor through three life stages until his oldest friend barely recognizes him — every protective layer that kept him safe also kept him isolated.',
    spiritualAngle: 'Remove the armor to receive the love. The self you built to survive can become a prison that prevents you from being known.',
    source: 'film',
    specificReference: 'Barry Jenkins, "Moonlight" (2016), Academy Award for Best Picture; final diner scene',
    spinnable: true,
  },
  {
    id: 'grave-fireflies-devotion',
    title: 'Love Is Not Always Enough to Save the One You Love',
    era: '1988',
    category: 'literature-film',
    themes: ['war', 'innocence', 'loss', 'helplessness', 'love'],
    oneLineSummary: 'A teenager tries to care for his little sister in wartime Japan — despite total devotion, she starves. You can do everything right and still lose.',
    spiritualAngle: 'Love is not always sufficient protection. This is the hardest truth: the value was in the faithfulness, not the outcome.',
    source: 'film',
    specificReference: 'Isao Takahata, "Grave of the Fireflies" (1988), Studio Ghibli',
    spinnable: true,
  },
  {
    id: 'spirited-away-name-stealing',
    title: 'Losing Your Name and Fighting to Remember Who You Are',
    era: '2001',
    category: 'literature-film',
    themes: ['identity', 'naming', 'slavery', 'freedom', 'memory'],
    oneLineSummary: 'Yubaba steals Chihiro\'s name — and Haku warns that if she forgets her true name, she can never go home. The entire film is recovering your identity in a world that wants to erase it.',
    spiritualAngle: 'Babylon renamed Daniel. The world will always try to rename you. Remembering who God says you are is the only way home.',
    source: 'film',
    specificReference: 'Hayao Miyazaki, "Spirited Away" (2001), Academy Award for Best Animated Feature',
    spinnable: true,
  },

  // ==========================================
  // TV / MODERN MEDIA — DEEPER CUTS
  // ==========================================
  {
    id: 'bear-every-second-sacrament',
    title: 'The Sacrament of Cooking Under Impossible Pressure',
    era: '2022',
    category: 'literature-film',
    themes: ['vocation', 'anxiety', 'service', 'excellence', 'sacrifice'],
    oneLineSummary: 'Carmy returns from fine dining to run his dead brother\'s sandwich shop — the show treats cooking as liturgy: repetitive, exhausting, sacred work done for others who may not appreciate it.',
    spiritualAngle: 'Ministry looks like this: inherited from someone who burned out, performed under impossible pressure, driven by love for people who may never thank you.',
    source: 'tv',
    specificReference: 'Christopher Storer, "The Bear" (2022-present), FX/Hulu',
    spinnable: true,
  },
  {
    id: 'midnight-gospel-mother-death',
    title: 'A Son Interviews His Dying Mother About Death',
    era: '2020',
    category: 'literature-film',
    themes: ['death', 'grief', 'love', 'acceptance', 'presence'],
    oneLineSummary: 'The final episode uses real audio of Duncan Trussell interviewing his mother weeks before her cancer death — animated as a cosmic journey where mother and son face the void with love and humor.',
    spiritualAngle: '"I will be with you" is what every dying parent promises and what every orphaned child needs to believe.',
    source: 'tv',
    specificReference: 'Pendleton Ward & Duncan Trussell, "The Midnight Gospel" (2020), Episode 8: "Mouse of Silver," Netflix',
    spinnable: true,
  },
  {
    id: 'last-of-us-joel-ellie',
    title: 'Choosing One Child Over the Entire Species',
    era: '2023',
    category: 'literature-film',
    themes: ['sacrifice', 'love', 'morality', 'parenthood', 'theodicy'],
    oneLineSummary: 'Joel murders the doctors who would sacrifice Ellie to create a vaccine — choosing one child over humanity. The audience debates whether this is monstrous selfishness or the purest love.',
    spiritualAngle: 'Abraham was asked to sacrifice his son and nearly did. Joel was asked and refused. The parable asks: is the love of one person ever wrong?',
    source: 'tv',
    specificReference: 'Craig Mazin & Neil Druckmann, "The Last of Us" (2023), HBO, Episode 9',
    spinnable: true,
  },
  {
    id: 'leftovers-unanswered-departure',
    title: 'How Do You Go On When the Answer Never Comes?',
    era: '2014',
    category: 'literature-film',
    themes: ['loss', 'grief', 'ambiguity', 'faith', 'unanswered-questions'],
    oneLineSummary: '2% of the world vanishes without explanation — and the show is not about where they went but about how the living survive without answers.',
    spiritualAngle: 'Sometimes the answer never comes. The spiritual life must accommodate permanent mystery. The Leftovers is Job without the epilogue.',
    source: 'tv',
    specificReference: 'Damon Lindelof, "The Leftovers" (2014-2017), HBO',
    spinnable: true,
  },
  {
    id: 'fleabag-hot-priest-love',
    title: 'Falling in Love with Someone Who Chose Something Bigger',
    era: '2019',
    category: 'literature-film',
    themes: ['love', 'sacrifice', 'calling', 'letting-go', 'vocation'],
    oneLineSummary: 'Fleabag and the Priest fall in love — and he chooses God over her. The bus stop scene where she says "I love you" and he says "It\'ll pass" is the most devastating depiction of vocational sacrifice on television.',
    spiritualAngle: 'Sometimes love is real and the other person still belongs somewhere else. The priest\'s choice is not a rejection of Fleabag but a painful fidelity to a prior claim. Some loves do not get to be lived.',
    source: 'tv',
    specificReference: 'Phoebe Waller-Bridge, "Fleabag" Season 2, Episode 6 (2019), the bus stop goodbye',
    spinnable: true,
  },
  {
    id: 'succession-who-actually-loves',
    title: 'A Family Where Everyone Competes and Nobody Loves',
    era: '2023',
    category: 'literature-film',
    themes: ['family', 'love', 'power', 'inheritance', 'emptiness'],
    oneLineSummary: 'The Roy children spend four seasons fighting for their father\'s approval and empire — and the final scene reveals they never wanted the company; they wanted their father\'s love, which he never had to give.',
    spiritualAngle: 'The prodigal son\'s elder brother, multiplied by three. Every corporate war in the Roy family is actually a prayer: "Father, do you love me?" Power pursued as a substitute for affection always ends in emptiness.',
    source: 'tv',
    specificReference: 'Jesse Armstrong, "Succession" (2018-2023), HBO; series finale',
    spinnable: true,
  },
  {
    id: 'mr-rogers-silence-television',
    title: 'Fred Rogers Was Silent on Television for Sixty Seconds',
    era: '1997',
    category: 'literature-film',
    themes: ['silence', 'presence', 'attention', 'courage', 'counter-culture'],
    oneLineSummary: 'At the Emmy Lifetime Achievement Award, Rogers asked the audience to take ten seconds to think of the people who helped them. The room fell completely silent. On national television. For what felt like forever.',
    spiritualAngle: 'In a culture that fears silence, Rogers created a sacred moment by simply refusing to fill the space. The most countercultural act on television was stopping to remember who helped you get here.',
    source: 'tv',
    specificReference: 'Fred Rogers, Emmy Lifetime Achievement Award acceptance (1997); Daytime Emmy Awards ceremony',
    spinnable: true,
  },

  // ==========================================
  // SPIRITUAL / THEOLOGICAL LITERATURE
  // ==========================================
  {
    id: 'dark-night-john-cross',
    title: 'The Dark Night Is God Trusting You with Advanced Curriculum',
    era: '1578',
    category: 'literature-film',
    themes: ['darkness', 'spiritual-growth', 'silence-of-God', 'purification', 'trust'],
    oneLineSummary: 'John of the Cross wrote from prison that the soul must pass through a "dark night" — the withdrawal of all spiritual consolation — not as punishment but as the way God weans you from spiritual milk.',
    spiritualAngle: 'When God feels absent, it may be the most advanced stage of development: God trusting you enough to withdraw the training wheels. The dark night is graduation, not abandonment.',
    source: 'poetry',
    specificReference: 'St. John of the Cross, "Dark Night of the Soul" (c. 1578-1579)',
    spinnable: true,
  },
  {
    id: 'julian-norwich-all-shall-be-well',
    title: 'All Shall Be Well',
    era: '1395',
    category: 'literature-film',
    themes: ['hope', 'assurance', 'trust', 'suffering', 'providence'],
    oneLineSummary: 'Julian, after visions during a near-death illness, wrote that Christ told her "All shall be well, and all shall be well, and all manner of thing shall be well."',
    spiritualAngle: 'This is not denial of suffering but an eschatological promise: the ending is good. Julian\'s optimism is not naive — it was born in a plague year.',
    source: 'literature',
    specificReference: 'Julian of Norwich, "Revelations of Divine Love" (c. 1395), the first known book by a woman in English',
    spinnable: true,
  },
  {
    id: 'augustine-restless-hearts',
    title: 'Our Hearts Are Restless Until They Rest in God',
    era: '397',
    category: 'literature-film',
    themes: ['longing', 'desire', 'restlessness', 'God', 'searching', 'home'],
    oneLineSummary: 'After decades pursuing pleasure, philosophy, and ambition, Augustine concluded: "You have made us for yourself, O Lord, and our hearts are restless until they rest in you."',
    spiritualAngle: 'Every addiction, every compulsive pursuit is evidence of the restless heart. The ache is not the problem — it is the homing signal.',
    source: 'literature',
    specificReference: 'Augustine of Hippo, "Confessions" (397 AD), Book 1, Chapter 1',
    spinnable: true,
  },
  {
    id: 'pascal-infinite-abyss',
    title: 'There Is a God-Shaped Hole in Every Human Heart',
    era: '1670',
    category: 'literature-film',
    themes: ['longing', 'emptiness', 'searching', 'God', 'desire'],
    oneLineSummary: 'Pascal argued that all human restlessness stems from an "infinite abyss" that can only be filled by God — we try relationships, success, and pleasure, but the shape is wrong.',
    spiritualAngle: 'The exhaustion of every other pursuit is the negative proof that points toward the One Thing that fits.',
    source: 'literature',
    specificReference: 'Blaise Pascal, "Pensees" (1670, posthumous), Fragment 425',
    spinnable: true,
  },
  {
    id: 'kierkegaard-leap-beyond-proof',
    title: 'Faith Begins Where Proof Ends',
    era: '1843',
    category: 'literature-film',
    themes: ['faith', 'doubt', 'reason', 'risk', 'commitment'],
    oneLineSummary: 'Kierkegaard argued that faith cannot be reached by reason alone — at some point, you must make a qualitative leap beyond evidence.',
    spiritualAngle: 'You will never have enough evidence to make faith safe. The leap is not irrational — it is trans-rational. Faith starts where certainty stops.',
    source: 'literature',
    specificReference: 'Soren Kierkegaard, "Fear and Trembling" (1843)',
    spinnable: true,
  },
  {
    id: 'bonhoeffer-cheap-vs-costly-grace',
    title: 'Cheap Grace Is the Deadly Enemy of the Church',
    era: '1937',
    category: 'literature-film',
    themes: ['grace', 'cost', 'discipleship', 'commitment', 'sacrifice'],
    oneLineSummary: 'Bonhoeffer distinguished cheap grace (forgiveness without repentance) from costly grace (the pearl of great price). He wrote this from Nazi Germany, where it would cost his life.',
    spiritualAngle: 'The man who wrote about costly grace paid for it on a gallows two weeks before the war ended. The cost of following Jesus is everything — and it is worth everything.',
    source: 'literature',
    specificReference: 'Dietrich Bonhoeffer, "The Cost of Discipleship" (1937); executed April 9, 1945',
    spinnable: true,
  },
  {
    id: 'buechner-deep-gladness-hunger',
    title: 'Your Deep Gladness Meets the World\'s Deep Hunger',
    era: '1973',
    category: 'literature-film',
    themes: ['calling', 'vocation', 'purpose', 'joy', 'service'],
    oneLineSummary: 'Buechner defined vocation as "the place where your deep gladness meets the world\'s deep hunger."',
    spiritualAngle: 'God does not call you to misery. The thing that makes you most alive and the thing the world most needs are the same thing.',
    source: 'literature',
    specificReference: 'Frederick Buechner, "Wishful Thinking: A Theological ABC" (1973)',
    spinnable: true,
  },
  {
    id: 'merton-false-self-true-self',
    title: 'Most People Live from a Self That Is Not Real',
    era: '1961',
    category: 'literature-film',
    themes: ['identity', 'authenticity', 'masks', 'true-self', 'contemplation'],
    oneLineSummary: 'Merton argued that most people live from a "false self" constructed by ego, culture, and fear — contemplation dismantles the false self to reveal the true self hidden in God.',
    spiritualAngle: 'The spiritual life is an excavation: removing what is false to reveal what is true. You are not who you pretend to be — and the real you is both more humble and more glorious.',
    source: 'literature',
    specificReference: 'Thomas Merton, "New Seeds of Contemplation" (1961), Chapter 5',
    spinnable: true,
  },
  {
    id: 'lewis-bearing-with-people',
    title: 'Holiness Is Persistence in Community',
    era: '1960',
    category: 'literature-film',
    themes: ['patience', 'community', 'irritation', 'love', 'perseverance'],
    oneLineSummary: 'Lewis wrote that the great challenge of Christian life is not resisting dramatic evil but bearing with the sheer irritation of actual people day after day.',
    spiritualAngle: 'Most spiritual growth happens not in mountaintop experiences but in the tedious, unglamorous work of being patient with the same people.',
    source: 'literature',
    specificReference: 'C.S. Lewis, "The Four Loves" (1960); on the difficulty of living with actual Christians',
    spinnable: true,
  },

  // ==========================================
  // MYTH / FABLE / ORAL TRADITION
  // ==========================================
  {
    id: 'orpheus-looked-back',
    title: 'He Lost Everything Because He Looked Back',
    era: 'ancient Greek',
    category: 'literature-film',
    themes: ['trust', 'doubt', 'patience', 'loss', 'obedience'],
    oneLineSummary: 'Orpheus descends to the underworld and is given his wife back with one condition: do not look back. He cannot bear the uncertainty, looks, and loses her forever.',
    spiritualAngle: '"No one who puts a hand to the plow and looks back is fit for the kingdom." The rescue requires trust without verification.',
    source: 'literature',
    specificReference: 'Ovid, "Metamorphoses" Book X; Virgil, "Georgics" Book IV',
    spinnable: true,
  },
  {
    id: 'icarus-middle-way',
    title: 'Daedalus Gave Two Warnings, Not One',
    era: 'ancient Greek',
    category: 'literature-film',
    themes: ['pride', 'hubris', 'boundaries', 'wisdom', 'balance'],
    oneLineSummary: 'Daedalus warned Icarus not to fly too high (sun melts wax) or too low (sea soaks feathers) — but we only remember the first. Both extremes kill.',
    spiritualAngle: 'Faith is the middle path: not so high that you think you are God, not so low that you forget you can fly.',
    source: 'literature',
    specificReference: 'Ovid, "Metamorphoses" Book VIII; the myth of Daedalus and Icarus',
    spinnable: true,
  },
  {
    id: 'sisyphus-imagine-happy',
    title: 'We Must Imagine Sisyphus Happy',
    era: '1942',
    category: 'literature-film',
    themes: ['meaning', 'absurdity', 'perseverance', 'daily-work'],
    oneLineSummary: 'Camus declares we "must imagine Sisyphus happy" — the man condemned to push a boulder uphill forever finds meaning not in the destination but in the struggle.',
    spiritualAngle: '"Sufficient for each day is its own trouble" does not promise arrival, only faithfulness. The daily boulder is the place where character forms.',
    source: 'literature',
    specificReference: 'Albert Camus, "The Myth of Sisyphus" (1942)',
    spinnable: true,
  },
  {
    id: 'platos-cave-shadows',
    title: 'The Prisoners Mistake Shadows for Reality',
    era: '380 BC',
    category: 'literature-film',
    themes: ['perception', 'truth', 'awakening', 'liberation'],
    oneLineSummary: 'Prisoners chained in a cave see only shadows and believe them to be reality. When one escapes and sees the sun, he returns — and they want to kill him.',
    spiritualAngle: '"He came to his own, and his own did not receive him." Truth-tellers are always initially unwelcome.',
    source: 'literature',
    specificReference: 'Plato, "The Republic" (c. 380 BC), Book VII: Allegory of the Cave',
    spinnable: true,
  },
  {
    id: 'two-wolves-which-you-feed',
    title: 'The Wolf You Feed Is the Wolf That Wins',
    era: 'attributed Cherokee tradition',
    category: 'literature-film',
    themes: ['choices', 'formation', 'attention', 'character'],
    oneLineSummary: 'A grandfather tells his grandson two wolves fight inside everyone — anger or love. Which wins? "The one you feed."',
    spiritualAngle: '"Whatever is true, whatever is noble... think about such things." You are shaped by what you feed your attention.',
    source: 'literature',
    specificReference: 'Attributed to Cherokee oral tradition; widely recounted',
    spinnable: true,
  },
  {
    id: 'chinese-farmer-maybe-parable',
    title: 'The Farmer Who Says "Maybe" to Every Fortune',
    era: 'Taoist oral tradition',
    category: 'literature-film',
    themes: ['perspective', 'patience', 'judgment', 'providence', 'trust'],
    oneLineSummary: 'A farmer\'s horse runs away (bad luck), returns with wild horses (good luck), his son breaks his leg (bad luck), is spared from war (good luck) — the farmer says only "maybe."',
    spiritualAngle: 'Romans 8:28 in parable form. You cannot judge any event in isolation because you cannot see the whole chain.',
    source: 'literature',
    specificReference: 'Traditional Taoist parable; Alan Watts frequently retold this story',
    spinnable: true,
  },
  {
    id: 'blind-men-elephant-parts',
    title: 'Six Blind Men Each Touch a Different Part of God',
    era: 'ancient Indian',
    category: 'literature-film',
    themes: ['perspective', 'humility', 'truth', 'partiality', 'community'],
    oneLineSummary: 'Six blind men each touch a different part of an elephant and declare it a snake, a spear, a fan, a tree, a wall, or a rope. Each is right and all are wrong.',
    spiritualAngle: 'Your theology touches a real part of God but not the whole. Denominational arguments are often blind men fighting about the elephant\'s shape.',
    source: 'literature',
    specificReference: 'Jain, Buddhist, and Hindu traditions; John Godfrey Saxe poem version (1872)',
    spinnable: true,
  },
  {
    id: 'kintsugi-gold-cracks',
    title: 'The Broken Bowl Repaired with Gold',
    era: '15th century',
    category: 'literature-film',
    themes: ['brokenness', 'beauty', 'repair', 'redemption', 'scars'],
    oneLineSummary: 'Kintsugi repairs broken pottery with gold-infused lacquer — making the cracks visible and beautiful. The repaired object is more valuable than the original.',
    spiritualAngle: 'God\'s repair work does not hide the breaks — it highlights them in gold. The resurrected Christ kept his wounds.',
    source: 'literature',
    specificReference: 'Japanese kintsugi tradition, 15th century; wabi-sabi aesthetics',
    spinnable: true,
  },
  {
    id: 'prodigal-elder-brother-real-lost',
    title: 'The Older Brother Is the One Still Lost',
    era: '1st century',
    category: 'literature-film',
    themes: ['resentment', 'religion', 'grace', 'self-righteousness'],
    oneLineSummary: 'The parable\'s devastating twist is the older brother who obeyed every rule and is furious that grace was free. He is the one left outside the party.',
    spiritualAngle: 'Two ways to be lost: breaking all the rules or keeping all the rules to earn what can only be given. The second is harder to diagnose.',
    source: 'literature',
    specificReference: 'Luke 15:11-32; Tim Keller, "The Prodigal God" (2008); Henri Nouwen, "The Return of the Prodigal Son" (1992)',
    spinnable: true,
  },

  // ==========================================
  // ADDITIONAL DIVERSE ENTRIES
  // ==========================================
  {
    id: 'brothers-grimm-stones-not-bread',
    title: 'The Permanent Trail Saves, the Convenient One Fails',
    era: '1812',
    category: 'literature-film',
    themes: ['guidance', 'impermanence', 'trust', 'provision'],
    oneLineSummary: 'Hansel\'s first escape uses white stones that gleam in moonlight. His second attempt uses breadcrumbs, which birds eat. The impermanent trail fails; the solid one saves.',
    spiritualAngle: 'Build your life on what endures. Breadcrumb faith — feelings, trends — gets consumed. Stone faith — Scripture, covenant, community — holds in the dark.',
    source: 'literature',
    specificReference: 'Brothers Grimm, "Hansel and Gretel" (1812)',
    spinnable: true,
  },
  {
    id: 'hunchback-sanctuary',
    title: 'The Church as the Only Place the Outcast Is Safe',
    era: '1831',
    category: 'literature-film',
    themes: ['sanctuary', 'outcast', 'belonging', 'church', 'hypocrisy'],
    oneLineSummary: 'Quasimodo finds safety only inside Notre-Dame — while Frollo, the archdeacon, represents the religious authority that oppresses him. The building does what its leaders fail to do.',
    spiritualAngle: 'Hugo\'s critique is not anti-faith but anti-hypocrisy: the church should be sanctuary for the outcast.',
    source: 'literature',
    specificReference: 'Victor Hugo, "The Hunchback of Notre-Dame" (1831)',
    spinnable: true,
  },
  {
    id: 'frankenstein-abandoned-creation',
    title: 'A Creator Who Abandons What He Made',
    era: '1818',
    category: 'literature-film',
    themes: ['creation', 'abandonment', 'responsibility', 'fatherhood', 'rejection'],
    oneLineSummary: 'Victor Frankenstein creates a being and immediately abandons it in horror. The creature\'s violence stems not from its nature but from being rejected by its creator — it was not born monstrous, it was made so by abandonment.',
    spiritualAngle: 'The counter-image to God: a creator who recoils from what he made. The creature\'s first question is every orphan\'s question: "Why did you make me if you were going to leave?"',
    source: 'literature',
    specificReference: 'Mary Shelley, "Frankenstein; or, The Modern Prometheus" (1818)',
    spinnable: true,
  },
  {
    id: 'dostoevsky-underground-man',
    title: 'I Am a Sick Man — The First Anti-Hero Confesses Everything',
    era: '1864',
    category: 'literature-film',
    themes: ['self-awareness', 'paralysis', 'confession', 'pride', 'isolation'],
    oneLineSummary: 'The Underground Man is painfully self-aware but cannot act — his intelligence becomes a prison. He sees through everything, including himself, and the clarity destroys rather than saves him.',
    spiritualAngle: 'Self-knowledge without grace is torture. The Underground Man has diagnosis without remedy. This is why confession must be directed toward a healer, not just spoken into the void.',
    source: 'literature',
    specificReference: 'Fyodor Dostoevsky, "Notes from Underground" (1864), Part 1: "Underground"',
    spinnable: true,
  },
  {
    id: 'old-man-and-sea-endurance',
    title: 'A Man Can Be Destroyed But Not Defeated',
    era: '1952',
    category: 'literature-film',
    themes: ['endurance', 'dignity', 'loss', 'perseverance', 'strength'],
    oneLineSummary: 'Santiago catches the greatest fish of his life — and sharks eat it on the way home. He returns with nothing but a skeleton. He was not defeated; he was destroyed, which is different.',
    spiritualAngle: 'Sometimes faithfulness looks like returning with a skeleton — the visible evidence consumed, but the integrity of the effort intact. "A man can be destroyed but not defeated" is the theology of Holy Saturday.',
    source: 'literature',
    specificReference: 'Ernest Hemingway, "The Old Man and the Sea" (1952), Nobel Prize in Literature (1954)',
    spinnable: true,
  },
  {
    id: 'oranges-not-only-fruit',
    title: 'Leaving the Faith That Raised You Without Leaving God',
    era: '1985',
    category: 'literature-film',
    themes: ['deconstruction', 'identity', 'church-hurt', 'authenticity', 'faith-journey'],
    oneLineSummary: 'Jeanette is raised in an aggressively religious household and must leave — but the novel shows that leaving a toxic expression of faith is not the same as leaving faith itself.',
    spiritualAngle: 'Many people leave church and think they left God. Winterson shows the difference: the God who was used as a weapon against you is not God. Deconstruction can be a deeper form of faithfulness.',
    source: 'literature',
    specificReference: 'Jeanette Winterson, "Oranges Are Not the Only Fruit" (1985), Whitbread Prize',
    spinnable: true,
  },
  {
    id: 'remains-of-day-unlived-life',
    title: 'A Life Spent in Perfect Service That Was Never Actually Lived',
    era: '1989',
    category: 'literature-film',
    themes: ['duty', 'regret', 'suppression', 'love', 'waste'],
    oneLineSummary: 'Stevens, a butler, devoted his life to perfect service — suppressing every emotion, rejecting the woman who loved him, serving a master who turned out to be a Nazi sympathizer. His dignity cost him his life.',
    spiritualAngle: 'Duty without love is a waste. Stevens kept every rule and missed every chance. Martha was busy serving while Mary sat at Jesus\' feet — and Jesus said Mary chose the better part.',
    source: 'literature',
    specificReference: 'Kazuo Ishiguro, "The Remains of the Day" (1989), Booker Prize; the pier scene with Miss Kenton',
    spinnable: true,
  },
  {
    id: 'one-hundred-years-solitude-cycle',
    title: 'The Same Mistakes Repeated Across Generations',
    era: '1967',
    category: 'literature-film',
    themes: ['generational-sin', 'repetition', 'family', 'cycle', 'redemption'],
    oneLineSummary: 'Seven generations of the Buendia family repeat the same patterns of solitude, pride, and destruction — as if they are trapped in a prophecy they cannot read until it is too late.',
    spiritualAngle: 'Generational sin is not metaphysics — it is pattern recognition. The sins of the fathers cycle through the children until someone breaks the pattern by reading it clearly. Awareness is the first step out.',
    source: 'literature',
    specificReference: 'Gabriel Garcia Marquez, "One Hundred Years of Solitude" (1967), Nobel Prize in Literature (1982)',
    spinnable: true,
  },
  {
    id: 'never-let-me-go-mortality',
    title: 'Created for a Purpose You Never Chose',
    era: '2005',
    category: 'literature-film',
    themes: ['mortality', 'purpose', 'autonomy', 'dignity', 'created-beings'],
    oneLineSummary: 'Students at Hailsham slowly realize they are clones, created to donate their organs. The horror is how quietly they accept it — and the question of whether a created being has the right to refuse its purpose.',
    spiritualAngle: 'Do you have the right to refuse the purpose you were made for? Ishiguro\'s novel inverts the Jonah story: what happens when the created being does not rebel but simply complies with a plan that seems to erase them?',
    source: 'literature',
    specificReference: 'Kazuo Ishiguro, "Never Let Me Go" (2005)',
    spinnable: true,
  },
  {
    id: 'dune-fear-is-mind-killer',
    title: 'Fear Is the Mind-Killer',
    era: '1965',
    category: 'literature-film',
    themes: ['fear', 'courage', 'facing-fear', 'awareness', 'overcoming'],
    oneLineSummary: 'Paul Atreides recites the Litany Against Fear: "I will face my fear. I will permit it to pass over me and through me. And when it has gone past, I will turn the inner eye to see its path."',
    spiritualAngle: '"God has not given us a spirit of fear." The Litany Against Fear is a secular prayer that describes the spiritual practice of letting fear move through you rather than controlling you.',
    source: 'literature',
    specificReference: 'Frank Herbert, "Dune" (1965), the Gom Jabbar scene and Litany Against Fear',
    spinnable: true,
  },
  {
    id: 'invisible-man-ellison',
    title: 'Being Seen Through but Never Seen',
    era: '1952',
    category: 'literature-film',
    themes: ['invisibility', 'dignity', 'recognition', 'identity', 'being-known'],
    oneLineSummary: 'Ellison\'s narrator is invisible not because of magic but because people refuse to see him — they see a category, a stereotype, a useful object, but never a person.',
    spiritualAngle: 'The deepest human need is to be truly seen. When Hagar is seen by God in the desert, she names God "El Roi" — "the God who sees me." Being invisible is being dehumanized; being seen is being saved.',
    source: 'literature',
    specificReference: 'Ralph Ellison, "Invisible Man" (1952), National Book Award',
    spinnable: true,
  },
  {
    id: 'watership-down-stories-save',
    title: 'The Rabbits Who Survived Because They Kept Telling Stories',
    era: '1972',
    category: 'literature-film',
    themes: ['storytelling', 'leadership', 'hope', 'community', 'tradition'],
    oneLineSummary: 'The rabbits of Watership Down survive their exodus because they carry the stories of El-ahrairah — a folk hero whose tricks and courage inspire them to keep going when the journey seems impossible.',
    spiritualAngle: 'Israel survived the wilderness because they kept telling the story of Exodus. A community that stops telling its founding stories loses its courage and its identity. Narrative is survival equipment.',
    source: 'literature',
    specificReference: 'Richard Adams, "Watership Down" (1972), the El-ahrairah stories throughout',
    spinnable: true,
  },
];
