// ==========================================
// STORY REPOSITORY: PSYCHOLOGY & SCIENCE — EXTENDED
// Deeper cuts, surprising findings, counterintuitive research
// Supplements the base stories-psychology-science.ts collection
// ==========================================

import type { StoryEntry } from './stories-psychology-science';

export const PSYCHOLOGY_SCIENCE_STORIES_EXTENDED: StoryEntry[] = [
  // ==========================================
  // BEHAVIORAL PSYCHOLOGY — DEEPER CUTS
  // ==========================================
  {
    id: 'pratfall-effect',
    title: 'Imperfection Makes the Competent More Lovable',
    era: '1966',
    category: 'psychology-science',
    themes: ['vulnerability', 'imperfection', 'grace', 'authenticity', 'humility'],
    oneLineSummary: 'Aronson found that a highly competent person who makes a clumsy mistake becomes more likable, not less — perfection is alienating.',
    spiritualAngle: 'God chose stuttering Moses, impulsive Peter, persecuting Paul — the "pratfall" of human weakness made their authority more accessible, not less.',
    source: 'research',
    specificReference: 'Elliot Aronson, "The effect of a pratfall on increasing interpersonal attractiveness" (1966), Psychonomic Science',
    spinnable: true,
  },
  {
    id: 'paradox-of-choice',
    title: 'More Options Make You Less Happy',
    era: '2004',
    category: 'psychology-science',
    themes: ['contentment', 'freedom', 'constraint', 'decision-making', 'simplicity'],
    oneLineSummary: 'Schwartz demonstrated that increasing choices leads to decision paralysis, regret, and decreased satisfaction — constraints actually liberate.',
    spiritualAngle: 'The narrow gate Jesus describes is not a punishment but a relief — fewer paths means less paralysis and more presence on the one you choose.',
    source: 'research',
    specificReference: 'Barry Schwartz, "The Paradox of Choice" (2004); Iyengar & Lepper jam study (2000)',
    spinnable: true,
  },
  {
    id: 'door-in-the-face',
    title: 'A Huge Ask Makes the Real Ask Easy',
    era: '1975',
    category: 'psychology-science',
    themes: ['persuasion', 'generosity', 'reciprocity', 'perspective'],
    oneLineSummary: 'Cialdini showed that people are far more likely to agree to a reasonable request if you first ask for something absurdly large — the contrast reframes their sense of proportion.',
    spiritualAngle: 'When God asks Abraham to sacrifice Isaac, then provides a ram — the "real ask" (total trust) becomes possible only after confronting the impossible one.',
    source: 'research',
    specificReference: 'Robert Cialdini, "Reciprocal Concessions" door-in-the-face technique (1975), Journal of Personality and Social Psychology',
    spinnable: true,
  },
  {
    id: 'endowment-effect',
    title: 'We Overvalue What We Already Hold',
    era: '1990',
    category: 'psychology-science',
    themes: ['attachment', 'letting-go', 'idolatry', 'possession', 'surrender'],
    oneLineSummary: 'People demand roughly twice as much to give up something they own as they would pay to acquire it — mere ownership inflates perceived value.',
    spiritualAngle: 'This is why "let go and let God" is so neurologically hard — your brain literally doubles the value of whatever you are gripping, making surrender feel like a worse deal than it is.',
    source: 'research',
    specificReference: 'Kahneman, Knetsch & Thaler, "Experimental tests of the endowment effect" (1990), Journal of Political Economy',
    spinnable: true,
  },
  {
    id: 'ironic-process-theory',
    title: 'Trying Not to Think About It Makes It Louder',
    era: '1987',
    category: 'psychology-science',
    themes: ['temptation', 'thought-life', 'surrender', 'control', 'obsession'],
    oneLineSummary: 'Wegner\'s white bear experiment showed that deliberately suppressing a thought makes it return more frequently and intensely than if you had never tried to suppress it.',
    spiritualAngle: 'White-knuckle resistance to temptation often backfires. Paul\'s "the thing I do not want to do, I do" may be describing ironic process theory two millennia early.',
    source: 'research',
    specificReference: 'Daniel Wegner, "Ironic Processes of Mental Control" (1994); original white bear experiment (1987)',
    spinnable: true,
  },
  {
    id: 'self-licensing-effect',
    title: 'Good Behavior Gives You Permission to Be Bad',
    era: '2001',
    category: 'psychology-science',
    themes: ['self-deception', 'pride', 'moral-failure', 'vigilance', 'humility'],
    oneLineSummary: 'After doing something virtuous, people unconsciously "license" themselves to act selfishly or unethically — as if morality has a balance sheet.',
    spiritualAngle: 'This is the Pharisee\'s trap: tithing mint and dill creates a felt credit that "pays for" neglecting justice and mercy. Virtue is not currency.',
    source: 'research',
    specificReference: 'Monin & Miller, "Moral credentials and the expression of prejudice" (2001), Journal of Personality and Social Psychology',
    spinnable: true,
  },
  {
    id: 'scope-insensitivity',
    title: 'Your Heart Cannot Scale',
    era: '1992',
    category: 'psychology-science',
    themes: ['compassion', 'empathy', 'suffering', 'numbness', 'individual-worth'],
    oneLineSummary: 'People offered nearly the same amount to save 2,000 birds, 20,000 birds, or 200,000 birds — the human heart responds to stories, not statistics.',
    spiritualAngle: 'Jesus never preached to "the masses" — he stopped for one blind man, one bleeding woman, one short tax collector. God\'s attention does not dilute with scale.',
    source: 'research',
    specificReference: 'Desvousges et al. (1992); replicated in Kahneman, "Thinking, Fast and Slow" scope neglect discussion',
    spinnable: true,
  },
  {
    id: 'ego-depletion-glucose',
    title: 'Willpower Is a Fuel Tank, Not a Character Trait',
    era: '1998',
    category: 'psychology-science',
    themes: ['willpower', 'weakness', 'rest', 'sabbath', 'limitation', 'grace'],
    oneLineSummary: 'Baumeister found that self-control is a depletable resource — people who resist one temptation are measurably worse at resisting the next one.',
    spiritualAngle: 'The Sabbath commandment makes neurological sense: God built willpower as a tank that empties, not a muscle that never tires. Rest is not laziness — it is refueling.',
    source: 'research',
    specificReference: 'Roy Baumeister, "Ego Depletion" research program (1998-2010); radish/cookie experiment',
    spinnable: true,
  },
  {
    id: 'affective-forecasting-error',
    title: 'You Are Terrible at Predicting Your Own Feelings',
    era: '1998',
    category: 'psychology-science',
    themes: ['worry', 'anxiety', 'trust', 'future', 'surrender', 'resilience'],
    oneLineSummary: 'Gilbert and Wilson showed people consistently overestimate how long and how intensely future events — good or bad — will affect their happiness.',
    spiritualAngle: '"Do not worry about tomorrow" is not just spiritual advice but psychological accuracy: your forecasting system is broken, and the feared future almost never feels as bad as you imagined.',
    source: 'research',
    specificReference: 'Daniel Gilbert & Timothy Wilson, "Miswanting" and affective forecasting research (1998-2005)',
    spinnable: true,
  },
  {
    id: 'contrast-effect-adaptation',
    title: 'Lottery Winners and Paraplegics Are Equally Happy',
    era: '1978',
    category: 'psychology-science',
    themes: ['contentment', 'suffering', 'joy', 'adaptation', 'circumstances'],
    oneLineSummary: 'Brickman found that lottery winners were no happier than controls after a year, and paraplegics returned to near-baseline happiness — we adapt to almost everything.',
    spiritualAngle: 'Paul writing "I have learned the secret of being content in any and every situation" is not superhuman — it is the natural endpoint of adaptation that God designed into every nervous system.',
    source: 'research',
    specificReference: 'Brickman, Coates & Janoff-Bulman, "Lottery Winners and Accident Victims" (1978), Journal of Personality and Social Psychology',
    spinnable: true,
  },
  {
    id: 'nominative-determinism',
    title: 'Your Name Quietly Steers Your Life',
    era: '2002',
    category: 'psychology-science',
    themes: ['naming', 'identity', 'calling', 'destiny', 'words-have-power'],
    oneLineSummary: 'Pelham found that people named Dennis or Denise are overrepresented among dentists, people named Louis in Louisiana — our names subtly pull us toward matching identities.',
    spiritualAngle: 'God renames people at turning points — Abram to Abraham, Jacob to Israel, Simon to Peter — because a new name does not just describe a new identity, it creates one.',
    source: 'research',
    specificReference: 'Brett Pelham et al., "Why Susie Sells Seashells" (2002), Journal of Personality and Social Psychology; implicit egotism research',
    spinnable: true,
  },
  {
    id: 'emotion-regulation-labeling',
    title: 'Naming Your Pain Shrinks It',
    era: '2007',
    category: 'psychology-science',
    themes: ['confession', 'naming', 'healing', 'vulnerability', 'awareness'],
    oneLineSummary: 'Lieberman\'s fMRI research showed that simply labeling an emotion ("I feel angry") reduces amygdala activation — putting feelings into words literally calms the brain.',
    spiritualAngle: 'Confession is not just a spiritual discipline — it is neurological medicine. The Psalms model this: David names his rage, fear, and despair, and the naming itself is part of the healing.',
    source: 'research',
    specificReference: 'Matthew Lieberman, "Putting Feelings Into Words" (2007), Psychological Science; affect labeling fMRI studies at UCLA',
    spinnable: true,
  },
  {
    id: 'social-proof-uncertainty',
    title: 'When Confused, We Copy Everyone Around Us',
    era: '1984',
    category: 'psychology-science',
    themes: ['conformity', 'community', 'discipleship', 'influence', 'formation'],
    oneLineSummary: 'Cialdini showed that social proof is most powerful in ambiguous situations — when we do not know what to do, we do what everyone around us is doing.',
    spiritualAngle: '"Bad company corrupts good character" is not moralism but neuroscience: in moments of uncertainty, your default is to mirror your community. Choose your community deliberately.',
    source: 'research',
    specificReference: 'Robert Cialdini, "Influence: The Psychology of Persuasion" (1984), social proof principle',
    spinnable: true,
  },
  {
    id: 'approach-avoidance-conflict',
    title: 'The Closer You Get, the More You Want to Run',
    era: '1944',
    category: 'psychology-science',
    themes: ['fear', 'intimacy', 'avoidance', 'breakthrough', 'growth'],
    oneLineSummary: 'Neal Miller discovered that avoidance motivation increases faster than approach motivation as you near a goal — you most want to quit right before the breakthrough.',
    spiritualAngle: 'Resistance is fiercest at the threshold. Elijah\'s darkest moment came right after his greatest victory on Carmel. The desire to flee spikes precisely when you are closest to transformation.',
    source: 'research',
    specificReference: 'Neal Miller, approach-avoidance gradient theory (1944), Journal of Experimental Psychology',
    spinnable: true,
  },
  {
    id: 'invisible-gorilla',
    title: 'You Miss What You Are Not Looking For',
    era: '1999',
    category: 'psychology-science',
    themes: ['attention', 'blindness', 'awareness', 'presence', 'perception'],
    oneLineSummary: 'Simons and Chabris showed that half of people counting basketball passes completely miss a gorilla walking through the scene — attention is a narrower beam than we think.',
    spiritualAngle: '"Eyes to see and ears to hear" is a real neurological condition: you literally cannot perceive what you are not attending to. Prayer may be less about God showing up and more about redirecting your attention to where God already is.',
    source: 'research',
    specificReference: 'Daniel Simons & Christopher Chabris, "Gorillas in Our Midst" (1999), Perception',
    spinnable: true,
  },

  // ==========================================
  // NEUROSCIENCE — DEEPER CUTS
  // ==========================================
  {
    id: 'default-mode-wandering',
    title: 'Your Brain Does Its Best Work When You Stop Trying',
    era: '2001',
    category: 'psychology-science',
    themes: ['rest', 'sabbath', 'creativity', 'stillness', 'surrender'],
    oneLineSummary: 'Raichle discovered the default mode network — a brain system that activates when you stop focusing, responsible for insight, creativity, and self-reflection.',
    spiritualAngle: '"Be still and know that I am God" has a neuroscience mechanism: the insights you need most arrive when you release deliberate control and let the brain wander.',
    source: 'research',
    specificReference: 'Marcus Raichle, "A default mode of brain function" (2001), PNAS; relation to insight and creativity research',
    spinnable: true,
  },
  {
    id: 'neuroplasticity-belief-changes-brain',
    title: 'What You Believe Physically Rewires Your Brain',
    era: '2005',
    category: 'psychology-science',
    themes: ['faith', 'transformation', 'renewal', 'mind', 'belief'],
    oneLineSummary: 'Pascual-Leone showed that people who merely imagined playing piano scales developed the same motor cortex changes as those who physically practiced — belief reshapes neural architecture.',
    spiritualAngle: '"Be transformed by the renewing of your mind" is not metaphor — mental rehearsal of new ways of seeing literally restructures the hardware of your brain.',
    source: 'research',
    specificReference: 'Alvaro Pascual-Leone, mental practice and motor cortex plasticity (2005), Journal of Neurophysiology',
    spinnable: true,
  },
  {
    id: 'music-whole-brain-activation',
    title: 'Music Lights Up More Brain Than Anything Else',
    era: '2014',
    category: 'psychology-science',
    themes: ['worship', 'music', 'wholeness', 'connection', 'transcendence'],
    oneLineSummary: 'Anita Collins\' synthesis of neuroscience research showed that playing music activates virtually every area of the brain simultaneously — more than any other human activity.',
    spiritualAngle: 'This may be why worship through music feels different from worship through words alone — singing engages your whole self, the way God asks for whole-heart devotion.',
    source: 'research',
    specificReference: 'Anita Collins, "How Playing an Instrument Benefits Your Brain" (2014); synthesis of Schlaug, Zatorre, and Koelsch fMRI studies',
    spinnable: true,
  },
  {
    id: 'awe-vagus-nerve',
    title: 'Awe Literally Slows Your Heart and Widens Your View',
    era: '2015',
    category: 'psychology-science',
    themes: ['awe', 'wonder', 'worship', 'transcendence', 'humility'],
    oneLineSummary: 'Keltner\'s lab found that experiences of awe activate the vagus nerve, slow heart rate, shift attention outward, and produce anti-inflammatory cytokines in the body.',
    spiritualAngle: 'The fear of the Lord is not terror but awe — and awe has measurable healing effects. Worship may be the most anti-inflammatory activity available to humans.',
    source: 'research',
    specificReference: 'Dacher Keltner, "Awe, the Small Self, and Prosocial Behavior" (2015); Stellar et al., awe and cytokine IL-6 reduction (2015), Emotion',
    spinnable: true,
  },
  {
    id: 'sleep-emotional-detoxification',
    title: 'Sleep Strips the Emotional Charge from Painful Memories',
    era: '2011',
    category: 'psychology-science',
    themes: ['grief', 'healing', 'rest', 'time', 'processing', 'peace'],
    oneLineSummary: 'Walker found that REM sleep replays emotional memories while suppressing norepinephrine, effectively keeping the memory but draining the pain — sleep is emotional detox.',
    spiritualAngle: '"He gives to his beloved sleep" is not a platitude — it is a description of God\'s nightly mercy: the mechanism by which painful memories lose their sting.',
    source: 'research',
    specificReference: 'Matthew Walker, "Sleep-Dependent Emotional Brain Processing" (2011), Current Biology; "Why We Sleep" (2017)',
    spinnable: true,
  },
  {
    id: 'anterior-cingulate-social-pain',
    title: 'Rejection Activates the Same Brain Region as a Broken Bone',
    era: '2003',
    category: 'psychology-science',
    themes: ['rejection', 'belonging', 'community', 'pain', 'compassion'],
    oneLineSummary: 'Eisenberger\'s fMRI studies showed that social exclusion activates the dorsal anterior cingulate cortex — the same region activated by physical pain — so completely that Tylenol reduces hurt feelings.',
    spiritualAngle: 'When Scripture describes being "cut off from the people" as a punishment comparable to physical harm, it is neurologically accurate. Isolation is not inconvenience — it is injury.',
    source: 'research',
    specificReference: 'Naomi Eisenberger, "Does Rejection Hurt?" (2003), Science; Cyberball paradigm; DeWall Tylenol study (2010)',
    spinnable: true,
  },
  {
    id: 'gut-brain-axis',
    title: 'Your Gut Has 500 Million Neurons and Talks to Your Brain',
    era: '2015',
    category: 'psychology-science',
    themes: ['intuition', 'embodiment', 'wisdom', 'wholeness', 'discernment'],
    oneLineSummary: 'The enteric nervous system contains as many neurons as a cat\'s brain, produces 95% of your serotonin, and communicates directly with the brain through the vagus nerve.',
    spiritualAngle: 'The biblical language of "bowels of compassion" and the Hebrew word for womb-love (rachamim) is anatomically prescient — your gut literally feels before your brain thinks.',
    source: 'research',
    specificReference: 'Mayer, "Gut Feelings" (2011); Cryan & Dinan, gut-brain axis and microbiome-gut-brain research (2015), Nature Reviews Neuroscience',
    spinnable: true,
  },
  {
    id: 'prefrontal-cortex-last-to-mature',
    title: 'The Part of Your Brain That Makes You Wise Finishes Last',
    era: '1999',
    category: 'psychology-science',
    themes: ['patience', 'formation', 'maturity', 'timing', 'sanctification'],
    oneLineSummary: 'The prefrontal cortex — responsible for judgment, impulse control, and long-term planning — is not fully myelinated until approximately age 25.',
    spiritualAngle: 'God designed wisdom to arrive slowly, built up layer by layer like myelin around an axon. Sanctification is not instant — it literally follows the brain\'s own developmental timeline.',
    source: 'research',
    specificReference: 'Jay Giedd, NIMH longitudinal brain development study (1999-2004); "The Teen Brain" research at National Institute of Mental Health',
    spinnable: true,
  },
  {
    id: 'phantom-limb-neuromatrix',
    title: 'The Brain Keeps Feeling What Is No Longer There',
    era: '1998',
    category: 'psychology-science',
    themes: ['loss', 'grief', 'memory', 'absence', 'longing', 'identity'],
    oneLineSummary: 'Ramachandran showed that amputees feel vivid pain, itching, and movement in limbs that no longer exist — the brain maintains a complete neural map of what is gone.',
    spiritualAngle: 'Grief for a lost person, a lost season, or a lost version of yourself is not weakness — your brain literally maintains the neural architecture of what you loved. The ache proves the bond was real.',
    source: 'research',
    specificReference: 'V.S. Ramachandran, mirror box therapy and phantom limb research (1998); "Phantoms in the Brain"',
    spinnable: true,
  },
  {
    id: 'neurological-synchrony-conversation',
    title: 'Two Brains Sync Up When People Truly Listen',
    era: '2010',
    category: 'psychology-science',
    themes: ['presence', 'listening', 'empathy', 'communion', 'unity'],
    oneLineSummary: 'Hasson\'s fMRI research showed that a speaker\'s and listener\'s brain activity patterns literally synchronize during engaged conversation — the listener\'s brain mirrors the speaker\'s with a slight delay.',
    spiritualAngle: 'When Scripture says believers are "of one mind," there is a neurological reality: deep listening creates neural coupling. True communion is not agreement — it is resonance.',
    source: 'research',
    specificReference: 'Uri Hasson, "Brain-to-brain coupling" (2010), PNAS; Princeton Neuroscience Institute',
    spinnable: true,
  },

  // ==========================================
  // BIOLOGY / NATURE — DEEPER CUTS
  // ==========================================
  {
    id: 'tardigrade-indestructible',
    title: 'The Microscopic Animal That Survives Everything',
    era: '2007',
    category: 'psychology-science',
    themes: ['resilience', 'survival', 'faithfulness', 'endurance', 'protection'],
    oneLineSummary: 'Tardigrades survive boiling, freezing, radiation, the vacuum of space, and pressures six times the deepest ocean trench by entering cryptobiosis — a deathlike state from which they revive.',
    spiritualAngle: 'Sometimes survival requires entering a kind of death — shutting down, going dormant, enduring — then coming back to life. Resurrection is patterned into the smallest creatures.',
    source: 'research',
    specificReference: 'Jönsson et al., "Tardigrades survive exposure to space" (2008), Current Biology; TARDIS space experiment (2007)',
    spinnable: true,
  },
  {
    id: 'axolotl-regeneration',
    title: 'The Creature That Regrows What Was Lost',
    era: '2009',
    category: 'psychology-science',
    themes: ['restoration', 'healing', 'wholeness', 'redemption', 'new-creation'],
    oneLineSummary: 'The axolotl can regenerate entire limbs, spinal cord, heart, and even portions of its brain — the only vertebrate capable of complete organ regeneration in adulthood.',
    spiritualAngle: 'God embedded the blueprint for complete restoration in living tissue. Restoration is not science fiction — it is biology. What was lost can be rebuilt.',
    source: 'research',
    specificReference: 'Elly Tanaka, axolotl limb regeneration research at MPI-CBG (2009-present); blastema formation studies',
    spinnable: true,
  },
  {
    id: 'whale-fall-ecosystem',
    title: 'A Dead Whale Feeds an Ecosystem for Fifty Years',
    era: '1989',
    category: 'psychology-science',
    themes: ['legacy', 'sacrifice', 'death-brings-life', 'generosity', 'community'],
    oneLineSummary: 'When a whale dies and sinks, its carcass becomes a "whale fall" — an ecosystem supporting over 400 species for 50 to 100 years on the otherwise barren ocean floor.',
    spiritualAngle: '"Unless a grain of wheat falls into the earth and dies, it remains alone; but if it dies, it bears much fruit." A whale fall is the deepest illustration: one death, a hundred years of life.',
    source: 'research',
    specificReference: 'Craig Smith, "Whale Falls" discovery and ecosystem studies (1989-present), University of Hawaii; deep-sea research via submersible',
    spinnable: true,
  },
  {
    id: 'lodgepole-pine-fire-adapted',
    title: 'Some Trees Need Fire to Release Their Seeds',
    era: '1994',
    category: 'psychology-science',
    themes: ['refinement', 'fire', 'testing', 'purpose', 'renewal', 'hidden-potential'],
    oneLineSummary: 'Lodgepole pines produce serotinous cones sealed with resin that only open in the extreme heat of a forest fire — the seeds literally require destruction to be released.',
    spiritualAngle: '"I have refined you in the furnace of affliction." Some of what God has placed in you can only be released by the very thing you fear most — the fire was always part of the plan.',
    source: 'research',
    specificReference: 'Turner et al., Yellowstone post-fire lodgepole pine regeneration (1994); serotinous cone ecology studies',
    spinnable: true,
  },
  {
    id: 'wood-wide-web-trees',
    title: 'Trees Share Nutrients Through an Underground Network',
    era: '1997',
    category: 'psychology-science',
    themes: ['community', 'generosity', 'interdependence', 'church', 'hidden-connections'],
    oneLineSummary: 'Simard discovered that trees share carbon, water, and nutrients through mycorrhizal fungal networks — "mother trees" even preferentially feed their offspring and sick neighbors.',
    spiritualAngle: 'The body of Christ works like a forest: invisible underground connections transfer resources from those who have to those who need. No tree thrives alone.',
    source: 'research',
    specificReference: 'Suzanne Simard, "Net transfer of carbon between ectomycorrhizal tree species" (1997), Nature; "Finding the Mother Tree" (2021)',
    spinnable: true,
  },
  {
    id: 'salmon-return-home',
    title: 'Salmon Swim Upstream to Die Where They Were Born',
    era: '1971',
    category: 'psychology-science',
    themes: ['home', 'sacrifice', 'return', 'faithfulness', 'death-brings-life', 'calling'],
    oneLineSummary: 'Pacific salmon navigate thousands of miles using Earth\'s magnetic field and olfactory memory to return to the exact stream where they hatched, spawn, and die — their decaying bodies fertilizing the next generation.',
    spiritualAngle: 'The homing instinct written into creation mirrors the prodigal son: no matter how far you travel, something pulls you back to where you began. And the return always costs something.',
    source: 'research',
    specificReference: 'Arthur Hasler, olfactory homing in salmon (1971); Putman et al., geomagnetic navigation (2014), Current Biology',
    spinnable: true,
  },
  {
    id: 'bioluminescence-deep-ocean',
    title: 'Most Life in the Deep Ocean Makes Its Own Light',
    era: '2017',
    category: 'psychology-science',
    themes: ['light', 'darkness', 'hope', 'witness', 'inner-light'],
    oneLineSummary: 'Up to 76% of deep-sea organisms produce bioluminescence — in absolute darkness where sunlight never reaches, life generates its own light from within.',
    spiritualAngle: '"The light shines in the darkness, and the darkness has not overcome it." Most ocean life does not wait for sunlight — it manufactures light in the blackest places on Earth.',
    source: 'research',
    specificReference: 'Martini & Haddock, "Quantification of bioluminescence from the surface to the deep sea" (2017), Scientific Reports; Monterey Bay Aquarium Research Institute',
    spinnable: true,
  },
  {
    id: 'honey-bee-waggle-dance',
    title: 'Bees Communicate Through Dance',
    era: '1967',
    category: 'psychology-science',
    themes: ['communication', 'community', 'service', 'guidance', 'testimony'],
    oneLineSummary: 'Karl von Frisch decoded the honey bee waggle dance — a figure-eight movement that precisely communicates the direction, distance, and quality of a food source to the entire colony.',
    spiritualAngle: 'When someone returns to the community having found something good, the best response is not hoarding but dancing — communicating the find so others can feast too. Testimony works like a waggle dance.',
    source: 'research',
    specificReference: 'Karl von Frisch, "The Dance Language and Orientation of Bees" (1967), Nobel Prize in Physiology or Medicine (1973)',
    spinnable: true,
  },
  {
    id: 'lichen-symbiosis-survival',
    title: 'Two Organisms That Can Only Survive Together',
    era: '1867',
    category: 'psychology-science',
    themes: ['partnership', 'unity', 'dependence', 'marriage', 'covenant', 'interdependence'],
    oneLineSummary: 'A lichen is not one organism but two — a fungus and an alga in such tight symbiosis that neither can survive alone, yet together they colonize bare rock and survive in arctic deserts.',
    spiritualAngle: '"Two are better than one" is a biological truth: the alga photosynthesizes food the fungus cannot make, and the fungus provides structure the alga cannot create. Some missions require partnership.',
    source: 'research',
    specificReference: 'Simon Schwendener, dual hypothesis of lichens (1867); modern lichenology confirming obligate mutualism',
    spinnable: true,
  },
  {
    id: 'cleaner-fish-trust',
    title: 'The Tiny Fish That Predators Let Inside Their Mouths',
    era: '1958',
    category: 'psychology-science',
    themes: ['trust', 'vulnerability', 'covenant', 'service', 'mutual-benefit'],
    oneLineSummary: 'Cleaner wrasses enter the open mouths and gill chambers of predatory fish to remove parasites — the predator restrains its instinct to eat, and both benefit from radical trust.',
    spiritualAngle: 'The most intimate acts of healing require the most dangerous vulnerability. The predator must open its mouth and not bite; the cleaner must enter and not flee. Trust is the precondition for all deep help.',
    source: 'research',
    specificReference: 'Conrad Limbaugh, "Cleaning Symbiosis" (1961), Scientific American; Grutter, cleaner fish mutualism studies (1999-present)',
    spinnable: true,
  },
  {
    id: 'cuttlefish-camouflage',
    title: 'The Animal That Becomes Whatever It Needs To Be',
    era: '2014',
    category: 'psychology-science',
    themes: ['adaptation', 'identity', 'authenticity', 'masks', 'transformation'],
    oneLineSummary: 'Cuttlefish change color, texture, and pattern in milliseconds — yet they are colorblind. They achieve perfect camouflage without being able to see their own disguise.',
    spiritualAngle: 'We are sometimes transformed in ways we cannot perceive ourselves. Sanctification may work like cuttlefish camouflage — others see the change before you do.',
    source: 'research',
    specificReference: 'Chung & Marshall, "Cuttlefish camouflage mechanisms" (2014); Hanlon, cephalopod rapid adaptive coloration research, Marine Biological Laboratory',
    spinnable: true,
  },
  {
    id: 'bristlecone-pine-oldest',
    title: 'The Oldest Living Things Grow in the Harshest Places',
    era: '1957',
    category: 'psychology-science',
    themes: ['endurance', 'adversity', 'growth', 'faithfulness', 'time', 'patience'],
    oneLineSummary: 'Bristlecone pines — the oldest non-clonal organisms on Earth at 5,000+ years — grow exclusively in extreme, high-altitude environments with poor soil and constant wind.',
    spiritualAngle: 'The longest-lived things on the planet did not grow in lush gardens but in harsh deserts. Comfort does not produce longevity. The wind that bent you made the wood denser.',
    source: 'research',
    specificReference: 'Edmund Schulman, discovery of Methuselah bristlecone pine (1957), White Mountains, California; dendrochronology research',
    spinnable: true,
  },
  {
    id: 'sea-turtle-magnetic-memory',
    title: 'Sea Turtles Navigate Back to the Beach Where They Hatched',
    era: '2015',
    category: 'psychology-science',
    themes: ['home', 'memory', 'return', 'faithfulness', 'origin', 'calling'],
    oneLineSummary: 'Loggerhead sea turtles imprint on the Earth\'s magnetic signature of their birth beach and use it to navigate back decades later across entire oceans to lay eggs on the same shore.',
    spiritualAngle: 'Something in you remembers where you came from. The longing for home, for a place you may not even consciously remember, is written as deep as a magnetic field in your bones.',
    source: 'research',
    specificReference: 'Brothers & Lohmann, "Evidence for Geomagnetic Imprinting and Magnetic Navigation in Sea Turtles" (2015), Current Biology',
    spinnable: true,
  },

  // ==========================================
  // PHYSICS / COSMOLOGY — DEEPER CUTS
  // ==========================================
  {
    id: 'entropy-arrow-of-time',
    title: 'The Universe Moves Toward Disorder Unless Energy Is Applied',
    era: '1865',
    category: 'psychology-science',
    themes: ['discipline', 'decay', 'renewal', 'effort', 'sanctification', 'entropy'],
    oneLineSummary: 'The second law of thermodynamics states that entropy always increases in a closed system — disorder is the natural direction of everything unless external energy is continuously applied.',
    spiritualAngle: 'Relationships, faith, health, character — everything drifts toward chaos without intentional energy. This is why spiritual disciplines exist: not to earn God\'s favor but to fight entropy.',
    source: 'research',
    specificReference: 'Rudolf Clausius, formulation of the second law of thermodynamics (1865); Boltzmann statistical mechanics',
    spinnable: true,
  },
  {
    id: 'hawking-radiation-information',
    title: 'Even Black Holes Cannot Destroy Information',
    era: '1974',
    category: 'psychology-science',
    themes: ['memory', 'loss', 'preservation', 'God-remembers', 'nothing-wasted'],
    oneLineSummary: 'Hawking radiation and the black hole information paradox suggest that information falling into a black hole is not destroyed but encoded on its surface — nothing is truly erased from the universe.',
    spiritualAngle: '"God collects your tears in a bottle and records each one" — even the most consuming darkness in physics cannot annihilate information. What happened to you is not lost.',
    source: 'research',
    specificReference: 'Stephen Hawking, "Black hole explosions?" (1974), Nature; black hole information paradox resolution research (2019, "Page curve" confirmation)',
    spinnable: true,
  },
  {
    id: 'anthropic-fine-tuning',
    title: 'The Universe\'s Constants Are Suspiciously Perfect for Life',
    era: '1986',
    category: 'psychology-science',
    themes: ['design', 'purpose', 'creation', 'intentionality', 'wonder'],
    oneLineSummary: 'If the strong nuclear force were 2% stronger or the cosmological constant differed by one part in 10^120, no stars, no chemistry, no life could exist — the universe appears tuned with absurd precision.',
    spiritualAngle: 'The fine-tuning argument does not prove God, but it shatters the illusion that your existence is casual. Even physics is shouting that you are not an accident.',
    source: 'research',
    specificReference: 'John Barrow & Frank Tipler, "The Anthropic Cosmological Principle" (1986); Martin Rees, "Just Six Numbers" (1999)',
    spinnable: true,
  },
  {
    id: 'delayed-choice-quantum-eraser',
    title: 'The Future Seems to Influence the Past',
    era: '2000',
    category: 'psychology-science',
    themes: ['mystery', 'sovereignty', 'time', 'providence', 'beyond-understanding'],
    oneLineSummary: 'In delayed-choice quantum eraser experiments, a measurement made after a photon has already been detected appears to retroactively change whether it behaved as a wave or particle.',
    spiritualAngle: 'God working "all things together for good" may operate outside our linear experience of time. The ending of the story can redeem what appeared irreversible in the middle.',
    source: 'research',
    specificReference: 'Kim et al., "A Delayed Choice Quantum Eraser" (2000), Physical Review Letters; Wheeler delayed-choice gedanken experiment',
    spinnable: true,
  },
  {
    id: 'dark-energy-accelerating-expansion',
    title: 'Something Invisible Is Pushing Everything Apart',
    era: '1998',
    category: 'psychology-science',
    themes: ['mystery', 'hiddenness', 'invisible-forces', 'faith', 'unknown'],
    oneLineSummary: 'The 1998 discovery that the universe\'s expansion is accelerating revealed that 68% of all energy is "dark energy" — invisible, undetectable, yet the dominant force in the cosmos.',
    spiritualAngle: 'The majority of what drives reality is invisible to every instrument we possess. Walking by faith and not by sight is not a spiritual weakness — it mirrors the actual structure of the universe.',
    source: 'research',
    specificReference: 'Riess et al. & Perlmutter et al., accelerating universe discovery (1998), Nobel Prize in Physics (2011); Type Ia supernovae observations',
    spinnable: true,
  },
  {
    id: 'stars-forge-elements',
    title: 'Every Atom in Your Body Was Forged Inside a Star',
    era: '1957',
    category: 'psychology-science',
    themes: ['origin', 'creation', 'interconnection', 'dust', 'wonder', 'sacrifice'],
    oneLineSummary: 'Burbidge, Burbidge, Fowler, and Hoyle proved that elements heavier than hydrogen and helium are only created in the nuclear furnaces of stars — and dispersed when those stars die.',
    spiritualAngle: '"From dust you came" is more profound than Genesis knew: the dust was stardust, forged in a supernova\'s death. Your very atoms required a star to sacrifice itself.',
    source: 'research',
    specificReference: 'B²FH paper, "Synthesis of the Elements in Stars" (1957), Reviews of Modern Physics; stellar nucleosynthesis',
    spinnable: true,
  },
  {
    id: 'cosmic-web-structure',
    title: 'The Universe Is Structured Like a Neural Network',
    era: '2020',
    category: 'psychology-science',
    themes: ['design', 'interconnection', 'pattern', 'creation', 'imago-dei'],
    oneLineSummary: 'Vazza and Feletti found that the large-scale structure of the universe — filaments of galaxies connected by dark matter — is structurally identical to a human neural network at the cellular level.',
    spiritualAngle: 'The cosmos and the mind are built on the same blueprint. A universe that mirrors a brain at every scale whispers of a designer who thinks — and who made thinkers in that same image.',
    source: 'research',
    specificReference: 'Franco Vazza & Alberto Feletti, "The Quantitative Comparison Between the Neuronal Network and the Cosmic Web" (2020), Frontiers in Physics',
    spinnable: true,
  },
  {
    id: 'gravitational-lensing-invisible-mass',
    title: 'The Invisible Bends Light Around It',
    era: '1979',
    category: 'psychology-science',
    themes: ['faith', 'invisible-influence', 'God-at-work', 'evidence', 'hiddenness'],
    oneLineSummary: 'Gravitational lensing shows that massive but invisible objects (dark matter) bend visible light around them — you can map invisible things by watching how they distort what you can see.',
    spiritualAngle: 'You cannot see God directly, but you can trace God\'s presence by watching what bends around that presence — the warped trajectories of lives, the distorted priorities, the impossible redirections.',
    source: 'research',
    specificReference: 'Walsh, Carswell & Weymann, first gravitational lens observation (1979); Hubble Frontier Fields dark matter mapping',
    spinnable: true,
  },

  // ==========================================
  // MEDICAL / HEALTH — DEEPER CUTS
  // ==========================================
  {
    id: 'placebo-getting-stronger',
    title: 'Placebos Are Getting More Powerful Over Time',
    era: '2015',
    category: 'psychology-science',
    themes: ['belief', 'faith', 'healing', 'expectation', 'mystery'],
    oneLineSummary: 'Tuttle found that placebo responses in clinical trials have been increasing over decades, particularly in the US — belief is becoming a more potent physiological force, and scientists do not know why.',
    spiritualAngle: 'If the human body\'s response to belief is literally getting stronger over time, then faith is not a relic of a pre-scientific age — it is an intensifying biological reality.',
    source: 'research',
    specificReference: 'Alexander Tuttle et al., "Increasing Placebo Responses Over Time in U.S. Clinical Trials of Neuropathic Pain" (2015), Pain',
    spinnable: true,
  },
  {
    id: 'ace-study-trauma-disease',
    title: 'Childhood Trauma Predicts Disease Decades Later',
    era: '1998',
    category: 'psychology-science',
    themes: ['trauma', 'healing', 'body-soul-connection', 'sin-consequences', 'restoration'],
    oneLineSummary: 'The ACE study of 17,000 people found a dose-response relationship between childhood adversity and adult disease — four or more adverse experiences doubled the risk of heart disease, cancer, and early death.',
    spiritualAngle: 'The sins of the fathers visiting the children "to the third and fourth generation" is not punishment but pathophysiology. Trauma embeds in the body. This is why healing prayer is not just spiritual — it is medical.',
    source: 'research',
    specificReference: 'Felitti et al., "Relationship of Childhood Abuse and Household Dysfunction to Many of the Leading Causes of Death in Adults" (1998), American Journal of Preventive Medicine',
    spinnable: true,
  },
  {
    id: 'roseto-effect-community-health',
    title: 'The Town Where Nobody Had Heart Attacks',
    era: '1961',
    category: 'psychology-science',
    themes: ['community', 'belonging', 'church', 'health', 'isolation', 'connection'],
    oneLineSummary: 'Roseto, Pennsylvania had virtually zero heart disease despite high-fat diets, smoking, and no exercise — the only protective factor was tight-knit Italian immigrant community with three-generation households and strong church life.',
    spiritualAngle: 'When the community dissolved in the 1970s as people moved to suburbs, heart disease rates immediately rose to national averages. Belonging is not a lifestyle bonus — it is a cardiovascular necessity.',
    source: 'research',
    specificReference: 'Stewart Wolf & John Bruhn, "The Roseto Effect" (1961-1979); "The Power of Clan" (1993)',
    spinnable: true,
  },
  {
    id: 'psychoneuroimmunology-emotions-immunity',
    title: 'Loneliness Changes Your Immune System at the Genetic Level',
    era: '2007',
    category: 'psychology-science',
    themes: ['isolation', 'community', 'healing', 'mind-body', 'wholeness'],
    oneLineSummary: 'Cole discovered that chronic loneliness upregulates inflammatory genes and downregulates antiviral genes — lonely people\'s immune systems literally prepare for wounds rather than viruses, as if expecting attack.',
    spiritualAngle: 'An isolated person\'s body shifts into a fortress posture — expecting injury, not infection. The church as "body of Christ" is not metaphor but immunology: connected bodies heal differently than isolated ones.',
    source: 'research',
    specificReference: 'Steve Cole, "Social Regulation of Gene Expression in Human Leukocytes" (2007), Genome Biology; CTRA (Conserved Transcriptional Response to Adversity)',
    spinnable: true,
  },
  {
    id: 'open-label-placebo',
    title: 'Placebos Work Even When You Know They Are Placebos',
    era: '2010',
    category: 'psychology-science',
    themes: ['faith', 'ritual', 'mystery', 'healing', 'practice'],
    oneLineSummary: 'Kaptchuk showed that patients given pills explicitly labeled "placebo" still experienced significant symptom improvement — the healing ritual itself has power independent of deception.',
    spiritualAngle: 'You do not have to understand how communion, baptism, or laying on hands works for them to work. The ritual itself carries power. Participation precedes comprehension.',
    source: 'research',
    specificReference: 'Ted Kaptchuk, "Placebos without Deception" (2010), PLoS ONE; open-label placebo in IBS patients, Harvard Medical School',
    spinnable: true,
  },
  {
    id: 'wound-healing-speed-relationships',
    title: 'Married Couples\' Wounds Heal Faster After Kind Conversations',
    era: '2005',
    category: 'psychology-science',
    themes: ['words', 'healing', 'relationships', 'conflict', 'power-of-tongue'],
    oneLineSummary: 'Kiecolt-Glaser found that small blister wounds healed 40% slower after hostile marital arguments compared to supportive conversations — the quality of words literally affects wound healing speed.',
    spiritualAngle: '"Death and life are in the power of the tongue" is measurable at the cellular level. Your words change the speed at which another person\'s body repairs itself.',
    source: 'research',
    specificReference: 'Kiecolt-Glaser et al., "Hostile Marital Interactions and Wound Healing" (2005), Archives of General Psychiatry',
    spinnable: true,
  },
  {
    id: 'telomere-stress-aging',
    title: 'Chronic Stress Physically Shortens Your Life at the Cellular Level',
    era: '2004',
    category: 'psychology-science',
    themes: ['anxiety', 'peace', 'rest', 'trust', 'sabbath', 'worry'],
    oneLineSummary: 'Blackburn and Epel found that caregivers under chronic stress had telomeres equivalent to ten additional years of aging — worry literally erodes the protective caps on your chromosomes.',
    spiritualAngle: '"Anxiety in a person\'s heart weighs them down" is cellular biology: chronic worry shortens your telomeres. "Cast all your anxiety on him" is not just spiritual advice — it is longevity medicine.',
    source: 'research',
    specificReference: 'Epel et al., "Accelerated telomere shortening in response to life stress" (2004), PNAS; Blackburn Nobel Prize (2009)',
    spinnable: true,
  },
  {
    id: 'laughter-immune-boost',
    title: 'Laughter Measurably Strengthens Immune Function',
    era: '1989',
    category: 'psychology-science',
    themes: ['joy', 'healing', 'humor', 'community', 'health'],
    oneLineSummary: 'Berk found that laughter increases natural killer cell activity, reduces cortisol, and boosts immunoglobulin levels — "a cheerful heart is good medicine" is clinically verifiable.',
    spiritualAngle: 'Proverbs 17:22 predated psychoneuroimmunology by three millennia. Joy is not frivolous — it is pharmacological. The communities that laugh together genuinely outlive the ones that don\'t.',
    source: 'research',
    specificReference: 'Lee Berk, "Neuroendocrine and stress hormone changes during mirthful laughter" (1989), American Journal of Medical Sciences; Loma Linda University',
    spinnable: true,
  },

  // ==========================================
  // SOCIAL PSYCHOLOGY — DEEPER CUTS
  // ==========================================
  {
    id: 'just-world-hypothesis',
    title: 'We Blame Victims Because Randomness Is Terrifying',
    era: '1966',
    category: 'psychology-science',
    themes: ['suffering', 'justice', 'theodicy', 'compassion', 'judgment'],
    oneLineSummary: 'Lerner found that people instinctively blame victims for their misfortune — not from cruelty but from a deep need to believe the world is fair and that bad things happen to bad people.',
    spiritualAngle: 'Job\'s friends were not monsters — they were just-world believers. If Job deserved it, the universe was orderly. Accepting his innocence meant accepting that randomness could touch them too.',
    source: 'research',
    specificReference: 'Melvin Lerner, "Belief in a Just World" (1980); original experiments (1966), Journal of Personality and Social Psychology',
    spinnable: true,
  },
  {
    id: 'prosocial-spending',
    title: 'Spending Money on Others Makes You Happier Than Spending on Yourself',
    era: '2008',
    category: 'psychology-science',
    themes: ['generosity', 'giving', 'joy', 'selflessness', 'blessing'],
    oneLineSummary: 'Dunn found that participants randomly assigned to spend money on others reported significantly higher happiness than those who spent on themselves — regardless of income level.',
    spiritualAngle: '"It is more blessed to give than to receive" is not moralism — it is a replicated finding in experimental psychology. Generosity is the more efficient path to joy.',
    source: 'research',
    specificReference: 'Elizabeth Dunn et al., "Spending Money on Others Promotes Happiness" (2008), Science',
    spinnable: true,
  },
  {
    id: 'moral-elevation',
    title: 'Witnessing Goodness Physically Warms Your Chest',
    era: '2000',
    category: 'psychology-science',
    themes: ['inspiration', 'virtue', 'witness', 'testimony', 'transformation'],
    oneLineSummary: 'Haidt discovered "moral elevation" — witnessing acts of moral beauty triggers a warm, expanding feeling in the chest, tears, and a desire to be a better person. It is mediated by oxytocin.',
    spiritualAngle: 'The burning in the chest that disciples felt on the road to Emmaus may have been moral elevation — a physiological response to encountering transcendent goodness.',
    source: 'research',
    specificReference: 'Jonathan Haidt, "Elevation and the Positive Psychology of Morality" (2000); Silvers & Haidt, "Moral Elevation" (2008)',
    spinnable: true,
  },
  {
    id: 'beautiful-mess-effect',
    title: 'Your Vulnerability Looks Like Courage to Everyone Else',
    era: '2018',
    category: 'psychology-science',
    themes: ['vulnerability', 'courage', 'authenticity', 'self-perception', 'community'],
    oneLineSummary: 'Bruk found that people rate their own vulnerability as weakness but rate the identical vulnerability in others as courageous and attractive — we systematically misjudge our own openness.',
    spiritualAngle: 'The confession you are terrified to make is the one your community most needs to hear. What feels like weakness from the inside radiates as courage from the outside.',
    source: 'research',
    specificReference: 'Anna Bruk et al., "Beautiful Mess Effect" (2018), Journal of Personality and Social Psychology',
    spinnable: true,
  },
  {
    id: 'power-of-ritual-harvard',
    title: 'Rituals Reduce Grief Even If You Do Not Believe in Them',
    era: '2014',
    category: 'psychology-science',
    themes: ['grief', 'ritual', 'practice', 'liturgy', 'healing', 'tradition'],
    oneLineSummary: 'Norton and Gino found that performing a ritual after experiencing a loss significantly reduced grief — even when participants reported not believing rituals had any effect.',
    spiritualAngle: 'Liturgy, communion, kneeling, candle-lighting — these work before you believe they work. The body leads and the heart follows. Practice precedes faith more often than we admit.',
    source: 'research',
    specificReference: 'Norton & Gino, "Rituals Alleviate Grieving for Loved Ones, Lovers, and Lotteries" (2014), Journal of Experimental Psychology: General',
    spinnable: true,
  },
  {
    id: 'fresh-start-effect',
    title: 'Temporal Landmarks Make New Beginnings Possible',
    era: '2014',
    category: 'psychology-science',
    themes: ['new-beginnings', 'repentance', 'fresh-start', 'time', 'hope'],
    oneLineSummary: 'Dai found that people are dramatically more likely to pursue goals after temporal landmarks — new years, birthdays, Mondays — because these dates create a psychological "fresh start" that separates past self from future self.',
    spiritualAngle: '"His mercies are new every morning" provides a daily temporal landmark — a psychologically real boundary between who you were yesterday and who you can become today.',
    source: 'research',
    specificReference: 'Hengchen Dai et al., "The Fresh Start Effect" (2014), Management Science; Wharton School',
    spinnable: true,
  },
  {
    id: 'power-of-touch',
    title: 'A Brief Touch from a Stranger Changes Behavior',
    era: '1992',
    category: 'psychology-science',
    themes: ['touch', 'embodiment', 'healing', 'connection', 'incarnation'],
    oneLineSummary: 'A half-second touch on the arm from a librarian made people rate the library experience higher, a touch from a server increased tips, and a brief touch from a stranger increased willingness to help — all without conscious awareness.',
    spiritualAngle: 'Jesus did not heal from a distance when proximity was possible — he touched lepers, held children, let a sinful woman wash his feet. The Incarnation insists that God\'s saving work is tactile.',
    source: 'research',
    specificReference: 'Fisher et al., library touch study (1976); Crusco & Wetzel, touch and tipping (1984); Guéguen, "Touch and Helping Behavior" (1992-2010)',
    spinnable: true,
  },
  {
    id: 'self-distancing-wisdom',
    title: 'You Give Better Advice to Others Than to Yourself',
    era: '2012',
    category: 'psychology-science',
    themes: ['wisdom', 'self-deception', 'perspective', 'community', 'counsel'],
    oneLineSummary: 'Kross found that when people refer to themselves in the third person ("What should John do?"), they make wiser, less emotionally reactive decisions — self-distance produces the perspective we lack in first person.',
    spiritualAngle: 'This is why you need a community of advisors, not just your own prayers. The wisdom you would give a friend about your exact situation is wisdom you literally cannot access from inside it.',
    source: 'research',
    specificReference: 'Ethan Kross, "Self-Distancing and Wise Reasoning" (2012), Journal of Personality and Social Psychology; replicated across cultures (Grossmann & Kross)',
    spinnable: true,
  },
  {
    id: 'contact-comfort-dying',
    title: 'Holding a Dying Person\'s Hand Changes Their Brain Activity',
    era: '2020',
    category: 'psychology-science',
    themes: ['death', 'presence', 'comfort', 'community', 'love', 'compassion'],
    oneLineSummary: 'Blundon\'s research showed that hearing a familiar voice and feeling touch produces measurable changes in brain activity even in unresponsive dying patients — presence registers when nothing else does.',
    spiritualAngle: '"I will be with you" may be the most important thing God says — because neurologically, presence is the last thing to go. Being with someone who is suffering is not insufficient. It is everything.',
    source: 'research',
    specificReference: 'Elizabeth Blundon et al., "Electrophysiological evidence of preserved hearing at end of life" (2020), Scientific Reports',
    spinnable: true,
  },

  // ==========================================
  // DEVELOPMENTAL / EDUCATIONAL PSYCHOLOGY
  // ==========================================
  {
    id: 'zone-of-proximal-development',
    title: 'Growth Happens in the Gap Between Can and Cannot',
    era: '1978',
    category: 'psychology-science',
    themes: ['growth', 'mentorship', 'scaffolding', 'discipleship', 'challenge'],
    oneLineSummary: 'Vygotsky identified the zone of proximal development — the space between what you can do alone and what you can do with help — as the only zone where learning actually occurs.',
    spiritualAngle: 'God consistently gives tasks slightly beyond your current ability with the implicit promise of help — Abraham leaving home, Moses confronting Pharaoh, Peter walking on water. Growth requires a guide and a stretch.',
    source: 'research',
    specificReference: 'Lev Vygotsky, "Mind in Society" (1978, posthumous); zone of proximal development and scaffolding theory',
    spinnable: true,
  },
  {
    id: 'spacing-effect-memory',
    title: 'Cramming Fails — Spaced Repetition Builds Forever',
    era: '1885',
    category: 'psychology-science',
    themes: ['discipline', 'habit', 'faithfulness', 'formation', 'daily-practice'],
    oneLineSummary: 'Ebbinghaus discovered that distributed practice over time produces dramatically stronger memories than concentrated study — the "spacing effect" is one of the most robust findings in all of psychology.',
    spiritualAngle: 'Daily devotion over decades beats a weekend retreat every time. God designed memory to reward faithfulness over intensity — "line upon line, precept upon precept."',
    source: 'research',
    specificReference: 'Hermann Ebbinghaus, "Memory: A Contribution to Experimental Psychology" (1885); Cepeda et al., spacing effect meta-analysis (2006)',
    spinnable: true,
  },
  {
    id: 'desirable-difficulties',
    title: 'Making Learning Harder Makes It Last Longer',
    era: '1994',
    category: 'psychology-science',
    themes: ['suffering', 'growth', 'difficulty', 'depth', 'perseverance'],
    oneLineSummary: 'Bjork showed that conditions that make learning feel harder — testing, spacing, interleaving — actually produce deeper, more durable knowledge than conditions that feel easy and fluent.',
    spiritualAngle: 'The season that feels most confusing and difficult may be the one producing the deepest formation. Fluency feels good but builds shallow. Struggle feels bad but builds deep.',
    source: 'research',
    specificReference: 'Robert Bjork, "Desirable Difficulties" framework (1994); Bjork & Bjork, "Making Things Hard on Yourself" (2011)',
    spinnable: true,
  },
  {
    id: 'generation-effect',
    title: 'You Remember What You Generate, Not What You Receive',
    era: '1978',
    category: 'psychology-science',
    themes: ['participation', 'discipleship', 'co-creation', 'active-faith', 'engagement'],
    oneLineSummary: 'Slamecka and Graf found that information you actively generate is remembered far better than information you passively receive — the act of creation embeds knowledge deeper.',
    spiritualAngle: 'This is why God asks questions rather than giving answers, why Jesus taught in parables rather than propositions. Faith that you wrestle into existence is stronger than faith handed to you.',
    source: 'research',
    specificReference: 'Slamecka & Graf, "The generation effect" (1978), Journal of Experimental Psychology: Human Learning and Memory',
    spinnable: true,
  },
  {
    id: 'testing-effect',
    title: 'Being Tested on Something Is Better Than Studying It Again',
    era: '2006',
    category: 'psychology-science',
    themes: ['testing', 'trials', 'growth', 'formation', 'memory'],
    oneLineSummary: 'Roediger and Karpicke demonstrated that retrieving information from memory (testing) strengthens it more than re-studying it — being tested is the superior form of learning.',
    spiritualAngle: 'James writes "consider it joy when you face trials" — not because suffering is good but because retrieval under pressure is how faith moves from short-term to permanent. Tests are formation.',
    source: 'research',
    specificReference: 'Roediger & Karpicke, "The Power of Testing Memory" (2006), Perspectives on Psychological Science; retrieval practice research',
    spinnable: true,
  },

  // ==========================================
  // EVOLUTIONARY PSYCHOLOGY / ANTHROPOLOGY
  // ==========================================
  {
    id: 'campfire-hypothesis',
    title: 'Fire Extended Conversation and Created Culture',
    era: '2014',
    category: 'psychology-science',
    themes: ['community', 'storytelling', 'gathering', 'rest', 'formation'],
    oneLineSummary: 'Wiessner studied Bushman fireside conversations and found that while daytime talk is 80% economic, nighttime fireside talk is 80% storytelling — fire literally created the conditions for imagination, bonding, and culture.',
    spiritualAngle: 'The campfire is the original church: people gathered around shared light in the darkness, telling the stories that hold the community together. Every worship gathering echoes this ancient architecture.',
    source: 'research',
    specificReference: 'Polly Wiessner, "Embers of society: Firelight talk among the Ju/\'hoansi Bushmen" (2014), PNAS',
    spinnable: true,
  },
  {
    id: 'dunbar-storytelling-bonding',
    title: 'Stories Bond Larger Groups Than Grooming Ever Could',
    era: '2017',
    category: 'psychology-science',
    themes: ['storytelling', 'community', 'church', 'narrative', 'belonging'],
    oneLineSummary: 'Dunbar showed that primates bond through grooming, limited to pairs, but humans evolved storytelling and laughter as "vocal grooming" — enabling social bonds across groups of 150.',
    spiritualAngle: 'The church has always been built on shared stories — testimony, Scripture, the Eucharist narrative. Stories are not decoration on community; they are the mechanism of community.',
    source: 'research',
    specificReference: 'Robin Dunbar, "The Social Brain, Language, and Storytelling" (2017); "Human Evolution" (2014)',
    spinnable: true,
  },
  {
    id: 'cooperative-breeding-human-altruism',
    title: 'Humans Are the Only Apes That Let Others Raise Their Children',
    era: '2009',
    category: 'psychology-science',
    themes: ['community', 'trust', 'interdependence', 'parenting', 'village'],
    oneLineSummary: 'Hrdy argues that human altruism evolved because we are cooperative breeders — the only great ape that routinely entrusts infants to non-parents. This required reading others\' intentions, which built our social intelligence.',
    spiritualAngle: '"It takes a village" is not a cliché but an evolutionary fact. Human cognition — including our capacity for faith, empathy, and morality — emerged because we learned to trust others with what we love most.',
    source: 'research',
    specificReference: 'Sarah Blaffer Hrdy, "Mothers and Others: The Evolutionary Origins of Mutual Understanding" (2009), Harvard University Press',
    spinnable: true,
  },
  {
    id: 'tears-unique-to-humans',
    title: 'Humans Are the Only Animals That Cry from Emotion',
    era: '2013',
    category: 'psychology-science',
    themes: ['emotion', 'uniqueness', 'vulnerability', 'communication', 'compassion'],
    oneLineSummary: 'Vingerhoets confirmed that emotional tears are unique to humans — no other species produces tears from grief, joy, or empathy. Emotional tears have a different chemical composition than reflex tears, containing stress hormones and natural painkillers.',
    spiritualAngle: '"Jesus wept" is not weakness — it is the most human act in Scripture. Tears are the body\'s way of externalizing inner pain, inviting others into it. God gave humans this signal and no other creature.',
    source: 'research',
    specificReference: 'Ad Vingerhoets, "Why Only Humans Weep" (2013), Oxford University Press; Frey, biochemistry of emotional tears (1985)',
    spinnable: true,
  },

  // ==========================================
  // ECOLOGY / EARTH SCIENCE
  // ==========================================
  {
    id: 'mycorrhizal-resource-sharing',
    title: 'Dying Trees Send Their Resources to Their Neighbors',
    era: '2015',
    category: 'psychology-science',
    themes: ['sacrifice', 'legacy', 'death-brings-life', 'generosity', 'community'],
    oneLineSummary: 'Simard found that dying trees dump massive amounts of carbon into the mycorrhizal network — transferring their accumulated resources to surrounding trees before they die.',
    spiritualAngle: 'A dying tree\'s last act is generosity. The final words and gifts of dying saints follow this same pattern — inheritance is the tree kingdom\'s version of a blessing before death.',
    source: 'research',
    specificReference: 'Suzanne Simard, "Dying Trees Transfer Resources to Neighbors" (2015); isotope tracing studies, University of British Columbia',
    spinnable: true,
  },
  {
    id: 'keystone-species',
    title: 'One Species Can Hold an Entire Ecosystem Together',
    era: '1969',
    category: 'psychology-science',
    themes: ['calling', 'purpose', 'influence', 'leadership', 'small-things-matter'],
    oneLineSummary: 'Paine discovered that removing a single species of starfish from a tidal ecosystem caused the entire community to collapse — some organisms have influence far beyond their size.',
    spiritualAngle: '"You are the salt of the earth" — a small amount of the right ingredient preserves everything around it. Faithfulness in one person can hold an entire community\'s ecosystem together.',
    source: 'research',
    specificReference: 'Robert Paine, "Food Web Complexity and Species Diversity" (1966), American Naturalist; keystone species concept (1969)',
    spinnable: true,
  },
  {
    id: 'wolves-change-rivers',
    title: 'Reintroducing Wolves to Yellowstone Changed the Rivers',
    era: '1995',
    category: 'psychology-science',
    themes: ['restoration', 'ripple-effect', 'influence', 'return', 'healing'],
    oneLineSummary: 'When wolves were reintroduced to Yellowstone in 1995, the trophic cascade was so dramatic that elk behavior changes allowed vegetation to regrow, which stabilized riverbanks, which literally altered the course of rivers.',
    spiritualAngle: 'Restoring one thing to its rightful place can change everything downstream. One act of restoration — one returned prodigal, one healed relationship — creates cascading effects you cannot predict.',
    source: 'research',
    specificReference: 'Ripple & Beschta, "Trophic Cascades in Yellowstone" (2012), Biological Conservation; wolf reintroduction (1995-present)',
    spinnable: true,
  },
  {
    id: 'mangrove-roots-protection',
    title: 'The Trees That Protect Land by Standing in the Storm',
    era: '2005',
    category: 'psychology-science',
    themes: ['protection', 'sacrifice', 'steadfastness', 'community', 'shelter'],
    oneLineSummary: 'Mangrove forests reduce tsunami wave height by up to 90% and absorb storm surges — they protect inland communities by positioning themselves in the most dangerous place.',
    spiritualAngle: 'Some callings require standing in the storm so others behind you are shielded. The protectors do not flee danger — they root into it. Christ-like leadership looks like a mangrove.',
    source: 'research',
    specificReference: 'Danielsen et al., "The Asian tsunami: a protective role for coastal vegetation" (2005), Science; post-2004 tsunami mangrove studies',
    spinnable: true,
  },
  {
    id: 'desert-varnish-time',
    title: 'The Desert Builds a Protective Coat That Takes Millennia',
    era: '1998',
    category: 'psychology-science',
    themes: ['patience', 'time', 'protection', 'slow-work', 'faithfulness'],
    oneLineSummary: 'Desert varnish — the dark coating on desert rocks — takes 2,000 to 10,000 years to form through the slow work of bacteria and mineral deposition, creating a protective shell one micron at a time.',
    spiritualAngle: 'Some of God\'s most protective work is measured in millennia, not moments. The coating that shields you from the elements is being built so slowly you cannot watch it happen.',
    source: 'research',
    specificReference: 'Dorn, "Rock Coatings" (1998), Elsevier; Kuhlman et al., microbial role in desert varnish formation',
    spinnable: true,
  },

  // ==========================================
  // PSYCHOLOGY OF RELIGION / MEANING
  // ==========================================
  {
    id: 'deathbed-regrets-study',
    title: 'The Dying Regret Inaction More Than Action',
    era: '2018',
    category: 'psychology-science',
    themes: ['regret', 'courage', 'action', 'calling', 'fear', 'faithfulness'],
    oneLineSummary: 'Across multiple studies, Davidai and Gilovich found that people\'s biggest regrets are overwhelmingly about inaction — things they did not do, say, or become — rather than mistakes they made.',
    spiritualAngle: 'The parable of the talents is a warning about inaction, not about failure. The servant who buried his talent was not punished for losing — he was punished for never trying.',
    source: 'research',
    specificReference: 'Davidai & Gilovich, "The Ideal Road Not Taken" (2018), Emotion; Gilovich & Medvec, action/inaction regret research (1995)',
    spinnable: true,
  },
  {
    id: 'quiet-ego',
    title: 'The Healthiest Self Is a Quiet Self, Not a Loud One',
    era: '2013',
    category: 'psychology-science',
    themes: ['humility', 'ego', 'identity', 'self-transcendence', 'wisdom'],
    oneLineSummary: 'Wayment and Bauer defined the "quiet ego" — not low self-esteem but a balanced, non-defensive self-awareness that includes others — and linked it to growth, compassion, and resilience.',
    spiritualAngle: 'Jesus did not teach self-hatred but quiet ego: a self secure enough to wash feet, absorb insults, and say "not my will but yours." Strength through non-defensiveness, not through volume.',
    source: 'research',
    specificReference: 'Heidi Wayment & Jack Bauer, "The Quiet Ego: Motives for Self-Other Balance" (2013), Journal of Happiness Studies',
    spinnable: true,
  },
  {
    id: 'awe-time-perception',
    title: 'Awe Makes Time Feel Expanded',
    era: '2012',
    category: 'psychology-science',
    themes: ['awe', 'presence', 'time', 'wonder', 'worship', 'sabbath'],
    oneLineSummary: 'Rudd found that people who experienced awe reported feeling like they had more time available, were less impatient, and were more willing to volunteer — awe literally dilates the subjective experience of time.',
    spiritualAngle: '"A thousand years are like a day" in God\'s presence may describe a real perceptual phenomenon: in awe, time stretches. Worship does not take time from you — it gives you the experience of having more.',
    source: 'research',
    specificReference: 'Melanie Rudd et al., "Awe Expands People\'s Perception of Time" (2012), Psychological Science',
    spinnable: true,
  },
  {
    id: 'expressive-suppression-cost',
    title: 'Hiding Your Emotions Is Exhausting for Everyone in the Room',
    era: '2003',
    category: 'psychology-science',
    themes: ['authenticity', 'vulnerability', 'masks', 'community', 'confession'],
    oneLineSummary: 'Gross found that suppressing emotional expression not only increases the suppressor\'s blood pressure but also raises the blood pressure of conversation partners — emotional hiding is physiologically costly to everyone nearby.',
    spiritualAngle: 'Wearing a mask at church does not just exhaust you — it physiologically stresses the people around you. Authenticity is not just self-care; it is an act of love for your community.',
    source: 'research',
    specificReference: 'James Gross, "Emotion Regulation: Affective, Cognitive, and Social Consequences" (2003); Butler et al., suppression and physiological responses in dyads (2003)',
    spinnable: true,
  },
  {
    id: 'purpose-longevity',
    title: 'Having a Purpose Adds Years to Your Life',
    era: '2019',
    category: 'psychology-science',
    themes: ['purpose', 'calling', 'meaning', 'life', 'vocation'],
    oneLineSummary: 'A meta-analysis of over 136,000 participants found that having a strong sense of purpose in life was associated with a 15% lower risk of all-cause mortality — purpose is literally life-extending.',
    spiritualAngle: '"For I know the plans I have for you" is not just encouragement — it is a health intervention. Believing your life has purpose measurably extends how long you live it.',
    source: 'research',
    specificReference: 'Cohen et al., "Purpose in Life and Its Relationship to All-Cause Mortality and Cardiovascular Events" (2016), Psychosomatic Medicine; Alimujiang et al. (2019), JAMA Network Open',
    spinnable: true,
  },

  // ==========================================
  // ADDITIONAL NATURE / BIOLOGY
  // ==========================================
  {
    id: 'octopus-distributed-intelligence',
    title: 'Two-Thirds of an Octopus\'s Brain Is in Its Arms',
    era: '2019',
    category: 'psychology-science',
    themes: ['embodiment', 'wisdom', 'diversity', 'intelligence', 'different-ways-of-knowing'],
    oneLineSummary: 'An octopus has 500 million neurons, but two-thirds are in its arms — each arm can taste, touch, and make independent decisions without consulting the central brain.',
    spiritualAngle: 'The body of Christ has distributed intelligence too. Not all wisdom comes from the "head" — hands, feet, and overlooked members carry their own knowledge. "The eye cannot say to the hand, I have no need of you."',
    source: 'research',
    specificReference: 'Godfrey-Smith, "Other Minds: The Octopus, the Sea, and the Deep Origins of Consciousness" (2016); Zullo et al., octopus arm autonomy (2019)',
    spinnable: true,
  },
  {
    id: 'earthquake-diamond-formation',
    title: 'Diamonds Form Under Extreme Pressure and Erupt Through Violence',
    era: '1797',
    category: 'psychology-science',
    themes: ['pressure', 'beauty', 'refinement', 'suffering', 'transformation'],
    oneLineSummary: 'Diamonds crystallize 150 km deep under 50,000 atmospheres of pressure, then reach the surface only through violent kimberlite eruptions — the most extreme volcanic events on Earth.',
    spiritualAngle: 'The most precious thing in you was formed under the most pressure and only became visible through eruption. The conditions you resented were the conditions required.',
    source: 'research',
    specificReference: 'Tennant, proof that diamond is pure carbon (1797); Haggerty, kimberlite pipe eruption dynamics and diamond transport',
    spinnable: true,
  },
  {
    id: 'pearl-formation-irritant',
    title: 'A Pearl Is an Oyster\'s Response to an Injury',
    era: 'ancient',
    category: 'psychology-science',
    themes: ['suffering', 'beauty', 'transformation', 'redemption', 'response'],
    oneLineSummary: 'A pearl forms when a foreign irritant enters the oyster — the animal coats the painful intrusion with layer after layer of nacre until the wound becomes the most valuable thing inside it.',
    spiritualAngle: 'The thing that hurt you becomes the thing of value — not because the wound was good, but because your response to it was. Beauty is often a wound that received enough layers of grace.',
    source: 'research',
    specificReference: 'Mikimoto pearl cultivation research; Addadi & Weiner, biomineralization and nacre formation studies',
    spinnable: true,
  },
  {
    id: 'kintsugi-brain-healing',
    title: 'Broken Bones Heal Stronger at the Break Point',
    era: '1892',
    category: 'psychology-science',
    themes: ['healing', 'brokenness', 'strength', 'restoration', 'redemption'],
    oneLineSummary: 'Wolff\'s Law demonstrates that bones remodel themselves in response to stress — a healed fracture develops a callus that is temporarily stronger than the original bone, as if the body over-engineers the repair.',
    spiritualAngle: 'God does not just fix the break — God over-engineers the repair. "He heals the brokenhearted" does not mean returning to baseline; it means the healed place becomes the strongest place.',
    source: 'research',
    specificReference: 'Julius Wolff, "The Law of Bone Remodelling" (1892); Frost, mechanostat theory and fracture callus research',
    spinnable: true,
  },
  {
    id: 'crows-remember-faces',
    title: 'Crows Remember Who Helped Them and Who Hurt Them',
    era: '2011',
    category: 'psychology-science',
    themes: ['memory', 'reputation', 'justice', 'consequences', 'relationship'],
    oneLineSummary: 'Marzluff showed that crows recognize individual human faces and hold grudges for years — they teach their offspring which faces to fear and which to trust, passing relational memory across generations.',
    spiritualAngle: 'How you treat the "least of these" is remembered and passed down. Even crows maintain a multi-generational record of kindness and cruelty. Your reputation before God\'s creation is real.',
    source: 'research',
    specificReference: 'John Marzluff, "Lasting recognition of threatening people by wild American crows" (2011), Animal Behaviour; University of Washington mask experiments',
    spinnable: true,
  },
  {
    id: 'cordyceps-parasitic-control',
    title: 'The Fungus That Hijacks Ants\' Brains',
    era: '2011',
    category: 'psychology-science',
    themes: ['spiritual-warfare', 'deception', 'control', 'awareness', 'bondage'],
    oneLineSummary: 'Cordyceps fungi infect ants and hijack their nervous systems — the ant climbs to a specific height, bites a leaf vein, and locks in place while the fungus consumes it from within and sprouts from its head.',
    spiritualAngle: 'Sin in Scripture works exactly like cordyceps: it takes over gradually, makes you think your actions are your own, positions you precisely where you are most useful to its purposes, and consumes you from within.',
    source: 'research',
    specificReference: 'Hughes et al., "Behavioral mechanisms and morphological symptoms of zombie ants" (2011), BMC Ecology; Ophiocordyceps unilateralis research',
    spinnable: true,
  },
  {
    id: 'caterpillar-imaginal-discs',
    title: 'Inside the Cocoon, the Caterpillar Completely Dissolves',
    era: '2008',
    category: 'psychology-science',
    themes: ['transformation', 'death-to-self', 'resurrection', 'new-creation', 'identity'],
    oneLineSummary: 'During metamorphosis, a caterpillar does not gradually grow wings — it dissolves into liquid. The butterfly is built from scratch using "imaginal discs" — cell clusters that survived the dissolution and contain the blueprint for the new form.',
    spiritualAngle: '"If anyone is in Christ, the new creation has come." Transformation is not renovation — it is dissolution and rebuilding. Something in you survives the destruction and carries the blueprint of who you are becoming.',
    source: 'research',
    specificReference: 'Blackiston et al., "Retention of memory through metamorphosis" (2008), PLoS ONE; imaginal disc biology research',
    spinnable: true,
  },
  {
    id: 'prairie-deep-roots',
    title: 'A Prairie\'s Roots Go Deeper Than Its Grass Is Tall',
    era: '1950',
    category: 'psychology-science',
    themes: ['roots', 'depth', 'hidden-life', 'foundation', 'resilience'],
    oneLineSummary: 'Prairie grasses that appear to be three feet tall have root systems extending fifteen feet underground — the invisible foundation is five times larger than the visible plant.',
    spiritualAngle: 'What sustains a life of faith is mostly invisible. The prayer life, the private worship, the unseen discipline — the root system must be five times deeper than the visible fruit.',
    source: 'research',
    specificReference: 'Weaver, "Root Development of Field Crops" (1926); USDA prairie root depth studies; Tallgrass Prairie National Preserve ecology',
    spinnable: true,
  },

  // ==========================================
  // COGNITIVE SCIENCE / DECISION MAKING
  // ==========================================
  {
    id: 'cognitive-load-moral-decay',
    title: 'When Your Brain Is Tired, Your Morals Are First to Go',
    era: '1999',
    category: 'psychology-science',
    themes: ['temptation', 'rest', 'vigilance', 'sabbath', 'discipline'],
    oneLineSummary: 'Shiv and Fedorikhin found that people under cognitive load chose chocolate cake over fruit salad — when mental resources are depleted, impulse defeats intention. Moral reasoning is the first capacity to degrade.',
    spiritualAngle: '"Watch and pray so that you will not fall into temptation. The spirit is willing, but the flesh is weak." Jesus described cognitive load theory in the Garden of Gethsemane.',
    source: 'research',
    specificReference: 'Shiv & Fedorikhin, "Heart and Mind in Conflict" (1999), Journal of Consumer Research; cognitive depletion and moral reasoning',
    spinnable: true,
  },
  {
    id: 'progress-principle',
    title: 'Small Wins Drive Motivation More Than Big Goals',
    era: '2011',
    category: 'psychology-science',
    themes: ['faithfulness', 'small-steps', 'perseverance', 'encouragement', 'progress'],
    oneLineSummary: 'Amabile found that the single strongest predictor of positive emotion and high motivation at work was making progress on meaningful work — even small, incremental progress on the same day.',
    spiritualAngle: '"Do not despise the day of small things." God designed motivation to run on small daily progress, not big dramatic breakthroughs. The mustard seed strategy works because neuroscience says it does.',
    source: 'research',
    specificReference: 'Teresa Amabile & Steven Kramer, "The Progress Principle" (2011); 12,000 diary entries from knowledge workers, Harvard Business School',
    spinnable: true,
  },
  {
    id: 'incubation-effect',
    title: 'Walking Away from a Problem Is the Best Way to Solve It',
    era: '1926',
    category: 'psychology-science',
    themes: ['rest', 'surrender', 'creativity', 'trust', 'letting-go'],
    oneLineSummary: 'Wallas identified the "incubation" stage of creativity — the period where you stop consciously working on a problem and the solution arrives unbidden during rest, a shower, or a walk.',
    spiritualAngle: '"In returning and rest shall you be saved, in quietness and confidence shall be your strength." Some breakthroughs require disengagement. God works in the background while you sleep.',
    source: 'research',
    specificReference: 'Graham Wallas, "The Art of Thought" (1926), four-stage creativity model; Sio & Ormerod incubation meta-analysis (2009)',
    spinnable: true,
  },
  {
    id: 'elaboration-likelihood-model',
    title: 'Deep Processing Produces Lasting Change, Shallow Processing Fades',
    era: '1986',
    category: 'psychology-science',
    themes: ['depth', 'transformation', 'engagement', 'formation', 'truth'],
    oneLineSummary: 'Petty and Cacioppo showed that persuasion via careful, deep thinking (central route) produces durable attitude change, while persuasion via surface cues (peripheral route) produces change that is fragile and easily reversed.',
    spiritualAngle: 'Faith built on emotional peaks and charismatic speakers (peripheral) fades. Faith built on wrestling with hard questions (central) endures. "Come, let us reason together" is superior formation strategy.',
    source: 'research',
    specificReference: 'Petty & Cacioppo, "Elaboration Likelihood Model" (1986), Advances in Experimental Social Psychology',
    spinnable: true,
  },

  // ==========================================
  // ADDITIONAL HEALTH / BODY SCIENCE
  // ==========================================
  {
    id: 'heart-brain-communication',
    title: 'Your Heart Sends More Signals to Your Brain Than the Reverse',
    era: '1991',
    category: 'psychology-science',
    themes: ['heart', 'wisdom', 'discernment', 'intuition', 'embodiment'],
    oneLineSummary: 'The HeartMath Institute found that the heart sends more neural signals to the brain than the brain sends to the heart — the heart has its own nervous system of 40,000 neurons and can process, learn, and remember independently.',
    spiritualAngle: '"Guard your heart, for it is the wellspring of life." The biblical emphasis on the heart over the mind was not pre-scientific naivety — the heart literally informs and directs the brain.',
    source: 'research',
    specificReference: 'Armour, "Neurocardiology" (1991); McCraty, HeartMath Research Center, heart-brain communication studies',
    spinnable: true,
  },
  {
    id: 'fasting-autophagy',
    title: 'Fasting Triggers the Body\'s Cellular Recycling System',
    era: '2016',
    category: 'psychology-science',
    themes: ['fasting', 'renewal', 'discipline', 'purification', 'restoration'],
    oneLineSummary: 'Ohsumi won the Nobel Prize for discovering autophagy — the process by which cells break down and recycle their own damaged components. Fasting is one of the most powerful triggers of this self-renewal mechanism.',
    spiritualAngle: 'Fasting as a spiritual discipline now has a cellular mechanism: when you deny the body food, it begins cleaning house — dismantling what is damaged and recycling it into new material. Fasting is literal self-renewal.',
    source: 'research',
    specificReference: 'Yoshinori Ohsumi, Nobel Prize in Physiology or Medicine (2016), autophagy mechanisms; Longo, fasting-mimicking diet and cellular regeneration',
    spinnable: true,
  },
  {
    id: 'skin-hunger',
    title: 'Touch Deprivation Is a Medical Condition with Measurable Damage',
    era: '1990',
    category: 'psychology-science',
    themes: ['isolation', 'touch', 'incarnation', 'embodiment', 'community'],
    oneLineSummary: 'Romanian orphanage studies showed that children deprived of physical touch developed stunted growth, impaired brain development, and elevated cortisol — the body literally fails to develop without human contact.',
    spiritualAngle: 'The Incarnation — God becoming touchable flesh — addresses the deepest human need. "The Word became flesh" is not theology for theologians; it is medicine for a touch-starved species.',
    source: 'research',
    specificReference: 'Nelson et al., Bucharest Early Intervention Project (2007); Rutter, English & Romanian Adoptees study (1990s); cortisol and growth hormone disruption in institutionalized children',
    spinnable: true,
  },
  {
    id: 'crying-catharsis-social',
    title: 'Crying Only Helps When Someone Is Watching',
    era: '2008',
    category: 'psychology-science',
    themes: ['vulnerability', 'community', 'grief', 'witness', 'presence'],
    oneLineSummary: 'Bylsma found that crying is only cathartic when done in the presence of a close, supportive other. Crying alone or in a hostile environment has no benefit or makes things worse.',
    spiritualAngle: '"Weep with those who weep" is not decorative advice — it is the mechanism that makes grief productive. Tears require a witness. Suffering metabolized alone stays toxic.',
    source: 'research',
    specificReference: 'Lauren Bylsma et al., "When is Crying Cathartic?" (2008), Journal of Social and Clinical Psychology',
    spinnable: true,
  },

  // ==========================================
  // POSITIVE PSYCHOLOGY / WELL-BEING
  // ==========================================
  {
    id: 'naikan-reflection-gratitude',
    title: 'The Japanese Practice of Counting What You Received',
    era: '1953',
    category: 'psychology-science',
    themes: ['gratitude', 'humility', 'awareness', 'dependence', 'grace'],
    oneLineSummary: 'Naikan therapy asks three questions daily: What did I receive? What did I give? What trouble did I cause? Research shows this practice dramatically shifts perspective from entitlement to gratitude.',
    spiritualAngle: 'The Naikan questions mirror the Examen prayer: receiving, giving, confessing. Systematic attention to what you have been given — rather than what you deserve — physically rewires the brain toward humility.',
    source: 'research',
    specificReference: 'Yoshimoto Ishin, Naikan therapy (1953); Krech, "Naikan: Gratitude, Grace, and the Japanese Art of Self-Reflection" (2002); adapted clinical applications',
    spinnable: true,
  },
  {
    id: 'self-transcendence-well-being',
    title: 'The Happiest People Have Moved Past Themselves',
    era: '2018',
    category: 'psychology-science',
    themes: ['self-transcendence', 'purpose', 'service', 'joy', 'calling'],
    oneLineSummary: 'Yaden and Haidt found that self-transcendent experiences — awe, flow, meditation, service — are the strongest predictors of well-being, stronger than self-focused pleasures or achievements.',
    spiritualAngle: '"Whoever loses their life for my sake will find it" is the central finding of self-transcendence research: the path to your deepest well-being runs through forgetting yourself.',
    source: 'research',
    specificReference: 'David Yaden & Jonathan Haidt, "The Varieties of Self-Transcendent Experience" (2018), Review of General Psychology',
    spinnable: true,
  },
  {
    id: 'compassion-vs-empathy-burnout',
    title: 'Empathy Burns You Out, Compassion Energizes You',
    era: '2014',
    category: 'psychology-science',
    themes: ['compassion', 'empathy', 'burnout', 'service', 'boundaries', 'resilience'],
    oneLineSummary: 'Singer found that empathy (feeling others\' pain as your own) activates pain circuits and leads to burnout, while compassion (warm concern without merging) activates reward circuits and is sustainable.',
    spiritualAngle: 'Jesus had compassion, not unbounded empathy. He wept at Lazarus\' tomb but also withdrew to pray alone. The sustainable form of caring is warm concern with boundaries, not total emotional absorption.',
    source: 'research',
    specificReference: 'Tania Singer & Olga Klimecki, "Empathy and Compassion" (2014), Current Biology; ReSource Project, Max Planck Institute',
    spinnable: true,
  },
  {
    id: 'best-possible-self',
    title: 'Imagining Your Best Future Improves Your Present',
    era: '2001',
    category: 'psychology-science',
    themes: ['hope', 'vision', 'future', 'optimism', 'calling'],
    oneLineSummary: 'King found that writing about your "best possible self" for 20 minutes daily for four days produced significant increases in positive affect and reduced illness visits for months afterward.',
    spiritualAngle: '"Where there is no vision, the people perish." Concretely imagining the future God has for you is not daydreaming — it is a clinically validated intervention that pulls your present toward your purpose.',
    source: 'research',
    specificReference: 'Laura King, "The Health Benefits of Writing about Life Goals" (2001), Personality and Social Psychology Bulletin',
    spinnable: true,
  },
  {
    id: 'nature-attention-restoration',
    title: 'Twenty Minutes in Nature Restores Your Brain',
    era: '1989',
    category: 'psychology-science',
    themes: ['creation', 'rest', 'restoration', 'attention', 'sabbath', 'nature'],
    oneLineSummary: 'Kaplan\'s attention restoration theory shows that natural environments replenish directed attention, reduce mental fatigue, and lower cortisol — 20 minutes in a park produces measurable cognitive recovery.',
    spiritualAngle: 'God placed humanity in a garden, not a library. The consistent biblical pattern of meeting God in wilderness, on mountains, and beside waters reflects a neurological truth: creation restores the capacity to pay attention.',
    source: 'research',
    specificReference: 'Stephen & Rachel Kaplan, Attention Restoration Theory (1989); "The Experience of Nature" (1989); Hunter et al., 20-minute nature dose (2019), Frontiers in Psychology',
    spinnable: true,
  },

  // ==========================================
  // ADDITIONAL UNIQUE FINDINGS
  // ==========================================
  {
    id: 'grandmother-hypothesis',
    title: 'Humans Are the Only Species with Grandmothers — And It Changes Everything',
    era: '1998',
    category: 'psychology-science',
    themes: ['legacy', 'generativity', 'wisdom', 'elders', 'purpose', 'community'],
    oneLineSummary: 'Hawkes proposed that human post-menopausal longevity — unique among primates — evolved because grandmothers who helped raise grandchildren dramatically increased their family\'s survival, making elder wisdom biologically essential.',
    spiritualAngle: 'The elder generation is not past its purpose — it is entering its most important one. The biblical pattern of elders as community pillars reflects a biological truth: grandparent investment changes survival rates.',
    source: 'research',
    specificReference: 'Kristen Hawkes, "Grandmother Hypothesis" (1998), PNAS; Lahdenperä et al., grandmothers and grandchild survival (2004), Nature',
    spinnable: true,
  },
  {
    id: 'attention-shapes-reality',
    title: 'What You Pay Attention to Becomes Your Life',
    era: '2009',
    category: 'psychology-science',
    themes: ['attention', 'worship', 'formation', 'focus', 'becoming'],
    oneLineSummary: 'Killingsworth and Gilbert found that people spend 47% of waking hours mind-wandering, and mind-wandering predicts unhappiness regardless of activity — what you attend to literally becomes the quality of your experience.',
    spiritualAngle: '"Set your minds on things above" is attentional therapy. You become what you behold. The practice of redirecting attention toward God is not escapism — it is the most practical thing you can do for your happiness.',
    source: 'research',
    specificReference: 'Matthew Killingsworth & Daniel Gilbert, "A Wandering Mind Is an Unhappy Mind" (2010), Science; Harvard experience-sampling study',
    spinnable: true,
  },
  {
    id: 'dark-adaptation-vision',
    title: 'Your Eyes Need 30 Minutes of Darkness to Fully See in the Dark',
    era: '1945',
    category: 'psychology-science',
    themes: ['patience', 'darkness', 'adaptation', 'faith', 'waiting', 'perception'],
    oneLineSummary: 'Dark adaptation — the process by which the eye adjusts from bright light to darkness — takes up to 30 minutes. During this time, sensitivity increases 100,000-fold as rhodopsin regenerates in the rod cells.',
    spiritualAngle: 'When you first enter a dark season, you are blind. But if you stay — if you do not flee back to the artificial light — your eyes adjust. The dark night of the soul requires patience, not escape.',
    source: 'research',
    specificReference: 'Hecht et al., scotopic vision and dark adaptation curve (1937-1945); duplex retina theory; rhodopsin regeneration kinetics',
    spinnable: true,
  },
  {
    id: 'social-facilitation',
    title: 'You Perform Better When Someone Is Watching',
    era: '1898',
    category: 'psychology-science',
    themes: ['accountability', 'community', 'witness', 'performance', 'presence'],
    oneLineSummary: 'Triplett found that cyclists rode faster when racing against others than alone — the mere presence of another person enhances performance on well-practiced tasks.',
    spiritualAngle: '"Spur one another on toward love and good deeds" is social facilitation applied to faith. You will run the race faster when you are not running it alone.',
    source: 'research',
    specificReference: 'Norman Triplett, "The Dynamogenic Factors in Pacemaking and Competition" (1898), American Journal of Psychology; considered the first social psychology experiment',
    spinnable: true,
  },
  {
    id: 'emotional-contagion',
    title: 'Emotions Spread Like Viruses Through Social Networks',
    era: '2014',
    category: 'psychology-science',
    themes: ['influence', 'community', 'joy', 'witness', 'emotional-health'],
    oneLineSummary: 'Kramer found that emotions are contagious even through text — when Facebook reduced positive posts in users\' feeds, those users generated fewer positive posts themselves, and the effect cascaded through their networks.',
    spiritualAngle: '"Rejoice with those who rejoice" is epidemiology: joy spreads through social networks like a contagion. Your emotional state is not private — it infects everyone connected to you.',
    source: 'research',
    specificReference: 'Adam Kramer et al., "Experimental evidence of massive-scale emotional contagion through social networks" (2014), PNAS; Fowler & Christakis, happiness networks (2008)',
    spinnable: true,
  },
];
