// ==========================================
// STORY REPOSITORY: BIBLICAL DEEP CUTS
// Obscure, overlooked, and underappreciated biblical narratives
// Used by AI devotional generation as illustration source material
// ==========================================

export interface BiblicalStoryEntry {
  id: string;
  title: string;
  era: string;
  category: 'biblical';
  themes: string[];
  oneLineSummary: string;
  scriptureConnection: string;
  source: 'biblical';
  spinnable: boolean;
}

export const BIBLICAL_DEEP_CUT_STORIES: BiblicalStoryEntry[] = [
  // ==========================================
  // GENEALOGY STORIES — Hidden People, Hidden Depth
  // ==========================================
  {
    id: 'jabez-prayer-in-the-genealogy',
    title: 'The Prayer Buried in a Genealogy',
    era: '~1000 BC',
    category: 'biblical',
    themes: ['prayer', 'pain', 'blessing', 'overlooked', 'audacity', 'hope'],
    oneLineSummary: 'Jabez appears in a dry genealogy list but his desperate prayer for blessing interrupts the monotony — and God grants it.',
    scriptureConnection: '1 Chronicles 4:9-10',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'zelophehads-daughters-inheritance',
    title: 'Five Sisters Who Changed Inheritance Law',
    era: '~1400 BC',
    category: 'biblical',
    themes: ['justice', 'women', 'courage', 'advocacy', 'inheritance', 'precedent'],
    oneLineSummary: 'Zelophehad\'s five daughters petitioned Moses for land rights when their father died without sons, and God sided with them.',
    scriptureConnection: 'Numbers 27:1-11',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'tamar-judah-radical-act',
    title: 'Tamar\'s Radical Act of Justice',
    era: '~1800 BC',
    category: 'biblical',
    themes: ['justice', 'desperation', 'shame', 'lineage', 'women', 'redemption'],
    oneLineSummary: 'Tamar disguised herself to confront Judah\'s broken promise, and rather than being condemned, she ended up in Jesus\'s genealogy.',
    scriptureConnection: 'Genesis 38; Matthew 1:3',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'rahab-in-jesus-lineage',
    title: 'A Prostitute in the Messiah\'s Family Tree',
    era: '~1400 BC',
    category: 'biblical',
    themes: ['grace', 'inclusion', 'faith', 'outsider', 'redemption', 'lineage'],
    oneLineSummary: 'Rahab the Canaanite prostitute hid Israelite spies, was spared in Jericho\'s fall, and became the great-great-grandmother of King David.',
    scriptureConnection: 'Joshua 2; Matthew 1:5; Hebrews 11:31',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'perez-breach-birth',
    title: 'The Twin Who Broke Through First',
    era: '~1800 BC',
    category: 'biblical',
    themes: ['breakthrough', 'lineage', 'unexpected', 'persistence', 'birth'],
    oneLineSummary: 'During Tamar\'s twin birth, Perez pushed past his brother Zerah to emerge first — his name means "breach" — and he became ancestor to David and Jesus.',
    scriptureConnection: 'Genesis 38:27-30; Ruth 4:18-22',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'bathsheba-lineage-survivor',
    title: 'From Victim to Queen Mother to Messiah\'s Ancestor',
    era: '~1000 BC',
    category: 'biblical',
    themes: ['suffering', 'survival', 'women', 'power', 'lineage', 'agency'],
    oneLineSummary: 'Bathsheba survived David\'s abuse of power, lost her first child, and became mother to Solomon and a direct ancestor of Jesus.',
    scriptureConnection: '2 Samuel 11-12; Matthew 1:6',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'enoch-walked-with-god',
    title: 'The Man Who Skipped Death',
    era: 'Antediluvian',
    category: 'biblical',
    themes: ['intimacy', 'walking-with-God', 'mystery', 'faith', 'eternity'],
    oneLineSummary: 'In a genealogy where everyone "lived and died," Enoch simply "walked with God, and was not, for God took him."',
    scriptureConnection: 'Genesis 5:24; Hebrews 11:5',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'shiphrah-puah-hebrew-midwives',
    title: 'Two Midwives Who Defied a Pharaoh',
    era: '~1500 BC',
    category: 'biblical',
    themes: ['civil-disobedience', 'courage', 'women', 'life', 'resistance', 'fear-of-God'],
    oneLineSummary: 'Shiphrah and Puah lied to Pharaoh to save Hebrew babies, and God rewarded their defiance with families of their own.',
    scriptureConnection: 'Exodus 1:15-21',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'bezalel-first-spirit-filled',
    title: 'The First Person Filled with the Spirit Was an Artist',
    era: '~1440 BC',
    category: 'biblical',
    themes: ['creativity', 'Holy-Spirit', 'craftsmanship', 'calling', 'beauty', 'worship'],
    oneLineSummary: 'Before prophets or priests, Bezalel was the first person Scripture says was "filled with the Spirit of God" — and it was to make art.',
    scriptureConnection: 'Exodus 31:1-5',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'keturah-abrahams-second-wife',
    title: 'Abraham\'s Forgotten Second Marriage',
    era: '~1800 BC',
    category: 'biblical',
    themes: ['life-after-loss', 'new-beginnings', 'overlooked', 'family', 'legacy'],
    oneLineSummary: 'After Sarah died, Abraham married Keturah and had six more children — a whole chapter of life most people skip over.',
    scriptureConnection: 'Genesis 25:1-4',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'obed-edom-ark-blessing',
    title: 'The Man Whose House Blessed an Entire Nation',
    era: '~1000 BC',
    category: 'biblical',
    themes: ['blessing', 'hospitality', 'presence-of-God', 'risk', 'generosity'],
    oneLineSummary: 'After Uzzah died touching the Ark, terrified David parked it at Obed-Edom\'s house — and everything Obed-Edom had was blessed for three months.',
    scriptureConnection: '2 Samuel 6:10-12',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'serach-bat-asher',
    title: 'The Woman Who Lived Across Four Centuries',
    era: '~1800-1400 BC',
    category: 'biblical',
    themes: ['memory', 'witness', 'women', 'generational-wisdom', 'continuity'],
    oneLineSummary: 'Serach daughter of Asher appears in both the migration to Egypt and the Exodus census — Jewish tradition calls her a living link across centuries.',
    scriptureConnection: 'Genesis 46:17; Numbers 26:46',
    source: 'biblical',
    spinnable: true,
  },

  // ==========================================
  // PROPHETIC ACTS — Performance Art as Prophecy
  // ==========================================
  {
    id: 'ezekiel-lying-390-days',
    title: 'The Prophet Who Lay Still for Over a Year',
    era: '~592 BC',
    category: 'biblical',
    themes: ['obedience', 'suffering', 'embodied-theology', 'patience', 'prophecy'],
    oneLineSummary: 'God told Ezekiel to lie on his left side for 390 days and his right side for 40 days, each day representing a year of Israel\'s sin.',
    scriptureConnection: 'Ezekiel 4:1-8',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'hosea-marries-gomer',
    title: 'The Prophet Commanded to Marry Unfaithfulness',
    era: '~750 BC',
    category: 'biblical',
    themes: ['faithfulness', 'love', 'betrayal', 'redemption', 'marriage', 'God-as-husband'],
    oneLineSummary: 'God told Hosea to marry Gomer, a woman who would be unfaithful, as a living parable of how God loves Israel despite her spiritual adultery.',
    scriptureConnection: 'Hosea 1-3',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'isaiah-naked-three-years',
    title: 'The Prophet Who Walked Naked for Three Years',
    era: '~713 BC',
    category: 'biblical',
    themes: ['vulnerability', 'obedience', 'shame', 'prophecy', 'warning', 'humiliation'],
    oneLineSummary: 'God commanded Isaiah to walk naked and barefoot for three years as a sign of the coming shame Egypt and Cush would face in exile.',
    scriptureConnection: 'Isaiah 20:1-6',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'jeremiah-buys-field-during-siege',
    title: 'Buying Real Estate During an Invasion',
    era: '~588 BC',
    category: 'biblical',
    themes: ['hope', 'faith', 'investment', 'future', 'trust', 'defiance'],
    oneLineSummary: 'While Babylon was literally besieging Jerusalem, God told Jeremiah to buy a field — a radical act of faith that God would restore the land.',
    scriptureConnection: 'Jeremiah 32:1-15',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'ezekiel-cooks-over-dung',
    title: 'The Prophet\'s Repulsive Object Lesson',
    era: '~592 BC',
    category: 'biblical',
    themes: ['exile', 'defilement', 'suffering', 'obedience', 'negotiation-with-God'],
    oneLineSummary: 'God told Ezekiel to cook bread over human dung; when Ezekiel protested, God compromised with cow dung — showing even prophets can push back.',
    scriptureConnection: 'Ezekiel 4:12-15',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'agabus-binds-himself',
    title: 'The Prophet Who Tied Himself Up as a Warning',
    era: '~57 AD',
    category: 'biblical',
    themes: ['prophecy', 'warning', 'courage', 'suffering', 'new-testament-prophets'],
    oneLineSummary: 'The prophet Agabus took Paul\'s belt, tied his own hands and feet, and prophesied that\'s what would happen to Paul in Jerusalem.',
    scriptureConnection: 'Acts 21:10-11',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'jeremiah-linen-belt',
    title: 'God\'s Message Hidden in a Rotting Belt',
    era: '~600 BC',
    category: 'biblical',
    themes: ['intimacy', 'decay', 'pride', 'closeness-to-God', 'ruin'],
    oneLineSummary: 'God told Jeremiah to buy a linen belt, wear it, then bury it by the Euphrates — when he dug it up ruined, it pictured how pride ruins intimacy with God.',
    scriptureConnection: 'Jeremiah 13:1-11',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'ezekiel-wife-death-no-mourning',
    title: 'The Prophet Forbidden to Grieve His Wife',
    era: '~588 BC',
    category: 'biblical',
    themes: ['grief', 'loss', 'obedience', 'prophecy', 'sacrifice', 'cost-of-calling'],
    oneLineSummary: 'God told Ezekiel his wife would die and he must not mourn publicly — a devastating sign of how Israel would lose the temple without proper grief.',
    scriptureConnection: 'Ezekiel 24:15-27',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'jeremiah-yoke-of-wood',
    title: 'The Prophet Who Wore an Ox Yoke in Public',
    era: '~594 BC',
    category: 'biblical',
    themes: ['submission', 'truth', 'opposition', 'false-prophets', 'courage'],
    oneLineSummary: 'Jeremiah walked around Jerusalem wearing an ox yoke to show nations must submit to Babylon; the false prophet Hananiah broke it off his neck.',
    scriptureConnection: 'Jeremiah 27-28',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'zechariah-silent-nine-months',
    title: 'The Priest Who Was Muted for Doubt',
    era: '~6 BC',
    category: 'biblical',
    themes: ['doubt', 'silence', 'waiting', 'faith', 'speech', 'restoration'],
    oneLineSummary: 'Zechariah doubted the angel Gabriel\'s promise of a son, was struck mute for nine months, then burst into prophetic song when he named him John.',
    scriptureConnection: 'Luke 1:5-25, 57-80',
    source: 'biblical',
    spinnable: true,
  },

  // ==========================================
  // WOMEN WARRIORS AND LEADERS
  // ==========================================
  {
    id: 'deborah-military-strategy',
    title: 'The Judge Who Commanded a General',
    era: '~1200 BC',
    category: 'biblical',
    themes: ['leadership', 'women', 'courage', 'strategy', 'faith', 'authority'],
    oneLineSummary: 'Deborah led Israel as judge and prophet, devised the military strategy to defeat Sisera, and shamed Barak into action when he refused to go without her.',
    scriptureConnection: 'Judges 4-5',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'jael-tent-peg',
    title: 'The Woman Who Ended a War with a Tent Peg',
    era: '~1200 BC',
    category: 'biblical',
    themes: ['courage', 'women', 'unexpected-heroes', 'violence', 'deliverance'],
    oneLineSummary: 'When the Canaanite general Sisera fled to her tent, Jael offered him milk and rest — then drove a tent peg through his temple while he slept.',
    scriptureConnection: 'Judges 4:17-22; 5:24-27',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'abigail-diplomacy',
    title: 'The Woman Who Talked David Out of Massacre',
    era: '~1010 BC',
    category: 'biblical',
    themes: ['wisdom', 'peace', 'diplomacy', 'courage', 'women', 'intervention'],
    oneLineSummary: 'When her foolish husband Nabal insulted David, Abigail intercepted David\'s army with provisions and a speech so wise it stopped a bloodbath.',
    scriptureConnection: '1 Samuel 25',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'wise-woman-of-abel',
    title: 'The Unnamed Negotiator Who Saved a City',
    era: '~1000 BC',
    category: 'biblical',
    themes: ['wisdom', 'negotiation', 'women', 'peace', 'civic-courage', 'unnamed'],
    oneLineSummary: 'When Joab besieged Abel Beth Maakah, an unnamed "wise woman" negotiated from the wall and convinced the city to hand over the rebel, ending the siege.',
    scriptureConnection: '2 Samuel 20:14-22',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'huldah-validates-scripture',
    title: 'The Prophetess Who Authenticated the Bible',
    era: '~622 BC',
    category: 'biblical',
    themes: ['women', 'authority', 'Scripture', 'prophecy', 'validation', 'reform'],
    oneLineSummary: 'When the lost Book of the Law was found in the temple, King Josiah sent his officials not to Jeremiah but to the prophetess Huldah to validate it.',
    scriptureConnection: '2 Kings 22:14-20',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'woman-of-shunem',
    title: 'The Wealthy Woman Who Built a Prophet\'s Room',
    era: '~850 BC',
    category: 'biblical',
    themes: ['hospitality', 'generosity', 'loss', 'resurrection', 'faith', 'women'],
    oneLineSummary: 'The Shunammite woman built Elisha a room, was promised a son, lost him to death, then demanded Elisha come raise him — and he did.',
    scriptureConnection: '2 Kings 4:8-37',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'woman-at-thebez',
    title: 'The Woman Who Killed a King with a Millstone',
    era: '~1150 BC',
    category: 'biblical',
    themes: ['courage', 'women', 'justice', 'unlikely-hero', 'humiliation-of-tyrants'],
    oneLineSummary: 'An unnamed woman dropped a millstone on Abimelech\'s head from a tower, and his dying shame was being killed by a woman.',
    scriptureConnection: 'Judges 9:50-57; 2 Samuel 11:21',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'rizpah-vigil-over-dead-sons',
    title: 'The Mother Who Guarded Her Sons\' Bodies for Months',
    era: '~1000 BC',
    category: 'biblical',
    themes: ['grief', 'protest', 'mother-love', 'injustice', 'dignity', 'women'],
    oneLineSummary: 'After David handed over Saul\'s descendants to be killed, Rizpah sat on a rock for months protecting their exposed bodies from birds and beasts.',
    scriptureConnection: '2 Samuel 21:1-14',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'lydia-first-european-convert',
    title: 'The Businesswoman Who Started European Christianity',
    era: '~49 AD',
    category: 'biblical',
    themes: ['women', 'business', 'hospitality', 'conversion', 'church-planting', 'leadership'],
    oneLineSummary: 'Lydia, a dealer in purple cloth, became the first recorded European convert and immediately opened her home as the first church in Philippi.',
    scriptureConnection: 'Acts 16:13-15, 40',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'priscilla-teaches-apollos',
    title: 'The Woman Who Corrected the Brilliant Preacher',
    era: '~52 AD',
    category: 'biblical',
    themes: ['women', 'teaching', 'theology', 'humility', 'mentorship', 'partnership'],
    oneLineSummary: 'Priscilla and Aquila pulled aside the eloquent preacher Apollos and explained the gospel more accurately to him — and her name is listed first.',
    scriptureConnection: 'Acts 18:24-28',
    source: 'biblical',
    spinnable: true,
  },

  // ==========================================
  // FAILED LEADERS REDEEMED
  // ==========================================
  {
    id: 'samson-final-act',
    title: 'The Strongman\'s Last Prayer Was His Best',
    era: '~1075 BC',
    category: 'biblical',
    themes: ['redemption', 'failure', 'sacrifice', 'prayer', 'restoration', 'final-act'],
    oneLineSummary: 'Blind, enslaved, and humiliated, Samson prayed one last time — not for revenge but for God to remember him — and brought down the Philistine temple.',
    scriptureConnection: 'Judges 16:23-31; Hebrews 11:32',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'peter-reinstatement',
    title: 'Three Denials Met by Three Questions',
    era: '~30 AD',
    category: 'biblical',
    themes: ['restoration', 'failure', 'forgiveness', 'calling', 'love', 'shame'],
    oneLineSummary: 'After denying Jesus three times, Peter was reinstated with three questions — "Do you love me?" — each one healing a wound.',
    scriptureConnection: 'John 21:15-19',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'mark-abandoned-then-restored',
    title: 'The Deserter Paul Eventually Called Useful',
    era: '~49-65 AD',
    category: 'biblical',
    themes: ['second-chances', 'failure', 'restoration', 'mentorship', 'growth'],
    oneLineSummary: 'John Mark abandoned Paul\'s mission trip, causing a bitter split with Barnabas — but years later Paul wrote "Get Mark; he is useful to me."',
    scriptureConnection: 'Acts 15:36-41; 2 Timothy 4:11',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'jonah-reluctant-success',
    title: 'The Prophet Furious That His Preaching Worked',
    era: '~760 BC',
    category: 'biblical',
    themes: ['reluctance', 'mercy', 'prejudice', 'anger', 'God\'s-compassion', 'mission'],
    oneLineSummary: 'Jonah preached to Nineveh hoping they\'d be destroyed, and when they repented, he sat outside the city furious that God showed mercy.',
    scriptureConnection: 'Jonah 3-4',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'manasseh-worst-king-redeemed',
    title: 'The Worst King in Israel\'s History Found God in Prison',
    era: '~687-642 BC',
    category: 'biblical',
    themes: ['redemption', 'repentance', 'evil', 'captivity', 'humility', 'transformation'],
    oneLineSummary: 'Manasseh practiced child sacrifice, filled Jerusalem with blood, and was the worst king ever — but in Babylonian captivity he repented, and God restored him.',
    scriptureConnection: '2 Chronicles 33:1-20',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'david-after-bathsheba',
    title: 'The King Who Wrote His Confession Into Scripture',
    era: '~1000 BC',
    category: 'biblical',
    themes: ['confession', 'shame', 'restoration', 'transparency', 'brokenness', 'worship'],
    oneLineSummary: 'After his adultery and murder, David didn\'t just repent privately — he turned his confession into Psalm 51, giving all future sinners words to pray.',
    scriptureConnection: 'Psalm 51',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'thomas-doubt-to-confession',
    title: 'From "I Won\'t Believe" to "My Lord and My God"',
    era: '~30 AD',
    category: 'biblical',
    themes: ['doubt', 'faith', 'honesty', 'encounter', 'confession', 'restoration'],
    oneLineSummary: 'Thomas refused to believe without evidence, and Jesus didn\'t scold him — He showed up and let Thomas touch His wounds.',
    scriptureConnection: 'John 20:24-29',
    source: 'biblical',
    spinnable: true,
  },

  // ==========================================
  // BIZARRE SUPERNATURAL EVENTS
  // ==========================================
  {
    id: 'balaams-donkey-speaks',
    title: 'When a Donkey Saw the Angel First',
    era: '~1400 BC',
    category: 'biblical',
    themes: ['humility', 'blindness', 'animals', 'supernatural', 'irony', 'perception'],
    oneLineSummary: 'A donkey saw the angel of the Lord blocking the road when the prophet Balaam couldn\'t — then God opened the donkey\'s mouth to rebuke him.',
    scriptureConnection: 'Numbers 22:21-35',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'floating-axe-head',
    title: 'The Borrowed Axe Head That Floated',
    era: '~850 BC',
    category: 'biblical',
    themes: ['provision', 'small-things', 'miracles', 'anxiety', 'debt', 'care-of-God'],
    oneLineSummary: 'When a prophet\'s student lost a borrowed axe head in the river, Elisha made iron float — God cares about your borrowed things and small debts.',
    scriptureConnection: '2 Kings 6:1-7',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'sun-stands-still',
    title: 'The Day the Sun Obeyed a Human',
    era: '~1400 BC',
    category: 'biblical',
    themes: ['boldness', 'prayer', 'cosmic-authority', 'warfare', 'audacious-faith'],
    oneLineSummary: 'Joshua commanded the sun and moon to stand still so Israel could finish the battle — and they did, for about a full day.',
    scriptureConnection: 'Joshua 10:12-14',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'elisha-bones-resurrection',
    title: 'Dead Bones That Raised a Dead Man',
    era: '~800 BC',
    category: 'biblical',
    themes: ['resurrection', 'power', 'legacy', 'death', 'supernatural', 'afterlife-of-influence'],
    oneLineSummary: 'A dead man\'s body was thrown into Elisha\'s tomb, touched Elisha\'s bones, and came back to life — even dead, the prophet\'s calling carried power.',
    scriptureConnection: '2 Kings 13:20-21',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'handwriting-on-wall',
    title: 'The Fingers That Wrote on a King\'s Wall',
    era: '539 BC',
    category: 'biblical',
    themes: ['judgment', 'pride', 'warning', 'supernatural', 'reckoning', 'power'],
    oneLineSummary: 'During Belshazzar\'s feast, disembodied fingers wrote "MENE MENE TEKEL UPHARSIN" on the wall — that night, the empire fell.',
    scriptureConnection: 'Daniel 5',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'shadow-retreats-ten-steps',
    title: 'The Shadow That Went Backward as Proof',
    era: '~700 BC',
    category: 'biblical',
    themes: ['healing', 'signs', 'time', 'faith', 'confirmation', 'impossible'],
    oneLineSummary: 'When Hezekiah asked for proof of God\'s healing promise, God made the shadow on the stairway go backward ten steps.',
    scriptureConnection: '2 Kings 20:8-11',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'iron-axe-chariots-of-fire',
    title: 'The Invisible Army Surrounding the Prophet',
    era: '~850 BC',
    category: 'biblical',
    themes: ['fear', 'protection', 'unseen-reality', 'spiritual-warfare', 'perspective'],
    oneLineSummary: 'When Elisha\'s servant panicked at the enemy army, Elisha prayed "Open his eyes" — and the hills were full of horses and chariots of fire.',
    scriptureConnection: '2 Kings 6:15-17',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'valley-of-dry-bones',
    title: 'A Graveyard That Became an Army',
    era: '~586 BC',
    category: 'biblical',
    themes: ['resurrection', 'hopelessness', 'restoration', 'Spirit', 'prophecy', 'new-life'],
    oneLineSummary: 'God led Ezekiel to a valley of dry bones and asked "Can these bones live?" — then breath entered them and they stood as a vast army.',
    scriptureConnection: 'Ezekiel 37:1-14',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'earthquake-opens-prison',
    title: 'The Earthquake That Started with Worship Music',
    era: '~50 AD',
    category: 'biblical',
    themes: ['worship', 'freedom', 'suffering', 'prison', 'supernatural', 'conversion'],
    oneLineSummary: 'Paul and Silas sang hymns at midnight in prison; an earthquake broke every chain and opened every door — but they stayed, and the jailer got saved.',
    scriptureConnection: 'Acts 16:25-34',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'elijahs-fire-from-heaven',
    title: 'The Prophet Who Mocked the Competition',
    era: '~870 BC',
    category: 'biblical',
    themes: ['confrontation', 'faith', 'mockery', 'power', 'idolatry', 'fire'],
    oneLineSummary: 'Elijah taunted 450 prophets of Baal — "Maybe your god is sleeping or on the toilet" — then drenched his altar in water and called down fire.',
    scriptureConnection: '1 Kings 18:20-40',
    source: 'biblical',
    spinnable: true,
  },

  // ==========================================
  // ECONOMIC / JUSTICE STORIES
  // ==========================================
  {
    id: 'year-of-jubilee',
    title: 'God\'s Economic Reset Button',
    era: '~1440 BC (Mosaic Law)',
    category: 'biblical',
    themes: ['justice', 'economics', 'freedom', 'land', 'debt', 'systemic-change'],
    oneLineSummary: 'Every 50 years, all debts were cancelled, all slaves freed, and all land returned to original families — God\'s radical economic restart.',
    scriptureConnection: 'Leviticus 25:8-55',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'ruth-gleaning-laws',
    title: 'The Welfare System Built Into Harvest Fields',
    era: '~1100 BC',
    category: 'biblical',
    themes: ['provision', 'justice', 'immigrants', 'dignity', 'work', 'generosity'],
    oneLineSummary: 'God commanded farmers to leave the edges of their fields unharvested so the poor, widows, and foreigners could gather food with dignity.',
    scriptureConnection: 'Leviticus 19:9-10; Ruth 2',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'nehemiah-economic-reforms',
    title: 'The Governor Who Made the Rich Give Back',
    era: '~445 BC',
    category: 'biblical',
    themes: ['justice', 'economic-reform', 'leadership', 'debt', 'exploitation', 'courage'],
    oneLineSummary: 'Nehemiah discovered the wealthy were charging interest on loans to the poor and enslaving fellow Jews, so he shamed the nobles into returning everything.',
    scriptureConnection: 'Nehemiah 5:1-13',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'amos-marketplace-prophecies',
    title: 'The Shepherd Who Denounced Corrupt Commerce',
    era: '~760 BC',
    category: 'biblical',
    themes: ['justice', 'economics', 'corruption', 'worship', 'hypocrisy', 'prophetic-anger'],
    oneLineSummary: 'Amos, a simple shepherd, stormed into wealthy Israel and declared that God hated their worship because they cheated the poor in the marketplace.',
    scriptureConnection: 'Amos 2:6-7; 5:21-24; 8:4-6',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'jubilee-debt-cancellation-jesus',
    title: 'Jesus Read the Jubilee Passage and Said "Today"',
    era: '~28 AD',
    category: 'biblical',
    themes: ['liberation', 'fulfillment', 'justice', 'proclamation', 'kingdom', 'today'],
    oneLineSummary: 'In his first public sermon, Jesus read Isaiah\'s Jubilee passage about freeing captives and cancelling debts, then said "Today this is fulfilled."',
    scriptureConnection: 'Luke 4:16-21; Isaiah 61:1-2',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'widows-mite',
    title: 'The Offering That Outgave the Millionaires',
    era: '~30 AD',
    category: 'biblical',
    themes: ['generosity', 'sacrifice', 'poverty', 'value', 'worship', 'perspective'],
    oneLineSummary: 'Jesus pointed out that the poor widow\'s two tiny coins were worth more than all the rich donors\' gifts because she gave everything she had.',
    scriptureConnection: 'Mark 12:41-44; Luke 21:1-4',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'zacchaeus-restitution',
    title: 'The Tax Collector Who Gave Back Four Times Over',
    era: '~30 AD',
    category: 'biblical',
    themes: ['repentance', 'restitution', 'economics', 'transformation', 'justice', 'joy'],
    oneLineSummary: 'After one meal with Jesus, Zacchaeus voluntarily promised to give half his wealth to the poor and repay four times what he\'d stolen.',
    scriptureConnection: 'Luke 19:1-10',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'sabbath-economics',
    title: 'The Radical Command to Stop Producing',
    era: '~1440 BC',
    category: 'biblical',
    themes: ['rest', 'trust', 'economics', 'anxiety', 'provision', 'identity'],
    oneLineSummary: 'In an ancient world where survival meant constant labor, God commanded Israel to stop working every seventh day — and every seventh year for the land.',
    scriptureConnection: 'Exodus 20:8-11; Leviticus 25:1-7',
    source: 'biblical',
    spinnable: true,
  },

  // ==========================================
  // EXILE AND DIASPORA
  // ==========================================
  {
    id: 'daniel-quiet-resistance',
    title: 'The Bureaucrat Who Prayed with Open Windows',
    era: '~539 BC',
    category: 'biblical',
    themes: ['resistance', 'courage', 'faithfulness', 'civil-disobedience', 'prayer', 'integrity'],
    oneLineSummary: 'When praying was outlawed, Daniel didn\'t hide — he prayed with his windows open toward Jerusalem, the same way he always had.',
    scriptureConnection: 'Daniel 6:6-10',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'esther-courage-calculus',
    title: 'The Queen Who Calculated the Cost of Speaking Up',
    era: '~473 BC',
    category: 'biblical',
    themes: ['courage', 'risk', 'identity', 'women', 'timing', 'providence'],
    oneLineSummary: 'Esther didn\'t rush in — she fasted three days, calculated her approach, and wagered her life with "If I perish, I perish."',
    scriptureConnection: 'Esther 4:15-16',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'ezra-public-reading-weeping',
    title: 'The Reading That Made an Entire Nation Weep',
    era: '~444 BC',
    category: 'biblical',
    themes: ['Scripture', 'weeping', 'conviction', 'revival', 'community', 'return'],
    oneLineSummary: 'When Ezra read the forgotten Law aloud to the returned exiles, the entire assembly wept because they realized how far they\'d drifted.',
    scriptureConnection: 'Nehemiah 8:1-12',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'psalms-by-rivers-of-babylon',
    title: 'The Song They Couldn\'t Sing in a Foreign Land',
    era: '~586 BC',
    category: 'biblical',
    themes: ['exile', 'grief', 'worship', 'memory', 'home', 'lament'],
    oneLineSummary: 'By the rivers of Babylon, the captors asked for a song of Zion — but the exiles hung their harps on willows and asked how to sing the Lord\'s song in a strange land.',
    scriptureConnection: 'Psalm 137:1-4',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'shadrach-meshach-abednego',
    title: 'The Three Who Said "Even If He Doesn\'t Save Us"',
    era: '~580 BC',
    category: 'biblical',
    themes: ['faith', 'courage', 'fire', 'defiance', 'trust', 'uncertainty'],
    oneLineSummary: 'Facing the furnace, they didn\'t say "God will save us" — they said "Our God is able, but even if He doesn\'t, we still won\'t bow."',
    scriptureConnection: 'Daniel 3:16-18',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'nehemiah-cupbearer-calling',
    title: 'The Cupbearer Who Rebuilt a Nation',
    era: '~445 BC',
    category: 'biblical',
    themes: ['calling', 'grief', 'leadership', 'unlikely-heroes', 'action', 'prayer'],
    oneLineSummary: 'Nehemiah was a cupbearer in exile — not a builder, prophet, or priest — but his grief for Jerusalem\'s ruins drove him to rebuild its walls in 52 days.',
    scriptureConnection: 'Nehemiah 1-2; 6:15',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'daniel-vegetable-test',
    title: 'The Quiet Rebellion of Eating Vegetables',
    era: '~605 BC',
    category: 'biblical',
    themes: ['resistance', 'identity', 'food', 'faithfulness', 'small-choices', 'integrity'],
    oneLineSummary: 'Daniel\'s first act of resistance wasn\'t dramatic — he simply asked to eat vegetables instead of the king\'s food, maintaining his identity in small choices.',
    scriptureConnection: 'Daniel 1:8-16',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'jews-build-houses-in-exile',
    title: 'God\'s Strange Command: Settle Where You\'re Captive',
    era: '~597 BC',
    category: 'biblical',
    themes: ['exile', 'faithfulness-in-place', 'patience', 'waiting', 'community', 'hope'],
    oneLineSummary: 'Through Jeremiah, God told the exiles not to rebel or withdraw but to build houses, plant gardens, and seek the welfare of the city that captured them.',
    scriptureConnection: 'Jeremiah 29:4-7',
    source: 'biblical',
    spinnable: true,
  },

  // ==========================================
  // MICRO-STORIES IN WISDOM LITERATURE
  // ==========================================
  {
    id: 'sluggard-and-ant',
    title: 'The Lazy Man\'s Teacher Has Six Legs',
    era: 'Wisdom tradition',
    category: 'biblical',
    themes: ['discipline', 'laziness', 'nature', 'wisdom', 'work', 'observation'],
    oneLineSummary: 'Proverbs sends the lazy person to study an ant — no boss, no foreman, yet it stores provisions in summer for winter.',
    scriptureConnection: 'Proverbs 6:6-11',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'psalm-88-prayer-with-no-answer',
    title: 'The Only Psalm That Doesn\'t Resolve',
    era: 'Wisdom tradition',
    category: 'biblical',
    themes: ['depression', 'lament', 'darkness', 'honesty', 'unanswered-prayer', 'suffering'],
    oneLineSummary: 'Psalm 88 is the darkest psalm — it begins in darkness, ends in darkness, and God never answers, yet it\'s still in the Bible as valid prayer.',
    scriptureConnection: 'Psalm 88',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'ecclesiastes-meaningless',
    title: 'The Richest Man Who Called Everything Meaningless',
    era: 'Wisdom tradition',
    category: 'biblical',
    themes: ['meaning', 'existentialism', 'wealth', 'despair', 'honesty', 'search'],
    oneLineSummary: 'Solomon had everything — wisdom, wealth, women, fame — and concluded "Meaningless! Everything is meaningless!" yet kept seeking God in the void.',
    scriptureConnection: 'Ecclesiastes 1:1-2; 12:13',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'song-of-solomon-erotic-love',
    title: 'The Erotic Poetry God Put in the Bible',
    era: 'Wisdom tradition',
    category: 'biblical',
    themes: ['love', 'desire', 'intimacy', 'beauty', 'sexuality', 'celebration'],
    oneLineSummary: 'The Song of Solomon is unfiltered erotic poetry celebrating physical desire between lovers — and God put it in Holy Scripture.',
    scriptureConnection: 'Song of Solomon 4:1-7; 7:1-9',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'psalm-22-from-cross-to-praise',
    title: 'The Psalm Jesus Quoted on the Cross',
    era: 'Wisdom tradition',
    category: 'biblical',
    themes: ['suffering', 'abandonment', 'prophecy', 'praise', 'trust', 'crucifixion'],
    oneLineSummary: '"My God, why have you forsaken me?" wasn\'t despair — it was the opening line of a psalm that ends in total vindication and praise.',
    scriptureConnection: 'Psalm 22; Matthew 27:46',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'job-questions-god',
    title: 'The Man Who Demanded God Show Up in Court',
    era: 'Wisdom tradition',
    category: 'biblical',
    themes: ['suffering', 'justice', 'questioning-God', 'honesty', 'encounter', 'humility'],
    oneLineSummary: 'Job didn\'t accept cliches about suffering — he demanded a court hearing with God, and God actually showed up, just not with the answers Job expected.',
    scriptureConnection: 'Job 31:35-37; 38-42',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'proverbs-31-woman-deconstructed',
    title: 'The Virtuous Woman Is Actually a Business Mogul',
    era: 'Wisdom tradition',
    category: 'biblical',
    themes: ['women', 'strength', 'economics', 'misunderstood-texts', 'power', 'wisdom'],
    oneLineSummary: 'The Proverbs 31 woman isn\'t a domestic ideal — she trades in real estate, runs a textile business, provides for employees, and makes her husband\'s reputation.',
    scriptureConnection: 'Proverbs 31:10-31',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'psalm-139-darkness-is-light',
    title: 'The Place Even Darkness Can\'t Hide You from God',
    era: 'Wisdom tradition',
    category: 'biblical',
    themes: ['omnipresence', 'known', 'hiding', 'darkness', 'comfort', 'intimacy'],
    oneLineSummary: '"Even the darkness is not dark to you" — the psalmist discovers there is nowhere to hide from the God who knit him in the womb.',
    scriptureConnection: 'Psalm 139:7-12',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'lament-psalms-as-therapy',
    title: 'Ancient Prayer Templates for Modern Rage and Grief',
    era: 'Wisdom tradition',
    category: 'biblical',
    themes: ['lament', 'anger', 'grief', 'mental-health', 'prayer', 'honesty'],
    oneLineSummary: 'Over a third of the Psalms are complaints, screams, and raw grief directed at God — Scripture validates bringing your worst emotions to prayer.',
    scriptureConnection: 'Psalms 10, 13, 22, 42, 69, 88, 137',
    source: 'biblical',
    spinnable: true,
  },

  // ==========================================
  // INTER-TESTAMENTAL CONNECTIONS
  // ==========================================
  {
    id: 'suffering-servant-to-cross',
    title: 'The Portrait Painted 700 Years Early',
    era: '~700 BC → ~30 AD',
    category: 'biblical',
    themes: ['prophecy', 'suffering', 'fulfillment', 'Messiah', 'sacrifice', 'connection'],
    oneLineSummary: 'Isaiah 53 describes a suffering servant pierced for others\' transgressions — written 700 years before crucifixion was even invented as a method of execution.',
    scriptureConnection: 'Isaiah 53; Luke 22-23',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'passover-to-communion',
    title: 'The Meal That Crossed a Millennium',
    era: '~1440 BC → ~30 AD',
    category: 'biblical',
    themes: ['covenant', 'remembrance', 'blood', 'lamb', 'freedom', 'continuity'],
    oneLineSummary: 'Jesus chose Passover night to reinterpret the bread and wine — the meal commemorating freedom from Egypt became the meal commemorating freedom from sin.',
    scriptureConnection: 'Exodus 12; Luke 22:14-20',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'temple-veil-torn',
    title: 'The Curtain Ripped from God\'s Side',
    era: '~30 AD',
    category: 'biblical',
    themes: ['access', 'barrier', 'death-of-Jesus', 'priesthood', 'new-covenant', 'invitation'],
    oneLineSummary: 'At the moment Jesus died, the massive temple curtain that separated God from humanity tore from top to bottom — from God\'s side to ours.',
    scriptureConnection: 'Matthew 27:51; Hebrews 10:19-22',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'serpent-bronze-to-cross',
    title: 'The Snake on a Pole That Prefigured the Cross',
    era: '~1400 BC → ~30 AD',
    category: 'biblical',
    themes: ['healing', 'type-and-shadow', 'cross', 'look-and-live', 'faith'],
    oneLineSummary: 'Moses lifted a bronze serpent on a pole so snakebite victims could look at it and live — Jesus said "Just as Moses lifted the serpent, so must I be lifted up."',
    scriptureConnection: 'Numbers 21:4-9; John 3:14-15',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'isaac-binding-to-calvary',
    title: 'The Son Who Carried Wood Up a Mountain',
    era: '~1900 BC → ~30 AD',
    category: 'biblical',
    themes: ['sacrifice', 'foreshadowing', 'faith', 'father-son', 'obedience', 'lamb'],
    oneLineSummary: 'Abraham\'s son Isaac carried the wood for his own sacrifice up Mount Moriah — the same mountain where centuries later, Jesus would carry his own cross.',
    scriptureConnection: 'Genesis 22:1-14; John 19:17',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'ruth-kinsman-redeemer',
    title: 'The Love Story That Previews Redemption',
    era: '~1100 BC',
    category: 'biblical',
    themes: ['redemption', 'kinsman-redeemer', 'love', 'type-and-shadow', 'loyalty', 'restoration'],
    oneLineSummary: 'Boaz redeemed Ruth by exercising the kinsman-redeemer law — buying back her family\'s land and taking her as his wife, foreshadowing how Jesus redeems.',
    scriptureConnection: 'Ruth 4; Galatians 3:13; 4:4-5',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'jonah-three-days-connection',
    title: 'Three Days in a Fish, Three Days in a Tomb',
    era: '~760 BC → ~30 AD',
    category: 'biblical',
    themes: ['death', 'resurrection', 'sign', 'prefigurement', 'three-days'],
    oneLineSummary: 'Jesus said the only sign He\'d give was "the sign of Jonah" — as Jonah was three days in the fish, so He would be three days in the earth.',
    scriptureConnection: 'Jonah 1:17; Matthew 12:39-40',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'joseph-parallel-to-jesus',
    title: 'The Rejected Brother Who Saved the World from Famine',
    era: '~1700 BC',
    category: 'biblical',
    themes: ['rejection', 'forgiveness', 'sovereignty', 'foreshadowing', 'provision', 'brothers'],
    oneLineSummary: 'Joseph was betrayed by his brothers, left for dead, exalted to save nations, and forgave those who sold him — an uncanny preview of Jesus.',
    scriptureConnection: 'Genesis 37-50',
    source: 'biblical',
    spinnable: true,
  },

  // ==========================================
  // OBSCURE BUT FASCINATING MICRO-NARRATIVES
  // ==========================================
  {
    id: 'ehud-left-handed-assassin',
    title: 'The Left-Handed Judge Who Assassinated a King',
    era: '~1350 BC',
    category: 'biblical',
    themes: ['liberation', 'unlikely-heroes', 'cunning', 'courage', 'disability-as-advantage'],
    oneLineSummary: 'Ehud was left-handed in a right-handed world — so his hidden sword wasn\'t found in the search, and he assassinated the obese king Eglon on his toilet.',
    scriptureConnection: 'Judges 3:12-30',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'elijah-depression-after-victory',
    title: 'The Prophet Who Won Big Then Wanted to Die',
    era: '~870 BC',
    category: 'biblical',
    themes: ['depression', 'burnout', 'victory', 'exhaustion', 'care', 'mental-health'],
    oneLineSummary: 'Right after his greatest victory over 450 prophets of Baal, Elijah ran away, collapsed under a tree, and begged God to let him die.',
    scriptureConnection: '1 Kings 19:1-8',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'god-feeds-elijah-with-ravens',
    title: 'Unclean Birds as God\'s Delivery Service',
    era: '~870 BC',
    category: 'biblical',
    themes: ['provision', 'unexpected-sources', 'trust', 'wilderness', 'unclean'],
    oneLineSummary: 'God sent ravens — unclean scavenger birds — to bring bread and meat to Elijah every morning and evening by the brook Cherith.',
    scriptureConnection: '1 Kings 17:2-6',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'uzzah-touches-ark',
    title: 'The Man Struck Dead for Trying to Help',
    era: '~1000 BC',
    category: 'biblical',
    themes: ['holiness', 'presumption', 'sacred', 'good-intentions', 'fear-of-God'],
    oneLineSummary: 'When the oxen stumbled and the Ark tilted, Uzzah reached out to steady it — and God struck him dead, a terrifying reminder that holiness is not casual.',
    scriptureConnection: '2 Samuel 6:6-7',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'jacob-wrestling-god',
    title: 'The Man Who Fought God and Won a Limp',
    era: '~1850 BC',
    category: 'biblical',
    themes: ['struggle', 'blessing', 'identity', 'persistence', 'wound', 'encounter'],
    oneLineSummary: 'Jacob wrestled a mysterious figure all night, refused to let go until blessed, received a new name (Israel), but walked with a limp forever after.',
    scriptureConnection: 'Genesis 32:22-32',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'naaman-simple-cure-offended',
    title: 'The General Offended by a Simple Cure',
    era: '~850 BC',
    category: 'biblical',
    themes: ['pride', 'simplicity', 'healing', 'humility', 'expectations', 'obedience'],
    oneLineSummary: 'Powerful Naaman expected a dramatic healing ritual, and almost walked away in rage when Elisha simply told him to wash seven times in a muddy river.',
    scriptureConnection: '2 Kings 5:1-14',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'gideon-fleece-test',
    title: 'The Warrior Who Needed God to Prove It Twice',
    era: '~1200 BC',
    category: 'biblical',
    themes: ['doubt', 'patience-of-God', 'confirmation', 'inadequacy', 'faith'],
    oneLineSummary: 'Gideon asked God for a sign with a fleece, got it, then asked for the opposite sign the next night — and God patiently obliged both times.',
    scriptureConnection: 'Judges 6:36-40',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'gideons-300',
    title: 'God Cut the Army from 32,000 to 300',
    era: '~1200 BC',
    category: 'biblical',
    themes: ['weakness', 'strategy', 'trust', 'glory', 'inadequacy', 'impossible-odds'],
    oneLineSummary: 'God deliberately shrunk Gideon\'s army from 32,000 to 300 so that "Israel may not boast that her own strength has saved her."',
    scriptureConnection: 'Judges 7:1-7',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'ebed-melech-rescues-jeremiah',
    title: 'The African Official Who Rescued a Prophet from a Pit',
    era: '~587 BC',
    category: 'biblical',
    themes: ['courage', 'advocacy', 'justice', 'compassion', 'risk', 'outsider-hero'],
    oneLineSummary: 'When Jeremiah was thrown into a muddy cistern to die, an Ethiopian official named Ebed-Melech risked his career to petition the king and pull him out.',
    scriptureConnection: 'Jeremiah 38:6-13; 39:15-18',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'mephibosheth-at-davids-table',
    title: 'The Crippled Prince Invited to the King\'s Table',
    era: '~1000 BC',
    category: 'biblical',
    themes: ['grace', 'covenant', 'adoption', 'disability', 'belonging', 'enemy-love'],
    oneLineSummary: 'David sought out Mephibosheth, Jonathan\'s disabled son hiding in exile, and gave him a permanent seat at the royal table — grace to the house of his enemy.',
    scriptureConnection: '2 Samuel 9',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'widow-of-zarephath',
    title: 'The Outsider Whose Last Meal Never Ran Out',
    era: '~870 BC',
    category: 'biblical',
    themes: ['provision', 'faith', 'sacrifice', 'outsider', 'scarcity', 'generosity'],
    oneLineSummary: 'A Sidonian widow was preparing her last meal to die with her son, but shared it with Elijah — and her flour jar and oil jug never went empty.',
    scriptureConnection: '1 Kings 17:7-16',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'gehazi-greed-leprosy',
    title: 'The Servant Who Chased a Profit and Caught Leprosy',
    era: '~850 BC',
    category: 'biblical',
    themes: ['greed', 'consequences', 'deception', 'grace-abused', 'integrity'],
    oneLineSummary: 'After Elisha healed Naaman for free, his servant Gehazi secretly chased Naaman to collect payment — and inherited Naaman\'s leprosy.',
    scriptureConnection: '2 Kings 5:20-27',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'absalom-hair-vanity-death',
    title: 'The Prince Killed by His Own Beauty',
    era: '~1000 BC',
    category: 'biblical',
    themes: ['vanity', 'pride', 'rebellion', 'consequences', 'irony', 'father-grief'],
    oneLineSummary: 'Absalom was famous for his magnificent hair — and it was that hair that got caught in a tree during battle, leaving him hanging for Joab\'s spears.',
    scriptureConnection: '2 Samuel 14:25-26; 18:9-15',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'micaiah-lone-dissenter',
    title: 'The One Prophet Who Told the King the Truth',
    era: '~853 BC',
    category: 'biblical',
    themes: ['truth', 'courage', 'dissent', 'popularity', 'loneliness', 'integrity'],
    oneLineSummary: '400 prophets told King Ahab what he wanted to hear; Micaiah alone said the truth — that the king would die — and was slapped and imprisoned for it.',
    scriptureConnection: '1 Kings 22:1-28',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'ananias-goes-to-saul',
    title: 'The Disciple Told to Visit the Man Who Killed His Friends',
    era: '~34 AD',
    category: 'biblical',
    themes: ['obedience', 'fear', 'forgiveness', 'enemy-love', 'trust', 'calling'],
    oneLineSummary: 'God told Ananias to go heal the man actively hunting Christians — and Ananias went, called him "Brother Saul," and changed the course of history.',
    scriptureConnection: 'Acts 9:10-19',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'philip-and-ethiopian-eunuch',
    title: 'The Bible Study in a Moving Chariot',
    era: '~34 AD',
    category: 'biblical',
    themes: ['inclusion', 'evangelism', 'Scripture', 'divine-appointment', 'outsider', 'baptism'],
    oneLineSummary: 'The Spirit led Philip to a chariot where an Ethiopian eunuch was reading Isaiah 53 and asking "Who is this about?" — and Philip climbed in.',
    scriptureConnection: 'Acts 8:26-40',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'eutychus-falls-from-window',
    title: 'The Young Man Killed by a Long Sermon',
    era: '~57 AD',
    category: 'biblical',
    themes: ['humor', 'resurrection', 'community', 'preaching', 'human-nature'],
    oneLineSummary: 'Paul preached until midnight, a young man named Eutychus fell asleep in a window, fell three stories to his death, and Paul raised him back to life.',
    scriptureConnection: 'Acts 20:7-12',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'four-lepers-discover-abundance',
    title: 'Four Outcasts Who Found a Feast',
    era: '~850 BC',
    category: 'biblical',
    themes: ['desperation', 'risk', 'outcasts', 'abundance', 'sharing', 'good-news'],
    oneLineSummary: 'Four starving lepers decided "Why sit here until we die?" and walked into the enemy camp — only to find God had already driven the army away, leaving everything.',
    scriptureConnection: '2 Kings 7:3-11',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'jethro-advises-moses',
    title: 'The Father-in-Law Who Invented Delegation',
    era: '~1440 BC',
    category: 'biblical',
    themes: ['wisdom', 'leadership', 'burnout', 'delegation', 'humility', 'outsider-wisdom'],
    oneLineSummary: 'Moses was burning out judging every dispute himself until his Midianite father-in-law Jethro said "This is too much for you — appoint leaders."',
    scriptureConnection: 'Exodus 18:13-27',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'caleb-at-85',
    title: 'The 85-Year-Old Who Demanded the Hardest Territory',
    era: '~1400 BC',
    category: 'biblical',
    themes: ['aging', 'courage', 'faith', 'persistence', 'vitality', 'promise-keeping'],
    oneLineSummary: 'At 85 years old, Caleb didn\'t ask for easy land — he demanded the hill country full of giants, saying "I am still as strong as I was at 40."',
    scriptureConnection: 'Joshua 14:6-14',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'two-prostitutes-before-solomon',
    title: 'The Case That Proved Solomon\'s Wisdom',
    era: '~960 BC',
    category: 'biblical',
    themes: ['wisdom', 'justice', 'mothers-love', 'discernment', 'truth'],
    oneLineSummary: 'Two women claimed the same baby; Solomon proposed cutting it in half, knowing the real mother would surrender her claim to save her child.',
    scriptureConnection: '1 Kings 3:16-28',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'achan-hidden-sin',
    title: 'The Hidden Plunder That Cost 36 Lives',
    era: '~1400 BC',
    category: 'biblical',
    themes: ['hidden-sin', 'community', 'consequences', 'greed', 'accountability'],
    oneLineSummary: 'Achan secretly kept plunder from Jericho that was devoted to God — and 36 soldiers died at the next battle because of one man\'s hidden sin.',
    scriptureConnection: 'Joshua 7',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'hannah-mistaken-for-drunk',
    title: 'The Desperate Prayer That Looked Like Drunkenness',
    era: '~1100 BC',
    category: 'biblical',
    themes: ['prayer', 'desperation', 'misunderstood', 'women', 'barrenness', 'surrender'],
    oneLineSummary: 'Hannah prayed with such raw, silent intensity at the temple that the priest Eli accused her of being drunk — but she was pouring out her soul to God.',
    scriptureConnection: '1 Samuel 1:9-18',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'david-danced-nearly-naked',
    title: 'The King Who Danced in His Underwear',
    era: '~1000 BC',
    category: 'biblical',
    themes: ['worship', 'abandon', 'dignity', 'joy', 'criticism', 'freedom'],
    oneLineSummary: 'David danced before the Ark in a linen ephod with such abandon that his wife Michal despised him — he chose worship over royal dignity.',
    scriptureConnection: '2 Samuel 6:14-23',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'prophet-eaten-by-lion-disobedience',
    title: 'The Prophet Killed for Accepting Lunch',
    era: '~930 BC',
    category: 'biblical',
    themes: ['obedience', 'deception', 'consequences', 'compromise', 'trust-God-not-men'],
    oneLineSummary: 'A prophet obeyed God perfectly until an older prophet lied and said "God told me to invite you to eat" — the man of God believed the lie and was killed by a lion.',
    scriptureConnection: '1 Kings 13',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'simon-cyrene-carries-cross',
    title: 'The African Man Forced to Carry the Cross',
    era: '~30 AD',
    category: 'biblical',
    themes: ['suffering', 'Simon', 'Africa', 'involuntary-service', 'witness', 'proximity-to-Jesus'],
    oneLineSummary: 'Simon of Cyrene (modern Libya) was grabbed from the crowd and forced to carry Jesus\'s cross — his sons Alexander and Rufus later became known Christians.',
    scriptureConnection: 'Mark 15:21; Romans 16:13',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'lots-wife-looks-back',
    title: 'The Woman Who Couldn\'t Stop Looking Back',
    era: '~2000 BC',
    category: 'biblical',
    themes: ['letting-go', 'attachment', 'judgment', 'freedom', 'past', 'warning'],
    oneLineSummary: 'Fleeing Sodom\'s destruction, Lot\'s wife looked back and became a pillar of salt — Jesus later said simply "Remember Lot\'s wife."',
    scriptureConnection: 'Genesis 19:26; Luke 17:32',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'jairus-daughter-interrupted',
    title: 'The Father Whose Emergency Got Interrupted',
    era: '~29 AD',
    category: 'biblical',
    themes: ['waiting', 'interruption', 'faith', 'desperation', 'death', 'resurrection'],
    oneLineSummary: 'Jairus begged Jesus to heal his dying daughter, but Jesus stopped to help a bleeding woman — by the time they arrived, the girl was dead, then Jesus raised her.',
    scriptureConnection: 'Mark 5:21-43',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'barabbas-set-free',
    title: 'The Criminal Who Got the Pardon Meant for the Innocent',
    era: '~30 AD',
    category: 'biblical',
    themes: ['substitution', 'grace', 'injustice', 'freedom', 'exchange'],
    oneLineSummary: 'Barabbas — a murderer and insurrectionist — walked free because the crowd chose to crucify Jesus instead, the most literal substitutionary act in history.',
    scriptureConnection: 'Matthew 27:15-26',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'woman-caught-in-adultery',
    title: 'The One Who Was Left When All Accusers Walked Away',
    era: '~30 AD',
    category: 'biblical',
    themes: ['shame', 'grace', 'accusation', 'mercy', 'hypocrisy', 'new-start'],
    oneLineSummary: 'The religious leaders brought a woman caught in adultery to trap Jesus — He wrote in the dirt, and one by one every accuser walked away.',
    scriptureConnection: 'John 8:1-11',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'jesus-wept-shortest-verse',
    title: 'The Two Words That Reveal Everything About God',
    era: '~30 AD',
    category: 'biblical',
    themes: ['grief', 'empathy', 'humanity-of-Jesus', 'tears', 'love', 'presence'],
    oneLineSummary: 'Even though He was about to raise Lazarus from the dead, Jesus wept at the tomb — He grieves with us even when He knows the ending.',
    scriptureConnection: 'John 11:35',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'woman-who-touched-hem',
    title: 'Twelve Years of Bleeding Ended by One Touch',
    era: '~29 AD',
    category: 'biblical',
    themes: ['desperation', 'faith', 'healing', 'shame', 'courage', 'women'],
    oneLineSummary: 'After 12 years of bleeding and spending everything on doctors, a woman touched Jesus\'s hem in a crowd and was healed — then He made her tell her story publicly.',
    scriptureConnection: 'Mark 5:25-34',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'feeding-5000-boys-lunch',
    title: 'The Kid Whose Lunch Fed a Stadium',
    era: '~29 AD',
    category: 'biblical',
    themes: ['generosity', 'small-offerings', 'multiplication', 'children', 'enough'],
    oneLineSummary: 'Andrew found a boy with five loaves and two fish and asked "What are these among so many?" — Jesus took the small offering and fed 5,000.',
    scriptureConnection: 'John 6:1-14',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'jesus-makes-breakfast',
    title: 'The Risen God Who Cooked Fish for Breakfast',
    era: '~30 AD',
    category: 'biblical',
    themes: ['intimacy', 'service', 'resurrection', 'normalcy', 'love', 'care'],
    oneLineSummary: 'After conquering death and rising from the grave, the first thing Jesus did for his disciples was make them breakfast on the beach.',
    scriptureConnection: 'John 21:1-14',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'pentecost-languages',
    title: 'The Day God Reversed the Tower of Babel',
    era: '~30 AD',
    category: 'biblical',
    themes: ['Spirit', 'unity', 'language', 'reversal', 'diversity', 'power'],
    oneLineSummary: 'At Babel, God confused languages to scatter humanity; at Pentecost, the Spirit enabled everyone to understand each other — the curse reversed.',
    scriptureConnection: 'Genesis 11:1-9; Acts 2:1-12',
    source: 'biblical',
    spinnable: true,
  },
  {
    id: 'thief-on-cross',
    title: 'The Last-Second Salvation That Offends Everyone',
    era: '~30 AD',
    category: 'biblical',
    themes: ['grace', 'last-minute', 'salvation', 'mercy', 'deathbed', 'justice'],
    oneLineSummary: 'A criminal being executed next to Jesus said "Remember me" — and Jesus promised him paradise that very day, no works, no baptism, no time to prove anything.',
    scriptureConnection: 'Luke 23:39-43',
    source: 'biblical',
    spinnable: true,
  },
];
