// ==========================================
// STORY REPOSITORY: HISTORICAL FIGURES — EXPANDED
// Diverse, unexpected figures across cultures, eras, and genders
// Supplement to the main historical figures batch
// Used by AI devotional generation as illustration source material
// ==========================================

export interface HistoricalStoryEntry {
  id: string;
  title: string;
  era: string;
  category: 'historical-figure';
  themes: string[];
  oneLineSummary: string;
  spiritualAngle: string;
  source: 'historical';
  spinnable: boolean;
}

export const HISTORICAL_FIGURES_EXPANDED: HistoricalStoryEntry[] = [
  // ==========================================
  // ANCIENT WORLD — PHILOSOPHERS & SAGES
  // ==========================================
  {
    id: 'socrates-hemlock',
    title: 'The Man Who Chose Death Over Compromise',
    era: '399 BC',
    category: 'historical-figure',
    themes: ['integrity', 'courage', 'conviction', 'martyrdom', 'truth'],
    oneLineSummary: 'Socrates drank hemlock rather than renounce his philosophical mission, telling Athens that the unexamined life is not worth living.',
    spiritualAngle: 'Like the prophets who chose faithfulness over comfort, Socrates shows that some truths are worth more than survival.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'marcus-aurelius-meditations',
    title: 'The Emperor Who Journaled His Way to Humility',
    era: '161-180 AD',
    category: 'historical-figure',
    themes: ['inner-life', 'power', 'humility', 'discipline', 'self-examination'],
    oneLineSummary: 'Marcus Aurelius ruled the Roman Empire by day and wrote private meditations by night, never intending anyone to read his honest wrestlings with ego and duty.',
    spiritualAngle: 'The most powerful man on earth practiced what the Psalms model — honest, private conversation with the deepest questions of the soul.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'seneca-letters-on-suffering',
    title: 'A Stoic Who Sounded Like a Preacher',
    era: '65 AD',
    category: 'historical-figure',
    themes: ['suffering', 'wisdom', 'contentment', 'exile', 'inner-freedom'],
    oneLineSummary: 'Seneca wrote letters from exile about finding peace in suffering and the futility of wealth — advice so biblical that early Christians claimed he secretly corresponded with Paul.',
    spiritualAngle: 'God scatters fragments of truth everywhere — even a pagan philosopher can echo "I have learned the secret of being content in any circumstance."',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'epictetus-born-slave-taught-emperors',
    title: 'The Slave Who Taught Emperors to Think',
    era: '50-135 AD',
    category: 'historical-figure',
    themes: ['freedom', 'suffering', 'identity', 'control', 'inner-strength'],
    oneLineSummary: 'Born a slave with a crippled leg, Epictetus taught that the only true freedom is choosing your response — a philosophy later adopted by emperors.',
    spiritualAngle: 'Paul wrote from prison that he had learned to be content in all circumstances — Epictetus discovered the same truth from the other side of faith.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'hypatia-of-alexandria',
    title: 'The Woman Who Taught Philosophy in a Mans World',
    era: '355-415 AD',
    category: 'historical-figure',
    themes: ['courage', 'wisdom', 'persecution', 'gender', 'learning'],
    oneLineSummary: 'Hypatia of Alexandria was the ancient worlds foremost female philosopher and mathematician, murdered by a mob for refusing to stop teaching.',
    spiritualAngle: 'The pursuit of truth will always cost something — and sometimes the people who silence seekers do so in Gods name.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'confucius-relationships',
    title: 'The Teacher Who Built Ethics on Relationship',
    era: '551-479 BC',
    category: 'historical-figure',
    themes: ['relationships', 'respect', 'community', 'wisdom', 'duty', 'honor'],
    oneLineSummary: 'Confucius taught that all morality flows from how we treat the five key relationships — ruler-subject, parent-child, husband-wife, elder-younger, friend-friend.',
    spiritualAngle: 'Jesus summarized the law as loving God and neighbor — Confucius arrived at a remarkably similar conclusion: ethics is always about how we treat each other.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'lao-tzu-water-wisdom',
    title: 'The Sage Who Said Strength Looks Like Water',
    era: '6th century BC',
    category: 'historical-figure',
    themes: ['humility', 'strength', 'paradox', 'gentleness', 'wisdom'],
    oneLineSummary: 'Lao Tzu taught that water — soft, yielding, flowing around obstacles — is the most powerful force in nature, wearing down stone over time.',
    spiritualAngle: 'The meek shall inherit the earth is not weakness — it is the water-like power of patience outlasting every rigid thing.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'rumi-spiritual-poetry',
    title: 'The Poet Who Lost Everything and Found God',
    era: '1207-1273',
    category: 'historical-figure',
    themes: ['loss', 'spiritual-seeking', 'love', 'transformation', 'mysticism'],
    oneLineSummary: 'After his beloved teacher Shams vanished, Rumi was so shattered that poetry poured out of him — 65,000 verses of longing that became the worlds best-selling poetry.',
    spiritualAngle: 'The wound is the place where the light enters you — Rumis greatest art came from his greatest grief, the pattern of all spiritual growth.',
    source: 'historical',
    spinnable: true,
  },

  // ==========================================
  // MEDIEVAL & RENAISSANCE — INVENTORS & VISIONARIES
  // ==========================================
  {
    id: 'gutenberg-printing-press',
    title: 'The Man Who Put the Bible in Every Home',
    era: '1440',
    category: 'historical-figure',
    themes: ['access', 'revolution', 'democratization', 'Scripture', 'technology'],
    oneLineSummary: 'Gutenbergs movable-type printing press made the Bible — previously chained to pulpits — affordable and available, igniting the Reformation.',
    spiritualAngle: 'God uses technology to remove barriers between people and his Word — from the printing press to the smartphone in your hand right now.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'galileo-letter-duchess-christina',
    title: 'The Scientist Who Loved God and Told the Truth',
    era: '1615',
    category: 'historical-figure',
    themes: ['faith-and-science', 'courage', 'truth', 'conflict', 'conviction'],
    oneLineSummary: 'Galileo wrote to Duchess Christina that the Bible teaches how to go to heaven, not how the heavens go — defending science as a form of worship.',
    spiritualAngle: 'Galileo believed studying creation was studying the mind of the Creator — and that truth never truly contradicts truth.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'leonardo-notebooks-curiosity',
    title: 'The Man Whose Notebooks Were Prayers of Curiosity',
    era: '1452-1519',
    category: 'historical-figure',
    themes: ['curiosity', 'wonder', 'creativity', 'observation', 'worship'],
    oneLineSummary: 'Leonardo da Vinci filled 7,200 pages of notebooks with questions about everything — how birds fly, why the sky is blue, how the heart pumps blood.',
    spiritualAngle: 'Relentless curiosity about the world is a form of honoring its Maker — every question asked of creation is a prayer addressed to the Creator.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'hildegard-of-bingen',
    title: 'The Medieval Nun Who Did Everything',
    era: '1098-1179',
    category: 'historical-figure',
    themes: ['creativity', 'calling', 'gender', 'mysticism', 'boldness'],
    oneLineSummary: 'Hildegard of Bingen composed music, wrote theology, practiced medicine, advised popes, and painted her visions — all from a 12th-century convent.',
    spiritualAngle: 'When God gives you a calling, the limitations of your circumstances become irrelevant — a cloistered nun became one of the most prolific creators in medieval Europe.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'bartolome-de-las-casas',
    title: 'The Colonizer Who Became the Colonized Peoples Advocate',
    era: '1484-1566',
    category: 'historical-figure',
    themes: ['repentance', 'justice', 'conversion', 'advocacy', 'courage'],
    oneLineSummary: 'Bartolome de las Casas arrived in the Americas as a slave-owning colonizer, then underwent a radical conversion and spent 50 years fighting for Indigenous rights.',
    spiritualAngle: 'True repentance does not just change what you believe — it changes what you do, even when it costs you everything you once profited from.',
    source: 'historical',
    spinnable: true,
  },

  // ==========================================
  // RESCUERS & UNSUNG HEROES
  // ==========================================
  {
    id: 'irena-sendler-2500-children',
    title: 'The Woman Who Hid 2500 Names in a Jar',
    era: '1940-1943',
    category: 'historical-figure',
    themes: ['courage', 'sacrifice', 'rescue', 'secrecy', 'children'],
    oneLineSummary: 'Irena Sendler smuggled 2,500 Jewish children out of the Warsaw Ghetto and buried their real names in jars so families could reunite after the war.',
    spiritualAngle: 'She preserved identities because she believed every child had a name that mattered — a conviction rooted in the God who calls us each by name.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'raoul-wallenberg-fake-passports',
    title: 'The Diplomat Who Forged Papers to Save Lives',
    era: '1944',
    category: 'historical-figure',
    themes: ['courage', 'sacrifice', 'rescue', 'risk', 'justice'],
    oneLineSummary: 'Swedish diplomat Raoul Wallenberg issued thousands of fake protective passports to Hungarian Jews, pulling people off death march trains with nothing but paper and nerve.',
    spiritualAngle: 'Sometimes the most sacred act is the most illegal one — when human law contradicts divine mercy, the faithful must choose mercy.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'chiune-sugihara-visas',
    title: 'The Japanese Diplomat Who Defied His Government',
    era: '1940',
    category: 'historical-figure',
    themes: ['disobedience', 'mercy', 'sacrifice', 'courage', 'conscience'],
    oneLineSummary: 'Against direct orders, Japanese consul Chiune Sugihara hand-wrote thousands of transit visas for Jewish refugees, saving an estimated 6,000 lives.',
    spiritualAngle: 'When asked why he defied his government, Sugihara said he simply could not abandon people who came to his door — the same instinct behind every act of Good Samaritan faith.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'paul-rusesabagina-hotel-rwanda',
    title: 'The Hotel Manager Who Sheltered a Thousand',
    era: '1994',
    category: 'historical-figure',
    themes: ['courage', 'protection', 'genocide', 'ordinary-heroism', 'leadership'],
    oneLineSummary: 'Hotel manager Paul Rusesabagina sheltered 1,268 Tutsi refugees in the Hotel des Mille Collines during the Rwandan genocide, using charm and bribery to keep killers at bay.',
    spiritualAngle: 'God often places ordinary people in extraordinary positions — your workplace, your influence, your network might be exactly the shelter someone needs.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'nicholas-winton-kindertransport',
    title: 'The Man Who Kept His Secret for 50 Years',
    era: '1939',
    category: 'historical-figure',
    themes: ['humility', 'rescue', 'secrecy', 'children', 'goodness'],
    oneLineSummary: 'Nicholas Winton organized the rescue of 669 Czech Jewish children and told no one — his wife found a scrapbook in their attic 50 years later.',
    spiritualAngle: 'Jesus said when you give, dont let your left hand know what your right hand is doing — Winton lived that command literally for half a century.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'witold-pilecki-volunteered-for-auschwitz',
    title: 'The Soldier Who Volunteered to Enter Auschwitz',
    era: '1940-1943',
    category: 'historical-figure',
    themes: ['sacrifice', 'courage', 'witness', 'truth-telling', 'endurance'],
    oneLineSummary: 'Polish officer Witold Pilecki deliberately got himself arrested to infiltrate Auschwitz, spend 2.5 years documenting atrocities, then escaped to deliver the first eyewitness reports to the Allies.',
    spiritualAngle: 'He walked into hell voluntarily so the world could know the truth — an echo of every prophet who entered the darkness to bring back a witness.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'sophie-scholl-white-rose',
    title: 'The 21-Year-Old Who Defied the Third Reich with Leaflets',
    era: '1942-1943',
    category: 'historical-figure',
    themes: ['courage', 'youth', 'resistance', 'conviction', 'martyrdom'],
    oneLineSummary: 'Sophie Scholl distributed anti-Nazi leaflets at the University of Munich, was caught, tried, and executed at 21 — telling the judge somebody had to make a start.',
    spiritualAngle: 'She proved that a conscience aligned with truth is more dangerous to tyranny than an army — and that the young can lead the way in moral courage.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'adelaide-hautval-refused-nazi-experiments',
    title: 'The Doctor Who Said No at Auschwitz',
    era: '1943',
    category: 'historical-figure',
    themes: ['integrity', 'courage', 'ethics', 'resistance', 'conscience'],
    oneLineSummary: 'French psychiatrist Adelaide Hautval was ordered to assist in Nazi medical experiments at Auschwitz and flatly refused, telling her captors that the experiments were against her medical ethics.',
    spiritualAngle: 'There are moments when no is the most sacred word you can speak — when obedience to authority would mean disobedience to everything you know is true.',
    source: 'historical',
    spinnable: true,
  },

  // ==========================================
  // MUSICIANS, POETS & ARTISTS
  // ==========================================
  {
    id: 'bob-dylan-gospel-period',
    title: 'Rock and Rolls Prophet Goes Born Again',
    era: '1979-1981',
    category: 'historical-figure',
    themes: ['conversion', 'transformation', 'art', 'controversy', 'faith'],
    oneLineSummary: 'Bob Dylan shocked the music world by releasing three overtly Christian albums, preaching at concerts, and refusing to play his old hits — the voice of a generation reborn.',
    spiritualAngle: 'When God gets hold of someone, the world finds it uncomfortable — Dylans fans wanted the old rebel, not the new believer.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'johnny-cash-folsom-prison',
    title: 'The Man in Black Who Sang for Prisoners',
    era: '1968',
    category: 'historical-figure',
    themes: ['redemption', 'empathy', 'addiction', 'broken', 'ministry'],
    oneLineSummary: 'Johnny Cash chose to record his comeback album live at Folsom Prison because he saw his own brokenness in the inmates — and they saw their dignity in him.',
    spiritualAngle: 'Cash understood that the people most dismissed by society are often the most ready to hear about grace — because they already know they need it.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'beethoven-heiligenstadt-testament',
    title: 'The Composer Who Nearly Ended It All',
    era: '1802',
    category: 'historical-figure',
    themes: ['suffering', 'despair', 'purpose', 'creativity', 'perseverance'],
    oneLineSummary: 'Going deaf, Beethoven wrote a suicide letter at 31 confessing his desperation — then decided to live because he had more music inside him than silence could steal.',
    spiritualAngle: 'Sometimes the only reason to keep going is the conviction that your calling is not yet finished — and that purpose can outweigh pain.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'maya-angelou-caged-bird',
    title: 'The Girl Who Stopped Speaking and Found Her Voice',
    era: '1928-2014',
    category: 'historical-figure',
    themes: ['trauma', 'silence', 'voice', 'resilience', 'freedom'],
    oneLineSummary: 'After being assaulted at age 7, Maya Angelou went mute for five years — then broke her silence to become one of Americas most powerful voices.',
    spiritualAngle: 'The caged bird sings not because it has answers but because it has a song — and God gives songs even in cages.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'bach-soli-deo-gloria',
    title: 'The Composer Who Signed Everything to God',
    era: '1685-1750',
    category: 'historical-figure',
    themes: ['worship', 'vocation', 'dedication', 'excellence', 'humility'],
    oneLineSummary: 'Johann Sebastian Bach inscribed SDG — Soli Deo Gloria, to God alone be the glory — at the bottom of every composition, sacred and secular alike.',
    spiritualAngle: 'Bach saw no divide between sacred and secular work — every cantata, fugue, and dance was worship because the Audience that mattered was always the same.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'fanny-crosby-blind-hymn-writer',
    title: 'The Blind Woman Who Wrote 9000 Hymns',
    era: '1820-1915',
    category: 'historical-figure',
    themes: ['disability', 'joy', 'worship', 'prolific', 'perspective'],
    oneLineSummary: 'Blinded at six weeks old by a doctors mistake, Fanny Crosby wrote over 9,000 hymns and said she would not trade her blindness because the first face she would ever see would be her Saviors.',
    spiritualAngle: 'She reframed her greatest loss as her greatest gift — a radical trust that God wastes nothing, not even what was stolen.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'mahalia-jackson-march-on-washington',
    title: 'The Voice That Told MLK to Tell Them About the Dream',
    era: '1963',
    category: 'historical-figure',
    themes: ['worship', 'justice', 'influence', 'boldness', 'partnership'],
    oneLineSummary: 'Standing behind Martin Luther King Jr. at the March on Washington, gospel singer Mahalia Jackson shouted "Tell them about the dream, Martin!" — and he abandoned his prepared speech.',
    spiritualAngle: 'The most pivotal moments in history are sometimes sparked by someone who knows when to shout an encouragement — a ministry of prompting.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'nina-simone-mississippi-goddam',
    title: 'The Pianist Who Turned Rage Into Prophecy',
    era: '1964',
    category: 'historical-figure',
    themes: ['anger', 'justice', 'art', 'prophecy', 'lament'],
    oneLineSummary: 'After the Birmingham church bombing killed four girls, Nina Simone wrote Mississippi Goddam in an hour — a song so raw that radio stations smashed the records.',
    spiritualAngle: 'Righteous anger is biblical — the prophets raged, Jesus flipped tables — and sometimes the most faithful response to injustice is a song that refuses to be polite.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'blind-willie-johnson-dark-was-night',
    title: 'The Blind Preacher Whose Song Left the Solar System',
    era: '1927',
    category: 'historical-figure',
    themes: ['suffering', 'beauty', 'transcendence', 'obscurity', 'legacy'],
    oneLineSummary: 'Blind Willie Johnson, a street preacher blinded as a child, recorded "Dark Was the Night, Cold Was the Ground" — later chosen by NASA for the Voyager Golden Record as humanitys sound.',
    spiritualAngle: 'A blind mans wordless moan of longing was deemed the most human sound ever recorded — because the deepest prayers have no words.',
    source: 'historical',
    spinnable: true,
  },

  // ==========================================
  // ENTREPRENEURS WITH MORAL CHOICES
  // ==========================================
  {
    id: 'cadbury-quaker-ethics',
    title: 'The Chocolate Maker Who Built a Village for Workers',
    era: '1879',
    category: 'historical-figure',
    themes: ['business-ethics', 'justice', 'generosity', 'community', 'faith-in-action'],
    oneLineSummary: 'Quaker George Cadbury built Bournville — a model village with parks, schools, and gardens for his chocolate factory workers — because profit without human flourishing was no profit at all.',
    spiritualAngle: 'Cadbury believed business was a form of ministry and that every employer is a steward of the lives that depend on them.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'yvon-chouinard-patagonia-giveaway',
    title: 'The Billionaire Who Gave His Company to the Earth',
    era: '2022',
    category: 'historical-figure',
    themes: ['stewardship', 'generosity', 'simplicity', 'creation-care', 'detachment'],
    oneLineSummary: 'Yvon Chouinard transferred ownership of $3 billion Patagonia to a trust dedicated to fighting climate change, saying "Earth is now our only shareholder."',
    spiritualAngle: 'Chouinard practiced what Jesus taught the rich young ruler — the willingness to let go of what you have built is the truest measure of what you actually worship.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'blake-mycoskie-toms-shoes',
    title: 'The Traveler Who Turned Empathy Into a Business Model',
    era: '2006',
    category: 'historical-figure',
    themes: ['compassion', 'generosity', 'innovation', 'seeing', 'action'],
    oneLineSummary: 'Blake Mycoskie saw barefoot children in Argentina and started TOMS Shoes on a one-for-one model — every pair purchased meant one donated to a child in need.',
    spiritualAngle: 'Compassion that stops at feeling is incomplete — the Good Samaritan didnt just feel sorry, he rearranged his entire schedule and wallet.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'jonas-salk-refused-to-patent',
    title: 'The Doctor Who Gave Away the Cure',
    era: '1955',
    category: 'historical-figure',
    themes: ['generosity', 'sacrifice', 'healing', 'service', 'integrity'],
    oneLineSummary: 'Jonas Salk refused to patent the polio vaccine, forgoing an estimated $7 billion, saying "Could you patent the sun?"',
    spiritualAngle: 'Some gifts are too important to monetize — Salk treated healing as a calling, not a commodity, echoing Jesus who said freely you have received, freely give.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'john-woolman-quaker-abolitionist',
    title: 'The Tailor Who Quietly Ended Quaker Slavery',
    era: '1720-1772',
    category: 'historical-figure',
    themes: ['justice', 'patience', 'persuasion', 'integrity', 'simplicity'],
    oneLineSummary: 'Quaker tailor John Woolman spent 30 years quietly visiting slave-owning Friends one by one, gently asking them to reconsider — until Quakers became the first group in America to free their slaves.',
    spiritualAngle: 'Woolman changed an entire community not through protests but through patient, personal conversation — the slow, relational work of conviction.',
    source: 'historical',
    spinnable: true,
  },

  // ==========================================
  // EDUCATORS & REFORMERS
  // ==========================================
  {
    id: 'maria-montessori-seeing-children',
    title: 'The Doctor Who Watched Children Before Teaching Them',
    era: '1907',
    category: 'historical-figure',
    themes: ['observation', 'respect', 'children', 'dignity', 'patience'],
    oneLineSummary: 'Maria Montessori revolutionized education by doing something radical: she stopped talking and started watching what children actually do when left to explore freely.',
    spiritualAngle: 'Before God teaches us, he watches us — and the best teachers, like the best parents, begin with observation rather than instruction.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'frederick-douglass-literacy',
    title: 'The Slave Who Taught Himself to Read the World Open',
    era: '1838',
    category: 'historical-figure',
    themes: ['freedom', 'education', 'perseverance', 'dignity', 'self-liberation'],
    oneLineSummary: 'Frederick Douglass taught himself to read by trading bread for lessons from white boys on the street, knowing that literacy was the pathway from slavery to freedom.',
    spiritualAngle: 'The truth will set you free — Douglass understood this literally, knowing that the ability to read was the beginning of the ability to be fully human.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'booker-t-washington-tuskegee',
    title: 'The Former Slave Who Built a University',
    era: '1881',
    category: 'historical-figure',
    themes: ['perseverance', 'education', 'dignity', 'building', 'service'],
    oneLineSummary: 'Born into slavery, Booker T. Washington arrived at Tuskegee with 30 students and a rundown church, building it into a world-class institution through relentless work and practical vision.',
    spiritualAngle: 'Washington believed in casting down your bucket where you are — that faithfulness starts with the resources and circumstances God has already given you.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'malala-yousafzai-shot-for-learning',
    title: 'The Girl Who Was Shot for Wanting School',
    era: '2012',
    category: 'historical-figure',
    themes: ['courage', 'education', 'youth', 'resilience', 'voice'],
    oneLineSummary: 'Malala Yousafzai was shot in the head by the Taliban at 15 for advocating girls education — survived, recovered, and became the youngest Nobel laureate in history.',
    spiritualAngle: 'One child saying I have a right to learn shook an empire — a reminder that God often uses the young and small to challenge the powerful.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'ruby-bridges-first-grader',
    title: 'The Six-Year-Old Who Integrated a School',
    era: '1960',
    category: 'historical-figure',
    themes: ['courage', 'innocence', 'justice', 'faith', 'children'],
    oneLineSummary: 'Six-year-old Ruby Bridges walked past screaming mobs to attend an all-white school in New Orleans, praying for the protesters as federal marshals escorted her.',
    spiritualAngle: 'She prayed Father, forgive them for the same people who were spitting at her — a first-grader practicing what Jesus preached on the cross.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'paulo-freire-pedagogy-oppressed',
    title: 'The Teacher Who Said Literacy Is Liberation',
    era: '1968',
    category: 'historical-figure',
    themes: ['education', 'justice', 'empowerment', 'dignity', 'liberation'],
    oneLineSummary: 'Brazilian educator Paulo Freire taught illiterate farmworkers to read in 45 days by using words from their own lives — then was exiled because literate peasants could vote.',
    spiritualAngle: 'Jesus taught in parables drawn from fishing and farming because the best teacher enters the students world before asking the student to enter his.',
    source: 'historical',
    spinnable: true,
  },

  // ==========================================
  // MEDICAL HEROES
  // ==========================================
  {
    id: 'albert-schweitzer-lambarene',
    title: 'The Genius Who Left Everything for a Jungle Hospital',
    era: '1913',
    category: 'historical-figure',
    themes: ['sacrifice', 'calling', 'service', 'purpose', 'leaving'],
    oneLineSummary: 'Albert Schweitzer was a world-class organist, theologian, and philosopher — then at 30, he went to medical school and spent the rest of his life running a hospital in Gabon.',
    spiritualAngle: 'Reverence for life was Schweitzers creed — the conviction that every living thing matters pushed him to trade prestige for bandages and bedpans.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'florence-nightingale-calling',
    title: 'The Woman Who Heard God Say "Serve"',
    era: '1854',
    category: 'historical-figure',
    themes: ['calling', 'service', 'data', 'reform', 'obedience'],
    oneLineSummary: 'Florence Nightingale recorded hearing Gods voice calling her to service at age 16, then revolutionized nursing and pioneered statistical graphics to prove that sanitation saves lives.',
    spiritualAngle: 'She combined mystical calling with rigorous data — proof that faith and evidence are not opposites but allies in the work of healing.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'paul-farmer-partners-in-health',
    title: 'The Doctor Who Said the Poor Deserve the Best',
    era: '1987-2022',
    category: 'historical-figure',
    themes: ['justice', 'healthcare', 'sacrifice', 'dignity', 'preferential-option'],
    oneLineSummary: 'Dr. Paul Farmer co-founded Partners in Health to bring world-class medicine to the poorest places on earth, insisting that poverty is not a character flaw but a policy failure.',
    spiritualAngle: 'Farmer lived the preferential option for the poor — the conviction that Gods attention gravitates toward whoever is most forgotten.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'james-barry-secret-surgeon',
    title: 'The Military Surgeon with a Lifelong Secret',
    era: '1795-1865',
    category: 'historical-figure',
    themes: ['identity', 'calling', 'barrier-breaking', 'service', 'secrecy'],
    oneLineSummary: 'James Barry served as a top British military surgeon for 46 years, performing one of the first successful cesarean sections in Africa — and was discovered after death to have been assigned female at birth.',
    spiritualAngle: 'Sometimes the barriers between a person and their calling are so unjust that the only path forward is a creative one — and God honors the determination to serve.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'henrietta-lacks-immortal-cells',
    title: 'The Womans Cells That Changed Medicine Forever',
    era: '1951',
    category: 'historical-figure',
    themes: ['dignity', 'justice', 'legacy', 'sacrifice', 'hidden-contribution'],
    oneLineSummary: 'Henrietta Lacks, a poor Black woman, had her cancer cells taken without consent — they became the immortal HeLa line that enabled the polio vaccine, cancer research, and gene mapping.',
    spiritualAngle: 'The stone the builders rejected became the cornerstone — a woman ignored in life became indispensable to medicine, and the ethics of her story still convict us.',
    source: 'historical',
    spinnable: true,
  },

  // ==========================================
  // NON-WESTERN FIGURES & INDIGENOUS WISDOM
  // ==========================================
  {
    id: 'gandhi-sermon-on-mount',
    title: 'The Hindu Who Was Changed by Christs Sermon',
    era: '1893-1948',
    category: 'historical-figure',
    themes: ['nonviolence', 'truth', 'cross-cultural', 'conviction', 'integrity'],
    oneLineSummary: 'Gandhi called the Sermon on the Mount the most beautiful thing he ever read and built his philosophy of nonviolent resistance on its principles — then was told Christians dont follow it.',
    spiritualAngle: 'I like your Christ but not your Christians is a devastating mirror — and the question it raises is whether we practice what we preach.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'wangari-maathai-planting-trees',
    title: 'The Woman Who Saved a Country One Tree at a Time',
    era: '1977-2011',
    category: 'historical-figure',
    themes: ['stewardship', 'perseverance', 'creation-care', 'empowerment', 'hope'],
    oneLineSummary: 'Kenyan biologist Wangari Maathai started a tree-planting movement that grew to 51 million trees, empowered women, and won the Nobel Peace Prize — all beginning with a single seedling.',
    spiritualAngle: 'The kingdom of heaven is like a mustard seed — Maathai proved that faithfulness to a small beginning can reforest an entire nation.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'desmond-tutu-rainbow-nation',
    title: 'The Archbishop Who Chose Forgiveness Over Revenge',
    era: '1984-2021',
    category: 'historical-figure',
    themes: ['forgiveness', 'justice', 'reconciliation', 'joy', 'ubuntu'],
    oneLineSummary: 'Desmond Tutu chaired South Africas Truth and Reconciliation Commission, choosing restorative justice over retribution and insisting that there is no future without forgiveness.',
    spiritualAngle: 'Tutu embodied ubuntu — I am because we are — believing that the perpetrators humanity was also at stake in the process of reconciliation.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'thich-nhat-hanh-mindful-peace',
    title: 'The Monk Who Walked Slowly Through a War Zone',
    era: '1960s-2022',
    category: 'historical-figure',
    themes: ['peace', 'mindfulness', 'presence', 'nonviolence', 'compassion'],
    oneLineSummary: 'During the Vietnam War, Thich Nhat Hanh taught monks to rebuild bombed villages with slow, deliberate mindfulness — Martin Luther King Jr. nominated him for the Nobel Prize.',
    spiritualAngle: 'Peace is not just the absence of war but the presence of attention — being fully present is itself a form of prayer.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'aboriginal-dreamtime-stewardship',
    title: 'The Oldest Living Culture and Their Sacred Duty to Land',
    era: '65000 years to present',
    category: 'historical-figure',
    themes: ['stewardship', 'creation-care', 'wisdom', 'belonging', 'interconnection'],
    oneLineSummary: 'Aboriginal Australians have maintained the same land, stories, and sacred responsibilities for 65,000 years — the longest continuous culture on earth, rooted in belonging to country rather than owning it.',
    spiritualAngle: 'The land does not belong to us; we belong to the land — this ancient wisdom echoes Gods declaration that the earth is the Lords, and we are its stewards.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'native-american-seventh-generation',
    title: 'The Principle of Thinking Seven Generations Ahead',
    era: 'pre-colonial to present',
    category: 'historical-figure',
    themes: ['stewardship', 'future', 'responsibility', 'community', 'wisdom'],
    oneLineSummary: 'The Haudenosaunee (Iroquois) Confederacy required leaders to consider the impact of every decision on seven generations yet to come.',
    spiritualAngle: 'Living for the seventh generation is the ultimate act of love for neighbors you will never meet — a faith that your choices echo beyond your lifetime.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'rigoberta-menchu-guatemala',
    title: 'The Mayan Woman Who Told Her People\'s Story',
    era: '1983',
    category: 'historical-figure',
    themes: ['voice', 'justice', 'witness', 'indigenous', 'courage'],
    oneLineSummary: 'Rigoberta Menchu, a Quiche Mayan woman from Guatemala, told the world about the genocide of her people — losing her parents and brother to the violence she exposed.',
    spiritualAngle: 'Bearing witness to injustice at the cost of your own safety is the prophets calling — the refusal to let suffering remain invisible.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'sadako-sasaki-thousand-cranes',
    title: 'The Girl Who Folded Paper Cranes for Life',
    era: '1955',
    category: 'historical-figure',
    themes: ['hope', 'peace', 'children', 'perseverance', 'symbols'],
    oneLineSummary: 'Twelve-year-old Sadako Sasaki, dying of leukemia from Hiroshima radiation, tried to fold 1,000 paper cranes believing it would grant her wish to live — she folded 644 before she died.',
    spiritualAngle: 'Her unfinished cranes became the worlds most powerful symbol of peace — a reminder that sometimes an incomplete act of hope accomplishes more than we could ask or imagine.',
    source: 'historical',
    spinnable: true,
  },

  // ==========================================
  // MODERN ACTIVISTS & CHANGE-MAKERS
  // ==========================================
  {
    id: 'greta-thunberg-school-strike',
    title: 'The Teenager Who Sat Alone Outside Parliament',
    era: '2018',
    category: 'historical-figure',
    themes: ['youth', 'courage', 'prophetic-voice', 'action', 'conviction'],
    oneLineSummary: 'Fifteen-year-old Greta Thunberg sat alone outside the Swedish parliament with a hand-painted sign, sparking a global climate movement of millions — all from one quiet act of defiance.',
    spiritualAngle: 'A child shall lead them — sometimes the most prophetic voice is the one with the least power and the most clarity.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'bryan-stevenson-just-mercy',
    title: 'The Lawyer Who Says You Are More Than Your Worst Day',
    era: '1989-present',
    category: 'historical-figure',
    themes: ['mercy', 'justice', 'dignity', 'redemption', 'advocacy'],
    oneLineSummary: 'Bryan Stevenson has spent his career defending the wrongly condemned on death row, insisting that each of us is more than the worst thing we have ever done.',
    spiritualAngle: 'This is the gospel in a courtroom — the conviction that no human being is reducible to their worst moment, because God sees the whole person.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'dolores-huerta-si-se-puede',
    title: 'The Woman Behind "Yes We Can"',
    era: '1962-present',
    category: 'historical-figure',
    themes: ['justice', 'perseverance', 'workers', 'courage', 'voice'],
    oneLineSummary: 'Dolores Huerta co-founded the United Farm Workers alongside Cesar Chavez, coined "Si se puede," and was beaten nearly to death at a protest at age 58 — then kept going.',
    spiritualAngle: 'Huerta spent her life fighting for people who feed us but cannot feed themselves — embodying the biblical mandate to defend those who cannot defend themselves.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'nelson-mandela-27-years',
    title: 'The Prisoner Who Forgave His Jailers',
    era: '1964-1990',
    category: 'historical-figure',
    themes: ['forgiveness', 'patience', 'transformation', 'leadership', 'endurance'],
    oneLineSummary: 'Nelson Mandela spent 27 years in prison and emerged not bitter but magnanimous, wearing a Springbok jersey to unite the nation that had tried to destroy him.',
    spiritualAngle: 'Mandela proved that bitterness is a prison you put yourself in — and that forgiving your enemy is the only way to walk out free.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'dorothy-day-catholic-worker',
    title: 'The Radical Who Fed the Hungry Without Asking Questions',
    era: '1933-1980',
    category: 'historical-figure',
    themes: ['hospitality', 'poverty', 'radical-faith', 'justice', 'service'],
    oneLineSummary: 'Dorothy Day founded the Catholic Worker movement, opening houses of hospitality that fed anyone who showed up — no intake forms, no means testing, no strings attached.',
    spiritualAngle: 'Day took literally the command to feed my sheep — and her radical hospitality still challenges every church that asks the hungry to prove they deserve dinner.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'bayard-rustin-invisible-organizer',
    title: 'The Man Who Organized the March but Was Hidden from View',
    era: '1963',
    category: 'historical-figure',
    themes: ['sacrifice', 'hidden-contribution', 'justice', 'identity', 'service'],
    oneLineSummary: 'Bayard Rustin organized the March on Washington for 250,000 people but was kept behind the scenes because he was gay — choosing the cause over his own visibility.',
    spiritualAngle: 'Some of the most important work in history was done by people who were willing to be invisible for the sake of something bigger than themselves.',
    source: 'historical',
    spinnable: true,
  },

  // ==========================================
  // SCIENTISTS & THINKERS
  // ==========================================
  {
    id: 'rachel-carson-silent-spring',
    title: 'The Biologist Who Took On an Industry to Save the Birds',
    era: '1962',
    category: 'historical-figure',
    themes: ['courage', 'stewardship', 'truth-telling', 'creation-care', 'resistance'],
    oneLineSummary: 'Rachel Carson wrote Silent Spring exposing pesticide dangers while dying of cancer, enduring a smear campaign from the chemical industry that called her a hysterical woman.',
    spiritualAngle: 'Caring for creation is not optional — Carson heard the silent spring and spoke for a voiceless creation, just as the biblical prophets spoke for the voiceless.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'george-washington-carver-peanut-prophet',
    title: 'The Former Slave Who Talked to Flowers',
    era: '1864-1943',
    category: 'historical-figure',
    themes: ['creativity', 'humility', 'stewardship', 'prayer', 'innovation'],
    oneLineSummary: 'George Washington Carver said he asked God what the universe was for, God said that was too big — so he asked about the peanut, and God gave him 300 products from it.',
    spiritualAngle: 'Carver prayed before every experiment, seeing science as reading Gods other book — creation reveals as much about the Creator as Scripture does.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'rosalind-franklin-photo-51',
    title: 'The Woman Whose Work Was Stolen and Changed Biology',
    era: '1952',
    category: 'historical-figure',
    themes: ['injustice', 'contribution', 'hidden-work', 'perseverance', 'truth'],
    oneLineSummary: 'Rosalind Franklin captured Photo 51 — the X-ray image that revealed DNAs double helix — but Watson and Crick used it without her knowledge and won the Nobel Prize.',
    spiritualAngle: 'History eventually reveals hidden contributions — and God sees the work that others take credit for, just as he saw Hagar when everyone else overlooked her.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'marie-curie-radium-sacrifice',
    title: 'The Scientist Who Gave Her Body to Her Discovery',
    era: '1898-1934',
    category: 'historical-figure',
    themes: ['sacrifice', 'dedication', 'discovery', 'cost', 'calling'],
    oneLineSummary: 'Marie Curie discovered radium and carried test tubes in her pockets, not knowing the radiation would kill her — her notebooks are still too radioactive to handle without protection.',
    spiritualAngle: 'Some callings cost you your life in slow motion — and the question is whether the truth you are pursuing is worth the price your body will pay.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'albert-einstein-thought-experiments',
    title: 'The Patent Clerk Who Reimagined the Universe',
    era: '1905',
    category: 'historical-figure',
    themes: ['imagination', 'humility', 'wonder', 'persistence', 'outsider'],
    oneLineSummary: 'Einstein was a patent clerk with no academic position when he published four papers that revolutionized physics — beginning with a thought experiment about riding a beam of light.',
    spiritualAngle: 'God chose the foolish things of the world to shame the wise — breakthroughs often come from outsiders precisely because insiders cannot imagine what they cannot see.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'katherine-johnson-nasa-calculations',
    title: 'The Human Computer NASA Could Not Launch Without',
    era: '1961',
    category: 'historical-figure',
    themes: ['persistence', 'excellence', 'hidden-contribution', 'barrier-breaking', 'precision'],
    oneLineSummary: 'Katherine Johnson, a Black woman mathematician, hand-calculated the orbital trajectory for John Glenns spaceflight — he refused to fly until she personally verified the computers numbers.',
    spiritualAngle: 'Faithfulness in the details matters more than visibility — Johnson did her work in a segregated office, but her precision put a man in orbit.',
    source: 'historical',
    spinnable: true,
  },

  // ==========================================
  // WRITERS & STORYTELLERS
  // ==========================================
  {
    id: 'victor-hugo-les-miserables',
    title: 'The Novelist Who Preached Grace Through Fiction',
    era: '1862',
    category: 'historical-figure',
    themes: ['grace', 'redemption', 'justice', 'mercy', 'transformation'],
    oneLineSummary: 'Victor Hugo wrote Les Miserables to show that one act of radical grace — a bishop giving silver to a thief — could redirect an entire life toward goodness.',
    spiritualAngle: 'The bishops candlesticks are the gospel in miniature: I have bought your soul for God — grace that refuses to let the past define the future.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'tolkien-eucatastrophe',
    title: 'The Professor Who Named the Unexpected Happy Ending',
    era: '1947',
    category: 'historical-figure',
    themes: ['hope', 'storytelling', 'redemption', 'joy', 'gospel'],
    oneLineSummary: 'J.R.R. Tolkien coined the word eucatastrophe — the sudden, joyous turn in a story when all seems lost — and said the Resurrection is the greatest eucatastrophe in history.',
    spiritualAngle: 'Every good story echoes the original good story — the darkness is real, but the dawn comes, and joy arrives precisely when hope has been abandoned.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'flannery-oconnor-grotesque-grace',
    title: 'The Southern Writer Who Showed Grace as Violence',
    era: '1952-1964',
    category: 'historical-figure',
    themes: ['grace', 'disruption', 'truth', 'suffering', 'revelation'],
    oneLineSummary: 'Flannery OConnor wrote stories where grace arrives violently — a grandmother shot by a serial killer, a bull goring a farm woman — because she believed the deaf need to hear loud.',
    spiritualAngle: 'OConnor understood that grace sometimes looks like interruption, not comfort — God breaking through our illusions by whatever means necessary.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'dostoevsky-brothers-karamazov',
    title: 'The Convict Who Wrote the Greatest Novel About Faith',
    era: '1880',
    category: 'historical-figure',
    themes: ['suffering', 'doubt', 'faith', 'evil', 'redemption'],
    oneLineSummary: 'Dostoevsky survived a mock execution and Siberian prison, then wrote The Brothers Karamazov — putting the strongest arguments against God into the mouth of Ivan so that Alyoshas faith would mean more.',
    spiritualAngle: 'Honest doubt strengthens faith more than easy belief — Dostoevsky knew that a God who cannot survive scrutiny is not worth worshiping.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'harriet-beecher-stowe-uncle-toms-cabin',
    title: 'The Novel That Helped Start a War',
    era: '1852',
    category: 'historical-figure',
    themes: ['justice', 'empathy', 'storytelling', 'conscience', 'power-of-narrative'],
    oneLineSummary: 'Harriet Beecher Stowes Uncle Toms Cabin sold 300,000 copies in its first year and made slavery personal to millions who had never thought about it — Lincoln allegedly called her the little woman who started the great war.',
    spiritualAngle: 'Stories change the world because they bypass our defenses — the way Nathans parable made David condemn himself before he realized it was about him.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'elie-wiesel-night-witness',
    title: 'The Witness Who Nearly Chose Silence',
    era: '1958',
    category: 'historical-figure',
    themes: ['witness', 'suffering', 'silence', 'memory', 'responsibility'],
    oneLineSummary: 'Elie Wiesel waited ten years after Auschwitz to write Night, breaking silence only because he realized forgetting would betray the dead — and silence would make him complicit.',
    spiritualAngle: 'The opposite of love is not hate but indifference — Wiesels life mission was ensuring the world could never say it did not know.',
    source: 'historical',
    spinnable: true,
  },

  // ==========================================
  // FAITH FIGURES — UNEXPECTED ANGLES
  // ==========================================
  {
    id: 'thomas-merton-seven-storey-mountain',
    title: 'The Party Boy Who Became Americas Most Famous Monk',
    era: '1948',
    category: 'historical-figure',
    themes: ['conversion', 'solitude', 'contemplation', 'transformation', 'seeking'],
    oneLineSummary: 'Thomas Merton was a hard-drinking Columbia University student who entered a Trappist monastery and wrote a bestselling memoir about finding God in silence.',
    spiritualAngle: 'Mertons journey from nightclubs to monastic silence proves that the loudest souls sometimes need the quietest rooms to hear what God has been saying all along.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'simone-weil-attention-prayer',
    title: 'The Philosopher Who Called Attention the Purest Prayer',
    era: '1909-1943',
    category: 'historical-figure',
    themes: ['attention', 'presence', 'prayer', 'suffering', 'generosity'],
    oneLineSummary: 'Simone Weil wrote that attention is the rarest and purest form of generosity — and starved herself in solidarity with occupied France, dying at 34.',
    spiritualAngle: 'If attention is generosity, then distraction is the opposite of love — and learning to be fully present to another person is the deepest form of prayer.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'howard-thurman-jesus-disinherited',
    title: 'The Mystic Who Showed Jesus Was a Poor Jew Under Rome',
    era: '1949',
    category: 'historical-figure',
    themes: ['justice', 'identity', 'liberation', 'belonging', 'power'],
    oneLineSummary: 'Howard Thurman wrote Jesus and the Disinherited, arguing that Jesus lived as a marginalized minority under an empire — and that changes everything about how the oppressed should read the gospels.',
    spiritualAngle: 'Thurman reminded the church that Jesus was not a comfortable middle-class teacher but a colonized subject — and the gospel sounds different when you hear it from below.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'pandita-ramabai-india',
    title: 'The Indian Widow Who Built a Sanctuary',
    era: '1889',
    category: 'historical-figure',
    themes: ['justice', 'women', 'conversion', 'sacrifice', 'barrier-breaking'],
    oneLineSummary: 'Pandita Ramabai, a Brahmin widow who converted to Christianity, founded Mukti Mission to rescue child widows and famine victims in India — eventually sheltering 2,000 women and girls.',
    spiritualAngle: 'Ramabai crossed every boundary her culture enforced — caste, gender, religion — because she believed the God she found had no such boundaries.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'kierkegaard-leap-of-faith',
    title: 'The Philosopher Who Said Faith Requires a Jump',
    era: '1843',
    category: 'historical-figure',
    themes: ['faith', 'doubt', 'risk', 'authenticity', 'decision'],
    oneLineSummary: 'Soren Kierkegaard argued that faith is not intellectual certainty but a passionate leap — you cannot reason your way to God, you must at some point jump.',
    spiritualAngle: 'Abraham did not have evidence when he left Haran — Kierkegaard understood that real faith begins where proof ends and trust begins.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'dag-hammarskjold-markings',
    title: 'The UN Secretary-General with a Secret Spiritual Diary',
    era: '1953-1961',
    category: 'historical-figure',
    themes: ['leadership', 'inner-life', 'service', 'solitude', 'sacrifice'],
    oneLineSummary: 'Dag Hammarskjold led the United Nations through the Cold War while keeping a private spiritual journal, Markings, found after his death in a plane crash — revealing a life of mystical devotion.',
    spiritualAngle: 'The most powerful diplomat on earth wrote privately about surrender to God — proof that the inner life sustains the outer mission.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'sojourner-truth-aint-i-a-woman',
    title: 'The Former Slave Who Silenced a Convention',
    era: '1851',
    category: 'historical-figure',
    themes: ['dignity', 'justice', 'voice', 'gender', 'faith'],
    oneLineSummary: 'Sojourner Truth, born into slavery and illiterate, stood before a womens rights convention and delivered one of historys most powerful speeches — "Aint I a woman?"',
    spiritualAngle: 'Truth spoke with prophetic authority that came not from education but from experience — God often gives the most powerful words to the most overlooked people.',
    source: 'historical',
    spinnable: true,
  },

  // ==========================================
  // SPORTS & PERSEVERANCE
  // ==========================================
  {
    id: 'wilma-rudolph-overcame-polio',
    title: 'The Girl in a Leg Brace Who Became the Fastest Woman Alive',
    era: '1960',
    category: 'historical-figure',
    themes: ['perseverance', 'healing', 'overcoming', 'disability', 'determination'],
    oneLineSummary: 'Wilma Rudolph could not walk without a brace until age 12 due to polio — then won three Olympic gold medals in sprinting, becoming the fastest woman in the world.',
    spiritualAngle: 'The very thing that seemed to disqualify her became the context for her greatest triumph — God specializes in stories where the obstacle becomes the origin.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'jesse-owens-berlin-1936',
    title: 'The Black Athlete Who Humiliated a Racist Ideology',
    era: '1936',
    category: 'historical-figure',
    themes: ['dignity', 'courage', 'racism', 'excellence', 'defiance'],
    oneLineSummary: 'Jesse Owens won four gold medals at Hitlers Berlin Olympics, demolishing the myth of Aryan supremacy — and it was a German competitor, Luz Long, who helped him qualify.',
    spiritualAngle: 'Owens and Longs friendship across enemy lines proved that human dignity cannot be legislated away — and that kindness can cross any divide.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'terry-fox-marathon-of-hope',
    title: 'The One-Legged Runner Who Tried to Cross Canada',
    era: '1980',
    category: 'historical-figure',
    themes: ['perseverance', 'sacrifice', 'cancer', 'hope', 'unfinished'],
    oneLineSummary: 'After losing his leg to cancer, 21-year-old Terry Fox ran a marathon a day across Canada to raise money for research — running 143 days before the cancer returned and stopped him.',
    spiritualAngle: 'Fox never finished his run, but his unfinished race has raised over $850 million — proof that faithfulness matters more than completion.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'simone-biles-mental-health-2021',
    title: 'The Greatest Gymnast Who Chose Herself Over Gold',
    era: '2021',
    category: 'historical-figure',
    themes: ['courage', 'vulnerability', 'mental-health', 'boundaries', 'self-care'],
    oneLineSummary: 'Simone Biles withdrew from Olympic events at the height of her career to protect her mental health, facing enormous backlash — then returned to win bronze on beam.',
    spiritualAngle: 'Sometimes the bravest thing is not pushing through but stepping back — recognizing that your worth is not your performance is its own kind of victory.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'muhammad-ali-refused-the-draft',
    title: 'The Champion Who Lost Everything for His Conscience',
    era: '1967',
    category: 'historical-figure',
    themes: ['conviction', 'sacrifice', 'courage', 'conscience', 'principle'],
    oneLineSummary: 'Muhammad Ali was stripped of his heavyweight title and banned from boxing for three years after refusing the Vietnam draft, saying "I aint got no quarrel with them Viet Cong."',
    spiritualAngle: 'Ali sacrificed his prime years and livelihood for a principle — a reminder that some things are worth more than career, money, and public approval.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'eric-liddell-chariots-of-fire',
    title: 'The Olympian Who Wouldnt Run on Sunday',
    era: '1924',
    category: 'historical-figure',
    themes: ['conviction', 'faith', 'sacrifice', 'integrity', 'calling'],
    oneLineSummary: 'Eric Liddell refused to run his best event at the 1924 Olympics because the heats fell on a Sunday, then won gold in the 400m — and later died in a Japanese internment camp as a missionary.',
    spiritualAngle: 'Liddell said God made me fast and when I run I feel His pleasure — his obedience to conviction rather than ambition is the definition of worship.',
    source: 'historical',
    spinnable: true,
  },

  // ==========================================
  // LEADERS & STATESPEOPLE
  // ==========================================
  {
    id: 'vaclav-havel-power-of-powerless',
    title: 'The Playwright Who Became President Through Truth',
    era: '1978-2003',
    category: 'historical-figure',
    themes: ['truth', 'courage', 'nonviolence', 'integrity', 'art'],
    oneLineSummary: 'Vaclav Havel wrote that the greengrocer who stops displaying false propaganda is performing a revolution — then proved it when Czechoslovakia\'s Velvet Revolution made him president.',
    spiritualAngle: 'Living in truth is inherently subversive — Havel showed that simply refusing to participate in a lie can topple an empire.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'lincoln-second-inaugural',
    title: 'The President Who Blamed Both Sides for the War',
    era: '1865',
    category: 'historical-figure',
    themes: ['humility', 'judgment', 'mercy', 'reconciliation', 'grief'],
    oneLineSummary: 'In his Second Inaugural Address, Lincoln refused to claim God was on the Unions side, saying both sides prayed to the same God and read the same Bible — and that the war was divine judgment on all of America.',
    spiritualAngle: 'Lincoln modeled a devastating theological humility — the refusal to weaponize God against your enemies when your own hands are not clean.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'aung-san-suu-kyi-house-arrest',
    title: 'The Woman Who Chose Her Country Over Her Family',
    era: '1989-2010',
    category: 'historical-figure',
    themes: ['sacrifice', 'conviction', 'loneliness', 'courage', 'cost'],
    oneLineSummary: 'Aung San Suu Kyi spent 15 years under house arrest in Myanmar, unable to see her dying husband in England because she knew if she left, she could never return.',
    spiritualAngle: 'Some callings require choosing between the people you love and the people who need you — a cost that has no clean answer, only faith.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'william-wilberforce-abolition',
    title: 'The Politician Who Spent 46 Years Ending Slavery',
    era: '1787-1833',
    category: 'historical-figure',
    themes: ['perseverance', 'justice', 'faith-in-action', 'patience', 'calling'],
    oneLineSummary: 'William Wilberforce introduced abolition bills in Parliament year after year for 46 years, facing mockery and defeat — dying three days after the Slavery Abolition Act finally passed.',
    spiritualAngle: 'Wilberforces life is a case study in what faithfulness looks like when the timeline is Gods, not yours — the willingness to plant seeds you may not live to harvest.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'dietrich-bonhoeffer-cost-of-discipleship',
    title: 'The Pastor Who Returned to Nazi Germany on Purpose',
    era: '1939-1945',
    category: 'historical-figure',
    themes: ['courage', 'sacrifice', 'cheap-grace', 'discipleship', 'conviction'],
    oneLineSummary: 'Dietrich Bonhoeffer escaped to safety in America, then turned around and returned to Nazi Germany because he could not rebuild his country if he had not shared its suffering.',
    spiritualAngle: 'When Christ calls a man, he bids him come and die — Bonhoeffer wrote it and then lived it, executed by the Nazis weeks before liberation.',
    source: 'historical',
    spinnable: true,
  },

  // ==========================================
  // FORGIVENESS & RECONCILIATION
  // ==========================================
  {
    id: 'eva-mozes-kor-forgiving-mengele',
    title: 'The Auschwitz Twin Who Forgave Her Torturer',
    era: '1995',
    category: 'historical-figure',
    themes: ['forgiveness', 'freedom', 'healing', 'trauma', 'choice'],
    oneLineSummary: 'Eva Mozes Kor, subjected to Mengeles twin experiments at Auschwitz, publicly forgave the Nazis — not for their sake, but because she refused to let them keep her imprisoned in rage.',
    spiritualAngle: 'Forgiveness is not saying what happened was okay — it is refusing to let the person who hurt you control the rest of your life.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'immaculee-ilibagiza-left-to-tell',
    title: 'The Woman Who Hid for 91 Days and Forgave',
    era: '1994',
    category: 'historical-figure',
    themes: ['forgiveness', 'survival', 'prayer', 'genocide', 'faith'],
    oneLineSummary: 'Immaculee Ilibagiza hid in a tiny bathroom with seven other women for 91 days during the Rwandan genocide, losing most of her family — then found the killer and forgave him face to face.',
    spiritualAngle: 'She prayed the rosary thousands of times in that bathroom and emerged not with bitterness but with the supernatural ability to look at a murderer and say I forgive you.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'amish-nickel-mines-forgiveness',
    title: 'The Community That Forgave Before the Funerals',
    era: '2006',
    category: 'historical-figure',
    themes: ['forgiveness', 'community', 'grace', 'mourning', 'radical-love'],
    oneLineSummary: 'After a gunman killed five Amish schoolgirls in Nickel Mines, Pennsylvania, the community visited the killers family with food and comfort within hours — and set up a fund for his widow.',
    spiritualAngle: 'The Amish did not deliberate about forgiveness — they practiced it reflexively, because decades of daily prayer had made it their first instinct, not their last resort.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'corrie-ten-boom-ravensbruck-guard',
    title: 'The Holocaust Survivor Who Shook Her Guards Hand',
    era: '1947',
    category: 'historical-figure',
    themes: ['forgiveness', 'grace', 'struggle', 'obedience', 'healing'],
    oneLineSummary: 'Corrie ten Boom, speaking about forgiveness after the war, recognized a former Ravensbruck guard reaching out to shake her hand — and felt her arm frozen at her side until she prayed for strength.',
    spiritualAngle: 'She discovered that forgiveness is not a feeling but a mechanical act of obedience — and that the feeling follows the choice, not the other way around.',
    source: 'historical',
    spinnable: true,
  },

  // ==========================================
  // VISIONARIES & DISRUPTORS
  // ==========================================
  {
    id: 'harriet-tubman-underground-railroad',
    title: 'The Conductor Who Never Lost a Passenger',
    era: '1849-1860',
    category: 'historical-figure',
    themes: ['courage', 'freedom', 'faith', 'leadership', 'risk'],
    oneLineSummary: 'Harriet Tubman escaped slavery, then returned south 13 times to lead approximately 70 enslaved people to freedom — carrying a pistol and saying she never ran her train off the track.',
    spiritualAngle: 'Tubman heard God giving her directions in the woods — her faith was not theoretical but navigational, a trust that divine guidance would keep her alive one more night.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'ada-lovelace-first-programmer',
    title: 'The Countess Who Imagined Computing a Century Early',
    era: '1843',
    category: 'historical-figure',
    themes: ['vision', 'creativity', 'imagination', 'ahead-of-time', 'innovation'],
    oneLineSummary: 'Ada Lovelace wrote what is considered the first computer algorithm in 1843 — a century before electronic computers existed — envisioning that machines could manipulate symbols, not just numbers.',
    spiritualAngle: 'Some people see what does not yet exist and describe it anyway — the faith substance of things hoped for, evidence of things not seen applies to visionaries as much as to believers.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'emmy-noether-abstract-algebra',
    title: 'The Mathematician Nobody Would Hire',
    era: '1918',
    category: 'historical-figure',
    themes: ['perseverance', 'gender', 'excellence', 'hidden-contribution', 'brilliance'],
    oneLineSummary: 'Emmy Noether proved a theorem that Einstein called the most important in modern physics, but could not get a paid professorship because she was a woman — and lectured under a male colleagues name.',
    spiritualAngle: 'Noether persisted because the work mattered more than the recognition — a quiet faithfulness that resonates with every unacknowledged servant in Scripture.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'nikola-tesla-alternating-current',
    title: 'The Genius Who Lit the World and Died Alone',
    era: '1856-1943',
    category: 'historical-figure',
    themes: ['genius', 'sacrifice', 'loneliness', 'vision', 'forgotten'],
    oneLineSummary: 'Nikola Tesla invented alternating current that powers the modern world, but died alone in a hotel room with almost nothing — having given away his patents and been overshadowed by Edison.',
    spiritualAngle: 'Tesla illuminated the world and was forgotten by it — a parable about the difference between impact and reward, and the faithfulness required when they never align.',
    source: 'historical',
    spinnable: true,
  },

  // ==========================================
  // UNEXPECTED CONNECTIONS TO FAITH
  // ==========================================
  {
    id: 'alcoholics-anonymous-bill-w',
    title: 'The Drunk Who Built a Fellowship on Surrender',
    era: '1935',
    category: 'historical-figure',
    themes: ['addiction', 'surrender', 'community', 'weakness', 'honesty'],
    oneLineSummary: 'Bill Wilson, a hopeless alcoholic, co-founded Alcoholics Anonymous on the principle that admitting powerlessness and surrendering to a higher power is the first step to freedom.',
    spiritualAngle: 'The twelve steps are the Beatitudes repackaged for addicts — blessed are the poor in spirit, for theirs is the kingdom of recovery.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'viktor-frankl-meaning-in-camps',
    title: 'The Psychiatrist Who Found Purpose in Auschwitz',
    era: '1942-1945',
    category: 'historical-figure',
    themes: ['meaning', 'suffering', 'purpose', 'endurance', 'choice'],
    oneLineSummary: 'Viktor Frankl survived Auschwitz and concluded that the last of human freedoms is the ability to choose ones attitude — those who found meaning survived, those who lost it perished.',
    spiritualAngle: 'He who has a why can endure any how — Frankl discovered in the camps what faith has always taught: meaning is not found in circumstances but in response to them.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'hannah-arendt-banality-of-evil',
    title: 'The Thinker Who Saw Evil as Ordinary',
    era: '1963',
    category: 'historical-figure',
    themes: ['evil', 'conformity', 'thinking', 'responsibility', 'conscience'],
    oneLineSummary: 'Hannah Arendt covered the Eichmann trial and coined the banality of evil — the disturbing insight that atrocities are committed not by monsters but by ordinary people who stop thinking.',
    spiritualAngle: 'The greatest danger is not dramatic wickedness but the quiet surrender of conscience — the failure to think is itself a moral failure.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'mr-rogers-ordained-minister',
    title: 'The Ordained Minister Who Chose a TV Studio Over a Pulpit',
    era: '1968-2001',
    category: 'historical-figure',
    themes: ['kindness', 'presence', 'children', 'ministry', 'gentleness'],
    oneLineSummary: 'Fred Rogers was an ordained Presbyterian minister who felt called to television, spending 33 years telling children you are special just the way you are — radical theology disguised as a cardigan.',
    spiritualAngle: 'Rogers preached the gospel without ever mentioning it — a quiet ministry of presence and affirmation that modeled what unconditional love actually looks like.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'jean-vanier-larche-communities',
    title: 'The Man Who Moved In with the Disabled',
    era: '1964',
    category: 'historical-figure',
    themes: ['dignity', 'community', 'vulnerability', 'weakness', 'belonging'],
    oneLineSummary: 'Jean Vanier left a prestigious academic career to live in community with intellectually disabled adults, founding LArche — insisting they were not projects but teachers of what it means to be human.',
    spiritualAngle: 'Vanier discovered that the people society calls weak are the ones who teach us what love actually requires — not competence but presence.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'cicely-saunders-hospice-movement',
    title: 'The Woman Who Made Dying a Human Experience',
    era: '1967',
    category: 'historical-figure',
    themes: ['compassion', 'death', 'dignity', 'presence', 'care'],
    oneLineSummary: 'Cicely Saunders founded the modern hospice movement because she believed dying people deserved not just pain management but to be seen, heard, and accompanied to the end.',
    spiritualAngle: 'She coined total pain — recognizing that suffering has physical, emotional, social, and spiritual dimensions — and that care for the dying mirrors the God who does not abandon us in the valley.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'oskar-schindler-list',
    title: 'The War Profiteer Who Became a Rescuer',
    era: '1939-1945',
    category: 'historical-figure',
    themes: ['transformation', 'rescue', 'moral-awakening', 'sacrifice', 'unlikely-hero'],
    oneLineSummary: 'Oskar Schindler started as a Nazi party member and war profiteer, then spent his entire fortune saving 1,200 Jewish workers — weeping at the end that he could have saved more.',
    spiritualAngle: 'God uses imperfect vessels — Schindlers transformation from opportunist to rescuer is a redemption story in real time.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'etty-hillesum-diary',
    title: 'The Young Woman Who Found God Heading to Auschwitz',
    era: '1941-1943',
    category: 'historical-figure',
    themes: ['faith', 'beauty', 'suffering', 'gratitude', 'inner-life'],
    oneLineSummary: 'Etty Hillesum, a young Dutch Jewish woman, kept a diary during the Holocaust that radiates astonishing gratitude and spiritual depth — writing that life is beautiful and meaningful even as she was deported to Auschwitz.',
    spiritualAngle: 'Hillesum found God not despite her circumstances but within them — proof that the inner life can flourish even when the outer world is collapsing.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'father-damien-molokai',
    title: 'The Priest Who Lived Among Lepers Until He Became One',
    era: '1873-1889',
    category: 'historical-figure',
    themes: ['sacrifice', 'incarnation', 'service', 'solidarity', 'identification'],
    oneLineSummary: 'Father Damien volunteered to serve the isolated leprosy colony on Molokai, and after 11 years began his sermon with "We lepers" — having contracted the disease himself.',
    spiritualAngle: 'The shift from "you" to "we" is the heart of incarnation — God did not advise humanity from a distance but moved into the neighborhood.',
    source: 'historical',
    spinnable: true,
  },
  {
    id: 'perpetua-and-felicitas-martyrs',
    title: 'The Noblewoman and the Slave Who Died Together',
    era: '203 AD',
    category: 'historical-figure',
    themes: ['courage', 'friendship', 'equality', 'martyrdom', 'faith'],
    oneLineSummary: 'Perpetua, a Roman noblewoman, and Felicitas, her slave, were martyred together in the arena at Carthage — their friendship across class lines scandalized Rome as much as their faith.',
    spiritualAngle: 'In Christ there is neither slave nor free — Perpetua and Felicitas walked into the arena as equals, proving that the gospel erases every social barrier.',
    source: 'historical',
    spinnable: true,
  },
];
