// ==========================================
// STORY REPOSITORY: LITERATURE & FILM
// Stories people already know, reframed through a spiritual lens
// Used by AI devotional generation as illustration source material
// ==========================================

import type { StoryEntry } from './stories-psychology-science';

export const LITERATURE_FILM_STORIES: StoryEntry[] = [
  // ==========================================
  // CLASSIC LITERATURE
  // ==========================================
  {
    id: 'les-mis-candlesticks',
    title: 'The Bishop Who Gave Away the Candlesticks',
    era: '1862',
    category: 'literature-film',
    themes: ['grace', 'mercy', 'transformation', 'second-chances', 'generosity'],
    oneLineSummary: 'When Jean Valjean is caught stealing the bishop\'s silver, the bishop tells the police he gave it as a gift — then hands Valjean the candlesticks too, whispering "I have bought your soul for God."',
    spiritualAngle: 'Grace doesn\'t just pardon what you stole. It adds to the gift. The bishop didn\'t minimize the theft — he overwhelmed it with generosity so excessive it broke Valjean\'s categories.',
    source: 'literature',
    specificReference: 'Victor Hugo, "Les Misérables" (1862), Volume 1, Book 2, Chapters 11-12',
    spinnable: true,
  },
  {
    id: 'les-mis-javert-suicide',
    title: 'The Man Who Couldn\'t Survive Grace',
    era: '1862',
    category: 'literature-film',
    themes: ['law-vs-grace', 'legalism', 'mercy', 'identity-crisis', 'rigid-faith'],
    oneLineSummary: 'Inspector Javert spends decades pursuing Valjean, then when Valjean spares his life, Javert\'s worldview — built entirely on justice without mercy — cannot hold. He walks into the Seine.',
    spiritualAngle: 'Javert is the warning for every legalist: a faith built only on rules, without room for mercy, will collapse the first time grace shows up uninvited.',
    source: 'literature',
    specificReference: 'Victor Hugo, "Les Misérables" (1862), Volume 5, Book 4: "Javert Off the Track"',
    spinnable: true,
  },
  {
    id: 'les-mis-fantine-descent',
    title: 'The Woman Who Sold Everything for Her Child',
    era: '1862',
    category: 'literature-film',
    themes: ['sacrifice', 'injustice', 'suffering', 'parenthood', 'exploitation', 'love'],
    oneLineSummary: 'Fantine sells her hair, her teeth, and finally her body to pay for her daughter Cosette\'s care — not because she chose this path but because every system failed her.',
    spiritualAngle: 'Before you judge someone\'s choices, trace the chain of failures that led there. Fantine\'s story is a rebuke to anyone who confuses systemic injustice with personal moral failure.',
    source: 'literature',
    specificReference: 'Victor Hugo, "Les Misérables" (1862), Volume 1, Books 5-8',
    spinnable: true,
  },
  {
    id: 'gandalf-mercy-pity',
    title: 'Many That Live Deserve Death — Can You Give It?',
    era: '1954',
    category: 'literature-film',
    themes: ['mercy', 'judgment', 'grace', 'providence', 'enemy-love', 'patience'],
    oneLineSummary: 'When Frodo says Gollum deserves death, Gandalf replies: "Many that live deserve death. And some that die deserve life. Can you give it to them? Do not be too eager to deal out death in judgment."',
    spiritualAngle: 'The whole plot hinged on this mercy. Gollum — the creature everyone wanted dead — was the one who destroyed the Ring. When you spare someone you\'d rather condemn, you may be preserving the instrument of your own salvation.',
    source: 'literature',
    specificReference: 'J.R.R. Tolkien, "The Fellowship of the Ring" (1954), Book 1, Chapter 2: "The Shadow of the Past"',
    spinnable: true,
  },
  {
    id: 'gandalf-fall-resurrection',
    title: 'The Wizard Who Died and Came Back Changed',
    era: '1954',
    category: 'literature-film',
    themes: ['death', 'resurrection', 'transformation', 'sacrifice', 'new-identity'],
    oneLineSummary: 'Gandalf the Grey falls fighting the Balrog in Moria, dies, and returns as Gandalf the White — the same person but transformed, carrying an authority and radiance he didn\'t have before.',
    spiritualAngle: 'Tolkien, a devout Catholic, embedded resurrection into the structure of Middle-earth: you don\'t come back the same. You come back more fully yourself than you were before the fall.',
    source: 'literature',
    specificReference: 'J.R.R. Tolkien, "The Two Towers" (1954), Book 3, Chapter 5: "The White Rider"',
    spinnable: true,
  },
  {
    id: 'frodo-burden-ring',
    title: 'The Weight That Only Grows Heavier',
    era: '1955',
    category: 'literature-film',
    themes: ['temptation', 'burden', 'perseverance', 'weakness', 'sin', 'endurance'],
    oneLineSummary: 'The Ring doesn\'t get lighter as Frodo gets closer to Mordor — it gets heavier. And in the end, he fails. He claims the Ring. It takes an act of grace (Gollum\'s fall) to finish the mission.',
    spiritualAngle: 'The most honest thing Tolkien wrote: the hero fails at the final moment. Salvation is accomplished not by the strength of the ring-bearer but by a grace so unexpected it looks like an accident.',
    source: 'literature',
    specificReference: 'J.R.R. Tolkien, "The Return of the King" (1955), Book 6, Chapter 3: "Mount Doom"',
    spinnable: true,
  },
  {
    id: 'samwise-carry-you',
    title: '"I Can\'t Carry It for You, But I Can Carry You"',
    era: '1955',
    category: 'literature-film',
    themes: ['friendship', 'bearing-burdens', 'loyalty', 'community', 'perseverance', 'love'],
    oneLineSummary: 'When Frodo collapses on the slopes of Mount Doom, unable to go further, Sam lifts him onto his back — he can\'t take away the burden, but he can carry the one who bears it.',
    spiritualAngle: 'We often can\'t remove someone\'s pain. But "bear one another\'s burdens" doesn\'t mean fixing them. Sometimes it means literally carrying the person when they can\'t walk anymore.',
    source: 'literature',
    specificReference: 'J.R.R. Tolkien, "The Return of the King" (1955), Book 6, Chapter 3: "Mount Doom"',
    spinnable: true,
  },
  {
    id: 'narnia-aslan-sacrifice',
    title: 'The Lion Lets Himself Be Killed',
    era: '1950',
    category: 'literature-film',
    themes: ['sacrifice', 'atonement', 'humiliation', 'resurrection', 'deeper-magic'],
    oneLineSummary: 'Aslan surrenders to the White Witch, is shaved, mocked, and killed on the Stone Table — but rises because there\'s a "deeper magic" the Witch didn\'t know: when a willing, innocent victim is killed in a traitor\'s stead, death itself works backward.',
    spiritualAngle: 'Lewis encoded the gospel so deeply into Narnia that children feel it before they understand it. The "deeper magic" isn\'t a plot device — it\'s the claim that self-sacrificial love is the fundamental law of reality.',
    source: 'literature',
    specificReference: 'C.S. Lewis, "The Lion, the Witch, and the Wardrobe" (1950), Chapters 14-15',
    spinnable: true,
  },
  {
    id: 'narnia-eustace-dragon',
    title: 'The Boy Who Couldn\'t Peel Off His Own Dragon Skin',
    era: '1952',
    category: 'literature-film',
    themes: ['transformation', 'repentance', 'grace', 'identity', 'self-effort', 'new-creation'],
    oneLineSummary: 'Eustace becomes a dragon through his own greed, then tries to claw off the dragon skin himself — layer after layer — but each time there\'s more underneath. Only when Aslan tears it off with his own claws, cutting deeper than Eustace could bear, is the boy free.',
    spiritualAngle: 'Self-improvement can shed layers. But some transformations require surgery you cannot perform on yourself — a grace that cuts deeper than self-discipline ever could.',
    source: 'literature',
    specificReference: 'C.S. Lewis, "The Voyage of the Dawn Treader" (1952), Chapter 7',
    spinnable: true,
  },
  {
    id: 'narnia-emeth-last-battle',
    title: 'The Enemy Soldier Who Was Serving God All Along',
    era: '1956',
    category: 'literature-film',
    themes: ['inclusion', 'sincerity', 'surprise', 'judgment', 'other-faiths', 'heart'],
    oneLineSummary: 'Emeth, a devout servant of the false god Tash, meets Aslan and is told: "All the service thou hast done to Tash, I account as service done to me... No service which is vile can be done to me, and none which is not vile can be done to him."',
    spiritualAngle: 'Lewis — no universalist — suggests that God can read the heart behind the label. The question isn\'t just "who did you say you were following?" but "what did your following actually look like?"',
    source: 'literature',
    specificReference: 'C.S. Lewis, "The Last Battle" (1956), Chapter 15: "Further Up and Further In"',
    spinnable: true,
  },
  {
    id: 'crime-punishment-raskolnikov',
    title: 'The Man Who Proved He Was Above Morality — and Shattered',
    era: '1866',
    category: 'literature-film',
    themes: ['guilt', 'conscience', 'pride', 'confession', 'redemption', 'moral-law'],
    oneLineSummary: 'Raskolnikov murders a pawnbroker to prove that extraordinary people transcend ordinary morality — then spends the rest of the novel being destroyed from within by guilt he cannot escape or rationalize away.',
    spiritualAngle: 'The conscience is not a social construct you can think your way past. Raskolnikov tried. His body revolted. The moral law written on the heart cannot be overridden by the mind that sits on top of it.',
    source: 'literature',
    specificReference: 'Fyodor Dostoevsky, "Crime and Punishment" (1866)',
    spinnable: true,
  },
  {
    id: 'brothers-karamazov-inquisitor',
    title: 'What If Jesus Came Back and the Church Arrested Him?',
    era: '1880',
    category: 'literature-film',
    themes: ['institutional-religion', 'freedom', 'control', 'religion-vs-faith', 'Jesus-vs-church'],
    oneLineSummary: 'In "The Grand Inquisitor," Jesus returns to Seville during the Inquisition. The Cardinal arrests him and explains that the church has "corrected" his work — people don\'t want freedom; they want bread, miracles, and authority.',
    spiritualAngle: 'Dostoevsky\'s most devastating question: Is the organized church the continuation of Christ\'s work or its replacement? Has institutional religion traded the terrifying freedom of faith for the comfortable chains of control?',
    source: 'literature',
    specificReference: 'Fyodor Dostoevsky, "The Brothers Karamazov" (1880), Book 5, Chapter 5: "The Grand Inquisitor"',
    spinnable: true,
  },
  {
    id: 'brothers-karamazov-alyosha-earth',
    title: 'He Fell to the Earth Weeping and Rose Up Whole',
    era: '1880',
    category: 'literature-film',
    themes: ['encounter', 'conversion', 'creation', 'embodiment', 'earth', 'mystical-experience'],
    oneLineSummary: 'After Father Zossima\'s death, Alyosha falls to the earth in anguish, kisses it, and rises with an unshakeable joy — "something firm and unshakeable as the vault of heaven descended into his soul."',
    spiritualAngle: 'The most important spiritual moments don\'t happen in cathedrals. They happen when your face hits the ground and something in the dirt speaks back.',
    source: 'literature',
    specificReference: 'Fyodor Dostoevsky, "The Brothers Karamazov" (1880), Book 7, Chapter 4: "Cana of Galilee"',
    spinnable: true,
  },
  {
    id: 'east-of-eden-timshel',
    title: '"Thou Mayest" — The Most Important Word in the World',
    era: '1952',
    category: 'literature-film',
    themes: ['free-will', 'choice', 'sin', 'potential', 'agency', 'hope'],
    oneLineSummary: 'In "East of Eden," Lee spends years researching the Hebrew word "timshel" from Genesis 4:7 and concludes that "thou mayest" — not "thou shalt" or "thou must" — is the most important word ever spoken, because it gives human beings the freedom to choose.',
    spiritualAngle: 'God doesn\'t say "you will overcome sin" (which removes your agency) or "you must overcome sin" (which becomes a burden). He says "you may" — which is the most terrifying and liberating gift possible.',
    source: 'literature',
    specificReference: 'John Steinbeck, "East of Eden" (1952), Chapter 24',
    spinnable: true,
  },
  {
    id: 'tale-two-cities-carton',
    title: '"It Is a Far, Far Better Thing..."',
    era: '1859',
    category: 'literature-film',
    themes: ['sacrifice', 'redemption', 'substitution', 'wasted-life', 'purpose', 'love'],
    oneLineSummary: 'Sydney Carton — a wasted, alcoholic lawyer — takes the place of the man his beloved loves at the guillotine, finding in his final act the meaning his whole dissolute life had lacked.',
    spiritualAngle: 'It took his whole failed, wasted life to reach the one moment that redeemed it all. Sometimes the purpose of everything that went wrong is to get you to the place where you can finally do the one right thing.',
    source: 'literature',
    specificReference: 'Charles Dickens, "A Tale of Two Cities" (1859), Book 3, Chapter 15',
    spinnable: true,
  },
  {
    id: 'pilgrims-progress-slough',
    title: 'The Swamp You Must Cross to Begin',
    era: '1678',
    category: 'literature-film',
    themes: ['doubt', 'despair', 'beginning', 'perseverance', 'discouragement', 'journey'],
    oneLineSummary: 'Almost immediately after beginning his journey, Christian falls into the Slough of Despond — a bog that represents the doubt and discouragement that hits everyone right after they decide to change.',
    spiritualAngle: 'The Slough of Despond comes early, not late. The hardest part of any spiritual journey is not the distant mountain — it\'s the swamp right after you say yes.',
    source: 'literature',
    specificReference: 'John Bunyan, "The Pilgrim\'s Progress" (1678), Part 1',
    spinnable: true,
  },
  {
    id: 'pilgrims-progress-burden',
    title: 'The Burden That Falls Off at the Cross',
    era: '1678',
    category: 'literature-film',
    themes: ['guilt', 'freedom', 'cross', 'salvation', 'release', 'unburdening'],
    oneLineSummary: 'Christian carries an enormous burden on his back through every obstacle until he reaches the cross — where the straps break and the burden rolls away into an open sepulchre, and he sees it no more.',
    spiritualAngle: 'Bunyan understood what therapists now confirm: you can\'t argue someone out of their burden. They have to arrive at the place where it falls off. The journey to freedom has no shortcuts.',
    source: 'literature',
    specificReference: 'John Bunyan, "The Pilgrim\'s Progress" (1678), Part 1, arrival at the Cross',
    spinnable: true,
  },
  {
    id: 'mockingbird-atticus-courage',
    title: '"Real Courage Is When You Know You\'re Licked Before You Begin"',
    era: '1960',
    category: 'literature-film',
    themes: ['courage', 'justice', 'moral-conviction', 'losing', 'integrity', 'faithfulness'],
    oneLineSummary: 'Atticus Finch defends a Black man he knows he will not acquit in 1930s Alabama, teaching his children that real courage isn\'t winning — it\'s standing for what\'s right when you know you\'ll lose.',
    spiritualAngle: 'Faithfulness is not measured by outcomes. The prophets who were ignored, the martyrs who died unnamed, the parents who poured into children who walked away — courage is about fidelity, not victory.',
    source: 'literature',
    specificReference: 'Harper Lee, "To Kill a Mockingbird" (1960), Chapter 11',
    spinnable: true,
  },
  {
    id: 'mockingbird-boo-radley',
    title: 'The Monster Next Door Was a Guardian All Along',
    era: '1960',
    category: 'literature-film',
    themes: ['judgment', 'appearances', 'grace', 'protection', 'mystery', 'surprise'],
    oneLineSummary: 'The children spend the whole novel terrified of Boo Radley, the reclusive neighbor. In the end, he saves their lives — and Scout realizes he\'d been quietly leaving gifts for them all along.',
    spiritualAngle: 'The grace you\'ve been afraid of is the grace that\'s been protecting you. Sometimes God\'s provision comes from the last source you\'d expect — or the one you\'ve been avoiding.',
    source: 'literature',
    specificReference: 'Harper Lee, "To Kill a Mockingbird" (1960), Chapters 28-31',
    spinnable: true,
  },
  {
    id: 'little-prince-essential-invisible',
    title: '"What Is Essential Is Invisible to the Eye"',
    era: '1943',
    category: 'literature-film',
    themes: ['unseen', 'faith', 'love', 'presence', 'mystery', 'perception'],
    oneLineSummary: 'The fox teaches the Little Prince that "it is only with the heart that one can see rightly; what is essential is invisible to the eye."',
    spiritualAngle: 'Faith is the substance of things hoped for, the evidence of things not seen. The most important realities — love, meaning, God\'s presence — are exactly the ones your eyes can\'t verify.',
    source: 'literature',
    specificReference: 'Antoine de Saint-Exupéry, "The Little Prince" (1943), Chapter 21',
    spinnable: true,
  },
  {
    id: 'little-prince-taming',
    title: '"You Become Responsible Forever for What You Have Tamed"',
    era: '1943',
    category: 'literature-film',
    themes: ['responsibility', 'love', 'commitment', 'relationship', 'covenant'],
    oneLineSummary: 'The fox explains that "taming" — investing time, creating ties — makes one rose out of millions unique: "It is the time you have wasted for your rose that makes your rose so important."',
    spiritualAngle: 'Love is not finding the perfect thing. It\'s investing so deeply in one thing that it becomes irreplaceable. This is covenant — choosing one and making it holy through fidelity.',
    source: 'literature',
    specificReference: 'Antoine de Saint-Exupéry, "The Little Prince" (1943), Chapter 21',
    spinnable: true,
  },
  {
    id: 'oconnor-good-man-misfit',
    title: 'Grace Arrives Through a Murderer\'s Bullet',
    era: '1953',
    category: 'literature-film',
    themes: ['grace', 'violence', 'disruption', 'pretense', 'honesty', 'shock'],
    oneLineSummary: 'In "A Good Man Is Hard to Find," the self-righteous grandmother only touches grace in her final moment — reaching out to The Misfit and calling him "one of my own children" — right before he shoots her.',
    spiritualAngle: 'O\'Connor wrote stories where grace arrives violently because she believed comfortable people can only be reached by shock. Sometimes the thing that breaks your pretenses is the thing that saves you.',
    source: 'literature',
    specificReference: 'Flannery O\'Connor, "A Good Man Is Hard to Find" (1953)',
    spinnable: true,
  },
  {
    id: 'oconnor-revelation-ruby',
    title: 'The "Good Christian Woman" Who Saw Herself Last in Line',
    era: '1964',
    category: 'literature-film',
    themes: ['pride', 'self-righteousness', 'humility', 'last-shall-be-first', 'judgment'],
    oneLineSummary: 'Ruby Turpin, a self-satisfied church lady, has a vision of a procession entering heaven — and sees the "white trash" and outcasts she\'d judged all her life entering first, while respectable people like herself bring up the rear, their virtues "burned away."',
    spiritualAngle: '"The last shall be first." O\'Connor makes you feel what this means for the comfortably religious person who assumed they\'d be at the front of the line.',
    source: 'literature',
    specificReference: 'Flannery O\'Connor, "Revelation" (1964), from "Everything That Rises Must Converge"',
    spinnable: true,
  },
  {
    id: 'oconnor-parker-back-tattoo',
    title: 'The Man Who Tattooed God on His Back to Please His Wife',
    era: '1965',
    category: 'literature-film',
    themes: ['seeking', 'restlessness', 'God-encounter', 'rejection', 'desperate-faith'],
    oneLineSummary: 'O.E. Parker, a tattoo-covered man married to a religious woman who despises his tattoos, gets a Byzantine Christ tattooed across his entire back — only for his wife to beat him with a broom, saying "Idolatry!"',
    spiritualAngle: 'The person desperately seeking God in all the wrong ways may be closer than the religious person who has God all figured out. Parker\'s desperate, confused longing is more honest than his wife\'s tidy theology.',
    source: 'literature',
    specificReference: 'Flannery O\'Connor, "Parker\'s Back" (1965, posthumous)',
    spinnable: true,
  },
  {
    id: 'great-gatsby-green-light',
    title: 'The Light Across the Water He Could Never Reach',
    era: '1925',
    category: 'literature-film',
    themes: ['desire', 'idolatry', 'longing', 'dissatisfaction', 'restless-heart', 'enough'],
    oneLineSummary: 'Gatsby spends his whole life reaching for the green light at the end of Daisy\'s dock — a symbol of an idealized past that never really existed. He dies still reaching.',
    spiritualAngle: 'Augustine: "Our hearts are restless until they rest in you." Gatsby\'s green light is every idol we pursue — beautiful from a distance, diminishing upon arrival, and always placed just across the water.',
    source: 'literature',
    specificReference: 'F. Scott Fitzgerald, "The Great Gatsby" (1925), Chapter 1 and final page',
    spinnable: true,
  },
  {
    id: 'hamlet-readiness-is-all',
    title: '"The Readiness Is All"',
    era: '1600',
    category: 'literature-film',
    themes: ['surrender', 'death', 'acceptance', 'providence', 'trust', 'letting-go'],
    oneLineSummary: 'After spending the entire play paralyzed by indecision, Hamlet finally reaches acceptance before the final duel: "There\'s a special providence in the fall of a sparrow... the readiness is all."',
    spiritualAngle: 'Hamlet quotes Jesus (Matthew 10:29 — not a sparrow falls without your Father) at his moment of surrender. The peace came not from solving the problem but from accepting that something larger was at work.',
    source: 'literature',
    specificReference: 'William Shakespeare, "Hamlet" (c. 1600), Act 5, Scene 2',
    spinnable: true,
  },
  {
    id: 'king-lear-nothing',
    title: 'The King Who Lost Everything and Found Himself',
    era: '1606',
    category: 'literature-film',
    themes: ['loss', 'pride', 'stripping', 'suffering', 'identity', 'humility'],
    oneLineSummary: 'Lear gives away his kingdom demanding love in return, is stripped of everything by the daughters who flattered him, goes mad on the heath — and only in his madness finally sees reality clearly.',
    spiritualAngle: 'Sometimes God doesn\'t take things away as punishment. He strips away everything that isn\'t you until the real you — the one buried under crowns and flattery — finally emerges.',
    source: 'literature',
    specificReference: 'William Shakespeare, "King Lear" (1606), Act 3, Scene 4 (the heath)',
    spinnable: true,
  },

  // ==========================================
  // MODERN LITERATURE
  // ==========================================
  {
    id: 'night-elie-wiesel',
    title: '"Where Is God? He Is Hanging Here on This Gallows"',
    era: '1960',
    category: 'literature-film',
    themes: ['suffering', 'theodicy', 'silence-of-God', 'doubt', 'lament', 'cross'],
    oneLineSummary: 'In the concentration camp, a child is hanged and a voice asks "Where is God now?" Wiesel writes: "Here He is — He is hanging here on this gallows."',
    spiritualAngle: 'This is either the death of faith or the deepest possible theology of the cross. God is not absent from suffering — he is in it, hanging alongside the innocent.',
    source: 'literature',
    specificReference: 'Elie Wiesel, "Night" (1960), the hanging of the boy',
    spinnable: true,
  },
  {
    id: 'the-road-carrying-the-fire',
    title: '"We\'re Carrying the Fire"',
    era: '2006',
    category: 'literature-film',
    themes: ['hope', 'perseverance', 'light', 'darkness', 'fatherhood', 'faithfulness'],
    oneLineSummary: 'In McCarthy\'s post-apocalyptic wasteland, the father tells his son they are "carrying the fire" — never defining what it means, only insisting they must keep it alive despite everything.',
    spiritualAngle: 'There are seasons when all theology reduces to one question: will you keep carrying the fire? Not explaining it, not understanding it — just refusing to let it go out.',
    source: 'literature',
    specificReference: 'Cormac McCarthy, "The Road" (2006)',
    spinnable: true,
  },
  {
    id: 'man-search-meaning-defiance',
    title: 'The Last Human Freedom Is Choosing Your Attitude',
    era: '1946',
    category: 'literature-film',
    themes: ['freedom', 'suffering', 'choice', 'agency', 'dignity', 'meaning'],
    oneLineSummary: 'Frankl wrote that in the camps, "everything can be taken from a man but one thing: the last of the human freedoms — to choose one\'s attitude in any given set of circumstances."',
    spiritualAngle: 'This is what it means to be made in God\'s image: even when every external freedom is stripped, the internal capacity to choose meaning remains. That capacity cannot be taken — only surrendered.',
    source: 'literature',
    specificReference: 'Viktor Frankl, "Man\'s Search for Meaning" (1946), Part 1',
    spinnable: true,
  },
  {
    id: 'wild-sheryl-strayed',
    title: 'She Walked 1,100 Miles to Grieve Her Mother',
    era: '2012',
    category: 'literature-film',
    themes: ['grief', 'journey', 'wilderness', 'healing', 'body', 'embodied-processing'],
    oneLineSummary: 'After her mother\'s death, Sheryl Strayed\'s life unraveled — heroin, infidelity, divorce. She hiked the Pacific Crest Trail alone, and the physical suffering became the container her grief needed.',
    spiritualAngle: 'Sometimes the body has to process what the mind can\'t hold. The Israelites didn\'t journal through the wilderness — they walked it. Forty years of dusty, embodied transformation.',
    source: 'literature',
    specificReference: 'Cheryl Strayed, "Wild" (2012)',
    spinnable: true,
  },
  {
    id: 'educated-tara-westover',
    title: 'The Girl Who Had to Leave Home to Find the Truth',
    era: '2018',
    category: 'literature-film',
    themes: ['truth', 'family', 'cost-of-growth', 'leaving', 'identity', 'painful-awakening'],
    oneLineSummary: 'Tara Westover grew up in an extremist survivalist family, never saw a doctor, never attended school — and education didn\'t free her without cost: it meant losing her family.',
    spiritualAngle: 'Sometimes following truth means losing the people who shaped you. Jesus said it: "I have come to set a man against his father." Growth that doesn\'t cost anything probably isn\'t growth.',
    source: 'literature',
    specificReference: 'Tara Westover, "Educated" (2018)',
    spinnable: true,
  },
  {
    id: 'giving-tree-shel-silverstein',
    title: 'The Tree That Gave Until It Was a Stump',
    era: '1964',
    category: 'literature-film',
    themes: ['sacrifice', 'giving', 'boundaries', 'exploitation', 'love', 'parenthood'],
    oneLineSummary: 'The tree gives the boy her apples, branches, and trunk — piece by piece over a lifetime — until she\'s just a stump. "And the tree was happy."',
    spiritualAngle: 'Is this self-sacrificial love or codependent enabling? The answer says more about your theology than about the book. The best spiritual stories make you argue with yourself.',
    source: 'literature',
    specificReference: 'Shel Silverstein, "The Giving Tree" (1964)',
    spinnable: true,
  },
  {
    id: 'gilead-marilynne-robinson',
    title: 'An Old Preacher\'s Letter to a Son He Won\'t See Grow Up',
    era: '2004',
    category: 'literature-film',
    themes: ['legacy', 'ordinary-holiness', 'fatherhood', 'mortality', 'beauty', 'attention'],
    oneLineSummary: 'Dying pastor John Ames writes a letter to his young son, and in the process finds astonishing beauty in completely ordinary things — light on a child\'s face, the smell of biscuits, the sound of laughter.',
    spiritualAngle: 'Robinson\'s genius: when you know you\'re dying, everything becomes communion. Every meal is the last supper. Every sunrise is genesis. Attention is the purest form of prayer.',
    source: 'literature',
    specificReference: 'Marilynne Robinson, "Gilead" (2004), Pulitzer Prize',
    spinnable: true,
  },
  {
    id: 'anne-frank-still-believe',
    title: '"In Spite of Everything, I Still Believe People Are Good"',
    era: '1947',
    category: 'literature-film',
    themes: ['hope', 'goodness', 'suffering', 'innocence', 'resilience', 'faith-in-humanity'],
    oneLineSummary: 'Anne Frank, hiding from Nazis in an attic, wrote in her diary: "In spite of everything I still believe that people are really good at heart."',
    spiritualAngle: 'This line is devastating because she died at Bergen-Belsen. Was she naive? Or did she see something deeper — an imago Dei that not even Auschwitz could fully extinguish?',
    source: 'literature',
    specificReference: 'Anne Frank, "The Diary of a Young Girl" (1947), entry of July 15, 1944',
    spinnable: true,
  },

  // ==========================================
  // FILM
  // ==========================================
  {
    id: 'shawshank-hope',
    title: '"Hope Is a Good Thing — Maybe the Best of Things"',
    era: '1994',
    category: 'literature-film',
    themes: ['hope', 'perseverance', 'freedom', 'endurance', 'patience', 'liberation'],
    oneLineSummary: 'Andy Dufresne crawls through a river of sewage to reach freedom, and writes to Red: "Hope is a good thing, maybe the best of things, and no good thing ever dies."',
    spiritualAngle: 'The escape required 19 years of tunneling. Hope isn\'t a feeling — it\'s a decision repeated for decades in the dark, behind a poster nobody looks behind.',
    source: 'film',
    specificReference: 'Frank Darabont (dir.), "The Shawshank Redemption" (1994), final letter scene',
    spinnable: true,
  },
  {
    id: 'shawshank-rain',
    title: 'The Man Who Stood in the Rain After 20 Years Inside',
    era: '1994',
    category: 'literature-film',
    themes: ['freedom', 'liberation', 'new-creation', 'joy', 'breakthrough', 'baptism'],
    oneLineSummary: 'After crawling through the sewer pipe and emerging on the other side, Andy Dufresne tears off his prison shirt and stands in the pouring rain with his arms spread wide — free.',
    spiritualAngle: 'The imagery is inescapable: through the filth, through the darkness, through the tunnel no one believed was there — and then the rain. It looks exactly like baptism because it is exactly like baptism.',
    source: 'film',
    specificReference: 'Frank Darabont (dir.), "The Shawshank Redemption" (1994), escape sequence',
    spinnable: true,
  },
  {
    id: 'schindlers-list-one-more',
    title: '"I Could Have Got More — This Pin, Two People..."',
    era: '1993',
    category: 'literature-film',
    themes: ['regret', 'sacrifice', 'impact', 'enough', 'calling', 'one-life'],
    oneLineSummary: 'After saving 1,100 Jews, Schindler breaks down: "I could have got more... this car — why did I keep the car? Ten people right there. This pin — two people."',
    spiritualAngle: 'The grief of the generous is always "I could have given more." Schindler\'s breakdown reveals that the closer you get to love, the more inadequate your love feels.',
    source: 'film',
    specificReference: 'Steven Spielberg (dir.), "Schindler\'s List" (1993), Schindler\'s breakdown scene',
    spinnable: true,
  },
  {
    id: 'schindlers-list-one-life',
    title: '"Whoever Saves One Life Saves the World Entire"',
    era: '1993',
    category: 'literature-film',
    themes: ['value-of-life', 'impact', 'one-person', 'significance', 'God-image'],
    oneLineSummary: 'The workers present Schindler a ring inscribed with a Talmudic verse: "Whoever saves one life saves the world entire."',
    spiritualAngle: 'Every person is an entire world. Saving one doesn\'t feel like enough until you realize that one contains everything — history, descendants, unrepeated image of God.',
    source: 'film',
    specificReference: 'Steven Spielberg (dir.), "Schindler\'s List" (1993), ring presentation; Talmud Sanhedrin 37a',
    spinnable: true,
  },
  {
    id: 'wonderful-life-impact',
    title: 'The Man Who Saw What the World Would Be Without Him',
    era: '1946',
    category: 'literature-film',
    themes: ['purpose', 'impact', 'suicide', 'significance', 'interconnection', 'ripple-effect'],
    oneLineSummary: 'George Bailey, about to jump from a bridge, is shown by an angel what Bedford Falls would look like if he\'d never been born — and realizes his "ordinary" life touched everything.',
    spiritualAngle: 'You cannot see your own impact from inside your life. The people most convinced they don\'t matter are often the ones whose absence would unravel the most threads.',
    source: 'film',
    specificReference: 'Frank Capra (dir.), "It\'s a Wonderful Life" (1946), Clarence\'s tour',
    spinnable: true,
  },
  {
    id: 'good-will-hunting-not-your-fault',
    title: '"It\'s Not Your Fault" — Repeated Until It Broke Through',
    era: '1997',
    category: 'literature-film',
    themes: ['shame', 'healing', 'truth', 'repetition', 'breakthrough', 'wounds'],
    oneLineSummary: 'Sean tells Will "it\'s not your fault" about his childhood abuse — and repeats it ten times as Will goes from deflection to anger to sobbing collapse in Sean\'s arms.',
    spiritualAngle: 'Some truths need to be heard not once but ten times, a hundred times, before they pass from your head to your heart. This is why we need gospel every day, not just the day we first believed.',
    source: 'film',
    specificReference: 'Gus Van Sant (dir.), "Good Will Hunting" (1997), park bench repetition scene',
    spinnable: true,
  },
  {
    id: 'good-will-hunting-sean-wife',
    title: '"You\'re Not Perfect and Neither Was She — That\'s How It Works"',
    era: '1997',
    category: 'literature-film',
    themes: ['vulnerability', 'intimacy', 'imperfection', 'love', 'risk', 'authenticity'],
    oneLineSummary: 'Sean describes how his wife would fart in her sleep or have bizarre quirks — "those are the things I miss the most... the little idiosyncrasies that only I knew about."',
    spiritualAngle: 'Real love doesn\'t seek the perfect version of someone. It seeks the real version — quirks, failures, 3 AM ugliness. This is what it means that "God knows the hairs on your head." He loves the details you hide.',
    source: 'film',
    specificReference: 'Gus Van Sant (dir.), "Good Will Hunting" (1997), park bench scene',
    spinnable: true,
  },
  {
    id: 'babettes-feast',
    title: 'The Woman Who Spent Everything on One Meal',
    era: '1987',
    category: 'literature-film',
    themes: ['generosity', 'extravagance', 'grace', 'art', 'gift', 'abundance'],
    oneLineSummary: 'Babette wins 10,000 francs and spends every cent preparing a single exquisite French meal for a puritanical Danish village that can\'t even appreciate it — and she has no regrets.',
    spiritualAngle: 'The extravagance of grace: Babette pours out everything, knowing the recipients can\'t fully understand what they\'re receiving. Like the woman who broke the alabaster jar — the watching disciples called it waste.',
    source: 'film',
    specificReference: 'Gabriel Axel (dir.), "Babette\'s Feast" (1987), based on Isak Dinesen\'s story',
    spinnable: true,
  },
  {
    id: 'the-mission-mercy-scene',
    title: 'The Slave Trader Climbing a Waterfall in Chains',
    era: '1986',
    category: 'literature-film',
    themes: ['penance', 'forgiveness', 'guilt', 'redemption', 'letting-go', 'mercy'],
    oneLineSummary: 'Rodrigo Mendoza, a repentant slave trader, drags his armor up a waterfall to the very tribe he enslaved — until a Guaraní man cuts the rope, sending the burden crashing into the river, and embraces him.',
    spiritualAngle: 'Sometimes you insist on carrying the weight of your own penance because letting go feels too easy. But grace is always the other person cutting the rope you keep retying.',
    source: 'film',
    specificReference: 'Roland Joffé (dir.), "The Mission" (1986), Mendoza\'s penance climb',
    spinnable: true,
  },
  {
    id: 'into-the-wild-happiness-shared',
    title: '"Happiness Is Only Real When Shared"',
    era: '2007',
    category: 'literature-film',
    themes: ['isolation', 'community', 'connection', 'regret', 'independence', 'loneliness'],
    oneLineSummary: 'Chris McCandless abandoned society for the Alaskan wild and found what he was looking for — only to discover, starving and alone, that "happiness is only real when shared."',
    spiritualAngle: 'The lie of radical self-sufficiency: you can find yourself in solitude, but you can only find meaning in relationship. McCandless learned too late what Genesis 2 says first: it is not good to be alone.',
    source: 'film',
    specificReference: 'Sean Penn (dir.), "Into the Wild" (2007), based on Jon Krakauer\'s book; McCandless\'s final journal entry',
    spinnable: true,
  },
  {
    id: 'soul-pixar-spark',
    title: 'Your "Spark" Isn\'t Your Purpose — It\'s Your Readiness to Live',
    era: '2020',
    category: 'literature-film',
    themes: ['purpose', 'calling', 'ordinary-life', 'present-moment', 'meaning', 'vocation'],
    oneLineSummary: 'Joe Gardner spends the whole movie thinking his "spark" is jazz — only to discover that a spark isn\'t a purpose or passion. It\'s the moment a soul is ready to live.',
    spiritualAngle: 'We torture ourselves looking for "God\'s plan for my life" as if it\'s a career path. But what if God\'s purpose for you today is simpler: to be fully alive to this ordinary, unrepeatable moment?',
    source: 'film',
    specificReference: 'Pete Docter (dir.), "Soul" (2020), Pixar; the spark revelation scene',
    spinnable: true,
  },
  {
    id: 'inside-out-sadness',
    title: 'The Whole Problem Was Trying to Keep Sadness Out',
    era: '2015',
    category: 'literature-film',
    themes: ['grief', 'emotions', 'wholeness', 'sadness', 'vulnerability', 'healing'],
    oneLineSummary: 'Joy spends the entire movie keeping Sadness away from Riley\'s core memories — until she realizes Sadness is what calls others close and creates the deepest connections.',
    spiritualAngle: '"Blessed are those who mourn, for they will be comforted." Jesus didn\'t say blessed are those who overcome mourning. The sadness itself is the door — it\'s what lets comfort in.',
    source: 'film',
    specificReference: 'Pete Docter (dir.), "Inside Out" (2015), Pixar; Bing Bong scene and Joy\'s realization',
    spinnable: true,
  },
  {
    id: 'inside-out-bing-bong',
    title: 'The Imaginary Friend Who Sacrificed Himself to Be Forgotten',
    era: '2015',
    category: 'literature-film',
    themes: ['sacrifice', 'letting-go', 'grief', 'growing-up', 'loss', 'selflessness'],
    oneLineSummary: 'Bing Bong, Riley\'s forgotten imaginary friend, leaps from the rocket to lighten the load so Joy can escape the memory dump — knowing he\'ll fade into nothing. "Take her to the moon for me."',
    spiritualAngle: 'Some loves serve by disappearing. Bing Bong\'s sacrifice is the purest kind — done without recognition, without remembrance, without anyone knowing the cost. The greatest love is often the one no one sees.',
    source: 'film',
    specificReference: 'Pete Docter (dir.), "Inside Out" (2015), Pixar; Bing Bong\'s sacrifice scene',
    spinnable: true,
  },
  {
    id: 'inside-out-2-anxiety',
    title: 'Anxiety Builds a Version of You That Isn\'t You',
    era: '2024',
    category: 'literature-film',
    themes: ['anxiety', 'identity', 'control', 'self-image', 'faith-vs-fear', 'acceptance'],
    oneLineSummary: 'In Inside Out 2, Anxiety takes over Riley\'s sense of self by projecting worst-case scenarios, constructing a new identity built entirely on fear of the future — until the other emotions reclaim: "I\'m not good enough" isn\'t who she is.',
    spiritualAngle: 'Anxiety rewrites your identity around what might go wrong. But your true self wasn\'t built by fear. It was spoken by God, who says you\'re his — past tense, present tense, settled.',
    source: 'film',
    specificReference: 'Kelsey Mann (dir.), "Inside Out 2" (2024), Pixar; Anxiety\'s takeover of the Sense of Self',
    spinnable: true,
  },
  {
    id: 'coco-remember-me',
    title: 'You Die Twice — The Second Time When No One Remembers',
    era: '2017',
    category: 'literature-film',
    themes: ['memory', 'legacy', 'death', 'family', 'being-known', 'eternity'],
    oneLineSummary: 'In the Land of the Dead, spirits continue to exist as long as living people remember them — but when the last person who knew them dies, they face "the final death."',
    spiritualAngle: 'The ache to be remembered is one of humanity\'s deepest drives. God answers it not with monuments but with a promise: "I have called you by name; you are mine." You are remembered by the one who cannot forget.',
    source: 'film',
    specificReference: 'Lee Unkrich (dir.), "Coco" (2017), Pixar; concept of "final death"',
    spinnable: true,
  },
  {
    id: 'wall-e-plant',
    title: 'A Robot Finds Life in a Wasteland',
    era: '2008',
    category: 'literature-film',
    themes: ['hope', 'stewardship', 'creation', 'new-life', 'persistence', 'beauty-in-ruins'],
    oneLineSummary: 'On a destroyed, abandoned Earth, the robot WALL-E finds a single green plant growing in a boot — and that one fragile sprout becomes the catalyst for humanity\'s return home.',
    spiritualAngle: 'God\'s sign to Noah after the flood was an olive branch — one green thing in a destroyed world. Hope doesn\'t require a garden. It requires a single, stubborn shoot refusing to die.',
    source: 'film',
    specificReference: 'Andrew Stanton (dir.), "WALL-E" (2008), Pixar; the plant discovery',
    spinnable: true,
  },

  // ==========================================
  // TV & OTHER MEDIA
  // ==========================================
  {
    id: 'ted-lasso-believe',
    title: 'The Coach Who Won by Believing in People',
    era: '2020-2023',
    category: 'literature-film',
    themes: ['belief', 'encouragement', 'kindness', 'leadership', 'vulnerability', 'change'],
    oneLineSummary: 'Ted Lasso, an American football coach in English soccer, puts up a sign that says "BELIEVE" and wins not by strategy but by relentlessly seeing the best in people who\'ve stopped seeing it in themselves.',
    spiritualAngle: 'The world calls this naive. Scripture calls it prophetic. Speaking what could be into what is — "you can do this, I believe in you" — is the human echo of God calling things that are not as though they were.',
    source: 'tv',
    specificReference: '"Ted Lasso" (2020-2023), Apple TV+; the BELIEVE sign, Ted\'s coaching philosophy',
    spinnable: true,
  },
  {
    id: 'ted-lasso-be-curious',
    title: '"Be Curious, Not Judgmental"',
    era: '2020',
    category: 'literature-film',
    themes: ['curiosity', 'judgment', 'empathy', 'understanding', 'listening', 'humility'],
    oneLineSummary: 'Ted attributes the quote to Walt Whitman during a dart game, explaining that the people who underestimated him never bothered to ask questions — they just judged.',
    spiritualAngle: 'Every time Jesus asked a question instead of making a pronouncement, he was choosing curiosity over judgment. "What do you want me to do for you?" — asked to a man who was obviously blind.',
    source: 'tv',
    specificReference: '"Ted Lasso" (2020), Season 1, Episode 8: "The Diamond Dogs"',
    spinnable: true,
  },
  {
    id: 'ted-lasso-goldfish',
    title: '"Be a Goldfish — Happiest Animal in the World"',
    era: '2020',
    category: 'literature-film',
    themes: ['forgetting', 'grace', 'shame', 'failure', 'moving-on', 'freedom'],
    oneLineSummary: 'After a player makes a terrible mistake, Ted tells him: "You know what the happiest animal in the world is? A goldfish. Know why? Ten-second memory. Be a goldfish."',
    spiritualAngle: 'God says: "I will remember their sins no more." Not "I will try to forget." The Divine memory chooses to release. The shame you keep replaying has already been deleted from the only record that matters.',
    source: 'tv',
    specificReference: '"Ted Lasso" (2020), Season 1, Episode 2',
    spinnable: true,
  },
  {
    id: 'the-chosen-nicodemus',
    title: 'The Religious Leader Who Came at Night',
    era: '2019-present',
    category: 'literature-film',
    themes: ['seeking', 'doubt', 'courage', 'questions', 'religion-vs-encounter', 'night'],
    oneLineSummary: 'The Chosen portrays Nicodemus not as a villain but as a man of genuine faith trapped in a system — who comes to Jesus at night because the questions burning in him are bigger than his reputation.',
    spiritualAngle: 'Nicodemus came at night because daylight questions are the ones you ask for an audience. Night questions are the ones you ask because you can\'t sleep until you know.',
    source: 'tv',
    specificReference: '"The Chosen" (2019-present), Season 1; Nicodemus storyline',
    spinnable: true,
  },
  {
    id: 'the-chosen-mary-magdalene',
    title: 'The Woman Jesus Called by Name in the Worst Moment',
    era: '2019-present',
    category: 'literature-film',
    themes: ['identity', 'calling', 'mental-health', 'rescue', 'names', 'personal-God'],
    oneLineSummary: 'The Chosen depicts Mary Magdalene\'s deliverance not as a dramatic exorcism but as Jesus finding her in a dark room, calling her by name, and quoting Isaiah: "I have called you by name. You are mine."',
    spiritualAngle: 'In your worst moment, God doesn\'t show up with a theology lecture. He shows up with your name. The rescue is personal before it\'s doctrinal.',
    source: 'tv',
    specificReference: '"The Chosen" (2019), Season 1, Episode 1: "I Have Called You by Name"',
    spinnable: true,
  },
  {
    id: 'mr-rogers-look-for-helpers',
    title: '"Look for the Helpers"',
    era: '1986/2018',
    category: 'literature-film',
    themes: ['helpers', 'hope', 'crisis', 'goodness', 'community', 'faith-in-people'],
    oneLineSummary: 'Fred Rogers quoted his mother\'s advice: "When I was a boy and I would see scary things in the news, my mother would say, \'Look for the helpers. You will always find people who are helping.\'"',
    spiritualAngle: 'In every disaster, there are people running toward the danger. The image of God doesn\'t disappear in crisis — it concentrates. The helpers are the proof.',
    source: 'tv',
    specificReference: 'Fred Rogers, multiple interviews; "Won\'t You Be My Neighbor?" documentary (2018)',
    spinnable: true,
  },
  {
    id: 'mr-rogers-just-as-you-are',
    title: '"I Like You Just the Way You Are"',
    era: '1968-2001',
    category: 'literature-film',
    themes: ['acceptance', 'unconditional-love', 'identity', 'belonging', 'God-as-parent'],
    oneLineSummary: 'Every episode, Mr. Rogers looked directly into the camera — directly at the child watching — and said, "I like you just the way you are."',
    spiritualAngle: 'For millions of children, Fred Rogers was their first experience of unconditional regard — the feeling of being looked at and found acceptable without performing. He was, for many, the first face of grace.',
    source: 'tv',
    specificReference: '"Mister Rogers\' Neighborhood" (1968-2001), PBS',
    spinnable: true,
  },
  {
    id: 'brene-brown-vulnerability',
    title: 'Vulnerability Is Not Weakness — It\'s the Birthplace of Everything',
    era: '2010',
    category: 'literature-film',
    themes: ['vulnerability', 'courage', 'shame', 'connection', 'authenticity', 'risk'],
    oneLineSummary: 'Brené Brown\'s research showed that the people with the deepest sense of love and belonging had one thing in common: they believed they were worthy of it. And that belief required vulnerability.',
    spiritualAngle: 'The gospel invitation is fundamentally a vulnerability request: admit you need help. That\'s it. The entire kingdom of God is behind a door that only opens from the kneeling position.',
    source: 'tv',
    specificReference: 'Brené Brown, "The Power of Vulnerability" TED Talk (2010), Houston; 65 million+ views',
    spinnable: true,
  },
  {
    id: 'brene-brown-arena',
    title: '"If You\'re Not in the Arena, I\'m Not Interested in Your Feedback"',
    era: '2012',
    category: 'literature-film',
    themes: ['criticism', 'courage', 'risk', 'doing-vs-judging', 'fear-of-failure'],
    oneLineSummary: 'Brown quotes Theodore Roosevelt: "It is not the critic who counts... The credit belongs to the man who is actually in the arena, whose face is marred by dust and sweat and blood."',
    spiritualAngle: 'Jesus didn\'t critique the world from heaven. He entered the arena — dusty, sweaty, bleeding. The incarnation is God saying: I won\'t comment from safety. I\'m coming in.',
    source: 'tv',
    specificReference: 'Brené Brown, "Daring Greatly" (2012); Roosevelt\'s "Citizenship in a Republic" speech (1910)',
    spinnable: true,
  },
  {
    id: 'breaking-bad-mr-chips',
    title: 'The Chemistry Teacher Who Became What He Was Fighting',
    era: '2008-2013',
    category: 'literature-film',
    themes: ['corruption', 'pride', 'self-deception', 'gradual-sin', 'identity', 'justification'],
    oneLineSummary: 'Walter White begins cooking meth "for his family," but his slow transformation reveals the truth: the darkness was always there. By the end, he admits: "I did it for me. I liked it."',
    spiritualAngle: 'Sin rarely announces itself. It arrives disguised as necessity, then duty, then habit, then identity. Walt\'s descent is a parable about the stories we tell to justify the person we\'re becoming.',
    source: 'tv',
    specificReference: 'Vince Gilligan (creator), "Breaking Bad" (2008-2013), AMC; Season 5 finale confession',
    spinnable: true,
  },
  {
    id: 'the-office-goodbye-michael',
    title: '"I Wish There Was a Way to Know You Were in the Good Old Days"',
    era: '2011',
    category: 'literature-film',
    themes: ['nostalgia', 'presence', 'gratitude', 'attention', 'time', 'savoring'],
    oneLineSummary: 'In the final season, Andy Bernard says: "I wish there was a way to know you were in the good old days before you actually left them."',
    spiritualAngle: 'Every spiritual discipline of gratitude and presence is trying to solve this exact problem — to make you notice the miracle while you\'re standing in it, not just when it\'s in the rearview mirror.',
    source: 'tv',
    specificReference: '"The Office" (2013), Season 9, Episode 23: "Finale"',
    spinnable: true,
  },
  {
    id: 'succession-love',
    title: 'The Children Who Destroyed Each Other for a Father\'s Love',
    era: '2018-2023',
    category: 'literature-film',
    themes: ['father-wound', 'approval', 'power', 'family', 'love-deprivation', 'identity'],
    oneLineSummary: 'The Roy siblings spend four seasons betraying, manipulating, and destroying each other — all to win the approval of a father who was constitutionally incapable of giving love.',
    spiritualAngle: 'When your deepest need is for a father\'s approval and that father is broken, you\'ll burn down the world trying to earn what was never available. The healing starts when you find a Father who gives freely.',
    source: 'tv',
    specificReference: '"Succession" (2018-2023), HBO; Logan Roy\'s relationship with Kendall, Shiv, Roman',
    spinnable: true,
  },
  {
    id: 'everything-everywhere-rock-scene',
    title: 'Two Rocks on a Cliff Having the Most Honest Conversation',
    era: '2022',
    category: 'literature-film',
    themes: ['nihilism', 'meaning', 'absurdity', 'hope', 'connection', 'presence'],
    oneLineSummary: 'In a universe where they\'re just rocks on a cliff, Evelyn and Joy have a text conversation about meaninglessness. Joy/Jobu Tupaki embraces the void. Evelyn stays — because even in absurdity, she chooses to be there.',
    spiritualAngle: 'When you\'ve followed nihilism to its logical end and everything is meaningless, the only rebellion left is love. Choosing to stay, to care, to be kind when nothing compels it — that\'s the deepest faith.',
    source: 'film',
    specificReference: 'Daniel Kwan & Daniel Scheinert (dirs.), "Everything Everywhere All at Once" (2022), A24; the rock universe scene',
    spinnable: true,
  },
  {
    id: 'everything-everywhere-kindness',
    title: '"The Only Thing I Do Know Is That We Have to Be Kind"',
    era: '2022',
    category: 'literature-film',
    themes: ['kindness', 'choice', 'multiverse', 'hope', 'compassion', 'meaning'],
    oneLineSummary: 'Facing infinite universes and infinite versions of herself, Evelyn discovers that the most powerful force in the multiverse isn\'t kung fu or hot dog fingers — it\'s choosing kindness when everything tells you not to.',
    spiritualAngle: 'In a world of infinite options and infinite noise, the radical act is the simple one: be kind anyway. This is the scandal of the cross reduced to its simplest form.',
    source: 'film',
    specificReference: 'Daniel Kwan & Daniel Scheinert (dirs.), "Everything Everywhere All at Once" (2022), A24; Evelyn\'s final choice',
    spinnable: true,
  },
  {
    id: 'arrival-knowing-the-ending',
    title: 'Would You Still Choose the Joy If You Knew the Pain?',
    era: '2016',
    category: 'literature-film',
    themes: ['suffering', 'foreknowledge', 'choice', 'love', 'loss', 'grief', 'free-will'],
    oneLineSummary: 'Louise Banks learns an alien language that lets her perceive all of time at once — including her daughter\'s future death. She chooses to have the child anyway.',
    spiritualAngle: 'God, who sees all time at once, chose to create knowing the full cost — knowing the cross before the cradle. Arrival asks you: if you saw all the pain ahead, would you still choose to love? God did.',
    source: 'film',
    specificReference: 'Denis Villeneuve (dir.), "Arrival" (2016), based on Ted Chiang\'s "Story of Your Life"',
    spinnable: true,
  },
  {
    id: 'life-is-beautiful-guido',
    title: 'The Father Who Made a Game Out of the Holocaust',
    era: '1997',
    category: 'literature-film',
    themes: ['protection', 'parenthood', 'sacrifice', 'joy', 'suffering', 'shielding'],
    oneLineSummary: 'In a concentration camp, Guido convinces his young son that it\'s all an elaborate game with points and prizes — using humor and imagination to shield him from the horror, even as Guido is led to his death.',
    spiritualAngle: 'There\'s a kind of love that absorbs the horror so the child never has to see it. Guido carried a weight his son never knew existed — like a parent\'s prayers that shield in ways children won\'t understand for decades.',
    source: 'film',
    specificReference: 'Roberto Benigni (dir.), "Life Is Beautiful" (La vita è bella, 1997)',
    spinnable: true,
  },
  {
    id: 'tree-of-life-grace-nature',
    title: '"There Are Two Ways Through Life: Grace and Nature"',
    era: '2011',
    category: 'literature-film',
    themes: ['grace', 'nature', 'motherhood', 'fatherhood', 'worldview', 'tenderness-vs-strength'],
    oneLineSummary: 'The mother\'s voiceover opens the film: "The nuns taught us there are two ways through life: the way of nature and the way of grace. Nature only wants to please itself... Grace doesn\'t try to please itself."',
    spiritualAngle: 'Malick frames all of existence as a choice between two orientations: grasping (nature) or receiving (grace). Every day, every decision, is a vote for which way through life you\'re walking.',
    source: 'film',
    specificReference: 'Terrence Malick (dir.), "The Tree of Life" (2011), opening narration',
    spinnable: true,
  },
  {
    id: 'the-truman-show-escape',
    title: 'The Man Who Discovered His Entire World Was Staged',
    era: '1998',
    category: 'literature-film',
    themes: ['freedom', 'truth', 'control', 'awakening', 'fear', 'courage'],
    oneLineSummary: 'Truman Burbank discovers his entire life — wife, friends, town — was a TV set controlled by a god-like director. He sails toward the edge of his world, finds the painted wall of the sky, and steps through.',
    spiritualAngle: 'The constructed world will do anything to keep you comfortable and controlled. Stepping through the door means trading a safe, curated life for an unknown, unscripted one. That trade is called faith.',
    source: 'film',
    specificReference: 'Peter Weir (dir.), "The Truman Show" (1998), Truman\'s escape scene',
    spinnable: true,
  },
  {
    id: 'the-matrix-red-pill',
    title: 'The Choice to See Reality as It Actually Is',
    era: '1999',
    category: 'literature-film',
    themes: ['truth', 'awakening', 'illusion', 'comfort-vs-reality', 'choice', 'red-pill'],
    oneLineSummary: 'Morpheus offers Neo a choice: the blue pill (return to comfortable ignorance) or the red pill (see the truth, which will be painful). "I didn\'t say it would be easy, Neo. I just said it would be the truth."',
    spiritualAngle: 'Jesus said "the truth will set you free" — he didn\'t say the truth would feel good. Spiritual awakening often means seeing a reality that\'s harder to live in but more real to live from.',
    source: 'film',
    specificReference: 'Lana & Lilly Wachowski (dirs.), "The Matrix" (1999), red pill/blue pill scene',
    spinnable: true,
  },
  {
    id: 'interstellar-love-dimension',
    title: '"Love Is the One Thing That Transcends Time and Space"',
    era: '2014',
    category: 'literature-film',
    themes: ['love', 'transcendence', 'time', 'connection', 'faith', 'science-and-spirit'],
    oneLineSummary: 'Dr. Brand argues that love isn\'t just an emotion — it\'s observable, quantifiable, and crosses dimensions of time and space. Cooper later proves her right from inside a tesseract.',
    spiritualAngle: 'Science fiction accidentally preached 1 Corinthians 13: love never fails, never ends, transcends even death. Maybe it\'s not an accident. Maybe love really is woven into the fabric of spacetime.',
    source: 'film',
    specificReference: 'Christopher Nolan (dir.), "Interstellar" (2014), Brand\'s speech on love; tesseract scene',
    spinnable: true,
  },
  {
    id: 'gran-torino-sacrifice',
    title: 'The Racist Old Man Who Died for His Neighbor',
    era: '2008',
    category: 'literature-film',
    themes: ['sacrifice', 'redemption', 'prejudice', 'transformation', 'laying-down-life'],
    oneLineSummary: 'Walt Kowalski, an angry, racist Korean War veteran, sacrifices his life to protect his Hmong neighbors — walking unarmed into a confrontation, arms spread like a crucifixion, to provoke the gang into killing him in front of witnesses.',
    spiritualAngle: 'Eastwood staged the sacrifice as a crucifixion on purpose. The man who spent his whole life hating found, in his final act, the courage to die for the people he once despised. Redemption doesn\'t require a lifetime of goodness. It requires one complete yes.',
    source: 'film',
    specificReference: 'Clint Eastwood (dir.), "Gran Torino" (2008), final sacrifice scene',
    spinnable: true,
  },
  {
    id: 'places-remaining-light',
    title: 'The Widower Who Ran Toward Grief Instead of Away',
    era: '2023',
    category: 'literature-film',
    themes: ['grief', 'love', 'presence', 'loss', 'staying', 'not-fixing'],
    oneLineSummary: 'In "All the Light We Cannot See," Anthony Doerr writes characters who survive not by escaping pain but by turning toward it — touching the wound rather than flinching from it.',
    spiritualAngle: 'Thomas was invited to put his hand into the wound. The resurrection doesn\'t erase the scars — it transforms them into proof. Running from grief is running from the very place where healing lives.',
    source: 'literature',
    specificReference: 'Anthony Doerr, "All the Light We Cannot See" (2014), Pulitzer Prize',
    spinnable: true,
  },
  {
    id: 'les-mis-musical-epilogue',
    title: '"To Love Another Person Is to See the Face of God"',
    era: '1985/2012',
    category: 'literature-film',
    themes: ['love', 'God-in-others', 'face-of-God', 'incarnation', 'service'],
    oneLineSummary: 'The final line of the Les Misérables musical is sung as Jean Valjean dies: "To love another person is to see the face of God."',
    spiritualAngle: 'The simplest theology is sometimes the truest: God is most visible not in cathedrals or arguments but in the face of someone you love. "Whatever you did for the least of these, you did for me."',
    source: 'film',
    specificReference: 'Schönberg & Boublil, "Les Misérables" musical (1985); Tom Hooper (dir.), film (2012), finale',
    spinnable: true,
  },
  {
    id: 'dead-poets-carpe-diem',
    title: '"Carpe Diem — Seize the Day, Boys"',
    era: '1989',
    category: 'literature-film',
    themes: ['time', 'mortality', 'urgency', 'living-fully', 'youth', 'calling'],
    oneLineSummary: 'Mr. Keating takes his students to the trophy cases and whispers: "Carpe diem. Seize the day, boys. Make your lives extraordinary." — reminding them that the smiling faces in old photos are now "fertilizing daffodils."',
    spiritualAngle: 'James 4:14 — "You are a mist that appears for a little while and then vanishes." The urgency isn\'t about achievement. It\'s about waking up to how little time you have to love the people standing next to you.',
    source: 'film',
    specificReference: 'Peter Weir (dir.), "Dead Poets Society" (1989), trophy case scene',
    spinnable: true,
  },
  {
    id: 'up-ellie-montage',
    title: 'An Entire Love Story in Four Minutes Without Dialogue',
    era: '2009',
    category: 'literature-film',
    themes: ['love', 'marriage', 'loss', 'grief', 'ordinary-life', 'faithfulness'],
    oneLineSummary: 'The first ten minutes of "Up" show Carl and Ellie\'s entire marriage — meeting as kids, building a home, failing to have children, growing old, and Ellie\'s death — without a single word of dialogue.',
    spiritualAngle: 'The most sacred story isn\'t epic. It\'s the ordinary: fixing the mailbox, eating breakfast, sitting together. Faithfulness isn\'t one dramatic act. It\'s a thousand unremarkable mornings, chosen again.',
    source: 'film',
    specificReference: 'Pete Docter (dir.), "Up" (2009), Pixar; the "Married Life" montage',
    spinnable: true,
  },
  {
    id: 'the-shack-papa',
    title: 'God as a Black Woman Making Pancakes',
    era: '2007',
    category: 'literature-film',
    themes: ['God-image', 'theology', 'comfort', 'controversy', 'grief', 'presence'],
    oneLineSummary: 'In "The Shack," a grieving father meets God not as a bearded patriarch but as Papa — a Black woman making pancakes — because "you need a mother right now."',
    spiritualAngle: 'Controversial as it is, The Shack raises a real question: what if your image of God is keeping you from God? What if the Father you need right now looks nothing like the one you were taught to expect?',
    source: 'literature',
    specificReference: 'William Paul Young, "The Shack" (2007)',
    spinnable: true,
  },
  {
    id: 'midnight-library-regret',
    title: 'Every Life You Could Have Lived Has Its Own Sadness',
    era: '2020',
    category: 'literature-film',
    themes: ['regret', 'choices', 'contentment', 'alternate-paths', 'acceptance', 'present'],
    oneLineSummary: 'In the Midnight Library, Nora Seed visits the lives she could have led if she\'d made different choices — and discovers that every version of her life has its own unique pain.',
    spiritualAngle: 'Regret assumes the other path would have been better. But every road has its own valley of the shadow. The question isn\'t "did I choose the right path?" but "will I walk faithfully on this one?"',
    source: 'literature',
    specificReference: 'Matt Haig, "The Midnight Library" (2020)',
    spinnable: true,
  },
  {
    id: 'wandavision-grief',
    title: '"What Is Grief, If Not Love Persevering?"',
    era: '2021',
    category: 'literature-film',
    themes: ['grief', 'love', 'loss', 'perseverance', 'memory', 'holding-on'],
    oneLineSummary: 'Vision asks Wanda why she\'s so sad. She describes how love felt like waves growing inside her. Vision responds: "But what is grief, if not love persevering?"',
    spiritualAngle: 'Grief isn\'t the opposite of faith — it\'s the echo of love in the room where someone used to be. You grieve because you loved, and that love didn\'t end when they left.',
    source: 'tv',
    specificReference: '"WandaVision" (2021), Marvel/Disney+, Season 1, Episode 8',
    spinnable: true,
  },
  {
    id: 'hamilton-legacy',
    title: '"Who Lives, Who Dies, Who Tells Your Story"',
    era: '2015',
    category: 'literature-film',
    themes: ['legacy', 'story', 'mortality', 'impact', 'control', 'memory'],
    oneLineSummary: 'Hamilton\'s final question isn\'t about achievement but about narrative: after you\'re gone, someone else decides what your life meant. You don\'t control the story — Eliza does.',
    spiritualAngle: 'We spend our lives trying to write our own story. But in the end, it\'s told by others — and ultimately by God. The freedom is in releasing the pen: "Nevertheless, not my will, but yours."',
    source: 'tv',
    specificReference: 'Lin-Manuel Miranda, "Hamilton" (2015), final number: "Who Lives, Who Dies, Who Tells Your Story"',
    spinnable: true,
  },
  {
    id: 'hamilton-wait-for-it',
    title: '"Death Doesn\'t Discriminate Between the Sinners and the Saints"',
    era: '2015',
    category: 'literature-film',
    themes: ['mortality', 'patience', 'waiting', 'faith', 'timing', 'providence'],
    oneLineSummary: 'Aaron Burr\'s anthem about patience and mortality: "Death doesn\'t discriminate between the sinners and the saints, it takes and it takes and it takes... I am the one thing in life I can control."',
    spiritualAngle: 'Burr\'s philosophy is a counterfeit faith: control through patience, survival through non-commitment. The tragedy is that "waiting for it" without committing to anything is its own form of death.',
    source: 'tv',
    specificReference: 'Lin-Manuel Miranda, "Hamilton" (2015), "Wait for It" (Act 1)',
    spinnable: true,
  },
  {
    id: 'bo-burnham-inside',
    title: 'A Comedian Alone in a Room, Falling Apart Beautifully',
    era: '2021',
    category: 'literature-film',
    themes: ['isolation', 'mental-health', 'performance', 'authenticity', 'loneliness', 'pandemic'],
    oneLineSummary: 'Trapped alone during COVID lockdown, Bo Burnham creates a comedy special that spirals from funny to devastating — performing for nobody, trying to make meaning in a room he can\'t leave.',
    spiritualAngle: 'When all the audiences are gone and the performance stops and it\'s just you in a room — who are you then? Lockdown was, for many, an involuntary desert experience: stripped of distraction, forced to face what was there all along.',
    source: 'tv',
    specificReference: 'Bo Burnham, "Inside" (2021), Netflix',
    spinnable: true,
  },
  {
    id: 'fleabag-kneel-scene',
    title: '"I Want Someone to Tell Me What to Do"',
    era: '2019',
    category: 'literature-film',
    themes: ['longing', 'surrender', 'desperation', 'prayer', 'kneeling', 'God-encounter'],
    oneLineSummary: 'Fleabag, the sharp, self-destructive protagonist who breaks the fourth wall to stay in control, finally kneels in a church and says: "I want someone to tell me what to wear... what to eat... who to vote for... what to do."',
    spiritualAngle: 'The most honest prayer isn\'t "thy kingdom come." It\'s "I can\'t do this anymore. Someone take over." Fleabag\'s kneeling is what surrender actually looks like — not pious but exhausted.',
    source: 'tv',
    specificReference: 'Phoebe Waller-Bridge, "Fleabag" (2019), Season 2, Episode 4, confessional scene',
    spinnable: true,
  },
  {
    id: 'severance-who-are-you',
    title: 'What If You Could Split Your Work Self From Your Real Self?',
    era: '2022-present',
    category: 'literature-film',
    themes: ['identity', 'wholeness', 'compartmentalization', 'integration', 'authenticity'],
    oneLineSummary: 'In "Severance," employees undergo a procedure that splits their consciousness: "work you" has no memories of life, and "life you" has no memories of work. It\'s presented as freedom — but it\'s a horror show.',
    spiritualAngle: 'Compartmentalized faith — Sunday you vs. Monday you — is its own severance procedure. The biblical call is integration: the same person in every room. Wholeness, not convenience.',
    source: 'tv',
    specificReference: '"Severance" (2022-present), Apple TV+; created by Dan Erickson',
    spinnable: true,
  },
  {
    id: 'station-eleven-survival-not-enough',
    title: '"Survival Is Insufficient"',
    era: '2021',
    category: 'literature-film',
    themes: ['meaning', 'art', 'flourishing', 'survival', 'beauty', 'purpose'],
    oneLineSummary: 'After a pandemic destroys civilization, a traveling Shakespeare troupe performs for survivors under the motto "Survival Is Insufficient" — insisting that staying alive without beauty, art, and community isn\'t really living.',
    spiritualAngle: 'Jesus said he came that they may have life "abundantly" — not just alive, but fully alive. Survival is the floor, not the ceiling. God didn\'t save you just to exist.',
    source: 'tv',
    specificReference: '"Station Eleven" (2021), HBO Max; based on Emily St. John Mandel\'s novel (2014); the Star Trek quote on the Traveling Symphony\'s lead caravan',
    spinnable: true,
  },
  {
    id: 'pursuit-of-happyness-bathroom',
    title: 'A Father and Son Sleeping in a Subway Bathroom',
    era: '2006',
    category: 'literature-film',
    themes: ['perseverance', 'fatherhood', 'poverty', 'hope', 'dignity', 'protection'],
    oneLineSummary: 'Chris Gardner, homeless with his son, locks themselves in a subway bathroom for the night. His son sleeps on his lap while Chris cries silently, bracing his foot against the door when someone tries to enter.',
    spiritualAngle: 'This scene has no dialogue about God. But it\'s a portrait of incarnate love: a father absorbing all the fear and humiliation so his son can sleep in peace. This is what bearing another\'s burdens looks like at 2 AM.',
    source: 'film',
    specificReference: 'Gabriele Muccino (dir.), "The Pursuit of Happyness" (2006), bathroom scene',
    spinnable: true,
  },
  {
    id: 'eternal-sunshine-try-again',
    title: 'Choosing to Love Again Even Knowing How It Ends',
    era: '2004',
    category: 'literature-film',
    themes: ['love', 'risk', 'memory', 'vulnerability', 'second-chances', 'choosing-pain'],
    oneLineSummary: 'Joel and Clementine learn they\'ve already erased each other from their memories once. They hear tapes of themselves describing exactly how the relationship will fail. They choose to try again anyway.',
    spiritualAngle: 'This is what covenant looks like: choosing someone with full knowledge of how they\'ll hurt you. Not because you\'re naive, but because the love is worth the wound.',
    source: 'film',
    specificReference: 'Michel Gondry (dir.), "Eternal Sunshine of the Spotless Mind" (2004), final scene',
    spinnable: true,
  },
  {
    id: 'blade-runner-tears-in-rain',
    title: '"All Those Moments Will Be Lost in Time, Like Tears in Rain"',
    era: '1982',
    category: 'literature-film',
    themes: ['mortality', 'meaning', 'memory', 'beauty', 'loss', 'impermanence'],
    oneLineSummary: 'The replicant Roy Batty, moments before death, releases the dove and recounts his wondrous experiences: "All those moments will be lost in time, like tears in rain. Time to die."',
    spiritualAngle: 'The ache for permanence in a temporary world is the ache for eternity that God placed in the human heart. Every beautiful moment that passes is an argument for something that doesn\'t.',
    source: 'film',
    specificReference: 'Ridley Scott (dir.), "Blade Runner" (1982), Roy Batty\'s death monologue (improvised by Rutger Hauer)',
    spinnable: true,
  },
  {
    id: 'cast-away-wilson',
    title: 'A Man Who Grieves a Volleyball',
    era: '2000',
    category: 'literature-film',
    themes: ['loneliness', 'connection', 'loss', 'belonging', 'image-of-God', 'relationship'],
    oneLineSummary: 'Chuck Noland paints a face on a volleyball and names it Wilson. When he loses Wilson at sea, his grief is genuine, ugly, devastating — because humans will create relationship out of anything rather than live without it.',
    spiritualAngle: 'We are so profoundly wired for connection that we\'ll draw a face on a ball rather than be alone. This isn\'t weakness. It\'s the image of a relational God, refusing to be extinguished.',
    source: 'film',
    specificReference: 'Robert Zemeckis (dir.), "Cast Away" (2000), Wilson scenes',
    spinnable: true,
  },
  {
    id: 'princess-bride-mostly-dead',
    title: '"There\'s a Big Difference Between Mostly Dead and All Dead"',
    era: '1987',
    category: 'literature-film',
    themes: ['hope', 'resurrection', 'humor', 'not-giving-up', 'miracles', 'surprise'],
    oneLineSummary: 'Miracle Max examines the hero and declares: "It just so happens your friend here is only MOSTLY dead. There\'s a big difference between mostly dead and all dead."',
    spiritualAngle: 'The thing you\'re ready to bury might be only mostly dead. God has an unfortunate habit of showing up at funerals and ruining them. "Lazarus, come out."',
    source: 'film',
    specificReference: 'Rob Reiner (dir.), "The Princess Bride" (1987); Miracle Max scene; based on William Goldman\'s novel',
    spinnable: true,
  },
  {
    id: 'stand-by-me-friends',
    title: '"I Never Had Any Friends Later Like the Ones I Had at Twelve"',
    era: '1986',
    category: 'literature-film',
    themes: ['friendship', 'youth', 'nostalgia', 'vulnerability', 'loss', 'innocence'],
    oneLineSummary: 'The narrator, now an adult, types the final line of his memoir about a childhood adventure: "I never had any friends later on like the ones I had when I was twelve. Jesus, does anyone?"',
    spiritualAngle: 'There\'s a purity to childhood friendship that adult self-consciousness makes almost impossible. "Unless you become like little children" — open, unguarded, all-in — "you will never enter the kingdom."',
    source: 'film',
    specificReference: 'Rob Reiner (dir.), "Stand by Me" (1986); based on Stephen King\'s "The Body"',
    spinnable: true,
  },
  {
    id: 'hachi-waiting',
    title: 'The Dog Who Waited at the Train Station for Ten Years',
    era: '2009/1925',
    category: 'literature-film',
    themes: ['faithfulness', 'loyalty', 'waiting', 'love', 'perseverance', 'devotion'],
    oneLineSummary: 'Hachiko the dog waited at Shibuya Station every day for nearly ten years after his owner\'s death, never understanding that the person he loved was never coming back — or perhaps understanding perfectly.',
    spiritualAngle: 'Is Hachiko\'s vigil foolish or faithful? The answer depends on whether you believe the waiting itself has value. "Even so, come, Lord Jesus" — the church has been at its own station for two thousand years.',
    source: 'film',
    specificReference: 'Lasse Hallström (dir.), "Hachi: A Dog\'s Tale" (2009); based on the true story of Hachikō, Tokyo, 1925-1935',
    spinnable: true,
  },
  {
    id: 'groundhog-day-transformation',
    title: 'The Man Trapped in the Same Day Until He Changed',
    era: '1993',
    category: 'literature-film',
    themes: ['transformation', 'repetition', 'sanctification', 'selfishness', 'service', 'growth'],
    oneLineSummary: 'Phil Connors relives February 2nd thousands of times. He tries hedonism, manipulation, and suicide — nothing works. Freedom only comes when he starts genuinely serving others.',
    spiritualAngle: 'Groundhog Day is an accidental parable of sanctification: you keep waking up in the same circumstances, making the same mistakes, until the day you finally choose to become the person the day needs you to be.',
    source: 'film',
    specificReference: 'Harold Ramis (dir.), "Groundhog Day" (1993)',
    spinnable: true,
  },
  {
    id: 'the-father-anthony-hopkins',
    title: 'The World Through Eyes That Can\'t Trust Themselves',
    era: '2020',
    category: 'literature-film',
    themes: ['vulnerability', 'aging', 'trust', 'dependency', 'loss-of-control', 'dignity'],
    oneLineSummary: 'Florian Zeller\'s film puts you inside the disorienting experience of dementia — rooms that change, faces that shift, time that loops — until Anthony suddenly cries: "I want my mummy."',
    spiritualAngle: 'Stripped of every pretense — intelligence, control, dignity — the deepest human cry is still for a parent. "Abba, Father." The first word and the last.',
    source: 'film',
    specificReference: 'Florian Zeller (dir.), "The Father" (2020), Anthony Hopkins\'s final scene',
    spinnable: true,
  },
  {
    id: 'field-of-dreams-catch',
    title: '"Hey Dad... You Wanna Have a Catch?"',
    era: '1989',
    category: 'literature-film',
    themes: ['father-wound', 'reconciliation', 'regret', 'second-chances', 'healing'],
    oneLineSummary: 'After building a baseball diamond in his cornfield and summoning dead players, Ray Kinsella finally understands: it was never about baseball. His young father emerges from the corn, and Ray asks the question he\'d give anything to ask: "Hey Dad... you wanna have a catch?"',
    spiritualAngle: 'The deepest adult wound is often the simplest childhood wish: to play catch with a father who was present. Every complicated pursuit circles back to the original ache for connection.',
    source: 'film',
    specificReference: 'Phil Alden Robinson (dir.), "Field of Dreams" (1989), final scene',
    spinnable: true,
  },
];
